/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyecto_m2b.Vista;

import com.mycompany.proyecto_m2b.Controlador.AccesosDAO;
import com.mycompany.proyecto_m2b.Controlador.CargoDAO;
import com.mycompany.proyecto_m2b.Controlador.TipoUsuarioDAO;
import com.mycompany.proyecto_m2b.Controlador.Validaciones;
import com.mycompany.proyecto_m2b.modelo.Accesos;
import com.mycompany.proyecto_m2b.modelo.Cargo;
import com.mycompany.proyecto_m2b.modelo.Tipos_de_usuario;
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JList;
import javax.swing.JOptionPane;

/**
 *
 * @author usuario
 */
public class Accesos_del_sistema extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Accesos_del_sistema.class.getName());

    /**
     * Creates new form Cargos
     */
    public Accesos_del_sistema() {
        initComponents();
        this.setLocationRelativeTo(null);
        List<Tipos_de_usuario> tipos = new TipoUsuarioDAO().listarTodos();
        TiposUsuarios.setListData(tipos.toArray(new Tipos_de_usuario[0]));
        TiposUsuarios.setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
    }

    
    int xMouse;
    int yMouse;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Menu = new javax.swing.JPanel();
        Barra = new javax.swing.JPanel();
        MJ = new javax.swing.JLabel();
        Talleres = new javax.swing.JLabel();
        Regresar = new javax.swing.JLabel();
        ImagenRegresar = new javax.swing.JLabel();
        PanelNuevo = new javax.swing.JPanel();
        Nuevo = new javax.swing.JLabel();
        ImagenADD = new javax.swing.JLabel();
        PanelGuardar = new javax.swing.JPanel();
        Guardar = new javax.swing.JLabel();
        ImagenSAVE = new javax.swing.JLabel();
        PanelEditar = new javax.swing.JPanel();
        Editar = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        PanelBuscar = new javax.swing.JPanel();
        Buscar = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        PanelDarBaja = new javax.swing.JPanel();
        DarDeBaja = new javax.swing.JLabel();
        ImagenDarBaja = new javax.swing.JLabel();
        PanelDarDeAlta = new javax.swing.JPanel();
        DarDeAlta = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        NombreAcceso = new javax.swing.JLabel();
        TXTAcceso = new javax.swing.JTextField();
        Descripcion = new javax.swing.JLabel();
        TXTDescripcion = new javax.swing.JTextField();
        AccesosCombo = new javax.swing.JComboBox<>();
        Estados = new javax.swing.JComboBox<>();
        NombreAcceso1 = new javax.swing.JLabel();
        NombreAcceso2 = new javax.swing.JLabel();
        NombreAcceso3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TiposUsuarios = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Menu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Barra.setBackground(new java.awt.Color(0, 0, 0));
        Barra.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                BarraMouseDragged(evt);
            }
        });
        Barra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BarraMousePressed(evt);
            }
        });

        MJ.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        MJ.setForeground(new java.awt.Color(152, 75, 45));
        MJ.setText("M&J");

        Talleres.setBackground(new java.awt.Color(152, 75, 45));
        Talleres.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Talleres.setForeground(new java.awt.Color(174, 63, 54));
        Talleres.setText("TALLERES");
        Talleres.setPreferredSize(new java.awt.Dimension(190, 47));

        Regresar.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        Regresar.setForeground(new java.awt.Color(145, 145, 145));
        Regresar.setText("Regresar");
        Regresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Regresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RegresarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                RegresarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                RegresarMouseExited(evt);
            }
        });

        ImagenRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/arrow_back_34dp_D9D9D9_FILL0_wght400_GRAD0_opsz40.png"))); // NOI18N
        ImagenRegresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ImagenRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ImagenRegresarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout BarraLayout = new javax.swing.GroupLayout(Barra);
        Barra.setLayout(BarraLayout);
        BarraLayout.setHorizontalGroup(
            BarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BarraLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Talleres, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MJ))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ImagenRegresar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Regresar)
                .addContainerGap())
        );
        BarraLayout.setVerticalGroup(
            BarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BarraLayout.createSequentialGroup()
                .addGroup(BarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(BarraLayout.createSequentialGroup()
                        .addComponent(MJ)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Talleres, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(BarraLayout.createSequentialGroup()
                        .addGroup(BarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(Regresar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ImagenRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(12, 12, 12)))
                .addGap(0, 12, Short.MAX_VALUE))
        );

        PanelNuevo.setBackground(new java.awt.Color(255, 255, 255));
        PanelNuevo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(187, 187, 187)));
        PanelNuevo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PanelNuevo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PanelNuevoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PanelNuevoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PanelNuevoMouseExited(evt);
            }
        });

        Nuevo.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        Nuevo.setText("Nuevo");

        ImagenADD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/add_22dp_000000_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N

        javax.swing.GroupLayout PanelNuevoLayout = new javax.swing.GroupLayout(PanelNuevo);
        PanelNuevo.setLayout(PanelNuevoLayout);
        PanelNuevoLayout.setHorizontalGroup(
            PanelNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelNuevoLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(ImagenADD)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Nuevo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelNuevoLayout.setVerticalGroup(
            PanelNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelNuevoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ImagenADD)
                    .addComponent(Nuevo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PanelGuardar.setBackground(new java.awt.Color(242, 101, 34));
        PanelGuardar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(187, 187, 187)));
        PanelGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PanelGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PanelGuardarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PanelGuardarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PanelGuardarMouseExited(evt);
            }
        });

        Guardar.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        Guardar.setForeground(new java.awt.Color(255, 255, 255));
        Guardar.setText("Guardar");

        ImagenSAVE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/save_22dp_FFFFFF_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N

        javax.swing.GroupLayout PanelGuardarLayout = new javax.swing.GroupLayout(PanelGuardar);
        PanelGuardar.setLayout(PanelGuardarLayout);
        PanelGuardarLayout.setHorizontalGroup(
            PanelGuardarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelGuardarLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(ImagenSAVE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Guardar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelGuardarLayout.setVerticalGroup(
            PanelGuardarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelGuardarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanelGuardarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Guardar)
                    .addComponent(ImagenSAVE))
                .addContainerGap())
        );

        PanelEditar.setBackground(new java.awt.Color(255, 255, 255));
        PanelEditar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(187, 187, 187)));
        PanelEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PanelEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PanelEditarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PanelEditarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PanelEditarMouseExited(evt);
            }
        });

        Editar.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        Editar.setText("Editar");

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/edit_22dp_000000_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N

        javax.swing.GroupLayout PanelEditarLayout = new javax.swing.GroupLayout(PanelEditar);
        PanelEditar.setLayout(PanelEditarLayout);
        PanelEditarLayout.setHorizontalGroup(
            PanelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelEditarLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Editar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelEditarLayout.setVerticalGroup(
            PanelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelEditarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Editar)
                    .addComponent(jLabel2))
                .addContainerGap())
        );

        PanelBuscar.setBackground(new java.awt.Color(255, 255, 255));
        PanelBuscar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(187, 187, 187)));
        PanelBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PanelBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PanelBuscarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PanelBuscarMouseExited(evt);
            }
        });

        Buscar.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        Buscar.setText("Buscar");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/person_search_22dp_000000_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N

        javax.swing.GroupLayout PanelBuscarLayout = new javax.swing.GroupLayout(PanelBuscar);
        PanelBuscar.setLayout(PanelBuscarLayout);
        PanelBuscarLayout.setHorizontalGroup(
            PanelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelBuscarLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Buscar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelBuscarLayout.setVerticalGroup(
            PanelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBuscarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Buscar)
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PanelDarBaja.setBackground(new java.awt.Color(255, 255, 255));
        PanelDarBaja.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(215, 106, 106)));
        PanelDarBaja.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PanelDarBaja.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PanelDarBajaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PanelDarBajaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PanelDarBajaMouseExited(evt);
            }
        });

        DarDeBaja.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        DarDeBaja.setForeground(new java.awt.Color(215, 106, 106));
        DarDeBaja.setText("Dar de baja");

        ImagenDarBaja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/person_cancel_22dp_EA3323_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N

        javax.swing.GroupLayout PanelDarBajaLayout = new javax.swing.GroupLayout(PanelDarBaja);
        PanelDarBaja.setLayout(PanelDarBajaLayout);
        PanelDarBajaLayout.setHorizontalGroup(
            PanelDarBajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelDarBajaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ImagenDarBaja)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(DarDeBaja)
                .addContainerGap())
        );
        PanelDarBajaLayout.setVerticalGroup(
            PanelDarBajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDarBajaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelDarBajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DarDeBaja)
                    .addComponent(ImagenDarBaja))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PanelDarDeAlta.setBackground(new java.awt.Color(255, 255, 255));
        PanelDarDeAlta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(187, 187, 187)));
        PanelDarDeAlta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PanelDarDeAlta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PanelDarDeAltaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PanelDarDeAltaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PanelDarDeAltaMouseExited(evt);
            }
        });

        DarDeAlta.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        DarDeAlta.setText("Dar de alta");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/add_22dp_000000_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N

        javax.swing.GroupLayout PanelDarDeAltaLayout = new javax.swing.GroupLayout(PanelDarDeAlta);
        PanelDarDeAlta.setLayout(PanelDarDeAltaLayout);
        PanelDarDeAltaLayout.setHorizontalGroup(
            PanelDarDeAltaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelDarDeAltaLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DarDeAlta)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelDarDeAltaLayout.setVerticalGroup(
            PanelDarDeAltaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDarDeAltaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelDarDeAltaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DarDeAlta)
                    .addComponent(jLabel3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        NombreAcceso.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        NombreAcceso.setText("Nombre para el acceso:");

        TXTAcceso.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        TXTAcceso.setForeground(new java.awt.Color(94, 94, 94));
        TXTAcceso.setText("Acceso");
        TXTAcceso.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TXTAccesoFocusGained(evt);
            }
        });
        TXTAcceso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TXTAccesoMousePressed(evt);
            }
        });
        TXTAcceso.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TXTAccesoKeyPressed(evt);
            }
        });

        Descripcion.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        Descripcion.setText("Descripción:");

        TXTDescripcion.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        TXTDescripcion.setForeground(new java.awt.Color(94, 94, 94));
        TXTDescripcion.setText("Descripción");
        TXTDescripcion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TXTDescripcionFocusGained(evt);
            }
        });
        TXTDescripcion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TXTDescripcionMousePressed(evt);
            }
        });
        TXTDescripcion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TXTDescripcionKeyPressed(evt);
            }
        });

        AccesosCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione uno" }));
        AccesosCombo.addItemListener(this::AccesosComboItemStateChanged);

        Estados.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una opción", "Activo", "En Pausa" }));

        NombreAcceso1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        NombreAcceso1.setText("Que usuario tendra este acceso:");

        NombreAcceso2.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        NombreAcceso2.setText("Estado del acceso:");

        NombreAcceso3.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        NombreAcceso3.setText("Accesos:");

        jScrollPane1.setViewportView(TiposUsuarios);

        javax.swing.GroupLayout MenuLayout = new javax.swing.GroupLayout(Menu);
        Menu.setLayout(MenuLayout);
        MenuLayout.setHorizontalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Barra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(MenuLayout.createSequentialGroup()
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, MenuLayout.createSequentialGroup()
                            .addGap(27, 27, 27)
                            .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(TXTAcceso, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(NombreAcceso))
                            .addGap(18, 18, 18)
                            .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(NombreAcceso1))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(AccesosCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(NombreAcceso3))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(NombreAcceso2)
                                .addComponent(Estados, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, MenuLayout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(TXTDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 745, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, MenuLayout.createSequentialGroup()
                                    .addComponent(PanelNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(PanelGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(PanelEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(PanelBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(PanelDarBaja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(PanelDarDeAlta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(MenuLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Descripcion)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        MenuLayout.setVerticalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addComponent(Barra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NombreAcceso)
                    .addComponent(NombreAcceso1)
                    .addComponent(NombreAcceso2)
                    .addComponent(NombreAcceso3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MenuLayout.createSequentialGroup()
                        .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TXTAcceso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AccesosCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Estados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Descripcion))
                    .addGroup(MenuLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 60, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TXTDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(PanelGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(PanelEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(PanelNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(PanelBuscar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(PanelDarBaja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PanelDarDeAlta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );

        getContentPane().add(Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RegresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegresarMouseClicked
        // TODO add your handling code here:
        Agregar A=new Agregar();
        A.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_RegresarMouseClicked

    private void RegresarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegresarMouseEntered
        // TODO add your handling code here:
        Regresar.setForeground(new Color(196, 196, 196));
    }//GEN-LAST:event_RegresarMouseEntered

    private void RegresarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegresarMouseExited
        // TODO add your handling code here:
        Regresar.setForeground(new Color(145, 145, 145));
    }//GEN-LAST:event_RegresarMouseExited

    private void PanelNuevoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelNuevoMouseClicked
        // TODO add your handling code here:
        LimpiarDatos();
        JOptionPane.showMessageDialog(this, "Datos limpiados correctamente"+"\n"
            +"Ingrese los datos");
    }//GEN-LAST:event_PanelNuevoMouseClicked

    private void PanelNuevoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelNuevoMouseEntered
        // TODO add your handling code here:
        PanelNuevo.setBackground(new Color(219,219,219));
        Nuevo.setForeground(new Color(66, 66, 66));
    }//GEN-LAST:event_PanelNuevoMouseEntered

    private void PanelNuevoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelNuevoMouseExited
        // TODO add your handling code here:
        PanelNuevo.setBackground(Color.white);
        Nuevo.setForeground(Color.black);
    }//GEN-LAST:event_PanelNuevoMouseExited

    private void PanelGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelGuardarMouseClicked
        // TODO add your handling code here:
        GuardarCargo();
    }//GEN-LAST:event_PanelGuardarMouseClicked

    private void PanelGuardarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelGuardarMouseEntered
        // TODO add your handling code here:
        PanelGuardar.setBackground(new Color(227, 95, 32));
        Guardar.setForeground(new Color(217, 217, 192));
    }//GEN-LAST:event_PanelGuardarMouseEntered

    private void PanelGuardarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelGuardarMouseExited
        // TODO add your handling code here:
        PanelGuardar.setBackground(new Color(242,101,34));
        Guardar.setForeground(Color.white);
    }//GEN-LAST:event_PanelGuardarMouseExited

    private void PanelEditarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelEditarMouseEntered
        // TODO add your handling code here:
        PanelEditar.setBackground(new Color(219,219,219));
        Editar.setForeground(new Color(66, 66, 66));
    }//GEN-LAST:event_PanelEditarMouseEntered

    private void PanelEditarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelEditarMouseExited
        // TODO add your handling code here:
        PanelEditar.setBackground(Color.white);
        Editar.setForeground(Color.black);
    }//GEN-LAST:event_PanelEditarMouseExited

    private void PanelBuscarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelBuscarMouseEntered
        // TODO add your handling code here:
        PanelBuscar.setBackground(new Color(219,219,219));
        Buscar.setForeground(new Color(66, 66, 66));
    }//GEN-LAST:event_PanelBuscarMouseEntered

    private void PanelBuscarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelBuscarMouseExited
        // TODO add your handling code here:
        PanelBuscar.setBackground(Color.white);
        Buscar.setForeground(Color.black);
    }//GEN-LAST:event_PanelBuscarMouseExited

    private void TXTAccesoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TXTAccesoFocusGained
        // TODO add your handling code here:
        if (TXTAcceso.getText().equals("Acceso")){
            TXTAcceso.setText("");
            TXTAcceso.setForeground(Color.BLACK);
        }
        if (TXTDescripcion.getText().isEmpty()){
            TXTDescripcion.setText("Descripción");
            TXTDescripcion.setForeground(new Color (94, 94, 94));
        }
    }//GEN-LAST:event_TXTAccesoFocusGained

    public void GuardarCargo (){
        Validaciones V=new Validaciones();
        String acceso=TXTAcceso.getText().trim().toUpperCase();
        String Descripcion=TXTDescripcion.getText().trim().toUpperCase();
        String estado=Estados.getSelectedItem().toString();
        if (acceso.isEmpty() || Descripcion.isEmpty()){
            JOptionPane.showMessageDialog (this, "Por favor ingrese los datos correspondientes");
            return;
        }
        if (estado.equals("Seleccione una opción")){
            JOptionPane.showMessageDialog(this, "Escoga un estado");
            return;
        }
        if (acceso.isBlank() || Descripcion.isBlank()){
            JOptionPane.showMessageDialog (this, "Por favor ingrese los datos correspondientes");
            return;
        }
        if(!V.validarAcceso(acceso) || !V.validarDescripcionAccesos(Descripcion)){
            LimpiarDatos();
            JOptionPane.showMessageDialog(this, "Por favor ingrese los datos de manera correcta");
            return;
        }
        if (acceso.equalsIgnoreCase("Acceso") || Descripcion.equalsIgnoreCase("Descripción")){
            JOptionPane.showMessageDialog(this, "Por favor ingrese los datos de manera correcta");
            return;
        }

        List <Tipos_de_usuario> seleccionados = TiposUsuarios.getSelectedValuesList();
        if (seleccionados.isEmpty()){
            JOptionPane.showMessageDialog(this, "Por favor escoga al menos un tipo de usuario");
            return;
        }
        AccesosDAO ad=new AccesosDAO();
        int agregados=0;
        
        
        for (Tipos_de_usuario tipo : seleccionados){
            if (ad.existeAcceso(acceso, tipo.getId_tip_de_usuario())){
                continue;
            }
            
            Accesos acce=new Accesos(); 
            acce.setAccesos(acceso);
            acce.setDesc_persmisos(Descripcion);
            acce.setId_tip_usuario(tipo.getId_tip_de_usuario());
            ad.insertarAccesos(acce);
            agregados++;
        }
        if (agregados>0){
            JOptionPane.showMessageDialog(this, "Se ha guardado correctamente el acceso para "+agregados+" tipo/s de usuario/s");
            LimpiarDatos();
        }
        else{
            JOptionPane.showMessageDialog(this, "Ese acceso ya ha estado disponible para todos los usuarios");
        }                
    }
    public void LimpiarDatos (){
        TXTAcceso.setText("Cargo");
        TXTAcceso.setForeground(new Color (94, 94, 94));
        TXTDescripcion.setText("Descripción");
        TXTDescripcion.setForeground(new Color (94, 94, 94));
        TiposUsuarios.clearSelection();
        Estados.setSelectedItem(0);
        PanelGuardar.setEnabled(true);
    }
    private void TXTAccesoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TXTAccesoMousePressed
        // TODO add your handling code here:
        if (TXTAcceso.getText().equals("Acceso")){
            TXTAcceso.setText("");
            TXTAcceso.setForeground(Color.BLACK);
        }
        if (TXTDescripcion.getText().isEmpty()){
            TXTDescripcion.setText("Descripción");
            TXTDescripcion.setForeground(new Color (94, 94, 94));
        }
    }//GEN-LAST:event_TXTAccesoMousePressed

    private void TXTAccesoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXTAccesoKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER){
            GuardarCargo();
        }
    }//GEN-LAST:event_TXTAccesoKeyPressed

    private void TXTDescripcionFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TXTDescripcionFocusGained
        // TODO add your handling code here:
        if (TXTDescripcion.getText().equals("Descripción")){
            TXTDescripcion.setText("");
            TXTDescripcion.setForeground(Color.BLACK);
        }
        if (TXTAcceso.getText().isEmpty()){
            TXTAcceso.setText("Acceso");
            TXTAcceso.setForeground(new Color (94, 94, 94));
        }
    }//GEN-LAST:event_TXTDescripcionFocusGained

    private void TXTDescripcionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TXTDescripcionMousePressed
        // TODO add your handling code here:
        if (TXTDescripcion.getText().equals("Descripción")){
            TXTDescripcion.setText("");
            TXTDescripcion.setForeground(Color.BLACK);
        }
        if (TXTAcceso.getText().isEmpty()){
            TXTAcceso.setText("Acceso");
            TXTAcceso.setForeground(new Color (94, 94, 94));
        }
    }//GEN-LAST:event_TXTDescripcionMousePressed

    private void TXTDescripcionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXTDescripcionKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER){
            GuardarCargo();
        }
    }//GEN-LAST:event_TXTDescripcionKeyPressed

    private void ImagenRegresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ImagenRegresarMouseClicked
        // TODO add your handling code here:
        Agregar A=new Agregar();
        A.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ImagenRegresarMouseClicked

    private void BarraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BarraMousePressed
        // TODO add your handling code here:
        xMouse=evt.getX();
        yMouse=evt.getY();
    }//GEN-LAST:event_BarraMousePressed

    private void BarraMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BarraMouseDragged
        // TODO add your handling code here:
        int x=evt.getXOnScreen();
        int y=evt.getYOnScreen();
        this.setLocation(x-xMouse, y-yMouse);
    }//GEN-LAST:event_BarraMouseDragged

    /*
    public void ModificarAccesos (){
        Validaciones V=new Validaciones();
        String Acceso=TXTAcceso.getText().trim();
        String Descrip=TXTDescripcion.getText().trim();        
        Accesos selec = (Accesos) AccesosCombo.getSelectedItem();
        
        if (selec==null){
            JOptionPane.showMessageDialog(this, "Por favor seleccione un cargo para modificar");
            return;
        }
        
        if (Acceso.isEmpty() || Descrip.isEmpty()){
            JOptionPane.showMessageDialog (this, "Por favor ingrese los datos correspondientes");
            return;
        }
        if (Acceso.isBlank() || Descrip.isBlank()){
            JOptionPane.showMessageDialog (this, "Por favor ingrese los datos correspondientes");
            return;
        }
        if(!V.validarAcceso(Acceso) || !V.validarDescripcionAccesos(Descrip)){
            LimpiarDatos();
            JOptionPane.showMessageDialog(this, "P favor ingrese los datos de manera correcta");
            return;
        }
        if (Acceso.equalsIgnoreCase("Acceso") || Descrip.equalsIgnoreCase("Descripción")){
            JOptionPane.showMessageDialog(this, "Por favor ingrese los datos de manera correcta");
            return;
        }
        Accesos ac=new Accesos();
        ac.setAccesos(Acceso);
        ac.setDesc_persmisos(Descrip);
        AccesosDAO ad=new AccesosDAO();
        
        ac.setId_tip_usuario(tu.getId_tip_de_usuario());
        ad.actualizar(ac);
        JOptionPane.showMessageDialog(this, "Se ha actualizado de manera correcta");
    }
    */
    private void PanelEditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelEditarMouseClicked
        // TODO add your handling code here:        
        /*
        Cargo car= (Cargo) TiposUsuario.getSelectedItem();
        if(car==null){
            JOptionPane.showMessageDialog(this, "Escoga una opción");
        }
        else{
            int opcion=JOptionPane.showConfirmDialog(this, "¿Quiere modificar la especialidad?","Confirmar",JOptionPane.YES_NO_OPTION);
            if(opcion==JOptionPane.YES_OPTION){
                ModificarCargos();
                LimpiarDatos();
                CargoDAO cd=new CargoDAO();
                cd.cargarCargos(TiposUsuario);
            }
            else{
                JOptionPane.showMessageDialog(this, "Gracias por confirmar");
            }
        }
        */
    }//GEN-LAST:event_PanelEditarMouseClicked

    private void PanelDarBajaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelDarBajaMouseClicked
        // TODO add your handling code here:
        Accesos selecc=(Accesos) AccesosCombo.getSelectedItem();
        if (selecc!=null){
            int opcion=JOptionPane.showConfirmDialog(this, "¿Esta seguro de dar de baja a este acceso?","Confirmar",JOptionPane.YES_NO_OPTION);
            if (opcion==JOptionPane.YES_OPTION){
                String id_acceso=selecc.getId_accesos();
                AccesosDAO ad=new AccesosDAO();
                boolean exito=ad.eliminar(id_acceso);
                if (exito){
                    Estados.setSelectedItem("En pausa");
                    JOptionPane.showMessageDialog(this, "Modificado de manera correcta");                    
                    LimpiarDatos();
                }
                else{
                    JOptionPane.showMessageDialog(this, "Error al dar de baja al acceso: "+selecc.getAccesos());
                }
            }
            else{
                JOptionPane.showMessageDialog(this, "Gracias por confirmar");
            }
        }
        else{
            JOptionPane.showMessageDialog(this, "Por favor un acceso");
        }
    }//GEN-LAST:event_PanelDarBajaMouseClicked

    private void PanelDarBajaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelDarBajaMouseEntered
        // TODO add your handling code here:
        PanelDarBaja.setBackground(new Color (252, 168, 168));
        DarDeBaja.setForeground(Color.white);
    }//GEN-LAST:event_PanelDarBajaMouseEntered

    private void PanelDarBajaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelDarBajaMouseExited
        // TODO add your handling code here:
        PanelDarBaja.setBackground(Color.white);
        DarDeBaja.setForeground(new Color(215, 106, 106));
    }//GEN-LAST:event_PanelDarBajaMouseExited

    private void PanelDarDeAltaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelDarDeAltaMouseClicked
        // TODO add your handling code here:
        Accesos selecc=(Accesos) AccesosCombo.getSelectedItem();
        if (selecc!=null){
            int opcion=JOptionPane.showConfirmDialog(this, "¿Esta seguro de dar de alta a este acceso?"+JOptionPane.YES_NO_OPTION);
            if (opcion==JOptionPane.YES_OPTION){
                String id_selecc=selecc.getId_accesos();
                AccesosDAO ad=new AccesosDAO();
                boolean exito=ad.reactivar(id_selecc);
                if (exito){
                    Estados.setSelectedItem("Activo");
                    JOptionPane.showMessageDialog(this, "Modificado de manera correcta");
                    LimpiarDatos();                    
                }
                else{
                    JOptionPane.showMessageDialog(this, "Error al reactivar el acceso: "+selecc.getAccesos());
                }
            }
            else{
                JOptionPane.showMessageDialog(this, "Gracias por confirmar");
            }
        }
        else{
            JOptionPane.showMessageDialog(this, "Por favor escoga a un acceso");
        }
    }//GEN-LAST:event_PanelDarDeAltaMouseClicked

    private void PanelDarDeAltaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelDarDeAltaMouseEntered
        // TODO add your handling code here:
        PanelDarDeAlta.setBackground(new Color(219,219,219));
        PanelDarDeAlta.setForeground(new Color(66, 66, 66));
    }//GEN-LAST:event_PanelDarDeAltaMouseEntered

    private void PanelDarDeAltaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelDarDeAltaMouseExited
        // TODO add your handling code here:
        PanelDarDeAlta.setBackground(Color.white);
        PanelDarDeAlta.setForeground(Color.black);
    }//GEN-LAST:event_PanelDarDeAltaMouseExited

    private void AccesosComboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_AccesosComboItemStateChanged
        // TODO add your handling code here:
        Accesos accesoSeleccionado = (Accesos) AccesosCombo.getSelectedItem();
        if (accesoSeleccionado == null){
            JOptionPane.showMessageDialog(this, "Escoga para buscar");
            return;
        }

        PanelGuardar.setEnabled(false);
        TXTAcceso.setText(accesoSeleccionado.getAccesos());
        TXTDescripcion.setText(accesoSeleccionado.getDesc_persmisos());

        if(accesoSeleccionado.isEstado_acti_acceso()){
                Estados.setSelectedItem("Activo");
            }
            else{
                Estados.setSelectedItem("En pausa");
            }
        AccesosDAO accesosDAO = new AccesosDAO();
        List<Integer> indicesAMarcar = new ArrayList<>();

        javax.swing.ListModel<Tipos_de_usuario> modelo = TiposUsuarios.getModel();
        for (int i = 0; i < modelo.getSize(); i++) {
            Tipos_de_usuario tipo = modelo.getElementAt(i);
            if (accesosDAO.existeAcceso(accesoSeleccionado.getAccesos(), tipo.getId_tip_de_usuario())) {
                indicesAMarcar.add(i);
            }
        }

        int[] indicesArray = indicesAMarcar.stream().mapToInt(Integer::intValue).toArray();
        TiposUsuarios.setSelectedIndices(indicesArray);
    }//GEN-LAST:event_AccesosComboItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Accesos_del_sistema().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> AccesosCombo;
    private javax.swing.JPanel Barra;
    private javax.swing.JLabel Buscar;
    private javax.swing.JLabel DarDeAlta;
    private javax.swing.JLabel DarDeBaja;
    private javax.swing.JLabel Descripcion;
    private javax.swing.JLabel Editar;
    private javax.swing.JComboBox<String> Estados;
    private javax.swing.JLabel Guardar;
    private javax.swing.JLabel ImagenADD;
    private javax.swing.JLabel ImagenDarBaja;
    private javax.swing.JLabel ImagenRegresar;
    private javax.swing.JLabel ImagenSAVE;
    private javax.swing.JLabel MJ;
    private javax.swing.JPanel Menu;
    private javax.swing.JLabel NombreAcceso;
    private javax.swing.JLabel NombreAcceso1;
    private javax.swing.JLabel NombreAcceso2;
    private javax.swing.JLabel NombreAcceso3;
    private javax.swing.JLabel Nuevo;
    private javax.swing.JPanel PanelBuscar;
    private javax.swing.JPanel PanelDarBaja;
    private javax.swing.JPanel PanelDarDeAlta;
    private javax.swing.JPanel PanelEditar;
    private javax.swing.JPanel PanelGuardar;
    private javax.swing.JPanel PanelNuevo;
    private javax.swing.JLabel Regresar;
    private javax.swing.JTextField TXTAcceso;
    private javax.swing.JTextField TXTDescripcion;
    private javax.swing.JLabel Talleres;
    private javax.swing.JList<com.mycompany.proyecto_m2b.modelo.Tipos_de_usuario> TiposUsuarios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
