/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyecto_m2b.Vista;

import com.mycompany.proyecto_m2b.Controlador.AccesosDAO;
import com.mycompany.proyecto_m2b.Controlador.CargoDAO;
import com.mycompany.proyecto_m2b.Controlador.TipoUsuarioDAO;
import com.mycompany.proyecto_m2b.Controlador.Validaciones;
import com.mycompany.proyecto_m2b.modelo.Accesos;
import com.mycompany.proyecto_m2b.modelo.Cargo;
import com.mycompany.proyecto_m2b.modelo.Tipos_de_usuario;
import java.awt.Color;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author usuario
 */
public class Accesos_del_sistema extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Accesos_del_sistema.class.getName());

    /**
     * Creates new form Cargos
     */
    public Accesos_del_sistema() {
        initComponents();
        this.setLocationRelativeTo(null);
        List<Tipos_de_usuario> tipos = new TipoUsuarioDAO().listarTodos();
        TiposUsuarios.setListData(tipos.toArray(new Tipos_de_usuario[0]));
        TiposUsuarios.setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        Accesos acce= (Accesos) AccesosCombo.getSelectedItem();
        AccesosDAO ad=new AccesosDAO();
        ad.cargarAccesos(AccesosCombo);
        cargarTablaAccesos();
        jPanelBuscar.setVisible(false);
    }

    
    int xMouse;
    int yMouse;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Menu = new javax.swing.JPanel();
        Barra = new javax.swing.JPanel();
        MJ = new javax.swing.JLabel();
        Talleres = new javax.swing.JLabel();
        Regresar = new javax.swing.JLabel();
        ImagenRegresar = new javax.swing.JLabel();
        PanelNuevo = new javax.swing.JPanel();
        Nuevo = new javax.swing.JLabel();
        ImagenADD = new javax.swing.JLabel();
        PanelGuardar = new javax.swing.JPanel();
        Guardar = new javax.swing.JLabel();
        ImagenSAVE = new javax.swing.JLabel();
        PanelEditar = new javax.swing.JPanel();
        Editar = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        PanelBuscar = new javax.swing.JPanel();
        Buscar = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        NombreAcceso = new javax.swing.JLabel();
        TXTAcceso = new javax.swing.JTextField();
        Descripcion = new javax.swing.JLabel();
        TXTDescripcion = new javax.swing.JTextField();
        AccesosCombo = new javax.swing.JComboBox<>();
        Estados = new javax.swing.JComboBox<>();
        NombreAcceso1 = new javax.swing.JLabel();
        NombreAcceso2 = new javax.swing.JLabel();
        NombreAcceso3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TiposUsuarios = new javax.swing.JList<>();
        jPanelBuscar = new javax.swing.JPanel();
        Acceso = new javax.swing.JLabel();
        TXTFiltrarAcces = new javax.swing.JTextField();
        textoDescripcion = new javax.swing.JLabel();
        TXTFiltrarDescrip = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaAccesos = new javax.swing.JTable();
        estado = new javax.swing.JLabel();
        FiltrarEstados = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Menu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Barra.setBackground(new java.awt.Color(0, 0, 0));
        Barra.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                BarraMouseDragged(evt);
            }
        });
        Barra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BarraMousePressed(evt);
            }
        });

        MJ.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        MJ.setForeground(new java.awt.Color(152, 75, 45));
        MJ.setText("M&J");

        Talleres.setBackground(new java.awt.Color(152, 75, 45));
        Talleres.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Talleres.setForeground(new java.awt.Color(174, 63, 54));
        Talleres.setText("TALLERES");
        Talleres.setPreferredSize(new java.awt.Dimension(190, 47));

        Regresar.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        Regresar.setForeground(new java.awt.Color(145, 145, 145));
        Regresar.setText("Regresar");
        Regresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Regresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RegresarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                RegresarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                RegresarMouseExited(evt);
            }
        });

        ImagenRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/arrow_back_34dp_D9D9D9_FILL0_wght400_GRAD0_opsz40.png"))); // NOI18N
        ImagenRegresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ImagenRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ImagenRegresarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout BarraLayout = new javax.swing.GroupLayout(Barra);
        Barra.setLayout(BarraLayout);
        BarraLayout.setHorizontalGroup(
            BarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BarraLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Talleres, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MJ))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ImagenRegresar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Regresar)
                .addContainerGap())
        );
        BarraLayout.setVerticalGroup(
            BarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BarraLayout.createSequentialGroup()
                .addGroup(BarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(BarraLayout.createSequentialGroup()
                        .addComponent(MJ)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Talleres, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(BarraLayout.createSequentialGroup()
                        .addGroup(BarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(Regresar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ImagenRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(12, 12, 12)))
                .addGap(0, 12, Short.MAX_VALUE))
        );

        PanelNuevo.setBackground(new java.awt.Color(255, 255, 255));
        PanelNuevo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(187, 187, 187)));
        PanelNuevo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PanelNuevo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PanelNuevoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PanelNuevoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PanelNuevoMouseExited(evt);
            }
        });

        Nuevo.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        Nuevo.setText("Nuevo");

        ImagenADD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/add_22dp_000000_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N

        javax.swing.GroupLayout PanelNuevoLayout = new javax.swing.GroupLayout(PanelNuevo);
        PanelNuevo.setLayout(PanelNuevoLayout);
        PanelNuevoLayout.setHorizontalGroup(
            PanelNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelNuevoLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(ImagenADD)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Nuevo)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        PanelNuevoLayout.setVerticalGroup(
            PanelNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelNuevoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ImagenADD)
                    .addComponent(Nuevo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PanelGuardar.setBackground(new java.awt.Color(242, 101, 34));
        PanelGuardar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(187, 187, 187)));
        PanelGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PanelGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PanelGuardarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PanelGuardarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PanelGuardarMouseExited(evt);
            }
        });

        Guardar.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        Guardar.setForeground(new java.awt.Color(255, 255, 255));
        Guardar.setText("Guardar");

        ImagenSAVE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/save_22dp_FFFFFF_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N

        javax.swing.GroupLayout PanelGuardarLayout = new javax.swing.GroupLayout(PanelGuardar);
        PanelGuardar.setLayout(PanelGuardarLayout);
        PanelGuardarLayout.setHorizontalGroup(
            PanelGuardarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelGuardarLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(ImagenSAVE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Guardar)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        PanelGuardarLayout.setVerticalGroup(
            PanelGuardarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelGuardarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanelGuardarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Guardar)
                    .addComponent(ImagenSAVE))
                .addContainerGap())
        );

        PanelEditar.setBackground(new java.awt.Color(255, 255, 255));
        PanelEditar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(187, 187, 187)));
        PanelEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PanelEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PanelEditarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PanelEditarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PanelEditarMouseExited(evt);
            }
        });

        Editar.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        Editar.setText("Editar");

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/edit_22dp_000000_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N

        javax.swing.GroupLayout PanelEditarLayout = new javax.swing.GroupLayout(PanelEditar);
        PanelEditar.setLayout(PanelEditarLayout);
        PanelEditarLayout.setHorizontalGroup(
            PanelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelEditarLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Editar)
                .addContainerGap(36, Short.MAX_VALUE))
        );
        PanelEditarLayout.setVerticalGroup(
            PanelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelEditarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Editar)
                    .addComponent(jLabel2))
                .addContainerGap())
        );

        PanelBuscar.setBackground(new java.awt.Color(255, 255, 255));
        PanelBuscar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(187, 187, 187)));
        PanelBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PanelBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PanelBuscarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PanelBuscarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PanelBuscarMouseExited(evt);
            }
        });

        Buscar.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        Buscar.setText("Buscar");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/person_search_22dp_000000_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N

        javax.swing.GroupLayout PanelBuscarLayout = new javax.swing.GroupLayout(PanelBuscar);
        PanelBuscar.setLayout(PanelBuscarLayout);
        PanelBuscarLayout.setHorizontalGroup(
            PanelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelBuscarLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Buscar)
                .addContainerGap(36, Short.MAX_VALUE))
        );
        PanelBuscarLayout.setVerticalGroup(
            PanelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBuscarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Buscar)
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        NombreAcceso.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        NombreAcceso.setText("Nombre para el acceso:");

        TXTAcceso.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        TXTAcceso.setForeground(new java.awt.Color(94, 94, 94));
        TXTAcceso.setText("Acceso");
        TXTAcceso.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TXTAccesoFocusGained(evt);
            }
        });
        TXTAcceso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TXTAccesoMousePressed(evt);
            }
        });
        TXTAcceso.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TXTAccesoKeyPressed(evt);
            }
        });

        Descripcion.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        Descripcion.setText("Descripción:");

        TXTDescripcion.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        TXTDescripcion.setForeground(new java.awt.Color(94, 94, 94));
        TXTDescripcion.setText("Descripción");
        TXTDescripcion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TXTDescripcionFocusGained(evt);
            }
        });
        TXTDescripcion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TXTDescripcionMousePressed(evt);
            }
        });
        TXTDescripcion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TXTDescripcionKeyPressed(evt);
            }
        });

        AccesosCombo.addItemListener(this::AccesosComboItemStateChanged);
        AccesosCombo.addActionListener(this::AccesosComboActionPerformed);

        Estados.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una opción", "Activo", "En Pausa" }));

        NombreAcceso1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        NombreAcceso1.setText("Que usuario tendra este acceso:");

        NombreAcceso2.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        NombreAcceso2.setText("Estado del acceso:");

        NombreAcceso3.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        NombreAcceso3.setText("Accesos:");

        jScrollPane1.setViewportView(TiposUsuarios);

        jPanelBuscar.setBackground(new java.awt.Color(255, 213, 158));
        jPanelBuscar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        Acceso.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        Acceso.setText("Acceso:");

        TXTFiltrarAcces.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        TXTFiltrarAcces.setForeground(new java.awt.Color(94, 94, 94));
        TXTFiltrarAcces.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TXTFiltrarAccesFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TXTFiltrarAccesFocusLost(evt);
            }
        });
        TXTFiltrarAcces.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TXTFiltrarAccesMousePressed(evt);
            }
        });
        TXTFiltrarAcces.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TXTFiltrarAccesKeyReleased(evt);
            }
        });

        textoDescripcion.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        textoDescripcion.setText("Descripción:");

        TXTFiltrarDescrip.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        TXTFiltrarDescrip.setForeground(new java.awt.Color(94, 94, 94));
        TXTFiltrarDescrip.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TXTFiltrarDescripFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TXTFiltrarDescripFocusLost(evt);
            }
        });
        TXTFiltrarDescrip.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TXTFiltrarDescripMousePressed(evt);
            }
        });
        TXTFiltrarDescrip.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TXTFiltrarDescripKeyReleased(evt);
            }
        });

        tablaAccesos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tablaAccesos);

        estado.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        estado.setText("Estado:");

        FiltrarEstados.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "En pausa" }));
        FiltrarEstados.addItemListener(this::FiltrarEstadosItemStateChanged);
        FiltrarEstados.addActionListener(this::FiltrarEstadosActionPerformed);

        javax.swing.GroupLayout jPanelBuscarLayout = new javax.swing.GroupLayout(jPanelBuscar);
        jPanelBuscar.setLayout(jPanelBuscarLayout);
        jPanelBuscarLayout.setHorizontalGroup(
            jPanelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBuscarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelBuscarLayout.createSequentialGroup()
                        .addComponent(TXTFiltrarAcces, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(TXTFiltrarDescrip, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelBuscarLayout.createSequentialGroup()
                        .addComponent(Acceso)
                        .addGap(121, 121, 121)
                        .addComponent(textoDescripcion)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(estado)
                    .addComponent(FiltrarEstados, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(335, Short.MAX_VALUE))
            .addGroup(jPanelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelBuscarLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 785, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanelBuscarLayout.setVerticalGroup(
            jPanelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBuscarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Acceso)
                    .addComponent(textoDescripcion)
                    .addComponent(estado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(TXTFiltrarAcces, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(TXTFiltrarDescrip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(FiltrarEstados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(170, Short.MAX_VALUE))
            .addGroup(jPanelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelBuscarLayout.createSequentialGroup()
                    .addGap(73, 73, 73)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(10, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout MenuLayout = new javax.swing.GroupLayout(Menu);
        Menu.setLayout(MenuLayout);
        MenuLayout.setHorizontalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Barra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(MenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TXTDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 745, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Descripcion)
                    .addGroup(MenuLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanelBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(MenuLayout.createSequentialGroup()
                                .addComponent(PanelNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(PanelGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(PanelEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(PanelBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(MenuLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(NombreAcceso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TXTAcceso))
                .addGap(18, 18, 18)
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NombreAcceso1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AccesosCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NombreAcceso3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NombreAcceso2)
                    .addComponent(Estados, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        MenuLayout.setVerticalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addComponent(Barra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NombreAcceso)
                    .addComponent(NombreAcceso1)
                    .addComponent(NombreAcceso2)
                    .addComponent(NombreAcceso3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(TXTAcceso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(AccesosCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Estados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(Descripcion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TXTDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(PanelGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(PanelNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(PanelEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PanelBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanelBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RegresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegresarMouseClicked
        // TODO add your handling code here:
        Agregar A=new Agregar();
        A.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_RegresarMouseClicked

    private void RegresarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegresarMouseEntered
        // TODO add your handling code here:
        Regresar.setForeground(new Color(196, 196, 196));
    }//GEN-LAST:event_RegresarMouseEntered

    private void RegresarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegresarMouseExited
        // TODO add your handling code here:
        Regresar.setForeground(new Color(145, 145, 145));
    }//GEN-LAST:event_RegresarMouseExited

    private void PanelNuevoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelNuevoMouseClicked
        // TODO add your handling code here:
        LimpiarDatos();
        JOptionPane.showMessageDialog(this, "Datos limpiados correctamente"+"\n"
            +"Ingrese los datos");
    }//GEN-LAST:event_PanelNuevoMouseClicked

    private void PanelNuevoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelNuevoMouseEntered
        // TODO add your handling code here:
        PanelNuevo.setBackground(new Color(219,219,219));
        Nuevo.setForeground(new Color(66, 66, 66));
    }//GEN-LAST:event_PanelNuevoMouseEntered

    private void PanelNuevoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelNuevoMouseExited
        // TODO add your handling code here:
        PanelNuevo.setBackground(Color.white);
        Nuevo.setForeground(Color.black);
    }//GEN-LAST:event_PanelNuevoMouseExited

    private void PanelGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelGuardarMouseClicked
        // TODO add your handling code here:
        GuardarAcceso();
    }//GEN-LAST:event_PanelGuardarMouseClicked

    private void PanelGuardarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelGuardarMouseEntered
        // TODO add your handling code here:
        PanelGuardar.setBackground(new Color(227, 95, 32));
        Guardar.setForeground(new Color(217, 217, 192));
    }//GEN-LAST:event_PanelGuardarMouseEntered

    private void PanelGuardarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelGuardarMouseExited
        // TODO add your handling code here:
        PanelGuardar.setBackground(new Color(242,101,34));
        Guardar.setForeground(Color.white);
    }//GEN-LAST:event_PanelGuardarMouseExited

    private void PanelEditarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelEditarMouseEntered
        // TODO add your handling code here:
        PanelEditar.setBackground(new Color(219,219,219));
        Editar.setForeground(new Color(66, 66, 66));
    }//GEN-LAST:event_PanelEditarMouseEntered

    private void PanelEditarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelEditarMouseExited
        // TODO add your handling code here:
        PanelEditar.setBackground(Color.white);
        Editar.setForeground(Color.black);
    }//GEN-LAST:event_PanelEditarMouseExited

    private void PanelBuscarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelBuscarMouseEntered
        // TODO add your handling code here:
        PanelBuscar.setBackground(new Color(219,219,219));
        Buscar.setForeground(new Color(66, 66, 66));
    }//GEN-LAST:event_PanelBuscarMouseEntered

    private void PanelBuscarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelBuscarMouseExited
        // TODO add your handling code here:
        PanelBuscar.setBackground(Color.white);
        Buscar.setForeground(Color.black);
    }//GEN-LAST:event_PanelBuscarMouseExited

    private void TXTAccesoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TXTAccesoFocusGained
        // TODO add your handling code here:
        if (TXTAcceso.getText().equals("Acceso")){
            TXTAcceso.setText("");
            TXTAcceso.setForeground(Color.BLACK);
        }
        if (TXTDescripcion.getText().isEmpty()){
            TXTDescripcion.setText("Descripción");
            TXTDescripcion.setForeground(new Color (94, 94, 94));
        }
    }//GEN-LAST:event_TXTAccesoFocusGained

    public void GuardarAcceso (){
        Validaciones V=new Validaciones();
        String acceso=TXTAcceso.getText().trim().toUpperCase();
        String Descripcion=TXTDescripcion.getText().trim().toUpperCase();
        Object itemselecc=Estados.getSelectedItem();
        
        if (!guardarHabilitado){
            JOptionPane.showMessageDialog(this, "Actualmente esta viendo un acceso ya registrado\n"
                    + "Presione ''Nuevo'' si quiere registrar un nuevo acceso");
            return;
        }
        
        if (itemselecc==null || itemselecc.toString().equals("Seleccione una opción")){
            JOptionPane.showMessageDialog(this, "Escoga un estado");
            return;
        }        
        String estado=itemselecc.toString();        
        if (acceso.isEmpty() || Descripcion.isEmpty()){
            JOptionPane.showMessageDialog (this, "Por favor ingrese los datos correspondientes");
            return;
        }        
        if (acceso.isBlank() || Descripcion.isBlank()){
            JOptionPane.showMessageDialog (this, "Por favor ingrese los datos correspondientes");
            return;
        }
        if(!V.validarAcceso(acceso) || !V.validarDescripcionAccesos(Descripcion)){
            LimpiarDatos();
            JOptionPane.showMessageDialog(this, "Por favor ingrese los datos de manera correcta \n"
                    + "(Acceso maximo 10 caracteres y Descripcion máximo 80 caracteres)");
            return;
        }
        if (acceso.equalsIgnoreCase("Acceso") || Descripcion.equalsIgnoreCase("Descripción")){
            JOptionPane.showMessageDialog(this, "Por favor ingrese los datos de manera correcta");
            return;
        }

        List <Tipos_de_usuario> seleccionados = TiposUsuarios.getSelectedValuesList();
        if (seleccionados.isEmpty()){
            JOptionPane.showMessageDialog(this, "Por favor escoga al menos un tipo de usuario");
            return;
        }
        AccesosDAO ad=new AccesosDAO();
        int agregados=0;
        boolean estadoActi=estado.equalsIgnoreCase("Activo");
        
        for (Tipos_de_usuario tipo : seleccionados){
            Accesos existeBD = ad.buscarAccesoEspecifico(acceso, tipo.getId_tip_de_usuario());
            if (existeBD == null){
            Accesos acce=new Accesos(); 
            acce.setAccesos(acceso);
            acce.setDesc_persmisos(Descripcion);
            acce.setId_tip_usuario(tipo.getId_tip_de_usuario());            
            acce.setEstado_acti_acceso(estadoActi);
            ad.insertarAccesos(acce);
            agregados++;
            }
            else if (existeBD.isEstado_acti_acceso() != estadoActi){
                existeBD.setEstado_acti_acceso(estadoActi);                
                existeBD.setDesc_persmisos(Descripcion);                                
                ad.actualizarConEstado(existeBD);
                agregados++;
            }
            else{
                continue;
            }                        
        }
        if (agregados>0){
            JOptionPane.showMessageDialog(this, "Se ha guardado correctamente el acceso para "+agregados+" tipo/s de usuario/s");
            LimpiarDatos();
        }
        else{
            JOptionPane.showMessageDialog(this, "Ese acceso ya ha estado disponible para todos los usuarios");
        }                
    }
    public void LimpiarDatos (){
        TXTAcceso.setText("Acceso");
        TXTAcceso.setForeground(new Color (94, 94, 94));
        TXTDescripcion.setText("Descripción");
        TXTDescripcion.setForeground(new Color (94, 94, 94));
        TiposUsuarios.clearSelection();
        Estados.setSelectedIndex(0);
        AccesosCombo.setSelectedIndex(0);
        PanelGuardar.setEnabled(true);
        guardarHabilitado=true;
        accesoSeleccionado=null;
        TXTAcceso.setEnabled(true);
    }
    private void TXTAccesoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TXTAccesoMousePressed
        // TODO add your handling code here:
        if (TXTAcceso.getText().equals("Acceso")){
            TXTAcceso.setText("");
            TXTAcceso.setForeground(Color.BLACK);
        }
        if (TXTDescripcion.getText().isEmpty()){
            TXTDescripcion.setText("Descripción");
            TXTDescripcion.setForeground(new Color (94, 94, 94));
        }
    }//GEN-LAST:event_TXTAccesoMousePressed

    private void TXTAccesoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXTAccesoKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER){
            GuardarAcceso();
        }
    }//GEN-LAST:event_TXTAccesoKeyPressed

    private void TXTDescripcionFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TXTDescripcionFocusGained
        // TODO add your handling code here:
        if (TXTDescripcion.getText().equals("Descripción")){
            TXTDescripcion.setText("");
            TXTDescripcion.setForeground(Color.BLACK);
        }
        if (TXTAcceso.getText().isEmpty()){
            TXTAcceso.setText("Acceso");
            TXTAcceso.setForeground(new Color (94, 94, 94));
        }
    }//GEN-LAST:event_TXTDescripcionFocusGained

    private void TXTDescripcionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TXTDescripcionMousePressed
        // TODO add your handling code here:
        if (TXTDescripcion.getText().equals("Descripción")){
            TXTDescripcion.setText("");
            TXTDescripcion.setForeground(Color.BLACK);
        }
        if (TXTAcceso.getText().isEmpty()){
            TXTAcceso.setText("Acceso");
            TXTAcceso.setForeground(new Color (94, 94, 94));
        }
    }//GEN-LAST:event_TXTDescripcionMousePressed

    private void TXTDescripcionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXTDescripcionKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER){
            GuardarAcceso();
        }
    }//GEN-LAST:event_TXTDescripcionKeyPressed

    private void ImagenRegresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ImagenRegresarMouseClicked
        // TODO add your handling code here:
        Agregar A=new Agregar();
        A.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ImagenRegresarMouseClicked

    private void BarraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BarraMousePressed
        // TODO add your handling code here:
        xMouse=evt.getX();
        yMouse=evt.getY();
    }//GEN-LAST:event_BarraMousePressed

    private void BarraMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BarraMouseDragged
        // TODO add your handling code here:
        int x=evt.getXOnScreen();
        int y=evt.getYOnScreen();
        this.setLocation(x-xMouse, y-yMouse);
    }//GEN-LAST:event_BarraMouseDragged

    public void cargarTablaAccesos(){
        
    }
    public void cargarTablaAccesos(String Nom_acceso, String descrip_acceso, boolean estado_selecc) {
        
        AccesosDAO ad = new AccesosDAO();
        
        List<Accesos> lista = ad.buscarAcceso(Nom_acceso, descrip_acceso, estado_selecc);
        
        String[] columnas = {"ID", "Acceso", "Descripción", "Tipo de usuario", "Estado"};
        
        DefaultTableModel modelo = new DefaultTableModel(null, columnas);
        
        for (Accesos acceso : lista) {
            String estado;
            
            if (acceso.isEstado_acti_acceso()) {
                estado = "Activo";
            } else {
                estado = "En pausa";
            }
            
            Object[] fila = {
                acceso.getId_accesos(),
                acceso.getAccesos(),
                acceso.getDesc_persmisos(),
                acceso.getId_tip_usuario(),
                estado
            };
            modelo.addRow(fila);
        }
        tablaAccesos.setModel(modelo);
    }
    
    public void editarAcceso() {
        if (accesoSeleccionado == null || "Seleccione una opción".equals(accesoSeleccionado.getAccesos())) {
            JOptionPane.showMessageDialog(this, "Seleccione un acceso para poder editar");
            return;
        }
        Validaciones validaciones = new Validaciones();
        
        String codigoAcceso = accesoSeleccionado.getAccesos();
        String descripcionNueva = TXTDescripcion.getText().trim().toUpperCase();
        Object itemEstado = Estados.getSelectedItem();
        
        if (itemEstado == null || itemEstado.toString().equals("Seleccione una opción")) {
            JOptionPane.showMessageDialog(this, "Escoja un estado");
            return;
        }
        
        if (descripcionNueva.isEmpty()) {
            JOptionPane.showMessageDialog(this,"Ingrese correctamente los datos");
            return;
        }

        if (descripcionNueva.equalsIgnoreCase("Descripción")){
            JOptionPane.showMessageDialog(this, "Ingrese los datos correctamente");
            return;
        }
        
        if (!validaciones.validarDescripcionAccesos(descripcionNueva)) {
            JOptionPane.showMessageDialog(this, "Ingrese los datos de manera correcta \n"
                    + "(Descripcion máximo 80 caracteres)");
            return;
        }
        
        List<Tipos_de_usuario> tiposSeleccionados = TiposUsuarios.getSelectedValuesList();
        
        if (tiposSeleccionados.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Seleccione al menos un tipo de usuario");
            return;
        }
        
        boolean estadoActivo = itemEstado.toString().equalsIgnoreCase("Activo");
        
        AccesosDAO ad = new AccesosDAO();
        
        List<Accesos> accesosActuales = ad.listarPorCodigo(codigoAcceso);
        
        if (accesosActuales.isEmpty()){
            JOptionPane.showMessageDialog(this, "No hay tipos seleccionados para este tipo de acceso");
            return;
        }
        
        Set<String> idsTiposSeleccionados = new HashSet<>();
        
        for (Tipos_de_usuario tipo : tiposSeleccionados) {
            idsTiposSeleccionados.add(tipo.getId_tip_de_usuario());
        }
        
        Set<String> idsTiposActuales = new HashSet<>();
        
        for (Accesos accesoActual : accesosActuales) {
            String idTipo = accesoActual.getId_tip_usuario();
            
            idsTiposActuales.add(idTipo);
            
            if (idsTiposSeleccionados.contains(idTipo)) {
                accesoActual.setDesc_persmisos(descripcionNueva);
                accesoActual.setEstado_acti_acceso(estadoActivo);
                
                ad.actualizarConEstado(accesoActual);
            } else {
                ad.eliminar(accesoActual.getId_accesos());
            }
        }
        
        for (Tipos_de_usuario tipo : tiposSeleccionados) {
            String idTipo = tipo.getId_tip_de_usuario();
            
            if (!idsTiposActuales.contains(idTipo)) {
                Accesos nuevoAcceso = new Accesos();
                
                nuevoAcceso.setAccesos(codigoAcceso);
                nuevoAcceso.setDesc_persmisos(descripcionNueva);
                nuevoAcceso.setId_tip_usuario(idTipo);
                nuevoAcceso.setEstado_acti_acceso(estadoActivo);
                
                ad.insertarAccesos(nuevoAcceso);
            }
        }

        JOptionPane.showMessageDialog(this, "Acceso actualizado correctamente.");
        
        accesoSeleccionado = null;
        LimpiarDatos();
    }
    
    private void PanelEditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelEditarMouseClicked
        // TODO add your handling code here:        
        Accesos ac= (Accesos) AccesosCombo.getSelectedItem();
        if(ac==null){
            JOptionPane.showMessageDialog(this, "Escoga una opción");
        }
        else{
            int opcion=JOptionPane.showConfirmDialog(this, "¿Quiere modificar el acceso?","Confirmar",JOptionPane.YES_NO_OPTION);
            if(opcion==JOptionPane.YES_OPTION){
                editarAcceso();
                LimpiarDatos();
                AccesosDAO ad=new AccesosDAO();
                ad.cargarAccesos(AccesosCombo);
            }
            else{
                JOptionPane.showMessageDialog(this, "Gracias por confirmar");
            }
        }
    }//GEN-LAST:event_PanelEditarMouseClicked

    public boolean guardarHabilitado;
    public Accesos accesoSeleccionado;
    
    private void cambiarEstadoGuardar(boolean habilitado) {
        guardarHabilitado = habilitado;

        PanelGuardar.setEnabled(habilitado);

        if (habilitado) {
            PanelGuardar.setBackground(new Color(242,101,34));
            PanelGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR)
            );
        } else {
            PanelGuardar.setBackground(new Color(242,101,34));
            PanelGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR)
            );
        }
    }
    
    private void AccesosComboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_AccesosComboItemStateChanged
        // TODO add your handling code here:
        //Esta parte del código sirve paras que no se disparo el evento dos veces de manera inecesaria, solamente cuando se escoga una seleccion del comboBox de Accesos
        if (evt.getStateChange() != java.awt.event.ItemEvent.SELECTED) {
            return;
        }
        accesoSeleccionado = (Accesos) AccesosCombo.getSelectedItem();
        if (accesoSeleccionado == null || accesoSeleccionado.getAccesos().equalsIgnoreCase("Seleccione una opción")){
            cambiarEstadoGuardar(true);
            TXTAcceso.setText("");
            TXTAcceso.setEnabled(true);
            TXTDescripcion.setText("");
            TiposUsuarios.clearSelection();
            return;  
        }

        cambiarEstadoGuardar(false);
        TXTAcceso.setText(accesoSeleccionado.getAccesos());
        TXTAcceso.setEnabled(false);
        TXTDescripcion.setText(accesoSeleccionado.getDesc_persmisos());

        if(accesoSeleccionado.isEstado_acti_acceso()){
                Estados.setSelectedItem("Activo");
            }
            else{
                Estados.setSelectedItem("En pausa");
            }
        AccesosDAO accesosDAO = new AccesosDAO();
        List<Integer> indicesAMarcar = new ArrayList<>();

        javax.swing.ListModel<Tipos_de_usuario> modelo = TiposUsuarios.getModel();
        for (int i = 0; i < modelo.getSize(); i++) {
            Tipos_de_usuario tipo = modelo.getElementAt(i);
            if (accesosDAO.existeAcceso(accesoSeleccionado.getAccesos(), tipo.getId_tip_de_usuario())) {
                indicesAMarcar.add(i);
            }
        }

        int[] indicesArray = indicesAMarcar.stream().mapToInt(Integer::intValue).toArray();
        TiposUsuarios.setSelectedIndices(indicesArray);
    }//GEN-LAST:event_AccesosComboItemStateChanged

    private void AccesosComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AccesosComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AccesosComboActionPerformed

    private void TXTFiltrarAccesFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TXTFiltrarAccesFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTFiltrarAccesFocusGained

    private void TXTFiltrarAccesFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TXTFiltrarAccesFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTFiltrarAccesFocusLost

    private void TXTFiltrarAccesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TXTFiltrarAccesMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTFiltrarAccesMousePressed

    private void TXTFiltrarAccesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXTFiltrarAccesKeyReleased
        // TODO add your handling code here:
        String NomAcceso=TXTFiltrarAcces.getText().trim().toUpperCase();
        String descripcion=TXTFiltrarDescrip.getText().trim().toUpperCase();
        String estadoSelecc=FiltrarEstados.getSelectedItem().toString();
        boolean estado;
        if(estadoSelecc.equalsIgnoreCase("Activo")){
            estado=true;
        }
        else{
            estado=false;
        }
        cargarTablaAccesos(NomAcceso, descripcion, estado);
    }//GEN-LAST:event_TXTFiltrarAccesKeyReleased

    private void TXTFiltrarDescripFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TXTFiltrarDescripFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTFiltrarDescripFocusGained

    private void TXTFiltrarDescripFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TXTFiltrarDescripFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTFiltrarDescripFocusLost

    private void TXTFiltrarDescripMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TXTFiltrarDescripMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTFiltrarDescripMousePressed

    private void TXTFiltrarDescripKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXTFiltrarDescripKeyReleased
        // TODO add your handling code here:
        String NomAcceso=TXTFiltrarAcces.getText().trim().toUpperCase();
        String descripcion=TXTFiltrarDescrip.getText().trim().toUpperCase();
        String estadoSelecc=FiltrarEstados.getSelectedItem().toString();
        boolean estado;
        if(estadoSelecc.equalsIgnoreCase("Activo")){
            estado=true;
        }
        else{
            estado=false;
        }
        cargarTablaAccesos(NomAcceso, descripcion, estado);
    }//GEN-LAST:event_TXTFiltrarDescripKeyReleased

    private void PanelBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelBuscarMouseClicked
        // TODO add your handling code here:
        if (jPanelBuscar.isVisible()){
            jPanelBuscar.setVisible(false);
        }
        else{
            jPanelBuscar.setVisible(true);
        }
    }//GEN-LAST:event_PanelBuscarMouseClicked

    private void FiltrarEstadosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_FiltrarEstadosItemStateChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_FiltrarEstadosItemStateChanged

    private void FiltrarEstadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FiltrarEstadosActionPerformed
        // TODO add your handling code here:
        String NomAcceso=TXTFiltrarAcces.getText().trim().toUpperCase();
        String descripcion=TXTFiltrarDescrip.getText().trim().toUpperCase();
        String estadoSelecc=FiltrarEstados.getSelectedItem().toString();
        boolean estado;
        if(estadoSelecc.equalsIgnoreCase("Activo")){
            estado=true;
        }
        else{
            estado=false;
        }
        cargarTablaAccesos(NomAcceso, descripcion, estado);
    }//GEN-LAST:event_FiltrarEstadosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Accesos_del_sistema().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Acceso;
    private javax.swing.JComboBox<String> AccesosCombo;
    private javax.swing.JPanel Barra;
    private javax.swing.JLabel Buscar;
    private javax.swing.JLabel Descripcion;
    private javax.swing.JLabel Editar;
    private javax.swing.JComboBox<String> Estados;
    private javax.swing.JComboBox<String> FiltrarEstados;
    private javax.swing.JLabel Guardar;
    private javax.swing.JLabel ImagenADD;
    private javax.swing.JLabel ImagenRegresar;
    private javax.swing.JLabel ImagenSAVE;
    private javax.swing.JLabel MJ;
    private javax.swing.JPanel Menu;
    private javax.swing.JLabel NombreAcceso;
    private javax.swing.JLabel NombreAcceso1;
    private javax.swing.JLabel NombreAcceso2;
    private javax.swing.JLabel NombreAcceso3;
    private javax.swing.JLabel Nuevo;
    private javax.swing.JPanel PanelBuscar;
    private javax.swing.JPanel PanelEditar;
    private javax.swing.JPanel PanelGuardar;
    private javax.swing.JPanel PanelNuevo;
    private javax.swing.JLabel Regresar;
    private javax.swing.JTextField TXTAcceso;
    private javax.swing.JTextField TXTDescripcion;
    private javax.swing.JTextField TXTFiltrarAcces;
    private javax.swing.JTextField TXTFiltrarDescrip;
    private javax.swing.JLabel Talleres;
    private javax.swing.JList<com.mycompany.proyecto_m2b.modelo.Tipos_de_usuario> TiposUsuarios;
    private javax.swing.JLabel estado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanelBuscar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tablaAccesos;
    private javax.swing.JLabel textoDescripcion;
    // End of variables declaration//GEN-END:variables
}
