/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyecto_m2b.Vista;

import com.mycompany.proyecto_m2b.Controlador.CargoDAO;
import com.mycompany.proyecto_m2b.Controlador.Validaciones;
import com.mycompany.proyecto_m2b.modelo.Cargo;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author usuario
 */
public class Cargos extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Cargos.class.getName());

    /**
     * Creates new form Cargos
     */
    public Cargos() {
        initComponents();
        this.setLocationRelativeTo(null);
        CargoDAO cd=new CargoDAO();
        cd.cargarCargos(Cargos);
    }

    int xMouse;
    int yMouse;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Menu = new javax.swing.JPanel();
        Barra = new javax.swing.JPanel();
        MJ = new javax.swing.JLabel();
        Talleres = new javax.swing.JLabel();
        Regresar = new javax.swing.JLabel();
        ImagenRegresar = new javax.swing.JLabel();
        PanelNuevo = new javax.swing.JPanel();
        Nuevo = new javax.swing.JLabel();
        ImagenADD = new javax.swing.JLabel();
        PanelGuardar = new javax.swing.JPanel();
        Guardar = new javax.swing.JLabel();
        ImagenSAVE = new javax.swing.JLabel();
        PanelEditar = new javax.swing.JPanel();
        Editar = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        NombreCargo = new javax.swing.JLabel();
        TXTCargo = new javax.swing.JTextField();
        Descripcion = new javax.swing.JLabel();
        TXTDescripcion = new javax.swing.JTextField();
        Cargos = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Menu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Barra.setBackground(new java.awt.Color(0, 0, 0));
        Barra.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                BarraMouseDragged(evt);
            }
        });
        Barra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BarraMousePressed(evt);
            }
        });

        MJ.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        MJ.setForeground(new java.awt.Color(152, 75, 45));
        MJ.setText("M&J");

        Talleres.setBackground(new java.awt.Color(152, 75, 45));
        Talleres.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Talleres.setForeground(new java.awt.Color(174, 63, 54));
        Talleres.setText("TALLERES");
        Talleres.setPreferredSize(new java.awt.Dimension(190, 47));

        Regresar.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        Regresar.setForeground(new java.awt.Color(145, 145, 145));
        Regresar.setText("Regresar");
        Regresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Regresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RegresarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                RegresarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                RegresarMouseExited(evt);
            }
        });

        ImagenRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/arrow_back_34dp_D9D9D9_FILL0_wght400_GRAD0_opsz40.png"))); // NOI18N
        ImagenRegresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ImagenRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ImagenRegresarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout BarraLayout = new javax.swing.GroupLayout(Barra);
        Barra.setLayout(BarraLayout);
        BarraLayout.setHorizontalGroup(
            BarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BarraLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Talleres, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MJ))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ImagenRegresar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Regresar)
                .addContainerGap())
        );
        BarraLayout.setVerticalGroup(
            BarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BarraLayout.createSequentialGroup()
                .addGroup(BarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(BarraLayout.createSequentialGroup()
                        .addComponent(MJ)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Talleres, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(BarraLayout.createSequentialGroup()
                        .addGroup(BarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(Regresar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ImagenRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(12, 12, 12)))
                .addGap(0, 12, Short.MAX_VALUE))
        );

        PanelNuevo.setBackground(new java.awt.Color(255, 255, 255));
        PanelNuevo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(187, 187, 187)));
        PanelNuevo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PanelNuevo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PanelNuevoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PanelNuevoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PanelNuevoMouseExited(evt);
            }
        });

        Nuevo.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        Nuevo.setText("Nuevo");

        ImagenADD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/add_22dp_000000_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N

        javax.swing.GroupLayout PanelNuevoLayout = new javax.swing.GroupLayout(PanelNuevo);
        PanelNuevo.setLayout(PanelNuevoLayout);
        PanelNuevoLayout.setHorizontalGroup(
            PanelNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelNuevoLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(ImagenADD)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Nuevo)
                .addContainerGap(33, Short.MAX_VALUE))
        );
        PanelNuevoLayout.setVerticalGroup(
            PanelNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelNuevoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ImagenADD)
                    .addComponent(Nuevo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PanelGuardar.setBackground(new java.awt.Color(242, 101, 34));
        PanelGuardar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(187, 187, 187)));
        PanelGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PanelGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PanelGuardarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PanelGuardarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PanelGuardarMouseExited(evt);
            }
        });

        Guardar.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        Guardar.setForeground(new java.awt.Color(255, 255, 255));
        Guardar.setText("Guardar");

        ImagenSAVE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/save_22dp_FFFFFF_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N

        javax.swing.GroupLayout PanelGuardarLayout = new javax.swing.GroupLayout(PanelGuardar);
        PanelGuardar.setLayout(PanelGuardarLayout);
        PanelGuardarLayout.setHorizontalGroup(
            PanelGuardarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelGuardarLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(ImagenSAVE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Guardar)
                .addContainerGap(36, Short.MAX_VALUE))
        );
        PanelGuardarLayout.setVerticalGroup(
            PanelGuardarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelGuardarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanelGuardarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Guardar)
                    .addComponent(ImagenSAVE))
                .addContainerGap())
        );

        PanelEditar.setBackground(new java.awt.Color(255, 255, 255));
        PanelEditar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(187, 187, 187)));
        PanelEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PanelEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PanelEditarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PanelEditarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PanelEditarMouseExited(evt);
            }
        });

        Editar.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        Editar.setText("Editar");

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/edit_22dp_000000_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N

        javax.swing.GroupLayout PanelEditarLayout = new javax.swing.GroupLayout(PanelEditar);
        PanelEditar.setLayout(PanelEditarLayout);
        PanelEditarLayout.setHorizontalGroup(
            PanelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelEditarLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Editar)
                .addContainerGap(33, Short.MAX_VALUE))
        );
        PanelEditarLayout.setVerticalGroup(
            PanelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelEditarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Editar)
                    .addComponent(jLabel2))
                .addContainerGap())
        );

        NombreCargo.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        NombreCargo.setText("Nombre del cargo:");

        TXTCargo.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        TXTCargo.setForeground(new java.awt.Color(94, 94, 94));
        TXTCargo.setText("Cargo");
        TXTCargo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TXTCargoFocusGained(evt);
            }
        });
        TXTCargo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TXTCargoMousePressed(evt);
            }
        });
        TXTCargo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TXTCargoKeyPressed(evt);
            }
        });

        Descripcion.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        Descripcion.setText("Descripción:");

        TXTDescripcion.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        TXTDescripcion.setForeground(new java.awt.Color(94, 94, 94));
        TXTDescripcion.setText("Descripción");
        TXTDescripcion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TXTDescripcionFocusGained(evt);
            }
        });
        TXTDescripcion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TXTDescripcionMousePressed(evt);
            }
        });
        TXTDescripcion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TXTDescripcionKeyPressed(evt);
            }
        });

        Cargos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Cargos.addItemListener(this::CargosItemStateChanged);

        javax.swing.GroupLayout MenuLayout = new javax.swing.GroupLayout(Menu);
        Menu.setLayout(MenuLayout);
        MenuLayout.setHorizontalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Barra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(MenuLayout.createSequentialGroup()
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(MenuLayout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addComponent(TXTDescripcion))
                        .addGroup(MenuLayout.createSequentialGroup()
                            .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(MenuLayout.createSequentialGroup()
                                    .addGap(17, 17, 17)
                                    .addComponent(NombreCargo))
                                .addGroup(MenuLayout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(TXTCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(51, 51, 51)
                                    .addComponent(Cargos, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(MenuLayout.createSequentialGroup()
                                    .addGap(17, 17, 17)
                                    .addComponent(Descripcion)))
                            .addGap(185, 185, 185)))
                    .addGroup(MenuLayout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(PanelNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PanelGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PanelEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        MenuLayout.setVerticalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addComponent(Barra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NombreCargo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TXTCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Cargos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Descripcion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TXTDescripcion, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PanelGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );

        getContentPane().add(Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RegresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegresarMouseClicked
        // TODO add your handling code here:
        Agregar A=new Agregar();
        A.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_RegresarMouseClicked

    private void RegresarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegresarMouseEntered
        // TODO add your handling code here:
        Regresar.setForeground(new Color(196, 196, 196));
    }//GEN-LAST:event_RegresarMouseEntered

    private void RegresarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegresarMouseExited
        // TODO add your handling code here:
        Regresar.setForeground(new Color(145, 145, 145));
    }//GEN-LAST:event_RegresarMouseExited

    private void PanelNuevoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelNuevoMouseClicked
        // TODO add your handling code here:
        LimpiarDatos();
        JOptionPane.showMessageDialog(this, "Datos limpiados correctamente"+"\n"
            +"Ingrese los datos");
    }//GEN-LAST:event_PanelNuevoMouseClicked

    private void PanelNuevoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelNuevoMouseEntered
        // TODO add your handling code here:
        PanelNuevo.setBackground(new Color(219,219,219));
        Nuevo.setForeground(new Color(66, 66, 66));
    }//GEN-LAST:event_PanelNuevoMouseEntered

    private void PanelNuevoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelNuevoMouseExited
        // TODO add your handling code here:
        PanelNuevo.setBackground(Color.white);
        Nuevo.setForeground(Color.black);
    }//GEN-LAST:event_PanelNuevoMouseExited

    private void PanelGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelGuardarMouseClicked
        // TODO add your handling code here:
        GuardarCargo();
    }//GEN-LAST:event_PanelGuardarMouseClicked

    private void PanelGuardarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelGuardarMouseEntered
        // TODO add your handling code here:
        PanelGuardar.setBackground(new Color(227, 95, 32));
        Guardar.setForeground(new Color(217, 217, 192));
    }//GEN-LAST:event_PanelGuardarMouseEntered

    private void PanelGuardarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelGuardarMouseExited
        // TODO add your handling code here:
        PanelGuardar.setBackground(new Color(242,101,34));
        Guardar.setForeground(Color.white);
    }//GEN-LAST:event_PanelGuardarMouseExited

    private void PanelEditarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelEditarMouseEntered
        // TODO add your handling code here:
        PanelEditar.setBackground(new Color(219,219,219));
        Editar.setForeground(new Color(66, 66, 66));
    }//GEN-LAST:event_PanelEditarMouseEntered

    private void PanelEditarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelEditarMouseExited
        // TODO add your handling code here:
        PanelEditar.setBackground(Color.white);
        Editar.setForeground(Color.black);
    }//GEN-LAST:event_PanelEditarMouseExited

    private void TXTCargoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TXTCargoFocusGained
        // TODO add your handling code here:
        if (TXTCargo.getText().equals("Cargo")){
            TXTCargo.setText("");
            TXTCargo.setForeground(Color.BLACK);
        }
        if (TXTDescripcion.getText().isEmpty()){
            TXTDescripcion.setText("Descripción");
            TXTDescripcion.setForeground(new Color (94, 94, 94));
        }
    }//GEN-LAST:event_TXTCargoFocusGained

    public void GuardarCargo (){
        Validaciones V=new Validaciones();
        String Cargo=TXTCargo.getText().trim();
        String Descripcion=TXTDescripcion.getText().trim();
        if (Cargo.isEmpty() || Descripcion.isEmpty()){
            JOptionPane.showMessageDialog (this, "Por favor ingrese los datos correspondientes");
            return;
        }
        if (Cargo.isBlank() || Descripcion.isBlank()){
            JOptionPane.showMessageDialog (this, "Por favor ingrese los datos correspondientes");
            return;
        }
        if(!V.validarCargo(Cargo) || !V.validarDescripcionCargo(Descripcion)){
            LimpiarDatos();
            JOptionPane.showMessageDialog(this, "Por favor ingrese los datos de manera correcta");
            return;
        }
        if (Cargo.equalsIgnoreCase("Cargo") || Descripcion.equalsIgnoreCase("Descripción")){
            JOptionPane.showMessageDialog(this, "Pro favor ingrese los datos de manera correcta");
            return;
        }
        //Se guarda el cargo en la base
        Cargo cargo=new Cargo(Cargo, Descripcion);
        CargoDAO cd=new CargoDAO();
        cd.insertarCargo(cargo);
        JOptionPane.showMessageDialog(this, "Se ha guardado correctamente el cargo");
        LimpiarDatos();
    }
    public void LimpiarDatos (){
        TXTCargo.setText("Cargo");
        TXTCargo.setForeground(new Color (94, 94, 94));
        TXTDescripcion.setText("Descripción");
        TXTDescripcion.setForeground(new Color (94, 94, 94));
    }
    private void TXTCargoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TXTCargoMousePressed
        // TODO add your handling code here:
        if (TXTCargo.getText().equals("Cargo")){
            TXTCargo.setText("");
            TXTCargo.setForeground(Color.BLACK);
        }
        if (TXTDescripcion.getText().isEmpty()){
            TXTDescripcion.setText("Descripción");
            TXTDescripcion.setForeground(new Color (94, 94, 94));
        }
    }//GEN-LAST:event_TXTCargoMousePressed

    private void TXTCargoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXTCargoKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER){
            GuardarCargo();
        }
    }//GEN-LAST:event_TXTCargoKeyPressed

    private void TXTDescripcionFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TXTDescripcionFocusGained
        // TODO add your handling code here:
        if (TXTDescripcion.getText().equals("Descripción")){
            TXTDescripcion.setText("");
            TXTDescripcion.setForeground(Color.BLACK);
        }
        if (TXTCargo.getText().isEmpty()){
            TXTCargo.setText("Cargo");
            TXTCargo.setForeground(new Color (94, 94, 94));
        }
    }//GEN-LAST:event_TXTDescripcionFocusGained

    private void TXTDescripcionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TXTDescripcionMousePressed
        // TODO add your handling code here:
        if (TXTDescripcion.getText().equals("Descripción")){
            TXTDescripcion.setText("");
            TXTDescripcion.setForeground(Color.BLACK);
        }
        if (TXTCargo.getText().isEmpty()){
            TXTCargo.setText("Cargo");
            TXTCargo.setForeground(new Color (94, 94, 94));
        }
    }//GEN-LAST:event_TXTDescripcionMousePressed

    private void TXTDescripcionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXTDescripcionKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER){
            GuardarCargo();
        }
    }//GEN-LAST:event_TXTDescripcionKeyPressed

    private void ImagenRegresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ImagenRegresarMouseClicked
        // TODO add your handling code here:
        Agregar A=new Agregar();
        A.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ImagenRegresarMouseClicked

    private void BarraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BarraMousePressed
        // TODO add your handling code here:
        xMouse=evt.getX();
        yMouse=evt.getY();
    }//GEN-LAST:event_BarraMousePressed

    private void BarraMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BarraMouseDragged
        // TODO add your handling code here:
        int x=evt.getXOnScreen();
        int y=evt.getYOnScreen();
        this.setLocation(x-xMouse, y-yMouse);
    }//GEN-LAST:event_BarraMouseDragged

    public void ModificarCargos (){
        Validaciones V=new Validaciones();
        String Cargo=TXTCargo.getText().trim();
        String Descrip=TXTDescripcion.getText().trim();
        Cargo car=(Cargo) Cargos.getSelectedItem();
        if (car==null){
            JOptionPane.showMessageDialog(this, "Por favor seleccione un cargo para modificar");
            return;
        }
        if (Cargo.isEmpty() || Descrip.isEmpty()){
            JOptionPane.showMessageDialog (this, "Por favor ingrese los datos correspondientes");
            return;
        }
        if (Cargo.isBlank() || Descrip.isBlank()){
            JOptionPane.showMessageDialog (this, "Por favor ingrese los datos correspondientes");
            return;
        }
        if(!V.validarCargo(Cargo) || !V.validarDescripcionCargo(Descrip)){
            LimpiarDatos();
            JOptionPane.showMessageDialog(this, "P favor ingrese los datos de manera correcta");
            return;
        }
        if (Cargo.equalsIgnoreCase("Cargo") || Descrip.equalsIgnoreCase("Descripción")){
            JOptionPane.showMessageDialog(this, "Por favor ingrese los datos de manera correcta");
            return;
        }
        Cargo cargo=new Cargo();
        cargo.setNom_cargo(Cargo);
        cargo.setDescrip_cargo(Descrip);
        CargoDAO cd=new CargoDAO();
        
        cargo.setID_cargo(car.getID_cargo());
        cd.modificarCargo(cargo);
        JOptionPane.showMessageDialog(this, "Se ha actualizado de manera correcta");
    }
    private void PanelEditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelEditarMouseClicked
        // TODO add your handling code here:        
        Cargo car= (Cargo) Cargos.getSelectedItem();
        if(car==null){
            JOptionPane.showMessageDialog(this, "Escoga una opción");
        }
        else{
            int opcion=JOptionPane.showConfirmDialog(this, "¿Quiere modificar la especialidad?","Confirmar",JOptionPane.YES_NO_OPTION);
            if(opcion==JOptionPane.YES_OPTION){
                ModificarCargos();
                LimpiarDatos();
                CargoDAO cd=new CargoDAO();
                cd.cargarCargos(Cargos);
            }
            else{
                JOptionPane.showMessageDialog(this, "Gracias por confirmar");
            }
        }
    }//GEN-LAST:event_PanelEditarMouseClicked

    private void CargosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CargosItemStateChanged
        // TODO add your handling code here:
        Cargo car=(Cargo) Cargos.getSelectedItem();
        if (car !=null){
            TXTCargo.setText(car.getNom_cargo());
            TXTDescripcion.setText(car.getDescrip_cargo());
            }
        
    }//GEN-LAST:event_CargosItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Cargos().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Barra;
    private javax.swing.JComboBox<String> Cargos;
    private javax.swing.JLabel Descripcion;
    private javax.swing.JLabel Editar;
    private javax.swing.JLabel Guardar;
    private javax.swing.JLabel ImagenADD;
    private javax.swing.JLabel ImagenRegresar;
    private javax.swing.JLabel ImagenSAVE;
    private javax.swing.JLabel MJ;
    private javax.swing.JPanel Menu;
    private javax.swing.JLabel NombreCargo;
    private javax.swing.JLabel Nuevo;
    private javax.swing.JPanel PanelEditar;
    private javax.swing.JPanel PanelGuardar;
    private javax.swing.JPanel PanelNuevo;
    private javax.swing.JLabel Regresar;
    private javax.swing.JTextField TXTCargo;
    private javax.swing.JTextField TXTDescripcion;
    private javax.swing.JLabel Talleres;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
