/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package com.mycompany.proyecto_m2b.Vista;
import com.mycompany.proyecto_m2b.Controlador.VehiculosDAO;
import com.mycompany.proyecto_m2b.modelo.Marca;
import com.mycompany.proyecto_m2b.modelo.Modelo;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author castr
 */
public class CrearNuevaMarcaModelo extends javax.swing.JFrame {
    private String idMarcaCreada = null;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CrearNuevaMarcaModelo.class.getName());

    /** Creates new form Propietario */
    public CrearNuevaMarcaModelo() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
int xMouse;
int yMouse;
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        PanelGuardarMarca = new javax.swing.JPanel();
        Guardar = new javax.swing.JLabel();
        ImagenSAVE = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        TXTmarca = new javax.swing.JTextField();
        TXTmodelo = new javax.swing.JTextField();
        PanelGuardarModelo = new javax.swing.JPanel();
        Guardar1 = new javax.swing.JLabel();
        ImagenSAVE1 = new javax.swing.JLabel();

        jTextField2.setText("jTextField2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(238, 238, 238));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(153, 153, 153));
        jLabel21.setText("<- REGRESAR");
        jLabel21.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel21MouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("GESTIÓN DE MARCAS Y MODELOS");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 306, Short.MAX_VALUE)
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 60));

        PanelGuardarMarca.setBackground(new java.awt.Color(242, 101, 34));
        PanelGuardarMarca.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(187, 187, 187)));
        PanelGuardarMarca.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PanelGuardarMarca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PanelGuardarMarcaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PanelGuardarMarcaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PanelGuardarMarcaMouseExited(evt);
            }
        });

        Guardar.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        Guardar.setForeground(new java.awt.Color(255, 255, 255));
        Guardar.setText("Guardar Marca");

        ImagenSAVE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/save_22dp_FFFFFF_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N

        javax.swing.GroupLayout PanelGuardarMarcaLayout = new javax.swing.GroupLayout(PanelGuardarMarca);
        PanelGuardarMarca.setLayout(PanelGuardarMarcaLayout);
        PanelGuardarMarcaLayout.setHorizontalGroup(
            PanelGuardarMarcaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelGuardarMarcaLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(ImagenSAVE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Guardar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelGuardarMarcaLayout.setVerticalGroup(
            PanelGuardarMarcaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelGuardarMarcaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanelGuardarMarcaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Guardar)
                    .addComponent(ImagenSAVE))
                .addContainerGap())
        );

        jPanel1.add(PanelGuardarMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));

        jLabel16.setText("Ingrese el nombre de la marca:");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        jLabel17.setText("Ingrese el nombre del modelo:");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        TXTmarca.setForeground(new java.awt.Color(153, 153, 153));
        jPanel1.add(TXTmarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 190, -1));

        TXTmodelo.setForeground(new java.awt.Color(153, 153, 153));
        jPanel1.add(TXTmodelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, 190, -1));

        PanelGuardarModelo.setBackground(new java.awt.Color(242, 101, 34));
        PanelGuardarModelo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(187, 187, 187)));
        PanelGuardarModelo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PanelGuardarModelo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PanelGuardarModeloMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PanelGuardarModeloMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PanelGuardarModeloMouseExited(evt);
            }
        });

        Guardar1.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        Guardar1.setForeground(new java.awt.Color(255, 255, 255));
        Guardar1.setText("Guardar Modelo");

        ImagenSAVE1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/save_22dp_FFFFFF_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N

        javax.swing.GroupLayout PanelGuardarModeloLayout = new javax.swing.GroupLayout(PanelGuardarModelo);
        PanelGuardarModelo.setLayout(PanelGuardarModeloLayout);
        PanelGuardarModeloLayout.setHorizontalGroup(
            PanelGuardarModeloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelGuardarModeloLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(ImagenSAVE1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Guardar1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelGuardarModeloLayout.setVerticalGroup(
            PanelGuardarModeloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelGuardarModeloLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanelGuardarModeloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Guardar1)
                    .addComponent(ImagenSAVE1))
                .addContainerGap())
        );

        jPanel1.add(PanelGuardarModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 797, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jLabel21MouseClicked

    private void PanelGuardarMarcaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelGuardarMarcaMouseClicked
        // TODO add your handling code here:
    String nombreMarca = TXTmarca.getText().trim();

    if (nombreMarca.isEmpty() || nombreMarca.equalsIgnoreCase("Ingrese marca")) {
        JOptionPane.showMessageDialog(this, "Ingrese el nombre de la marca", "Campo Vacío", JOptionPane.WARNING_MESSAGE);
        return;
    }

    String timestamp = String.valueOf(System.currentTimeMillis());
    String idMarca = "MAR-" + timestamp.substring(timestamp.length() - 8);
    Marca marca = new Marca(idMarca, nombreMarca, "N/A", "N/A");
    
    VehiculosDAO dao = new VehiculosDAO();
    if (dao.insertarMarca(marca)) {
        // GUARDAS EL ID EN LA VARIABLE GLOBAL
        this.idMarcaCreada = idMarca; 
        
        JOptionPane.showMessageDialog(this, "Marca guardada con éxito.");
        TXTmarca.setText("");
    } else {
        JOptionPane.showMessageDialog(this, "Error al guardar la marca", "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_PanelGuardarMarcaMouseClicked

    private void PanelGuardarMarcaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelGuardarMarcaMouseEntered
        // TODO add your handling code here:
        PanelGuardarMarca.setBackground(new Color(227, 95, 32));
        Guardar.setForeground(new Color(217, 217, 192));
    }//GEN-LAST:event_PanelGuardarMarcaMouseEntered

    private void PanelGuardarMarcaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelGuardarMarcaMouseExited
        // TODO add your handling code here:
        PanelGuardarMarca.setBackground(new Color(242,101,34));
        Guardar.setForeground(Color.white);
    }//GEN-LAST:event_PanelGuardarMarcaMouseExited

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        // TODO add your handling code here:
        xMouse= evt.getX();
        yMouse= evt.getY();
    }//GEN-LAST:event_jPanel2MousePressed
    public void LimpiarDatos (){
        TXTmarca.setText("");
        TXTmarca.setForeground(new Color(94, 94, 94));
        TXTmodelo.setText("");
        TXTmodelo.setForeground(new Color(94, 94, 94));
    }
    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        // TODO add your handling code here:
        int x=evt.getXOnScreen();
        int y=evt.getYOnScreen();
        this.setLocation(x-xMouse, y-yMouse);
    }//GEN-LAST:event_jPanel2MouseDragged

    private void PanelGuardarModeloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelGuardarModeloMouseClicked
        // TODO add your handling code here:
        String nombreModelo = TXTmodelo.getText().trim();

    if (nombreModelo.isEmpty() || nombreModelo.equalsIgnoreCase("Ingrese modelo")) {
        JOptionPane.showMessageDialog(this, "Ingrese el nombre del modelo", "Campos Incompletos", JOptionPane.WARNING_MESSAGE);
        return;
    }

    // VALIDACIÓN: Verificar si el usuario guardó una marca primero
    if (this.idMarcaCreada == null) {
        JOptionPane.showMessageDialog(this, "Primero debe guardar una marca antes de asignarle un modelo.", "Atención", JOptionPane.WARNING_MESSAGE);
        return;
    }

    String timestamp = String.valueOf(System.currentTimeMillis());
    String idModelo = "MOD-" + timestamp.substring(timestamp.length() - 8);
    
    // USAS EL ID DE LA MARCA QUE SE GUARDÓ EN LA VARIABLE GLOBAL
    Modelo modelo = new Modelo(idModelo, nombreModelo, this.idMarcaCreada, "TIP-001");

    VehiculosDAO dao = new VehiculosDAO();
    if (dao.insertarModelo(modelo)) {
        JOptionPane.showMessageDialog(this, "Modelo guardado con éxito");
        TXTmodelo.setText("");
    } else {
        JOptionPane.showMessageDialog(this, "Error al guardar el modelo", "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_PanelGuardarModeloMouseClicked

    private void PanelGuardarModeloMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelGuardarModeloMouseEntered
        // TODO add your handling code here:
        PanelGuardarModelo.setBackground(new java.awt.Color(227, 95, 32));
        Guardar1.setForeground(new java.awt.Color(217, 217, 192));
    }//GEN-LAST:event_PanelGuardarModeloMouseEntered

    private void PanelGuardarModeloMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelGuardarModeloMouseExited
        // TODO add your handling code here:
        PanelGuardarModelo.setBackground(new java.awt.Color(242,101,34));
        Guardar1.setForeground(java.awt.Color.white);
    }//GEN-LAST:event_PanelGuardarModeloMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CrearNuevaMarcaModelo().setVisible(true));
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Guardar;
    private javax.swing.JLabel Guardar1;
    private javax.swing.JLabel ImagenSAVE;
    private javax.swing.JLabel ImagenSAVE1;
    private javax.swing.JPanel PanelGuardarMarca;
    private javax.swing.JPanel PanelGuardarModelo;
    private javax.swing.JTextField TXTmarca;
    private javax.swing.JTextField TXTmodelo;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}