/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyecto_m2b.Vista;
import java.awt.BorderLayout;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.data.general.DefaultPieDataset;
/**
 *
 * @author HP
 */
public class Estadisticas extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Estadisticas.class.getName());

    /**
     * Creates new form Estadisticas
     */
    public Estadisticas() {
        initComponents(); // Inicializa los componentes de NetBeans
        
        // Configuración de la ventana
        setTitle("Estadísticas del Taller");
        setSize(600, 400);
        setLocationRelativeTo(null);

        // 1. Crear el conjunto de datos (Ejemplo: Servicios realizados)
        DefaultPieDataset dataset = new DefaultPieDataset();
        dataset.setValue("Mecanica General", 45);
        dataset.setValue("Latoneria y Pintura", 25);
        dataset.setValue("Electricidad", 15);
        dataset.setValue("Diagnostico OBD2", 15);

        // 2. Crear el gráfico de pastel
        JFreeChart chart = ChartFactory.createPieChart(
            "Distribución de Servicios Realizados", // Título
            dataset,                                 // Datos
            true,                                    // Leyenda
            true,                                    // Tooltips
            false                                    // URLs
        );

        // 3. Agregar el gráfico a la ventana
        ChartPanel panel = new ChartPanel(chart);
        getContentPane().setLayout(new BorderLayout());
        getContentPane().add(panel, BorderLayout.CENTER);
        getContentPane().revalidate();
        getContentPane().repaint();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(() -> new Estadisticas().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
