/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyecto_m2b.Vista;

import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author usuario
 */
public class Menu extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Menu.class.getName());

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        this.setLocationRelativeTo(null);
        PanelPaneles.add(new PanelBlanco(), "Blanco");
        PanelPaneles.add(new PanelVehiculos(), "VEHICULOS");
        PanelPaneles.add(new PanelOrdenesServicio(), "ORDENES_SERVICIO");
        PanelPaneles.add(new PanelResiduos(), "RESIDUOS");
        PanelPaneles.add(new PanelPropietarios(), "PROPIETARIOS");
        PanelPaneles.add(new PanelRepuestos(), "REPUESTOS");
        PanelPaneles.add(new PanelProveedores(), "PROVEEDORES");
        PanelPaneles.add(new PanelCatalogoServicio(), "CATALOGO_SERVICIOS");
       
    }
    int xMouse;
    int yMouse;
    private Agregar AG = null;
    private Cargos Car= null;
    private PanelCatalogoServicio Cata=null;
    private CrearEmpleado CrearEmp=null;
    private Especialidad Espe=null;
    private Estadisticas Esta=null;
    private OrdenesDeServicio OrdenesServ=null;
    private Propietarios Prop=null;
    private Proveedores Provee=null;
    private Repuestos Repues=null;
    private Residuos Resi=null;
    private Vehiculos Vehi=null;
    private Usuarios Usu=null;
    
    private boolean catalogoAbierto = false;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelFondoMenu = new javax.swing.JPanel();
        PanelBarra = new javax.swing.JPanel();
        Regresar = new javax.swing.JLabel();
        ImagenRegresar = new javax.swing.JLabel();
        Cerrar = new javax.swing.JLabel();
        Minimizar = new javax.swing.JLabel();
        Usuarios = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        MJ = new javax.swing.JLabel();
        Talleres = new javax.swing.JLabel();
        Titulo = new javax.swing.JLabel();
        PanelBarraInferior = new javax.swing.JPanel();
        PanelAccesos = new javax.swing.JPanel();
        PanelOrdenesServicio = new javax.swing.JPanel();
        OrdenesDeServicio = new javax.swing.JLabel();
        ImagenOrdenesServicio = new javax.swing.JLabel();
        PanelVehiculos = new javax.swing.JPanel();
        Vehiculos = new javax.swing.JLabel();
        ImangenVehiculos = new javax.swing.JLabel();
        PanelPropietarios = new javax.swing.JPanel();
        Propietarios = new javax.swing.JLabel();
        ImagenPropietarios = new javax.swing.JLabel();
        PanelServicios = new javax.swing.JPanel();
        Servicios = new javax.swing.JLabel();
        ImagenServicios = new javax.swing.JLabel();
        PanelRepuestos = new javax.swing.JPanel();
        Repuestos = new javax.swing.JLabel();
        ImagenRepuestos = new javax.swing.JLabel();
        PanelProveedores = new javax.swing.JPanel();
        Proveedores = new javax.swing.JLabel();
        ImagenProveedores = new javax.swing.JLabel();
        PanelResiduos = new javax.swing.JPanel();
        Residuos = new javax.swing.JLabel();
        ImagenResiduos = new javax.swing.JLabel();
        PanelEstadisticas = new javax.swing.JPanel();
        Estadisticas = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Accesos = new javax.swing.JLabel();
        PanelFondoBlanco = new javax.swing.JPanel();
        PanelPaneles = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelFondoMenu.setBackground(new java.awt.Color(238, 238, 238));
        PanelFondoMenu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        PanelFondoMenu.setLayout(new java.awt.BorderLayout());

        PanelBarra.setBackground(new java.awt.Color(0, 0, 0));
        PanelBarra.setPreferredSize(new java.awt.Dimension(1710, 163));
        PanelBarra.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                PanelBarraMouseDragged(evt);
            }
        });
        PanelBarra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PanelBarraMousePressed(evt);
            }
        });

        Regresar.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        Regresar.setForeground(new java.awt.Color(145, 145, 145));
        Regresar.setText("Regresar");
        Regresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Regresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RegresarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                RegresarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                RegresarMouseExited(evt);
            }
        });

        ImagenRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/arrow_back_34dp_D9D9D9_FILL0_wght400_GRAD0_opsz40.png"))); // NOI18N

        Cerrar.setBackground(new java.awt.Color(255, 255, 255));
        Cerrar.setFont(new java.awt.Font("Roboto", 0, 36)); // NOI18N
        Cerrar.setForeground(new java.awt.Color(255, 255, 255));
        Cerrar.setText("X");
        Cerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Cerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CerrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CerrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CerrarMouseExited(evt);
            }
        });

        Minimizar.setBackground(new java.awt.Color(255, 255, 255));
        Minimizar.setFont(new java.awt.Font("Roboto", 0, 36)); // NOI18N
        Minimizar.setForeground(new java.awt.Color(255, 255, 255));
        Minimizar.setText("-");
        Minimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Minimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MinimizarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MinimizarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MinimizarMouseExited(evt);
            }
        });

        Usuarios.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        Usuarios.setForeground(new java.awt.Color(145, 145, 145));
        Usuarios.setText("Usuarios");
        Usuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Usuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UsuariosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                UsuariosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                UsuariosMouseExited(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/images (2).jpg"))); // NOI18N

        MJ.setBackground(new java.awt.Color(152, 75, 45));
        MJ.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        MJ.setForeground(new java.awt.Color(152, 75, 45));
        MJ.setText("M&J");

        Talleres.setBackground(new java.awt.Color(152, 75, 45));
        Talleres.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        Talleres.setForeground(new java.awt.Color(174, 63, 54));
        Talleres.setText("TALLERES");

        Titulo.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        Titulo.setForeground(new java.awt.Color(145, 145, 145));
        Titulo.setText("Menú Principal");
        Titulo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Titulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TituloMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TituloMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TituloMouseExited(evt);
            }
        });

        javax.swing.GroupLayout PanelBarraLayout = new javax.swing.GroupLayout(PanelBarra);
        PanelBarra.setLayout(PanelBarraLayout);
        PanelBarraLayout.setHorizontalGroup(
            PanelBarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelBarraLayout.createSequentialGroup()
                .addGroup(PanelBarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelBarraLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(PanelBarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MJ, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Talleres))
                        .addGap(274, 274, 274))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelBarraLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Titulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addComponent(Usuarios)
                .addGroup(PanelBarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelBarraLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Minimizar)
                        .addGap(18, 18, 18)
                        .addComponent(Cerrar))
                    .addGroup(PanelBarraLayout.createSequentialGroup()
                        .addGap(258, 258, 258)
                        .addComponent(ImagenRegresar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Regresar)))
                .addGap(234, 234, 234))
        );
        PanelBarraLayout.setVerticalGroup(
            PanelBarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBarraLayout.createSequentialGroup()
                .addGroup(PanelBarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelBarraLayout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(Usuarios)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelBarraLayout.createSequentialGroup()
                        .addGroup(PanelBarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(PanelBarraLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ImagenRegresar))
                            .addGroup(PanelBarraLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(PanelBarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Cerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Minimizar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(Regresar)))
                        .addGap(34, 34, 34)))
                .addContainerGap())
            .addGroup(PanelBarraLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(MJ, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Talleres, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Titulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PanelFondoMenu.add(PanelBarra, java.awt.BorderLayout.NORTH);

        PanelBarraInferior.setBackground(new java.awt.Color(227, 153, 106));
        PanelBarraInferior.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout PanelBarraInferiorLayout = new javax.swing.GroupLayout(PanelBarraInferior);
        PanelBarraInferior.setLayout(PanelBarraInferiorLayout);
        PanelBarraInferiorLayout.setHorizontalGroup(
            PanelBarraInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1941, Short.MAX_VALUE)
        );
        PanelBarraInferiorLayout.setVerticalGroup(
            PanelBarraInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 78, Short.MAX_VALUE)
        );

        PanelFondoMenu.add(PanelBarraInferior, java.awt.BorderLayout.SOUTH);

        PanelAccesos.setBackground(new java.awt.Color(79, 84, 90));

        PanelOrdenesServicio.setBackground(new java.awt.Color(53, 58, 61));
        PanelOrdenesServicio.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 116, 78), 2, true));
        PanelOrdenesServicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PanelOrdenesServicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PanelOrdenesServicioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PanelOrdenesServicioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PanelOrdenesServicioMouseExited(evt);
            }
        });

        OrdenesDeServicio.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        OrdenesDeServicio.setForeground(new java.awt.Color(255, 255, 255));
        OrdenesDeServicio.setText("Ordenes de servicio");

        ImagenOrdenesServicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/order_approve_24dp_CE8B60_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N

        javax.swing.GroupLayout PanelOrdenesServicioLayout = new javax.swing.GroupLayout(PanelOrdenesServicio);
        PanelOrdenesServicio.setLayout(PanelOrdenesServicioLayout);
        PanelOrdenesServicioLayout.setHorizontalGroup(
            PanelOrdenesServicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelOrdenesServicioLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(ImagenOrdenesServicio)
                .addGap(57, 57, 57)
                .addComponent(OrdenesDeServicio)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelOrdenesServicioLayout.setVerticalGroup(
            PanelOrdenesServicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelOrdenesServicioLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(PanelOrdenesServicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ImagenOrdenesServicio)
                    .addComponent(OrdenesDeServicio))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        PanelVehiculos.setBackground(new java.awt.Color(53, 58, 61));
        PanelVehiculos.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 116, 78), 2, true));
        PanelVehiculos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PanelVehiculos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PanelVehiculosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PanelVehiculosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PanelVehiculosMouseExited(evt);
            }
        });

        Vehiculos.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        Vehiculos.setForeground(new java.awt.Color(255, 255, 255));
        Vehiculos.setText("Vehiculos");

        ImangenVehiculos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/directions_car_24dp_CE8B60_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N

        javax.swing.GroupLayout PanelVehiculosLayout = new javax.swing.GroupLayout(PanelVehiculos);
        PanelVehiculos.setLayout(PanelVehiculosLayout);
        PanelVehiculosLayout.setHorizontalGroup(
            PanelVehiculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelVehiculosLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(ImangenVehiculos)
                .addGap(62, 62, 62)
                .addComponent(Vehiculos)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelVehiculosLayout.setVerticalGroup(
            PanelVehiculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelVehiculosLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(PanelVehiculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Vehiculos)
                    .addComponent(ImangenVehiculos))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        PanelPropietarios.setBackground(new java.awt.Color(53, 58, 61));
        PanelPropietarios.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 116, 78), 2, true));
        PanelPropietarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PanelPropietarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PanelPropietariosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PanelPropietariosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PanelPropietariosMouseExited(evt);
            }
        });

        Propietarios.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        Propietarios.setForeground(new java.awt.Color(255, 255, 255));
        Propietarios.setText("Propietarios");

        ImagenPropietarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/groups_24dp_CE8B60_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N

        javax.swing.GroupLayout PanelPropietariosLayout = new javax.swing.GroupLayout(PanelPropietarios);
        PanelPropietarios.setLayout(PanelPropietariosLayout);
        PanelPropietariosLayout.setHorizontalGroup(
            PanelPropietariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPropietariosLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(ImagenPropietarios)
                .addGap(58, 58, 58)
                .addComponent(Propietarios)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelPropietariosLayout.setVerticalGroup(
            PanelPropietariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPropietariosLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(PanelPropietariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ImagenPropietarios)
                    .addComponent(Propietarios))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        PanelServicios.setBackground(new java.awt.Color(53, 58, 61));
        PanelServicios.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 116, 78), 2, true));
        PanelServicios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PanelServicios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PanelServiciosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PanelServiciosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PanelServiciosMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PanelServiciosMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                PanelServiciosMouseReleased(evt);
            }
        });

        Servicios.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        Servicios.setForeground(new java.awt.Color(255, 255, 255));
        Servicios.setText("Servicios");

        ImagenServicios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/build_24dp_CE8B60_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N

        javax.swing.GroupLayout PanelServiciosLayout = new javax.swing.GroupLayout(PanelServicios);
        PanelServicios.setLayout(PanelServiciosLayout);
        PanelServiciosLayout.setHorizontalGroup(
            PanelServiciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelServiciosLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(ImagenServicios)
                .addGap(59, 59, 59)
                .addComponent(Servicios)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelServiciosLayout.setVerticalGroup(
            PanelServiciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelServiciosLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(PanelServiciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ImagenServicios)
                    .addComponent(Servicios))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        PanelRepuestos.setBackground(new java.awt.Color(53, 58, 61));
        PanelRepuestos.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 116, 78), 2, true));
        PanelRepuestos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PanelRepuestos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PanelRepuestosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PanelRepuestosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PanelRepuestosMouseExited(evt);
            }
        });

        Repuestos.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        Repuestos.setForeground(new java.awt.Color(255, 255, 255));
        Repuestos.setText("Repuestos");

        ImagenRepuestos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/box_24dp_CCCCCC_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N

        javax.swing.GroupLayout PanelRepuestosLayout = new javax.swing.GroupLayout(PanelRepuestos);
        PanelRepuestos.setLayout(PanelRepuestosLayout);
        PanelRepuestosLayout.setHorizontalGroup(
            PanelRepuestosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelRepuestosLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(ImagenRepuestos)
                .addGap(64, 64, 64)
                .addComponent(Repuestos)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelRepuestosLayout.setVerticalGroup(
            PanelRepuestosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelRepuestosLayout.createSequentialGroup()
                .addGroup(PanelRepuestosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PanelRepuestosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ImagenRepuestos, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelRepuestosLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(Repuestos)))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        PanelProveedores.setBackground(new java.awt.Color(53, 58, 61));
        PanelProveedores.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 116, 78), 2, true));
        PanelProveedores.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PanelProveedores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PanelProveedoresMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PanelProveedoresMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PanelProveedoresMouseExited(evt);
            }
        });

        Proveedores.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        Proveedores.setForeground(new java.awt.Color(255, 255, 255));
        Proveedores.setText("Proveedores");

        ImagenProveedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/delivery_truck_speed_24dp_CCCCCC_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N

        javax.swing.GroupLayout PanelProveedoresLayout = new javax.swing.GroupLayout(PanelProveedores);
        PanelProveedores.setLayout(PanelProveedoresLayout);
        PanelProveedoresLayout.setHorizontalGroup(
            PanelProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelProveedoresLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(ImagenProveedores)
                .addGap(57, 57, 57)
                .addComponent(Proveedores)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelProveedoresLayout.setVerticalGroup(
            PanelProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelProveedoresLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(PanelProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ImagenProveedores)
                    .addComponent(Proveedores))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        PanelResiduos.setBackground(new java.awt.Color(53, 58, 61));
        PanelResiduos.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 116, 78), 2, true));
        PanelResiduos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PanelResiduos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PanelResiduosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PanelResiduosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PanelResiduosMouseExited(evt);
            }
        });

        Residuos.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        Residuos.setForeground(new java.awt.Color(255, 255, 255));
        Residuos.setText("Residuos");

        ImagenResiduos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/recycling_24dp_CCCCCC_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N

        javax.swing.GroupLayout PanelResiduosLayout = new javax.swing.GroupLayout(PanelResiduos);
        PanelResiduos.setLayout(PanelResiduosLayout);
        PanelResiduosLayout.setHorizontalGroup(
            PanelResiduosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelResiduosLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(ImagenResiduos)
                .addGap(69, 69, 69)
                .addComponent(Residuos)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelResiduosLayout.setVerticalGroup(
            PanelResiduosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelResiduosLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(PanelResiduosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ImagenResiduos)
                    .addComponent(Residuos))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        PanelEstadisticas.setBackground(new java.awt.Color(53, 58, 61));
        PanelEstadisticas.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 116, 78), 2, true));
        PanelEstadisticas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PanelEstadisticas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PanelEstadisticasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PanelEstadisticasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PanelEstadisticasMouseExited(evt);
            }
        });

        Estadisticas.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        Estadisticas.setForeground(new java.awt.Color(255, 255, 255));
        Estadisticas.setText("Estadisticas");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/align_vertical_bottom_24dp_CCCCCC_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N

        javax.swing.GroupLayout PanelEstadisticasLayout = new javax.swing.GroupLayout(PanelEstadisticas);
        PanelEstadisticas.setLayout(PanelEstadisticasLayout);
        PanelEstadisticasLayout.setHorizontalGroup(
            PanelEstadisticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelEstadisticasLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addGap(68, 68, 68)
                .addComponent(Estadisticas)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelEstadisticasLayout.setVerticalGroup(
            PanelEstadisticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelEstadisticasLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(PanelEstadisticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(Estadisticas))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(79, 84, 90));

        Accesos.setFont(new java.awt.Font("Roboto", 1, 48)); // NOI18N
        Accesos.setForeground(new java.awt.Color(135, 135, 135));
        Accesos.setText("ACCESOS");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(Accesos)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Accesos, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PanelAccesosLayout = new javax.swing.GroupLayout(PanelAccesos);
        PanelAccesos.setLayout(PanelAccesosLayout);
        PanelAccesosLayout.setHorizontalGroup(
            PanelAccesosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAccesosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelAccesosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanelProveedores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelVehiculos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelOrdenesServicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelPropietarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelServicios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelResiduos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelEstadisticas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelRepuestos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(PanelAccesosLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 23, Short.MAX_VALUE))
        );
        PanelAccesosLayout.setVerticalGroup(
            PanelAccesosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelAccesosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelOrdenesServicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PanelVehiculos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PanelPropietarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PanelServicios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PanelRepuestos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PanelProveedores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PanelResiduos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PanelEstadisticas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PanelFondoMenu.add(PanelAccesos, java.awt.BorderLayout.WEST);

        PanelFondoBlanco.setBackground(new java.awt.Color(255, 255, 255));

        PanelPaneles.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout PanelFondoBlancoLayout = new javax.swing.GroupLayout(PanelFondoBlanco);
        PanelFondoBlanco.setLayout(PanelFondoBlancoLayout);
        PanelFondoBlancoLayout.setHorizontalGroup(
            PanelFondoBlancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelFondoBlancoLayout.createSequentialGroup()
                .addComponent(PanelPaneles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1634, Short.MAX_VALUE))
        );
        PanelFondoBlancoLayout.setVerticalGroup(
            PanelFondoBlancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelPaneles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        PanelFondoMenu.add(PanelFondoBlanco, java.awt.BorderLayout.CENTER);

        getContentPane().add(PanelFondoMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PanelEstadisticasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelEstadisticasMouseExited
        // TODO add your handling code here:
        PanelEstadisticas.setBackground(Color.white);
        Estadisticas.setForeground(Color.black);
    }//GEN-LAST:event_PanelEstadisticasMouseExited

    private void PanelEstadisticasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelEstadisticasMouseEntered
        // TODO add your handling code here:
        PanelEstadisticas.setBackground(new Color(179, 179, 179));
        Estadisticas.setForeground(Color.white);
    }//GEN-LAST:event_PanelEstadisticasMouseEntered

    private void PanelEstadisticasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelEstadisticasMouseClicked
        // TODO add your handling code here:
        if (Esta==null || !Esta.isVisible()){
            Esta = new Estadisticas();
            Esta.setVisible(true);
        }
        else {
            Esta.setState(java.awt.Frame.NORMAL);
            Esta.toFront();
            Esta.requestFocus();
        }
    }//GEN-LAST:event_PanelEstadisticasMouseClicked

    private void PanelResiduosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelResiduosMouseExited
        // TODO add your handling code here:
        PanelResiduos.setBackground(Color.white);
        Residuos.setForeground(Color.black);
    }//GEN-LAST:event_PanelResiduosMouseExited

    private void PanelResiduosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelResiduosMouseEntered
        // TODO add your handling code here:
        PanelResiduos.setBackground(new Color(179, 179, 179));
        Residuos.setForeground(Color.white);
    }//GEN-LAST:event_PanelResiduosMouseEntered
    
    private boolean mostrandoresiduos = false;
    private void PanelResiduosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelResiduosMouseClicked
                                            
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) PanelPaneles.getLayout();
        if (!mostrandoresiduos) {
            cl.show(PanelPaneles, "RESIDUOS");
        } else {
            cl.show(PanelPaneles, "Blanco");
        }
        mostrandoresiduos = !mostrandoresiduos;

    }//GEN-LAST:event_PanelResiduosMouseClicked

    private void PanelProveedoresMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelProveedoresMouseExited
        // TODO add your handling code here:
        PanelProveedores.setBackground(Color.white);
        Proveedores.setForeground(Color.black);
    }//GEN-LAST:event_PanelProveedoresMouseExited

    private void PanelProveedoresMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelProveedoresMouseEntered
        // TODO add your handling code here:
        PanelProveedores.setBackground(new Color(179, 179, 179));
        Proveedores.setForeground(Color.white);
    }//GEN-LAST:event_PanelProveedoresMouseEntered

    private boolean mostrandoProveedores = false;
    private void PanelProveedoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelProveedoresMouseClicked

        CardLayout cl = (CardLayout) PanelPaneles.getLayout();
        if (!mostrandoProveedores) {
            cl.show(PanelPaneles, "PROVEEDORES");
        } else {
            cl.show(PanelPaneles, "Blanco");
        }
        mostrandoProveedores = !mostrandoProveedores;        
    }//GEN-LAST:event_PanelProveedoresMouseClicked

    private void PanelRepuestosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelRepuestosMouseExited
        // TODO add your handling code here:
        PanelRepuestos.setBackground(Color.white);
        Repuestos.setForeground(Color.black);
    }//GEN-LAST:event_PanelRepuestosMouseExited

    private void PanelRepuestosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelRepuestosMouseEntered
        // TODO add your handling code here:
        PanelRepuestos.setBackground(new Color(179, 179, 179));
        Repuestos.setForeground(Color.white);
    }//GEN-LAST:event_PanelRepuestosMouseEntered

    private boolean mostrandoRepuestos = false;
    private void PanelRepuestosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelRepuestosMouseClicked
                                           
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) PanelPaneles.getLayout();
        if (!mostrandoRepuestos) {
            cl.show(PanelPaneles, "REPUESTOS");
        } else {
            cl.show(PanelPaneles, "Blanco");
        }
        mostrandoRepuestos = !mostrandoRepuestos;        
    }//GEN-LAST:event_PanelRepuestosMouseClicked

    private void PanelServiciosMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelServiciosMouseReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_PanelServiciosMouseReleased

    private void PanelServiciosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelServiciosMousePressed
        // TODO add your handling code here:

    }//GEN-LAST:event_PanelServiciosMousePressed

    private void PanelServiciosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelServiciosMouseExited
        // TODO add your handling code here:
        PanelServicios.setBackground(Color.white);
        Servicios.setForeground(Color.black);
    }//GEN-LAST:event_PanelServiciosMouseExited

    private void PanelServiciosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelServiciosMouseEntered
        // TODO add your handling code here:
        PanelServicios.setBackground(new Color (252, 170, 118));
        Servicios.setForeground(Color.white);
    }//GEN-LAST:event_PanelServiciosMouseEntered
    
    private boolean mostrandoCatalogoServicios = false;
    private void PanelServiciosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelServiciosMouseClicked

        CardLayout cl = (CardLayout) PanelPaneles.getLayout();
        if (!mostrandoCatalogoServicios) {
            cl.show(PanelPaneles, "CATALOGO_SERVICIOS");
        } else {
            cl.show(PanelPaneles, "Blanco");
        }
        mostrandoCatalogoServicios = !mostrandoCatalogoServicios;
    }//GEN-LAST:event_PanelServiciosMouseClicked

    private void PanelPropietariosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelPropietariosMouseExited
        // TODO add your handling code here:
        PanelPropietarios.setBackground(Color.white);
        Propietarios.setForeground(Color.black);
    }//GEN-LAST:event_PanelPropietariosMouseExited

    private void PanelPropietariosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelPropietariosMouseEntered
        // TODO add your handling code here:
        PanelPropietarios.setBackground(new Color (252, 170, 118));
        Propietarios.setForeground(Color.WHITE);
    }//GEN-LAST:event_PanelPropietariosMouseEntered

    private boolean mostrandoPropietarios = false;
    private void PanelPropietariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelPropietariosMouseClicked
        // TODO add your handling code here:
                                            
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) PanelPaneles.getLayout();
        if (!mostrandoPropietarios) {
            cl.show(PanelPaneles, "PROPIETARIOS");
        } else {
            cl.show(PanelPaneles, "Blanco");
        }
        mostrandoPropietarios = !mostrandoPropietarios;
    }//GEN-LAST:event_PanelPropietariosMouseClicked

    private void PanelVehiculosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelVehiculosMouseExited
        // TODO add your handling code here:
        PanelVehiculos.setBackground(Color.white);
        Vehiculos.setForeground(Color.black);
    }//GEN-LAST:event_PanelVehiculosMouseExited

    private void PanelVehiculosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelVehiculosMouseEntered
        // TODO add your handling code here:
        PanelVehiculos.setBackground(new Color(53, 58, 61));
        Vehiculos.setForeground(Color.white);
    }//GEN-LAST:event_PanelVehiculosMouseEntered
    
    private boolean mostrandoVehiculos = false;
    private void PanelVehiculosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelVehiculosMouseClicked
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) PanelPaneles.getLayout();
        if (!mostrandoVehiculos) {
            cl.show(PanelPaneles, "VEHICULOS");
        } else {
            cl.show(PanelPaneles, "Blanco");
        }
        mostrandoVehiculos = !mostrandoVehiculos;
        
    }//GEN-LAST:event_PanelVehiculosMouseClicked

    private void PanelOrdenesServicioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelOrdenesServicioMouseExited
        // TODO add your handling code here:
        PanelOrdenesServicio.setBackground(Color.white);
        OrdenesDeServicio.setForeground(Color.black);
    }//GEN-LAST:event_PanelOrdenesServicioMouseExited

    private void PanelOrdenesServicioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelOrdenesServicioMouseEntered
        // TODO add your handling code here:
        PanelOrdenesServicio.setBackground(new Color (252, 170, 118));
        OrdenesDeServicio.setForeground(Color.white);
    }//GEN-LAST:event_PanelOrdenesServicioMouseEntered

    private boolean mostrandoOrdenesServicio = false;
    private void PanelOrdenesServicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelOrdenesServicioMouseClicked
                                             
        CardLayout cl = (CardLayout) PanelPaneles.getLayout();
        if (!mostrandoOrdenesServicio) {
            cl.show(PanelPaneles, "ORDENES_SERVICIO");
        } else {
            cl.show(PanelPaneles, "Blanco");
        }
        mostrandoOrdenesServicio = !mostrandoOrdenesServicio;
    }//GEN-LAST:event_PanelOrdenesServicioMouseClicked

    private void PanelBarraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelBarraMousePressed
        // TODO add your handling code here:
        xMouse=evt.getX();
        yMouse=evt.getY();
    }//GEN-LAST:event_PanelBarraMousePressed

    private void PanelBarraMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelBarraMouseDragged
        // TODO add your handling code here:
        int x= evt.getXOnScreen();
        int y= evt.getYOnScreen();
        this.setLocation(x-xMouse, y-yMouse);
    }//GEN-LAST:event_PanelBarraMouseDragged

    private void TituloMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TituloMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_TituloMouseExited

    private void TituloMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TituloMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_TituloMouseEntered

    private void TituloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TituloMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_TituloMouseClicked

    private void UsuariosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UsuariosMouseExited
        // TODO add your handling code here:
        Usuarios.setForeground(new Color (145, 145, 145));
    }//GEN-LAST:event_UsuariosMouseExited

    private void UsuariosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UsuariosMouseEntered
        // TODO add your handling code here:
        Usuarios.setForeground(Color.white);
    }//GEN-LAST:event_UsuariosMouseEntered

    private void UsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UsuariosMouseClicked
        // TODO add your handling code here:
        if (Usu==null || !Usu.isVisible()){
            Usu = new Usuarios();
            Usu.setVisible(true);
        }
        else {
            Usu.setState(java.awt.Frame.NORMAL);
            Usu.toFront();
            Usu.requestFocus();
        }
    }//GEN-LAST:event_UsuariosMouseClicked

    private void MinimizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizarMouseExited
        // TODO add your handling code here:
        Minimizar.setForeground(Color.white);
    }//GEN-LAST:event_MinimizarMouseExited

    private void MinimizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizarMouseEntered
        // TODO add your handling code here:
        Minimizar.setForeground(Color.gray);
    }//GEN-LAST:event_MinimizarMouseEntered

    private void MinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizarMouseClicked
        // TODO add your handling code here:
        this.setExtendedState(Menu.ICONIFIED);
    }//GEN-LAST:event_MinimizarMouseClicked

    private void CerrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CerrarMouseExited
        // TODO add your handling code here:
        Cerrar.setForeground(Color.white);
    }//GEN-LAST:event_CerrarMouseExited

    private void CerrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CerrarMouseEntered
        // TODO add your handling code here:
        Cerrar.setForeground(Color.red);
    }//GEN-LAST:event_CerrarMouseEntered

    private void CerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CerrarMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Gracias por usar este programa");
        System.exit(0);
    }//GEN-LAST:event_CerrarMouseClicked

    private void RegresarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegresarMouseExited
        // TODO add your handling code here:
        Regresar.setForeground(new Color(145, 145, 145));
    }//GEN-LAST:event_RegresarMouseExited

    private void RegresarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegresarMouseEntered
        // TODO add your handling code here:
        Regresar.setForeground(new Color(196, 196, 196));
    }//GEN-LAST:event_RegresarMouseEntered

    private void RegresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegresarMouseClicked
        // TODO add your handling code here:
        Login L=new Login();
        L.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_RegresarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Menu().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Accesos;
    private javax.swing.JLabel Cerrar;
    private javax.swing.JLabel Estadisticas;
    private javax.swing.JLabel ImagenOrdenesServicio;
    private javax.swing.JLabel ImagenPropietarios;
    private javax.swing.JLabel ImagenProveedores;
    private javax.swing.JLabel ImagenRegresar;
    private javax.swing.JLabel ImagenRepuestos;
    private javax.swing.JLabel ImagenResiduos;
    private javax.swing.JLabel ImagenServicios;
    private javax.swing.JLabel ImangenVehiculos;
    private javax.swing.JLabel MJ;
    private javax.swing.JLabel Minimizar;
    private javax.swing.JLabel OrdenesDeServicio;
    private javax.swing.JPanel PanelAccesos;
    private javax.swing.JPanel PanelBarra;
    private javax.swing.JPanel PanelBarraInferior;
    private javax.swing.JPanel PanelEstadisticas;
    private javax.swing.JPanel PanelFondoBlanco;
    private javax.swing.JPanel PanelFondoMenu;
    private javax.swing.JPanel PanelOrdenesServicio;
    private javax.swing.JPanel PanelPaneles;
    private javax.swing.JPanel PanelPropietarios;
    private javax.swing.JPanel PanelProveedores;
    private javax.swing.JPanel PanelRepuestos;
    private javax.swing.JPanel PanelResiduos;
    private javax.swing.JPanel PanelServicios;
    private javax.swing.JPanel PanelVehiculos;
    private javax.swing.JLabel Propietarios;
    private javax.swing.JLabel Proveedores;
    private javax.swing.JLabel Regresar;
    private javax.swing.JLabel Repuestos;
    private javax.swing.JLabel Residuos;
    private javax.swing.JLabel Servicios;
    private javax.swing.JLabel Talleres;
    private javax.swing.JLabel Titulo;
    private javax.swing.JLabel Usuarios;
    private javax.swing.JLabel Vehiculos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
