
package com.mycompany.proyecto_m2b.Vista;

import com.mycompany.proyecto_m2b.Controlador.OrdenServicioDAO;
import com.mycompany.proyecto_m2b.Controlador.ProduceDAO;
import com.mycompany.proyecto_m2b.Controlador.RepuestoDAO;
import com.mycompany.proyecto_m2b.Controlador.ServicioDAO;
import com.mycompany.proyecto_m2b.modelo.ItemReporteDTO;
import com.mycompany.proyecto_m2b.modelo.Usuario;
import java.awt.BorderLayout;
import java.awt.Color;
import java.time.LocalDate;
import java.util.Locale;
import java.util.Map;
import javax.swing.BoxLayout;
import javax.swing.JLabel;
import javax.swing.JPanel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.RingPlot;
import org.jfree.data.general.DefaultPieDataset;
import org.jfree.data.time.Day;
import org.jfree.data.time.TimeSeries;
import org.jfree.data.time.TimeSeriesCollection;
import org.jfree.chart.axis.DateAxis;
import org.jfree.chart.plot.XYPlot;
import org.jfree.chart.renderer.xy.XYAreaRenderer;
import java.text.SimpleDateFormat;
import java.time.format.DateTimeFormatter;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.renderer.category.BarRenderer;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.renderer.category.BarRenderer;
import java.time.format.DateTimeFormatter;
import java.time.temporal.ChronoUnit;

public class PanelEstadistica extends javax.swing.JPanel {
    
    private Usuario usuarioActual;
    public PanelEstadistica(Usuario usuario) {
        initComponents();
        this.usuarioActual = usuario;
        if (usuarioActual != null) {
            lblUsuarios.setText("Usuario: " + usuarioActual.getNombre_usuario());
        }
        Desde.setDate(java.sql.Date.valueOf(LocalDate.now().withDayOfMonth(1)));
        Hasta.setDate(java.sql.Date.valueOf(LocalDate.now()));
        bloquearTamano(tarjetaOrdenesServicioPorEstado);
        bloquearTamano(tarjetaOrdenesServicioPorDia);
        bloquearTamano(TarjetaIngresosDia);
        bloquearTamano(TarjetaServiciosRealizados);
        bloquearTamano(TarjetaRepuestosMasUtilizados);
    }
    private void bloquearTamano(javax.swing.JComponent comp) {
        java.awt.Dimension tam = comp.getPreferredSize();
        comp.setPreferredSize(tam);
        comp.setMinimumSize(tam);
        comp.setMaximumSize(tam);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        tarjetaIngresos = new com.mycompany.proyecto_m2b.Vista.TarjetaRedonda();
        labelIngresos = new javax.swing.JLabel();
        txtValorIngresos = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tarjetaServicios = new com.mycompany.proyecto_m2b.Vista.TarjetaRedonda();
        labelServicios = new javax.swing.JLabel();
        txtValorServicios = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tarjetaOrdenes = new com.mycompany.proyecto_m2b.Vista.TarjetaRedonda();
        labelOrdenes = new javax.swing.JLabel();
        txtValorOrdenes = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tarjetaRepuestos = new com.mycompany.proyecto_m2b.Vista.TarjetaRedonda();
        labelRepuestos = new javax.swing.JLabel();
        txtValorRepuestos = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tarjetaVehiculos = new com.mycompany.proyecto_m2b.Vista.TarjetaRedonda();
        labelVehiculos = new javax.swing.JLabel();
        txtValorVehiculos = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tarjetaOrdenesServicioPorEstado = new com.mycompany.proyecto_m2b.Vista.TarjetaRedonda();
        labelOrdenesServicioEstado = new javax.swing.JLabel();
        tarjetaOrdenesServicioPorDia = new com.mycompany.proyecto_m2b.Vista.TarjetaRedonda();
        labelOrdenesServicioDia = new javax.swing.JLabel();
        TarjetaServiciosRealizados = new javax.swing.JPanel();
        lblSeriviciosRealzados = new javax.swing.JLabel();
        TarjetaIngresosDia = new javax.swing.JPanel();
        lblIngresosDia = new javax.swing.JLabel();
        TarjetaRepuestosMasUtilizados = new javax.swing.JPanel();
        lblRepuestosUtilizados = new javax.swing.JLabel();
        TarjetaUsuario = new javax.swing.JPanel();
        lblUsuarios = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        labelVehiculos2 = new javax.swing.JLabel();
        labelVehiculos3 = new javax.swing.JLabel();
        labelVehiculos4 = new javax.swing.JLabel();
        labelVehiculos5 = new javax.swing.JLabel();
        txtDias = new javax.swing.JLabel();
        txtPromedioOrdenes = new javax.swing.JLabel();
        txtPromedioIngresos = new javax.swing.JLabel();
        Titulo = new javax.swing.JLabel();
        Reportes = new javax.swing.JPanel();
        Guardar = new javax.swing.JLabel();
        ImagenSAVE = new javax.swing.JLabel();
        Guardar1 = new javax.swing.JLabel();
        Desde = new com.toedter.calendar.JDateChooser();
        Guardar2 = new javax.swing.JLabel();
        Hasta = new com.toedter.calendar.JDateChooser();
        btnAplicar = new javax.swing.JButton();

        jPanel2.setLayout(new java.awt.GridBagLayout());

        tarjetaIngresos.setBackground(new java.awt.Color(255, 255, 255));
        tarjetaIngresos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        tarjetaIngresos.setPreferredSize(new java.awt.Dimension(266, 170));

        labelIngresos.setBackground(new java.awt.Color(0, 0, 0));
        labelIngresos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelIngresos.setForeground(new java.awt.Color(0, 0, 0));
        labelIngresos.setText("INGRESOS TOTALES");

        txtValorIngresos.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtValorIngresos.setForeground(new java.awt.Color(0, 0, 0));
        txtValorIngresos.setText("$0");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 153, 153));
        jLabel7.setText("Total en el periodo");

        javax.swing.GroupLayout tarjetaIngresosLayout = new javax.swing.GroupLayout(tarjetaIngresos);
        tarjetaIngresos.setLayout(tarjetaIngresosLayout);
        tarjetaIngresosLayout.setHorizontalGroup(
            tarjetaIngresosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tarjetaIngresosLayout.createSequentialGroup()
                .addGroup(tarjetaIngresosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tarjetaIngresosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(labelIngresos))
                    .addGroup(tarjetaIngresosLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(txtValorIngresos))
                    .addGroup(tarjetaIngresosLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel7)))
                .addContainerGap(84, Short.MAX_VALUE))
        );
        tarjetaIngresosLayout.setVerticalGroup(
            tarjetaIngresosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tarjetaIngresosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelIngresos)
                .addGap(18, 18, 18)
                .addComponent(txtValorIngresos)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        tarjetaServicios.setBackground(new java.awt.Color(255, 255, 255));
        tarjetaServicios.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tarjetaServicios.setPreferredSize(new java.awt.Dimension(266, 170));

        labelServicios.setBackground(new java.awt.Color(0, 0, 0));
        labelServicios.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelServicios.setForeground(new java.awt.Color(0, 0, 0));
        labelServicios.setText("Servicios Realizados");

        txtValorServicios.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtValorServicios.setForeground(new java.awt.Color(0, 0, 0));
        txtValorServicios.setText("0");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(153, 153, 153));
        jLabel9.setText("Total en el periodo");

        javax.swing.GroupLayout tarjetaServiciosLayout = new javax.swing.GroupLayout(tarjetaServicios);
        tarjetaServicios.setLayout(tarjetaServiciosLayout);
        tarjetaServiciosLayout.setHorizontalGroup(
            tarjetaServiciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tarjetaServiciosLayout.createSequentialGroup()
                .addGroup(tarjetaServiciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tarjetaServiciosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(labelServicios))
                    .addGroup(tarjetaServiciosLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(txtValorServicios))
                    .addGroup(tarjetaServiciosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel9)))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        tarjetaServiciosLayout.setVerticalGroup(
            tarjetaServiciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tarjetaServiciosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelServicios)
                .addGap(18, 18, 18)
                .addComponent(txtValorServicios)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tarjetaOrdenes.setBackground(new java.awt.Color(255, 255, 255));
        tarjetaOrdenes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        labelOrdenes.setBackground(new java.awt.Color(0, 0, 0));
        labelOrdenes.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelOrdenes.setForeground(new java.awt.Color(0, 0, 0));
        labelOrdenes.setText("ORDENES DE SERVICIO");

        txtValorOrdenes.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtValorOrdenes.setForeground(new java.awt.Color(0, 0, 0));
        txtValorOrdenes.setText("0");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 153, 153));
        jLabel6.setText("Total en el periodo");

        javax.swing.GroupLayout tarjetaOrdenesLayout = new javax.swing.GroupLayout(tarjetaOrdenes);
        tarjetaOrdenes.setLayout(tarjetaOrdenesLayout);
        tarjetaOrdenesLayout.setHorizontalGroup(
            tarjetaOrdenesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tarjetaOrdenesLayout.createSequentialGroup()
                .addGroup(tarjetaOrdenesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tarjetaOrdenesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(labelOrdenes))
                    .addGroup(tarjetaOrdenesLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(txtValorOrdenes))
                    .addGroup(tarjetaOrdenesLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel6)))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        tarjetaOrdenesLayout.setVerticalGroup(
            tarjetaOrdenesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tarjetaOrdenesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelOrdenes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtValorOrdenes)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        tarjetaRepuestos.setBackground(new java.awt.Color(255, 255, 255));
        tarjetaRepuestos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tarjetaRepuestos.setPreferredSize(new java.awt.Dimension(266, 170));

        labelRepuestos.setBackground(new java.awt.Color(0, 0, 0));
        labelRepuestos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelRepuestos.setForeground(new java.awt.Color(0, 0, 0));
        labelRepuestos.setText("Repuestos Utilizados");

        txtValorRepuestos.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtValorRepuestos.setForeground(new java.awt.Color(0, 0, 0));
        txtValorRepuestos.setText("0");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(153, 153, 153));
        jLabel10.setText("Total en el periodo");

        javax.swing.GroupLayout tarjetaRepuestosLayout = new javax.swing.GroupLayout(tarjetaRepuestos);
        tarjetaRepuestos.setLayout(tarjetaRepuestosLayout);
        tarjetaRepuestosLayout.setHorizontalGroup(
            tarjetaRepuestosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tarjetaRepuestosLayout.createSequentialGroup()
                .addGroup(tarjetaRepuestosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tarjetaRepuestosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(labelRepuestos))
                    .addGroup(tarjetaRepuestosLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(txtValorRepuestos))
                    .addGroup(tarjetaRepuestosLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel10)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tarjetaRepuestosLayout.setVerticalGroup(
            tarjetaRepuestosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tarjetaRepuestosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelRepuestos)
                .addGap(18, 18, 18)
                .addComponent(txtValorRepuestos)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tarjetaVehiculos.setBackground(new java.awt.Color(255, 255, 255));
        tarjetaVehiculos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tarjetaVehiculos.setPreferredSize(new java.awt.Dimension(250, 170));

        labelVehiculos.setBackground(new java.awt.Color(0, 0, 0));
        labelVehiculos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelVehiculos.setForeground(new java.awt.Color(0, 0, 0));
        labelVehiculos.setText("Vehiculos Atendidos");

        txtValorVehiculos.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtValorVehiculos.setForeground(new java.awt.Color(0, 0, 0));
        txtValorVehiculos.setText("0");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 153, 153));
        jLabel8.setText("Total en el periodo");

        javax.swing.GroupLayout tarjetaVehiculosLayout = new javax.swing.GroupLayout(tarjetaVehiculos);
        tarjetaVehiculos.setLayout(tarjetaVehiculosLayout);
        tarjetaVehiculosLayout.setHorizontalGroup(
            tarjetaVehiculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tarjetaVehiculosLayout.createSequentialGroup()
                .addGroup(tarjetaVehiculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tarjetaVehiculosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(labelVehiculos))
                    .addGroup(tarjetaVehiculosLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(tarjetaVehiculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addGroup(tarjetaVehiculosLayout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(txtValorVehiculos)))))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        tarjetaVehiculosLayout.setVerticalGroup(
            tarjetaVehiculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tarjetaVehiculosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelVehiculos)
                .addGap(18, 18, 18)
                .addComponent(txtValorVehiculos)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tarjetaOrdenesServicioPorEstado.setBackground(new java.awt.Color(255, 255, 255));
        tarjetaOrdenesServicioPorEstado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        labelOrdenesServicioEstado.setBackground(new java.awt.Color(0, 0, 0));
        labelOrdenesServicioEstado.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelOrdenesServicioEstado.setForeground(new java.awt.Color(0, 0, 0));
        labelOrdenesServicioEstado.setText("ORDENES DE SERVICIO POR ESTADO");

        javax.swing.GroupLayout tarjetaOrdenesServicioPorEstadoLayout = new javax.swing.GroupLayout(tarjetaOrdenesServicioPorEstado);
        tarjetaOrdenesServicioPorEstado.setLayout(tarjetaOrdenesServicioPorEstadoLayout);
        tarjetaOrdenesServicioPorEstadoLayout.setHorizontalGroup(
            tarjetaOrdenesServicioPorEstadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tarjetaOrdenesServicioPorEstadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelOrdenesServicioEstado)
                .addContainerGap(167, Short.MAX_VALUE))
        );
        tarjetaOrdenesServicioPorEstadoLayout.setVerticalGroup(
            tarjetaOrdenesServicioPorEstadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tarjetaOrdenesServicioPorEstadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelOrdenesServicioEstado)
                .addContainerGap(175, Short.MAX_VALUE))
        );

        tarjetaOrdenesServicioPorDia.setBackground(new java.awt.Color(255, 255, 255));
        tarjetaOrdenesServicioPorDia.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        labelOrdenesServicioDia.setBackground(new java.awt.Color(0, 0, 0));
        labelOrdenesServicioDia.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelOrdenesServicioDia.setForeground(new java.awt.Color(0, 0, 0));
        labelOrdenesServicioDia.setText("ORDENES DE SERVICIO POR DIA");

        javax.swing.GroupLayout tarjetaOrdenesServicioPorDiaLayout = new javax.swing.GroupLayout(tarjetaOrdenesServicioPorDia);
        tarjetaOrdenesServicioPorDia.setLayout(tarjetaOrdenesServicioPorDiaLayout);
        tarjetaOrdenesServicioPorDiaLayout.setHorizontalGroup(
            tarjetaOrdenesServicioPorDiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tarjetaOrdenesServicioPorDiaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelOrdenesServicioDia)
                .addContainerGap(308, Short.MAX_VALUE))
        );
        tarjetaOrdenesServicioPorDiaLayout.setVerticalGroup(
            tarjetaOrdenesServicioPorDiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tarjetaOrdenesServicioPorDiaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelOrdenesServicioDia)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TarjetaServiciosRealizados.setBackground(new java.awt.Color(255, 255, 255));
        TarjetaServiciosRealizados.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblSeriviciosRealzados.setBackground(new java.awt.Color(0, 0, 0));
        lblSeriviciosRealzados.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblSeriviciosRealzados.setForeground(new java.awt.Color(0, 0, 0));
        lblSeriviciosRealzados.setText("SERVICIOS MAS REALIZADOS");

        javax.swing.GroupLayout TarjetaServiciosRealizadosLayout = new javax.swing.GroupLayout(TarjetaServiciosRealizados);
        TarjetaServiciosRealizados.setLayout(TarjetaServiciosRealizadosLayout);
        TarjetaServiciosRealizadosLayout.setHorizontalGroup(
            TarjetaServiciosRealizadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TarjetaServiciosRealizadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSeriviciosRealzados, javax.swing.GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE)
                .addContainerGap())
        );
        TarjetaServiciosRealizadosLayout.setVerticalGroup(
            TarjetaServiciosRealizadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TarjetaServiciosRealizadosLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(lblSeriviciosRealzados)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TarjetaIngresosDia.setBackground(new java.awt.Color(255, 255, 255));
        TarjetaIngresosDia.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblIngresosDia.setBackground(new java.awt.Color(0, 0, 0));
        lblIngresosDia.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblIngresosDia.setForeground(new java.awt.Color(0, 0, 0));
        lblIngresosDia.setText("INGRESOS POR DIA");

        javax.swing.GroupLayout TarjetaIngresosDiaLayout = new javax.swing.GroupLayout(TarjetaIngresosDia);
        TarjetaIngresosDia.setLayout(TarjetaIngresosDiaLayout);
        TarjetaIngresosDiaLayout.setHorizontalGroup(
            TarjetaIngresosDiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TarjetaIngresosDiaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblIngresosDia, javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE)
                .addContainerGap())
        );
        TarjetaIngresosDiaLayout.setVerticalGroup(
            TarjetaIngresosDiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TarjetaIngresosDiaLayout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addComponent(lblIngresosDia)
                .addGap(277, 277, 277))
        );

        TarjetaRepuestosMasUtilizados.setBackground(new java.awt.Color(255, 255, 255));
        TarjetaRepuestosMasUtilizados.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblRepuestosUtilizados.setBackground(new java.awt.Color(0, 0, 0));
        lblRepuestosUtilizados.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblRepuestosUtilizados.setForeground(new java.awt.Color(0, 0, 0));
        lblRepuestosUtilizados.setText("REPUESTOS MAS UTILIZADOS");

        javax.swing.GroupLayout TarjetaRepuestosMasUtilizadosLayout = new javax.swing.GroupLayout(TarjetaRepuestosMasUtilizados);
        TarjetaRepuestosMasUtilizados.setLayout(TarjetaRepuestosMasUtilizadosLayout);
        TarjetaRepuestosMasUtilizadosLayout.setHorizontalGroup(
            TarjetaRepuestosMasUtilizadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TarjetaRepuestosMasUtilizadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblRepuestosUtilizados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        TarjetaRepuestosMasUtilizadosLayout.setVerticalGroup(
            TarjetaRepuestosMasUtilizadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TarjetaRepuestosMasUtilizadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblRepuestosUtilizados)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TarjetaUsuario.setBackground(new java.awt.Color(255, 255, 255));
        TarjetaUsuario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblUsuarios.setBackground(new java.awt.Color(0, 0, 0));
        lblUsuarios.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblUsuarios.setForeground(new java.awt.Color(0, 0, 0));
        lblUsuarios.setText("Usuario:");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Cute_mechanic_holding_wrench_cartoon_icon_illustration___Premium_Vector-removebg-preview.png"))); // NOI18N

        javax.swing.GroupLayout TarjetaUsuarioLayout = new javax.swing.GroupLayout(TarjetaUsuario);
        TarjetaUsuario.setLayout(TarjetaUsuarioLayout);
        TarjetaUsuarioLayout.setHorizontalGroup(
            TarjetaUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TarjetaUsuarioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(TarjetaUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TarjetaUsuarioLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(66, 66, 66))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TarjetaUsuarioLayout.createSequentialGroup()
                        .addComponent(lblUsuarios)
                        .addGap(81, 81, 81))))
        );
        TarjetaUsuarioLayout.setVerticalGroup(
            TarjetaUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TarjetaUsuarioLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(lblUsuarios)
                .addContainerGap(76, Short.MAX_VALUE))
        );

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        labelVehiculos2.setBackground(new java.awt.Color(0, 0, 0));
        labelVehiculos2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelVehiculos2.setForeground(new java.awt.Color(0, 0, 0));
        labelVehiculos2.setText("Resumen del Periodo");

        labelVehiculos3.setBackground(new java.awt.Color(0, 0, 0));
        labelVehiculos3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelVehiculos3.setForeground(new java.awt.Color(0, 0, 0));
        labelVehiculos3.setText("Dias en el periodo:");

        labelVehiculos4.setBackground(new java.awt.Color(0, 0, 0));
        labelVehiculos4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelVehiculos4.setForeground(new java.awt.Color(0, 0, 0));
        labelVehiculos4.setText("Promedio diario de ingresos:");

        labelVehiculos5.setBackground(new java.awt.Color(0, 0, 0));
        labelVehiculos5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelVehiculos5.setForeground(new java.awt.Color(0, 0, 0));
        labelVehiculos5.setText("Promedio de ordenes por dia:");

        txtDias.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtDias.setForeground(new java.awt.Color(0, 0, 0));
        txtDias.setText("0");

        txtPromedioOrdenes.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtPromedioOrdenes.setForeground(new java.awt.Color(0, 0, 0));
        txtPromedioOrdenes.setText("0");

        txtPromedioIngresos.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtPromedioIngresos.setForeground(new java.awt.Color(0, 0, 0));
        txtPromedioIngresos.setText("$0");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelVehiculos2)
                    .addComponent(labelVehiculos4)
                    .addComponent(labelVehiculos5)
                    .addComponent(labelVehiculos3)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPromedioIngresos)
                            .addComponent(txtPromedioOrdenes)
                            .addComponent(txtDias))))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelVehiculos2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelVehiculos3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDias)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(labelVehiculos5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPromedioOrdenes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelVehiculos4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPromedioIngresos)
                .addGap(31, 31, 31))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(TarjetaIngresosDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TarjetaServiciosRealizados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TarjetaRepuestosMasUtilizados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(tarjetaOrdenesServicioPorEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tarjetaOrdenesServicioPorDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TarjetaUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(tarjetaOrdenes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tarjetaIngresos, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tarjetaVehiculos, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tarjetaServicios, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tarjetaRepuestos, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tarjetaOrdenes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(tarjetaIngresos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                                    .addComponent(tarjetaVehiculos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                                    .addComponent(tarjetaServicios, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                                    .addComponent(tarjetaRepuestos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tarjetaOrdenesServicioPorEstado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tarjetaOrdenesServicioPorDia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(TarjetaIngresosDia, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TarjetaServiciosRealizados, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TarjetaRepuestosMasUtilizados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(TarjetaUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        Titulo.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        Titulo.setForeground(new java.awt.Color(145, 145, 145));
        Titulo.setText("Estadisticas Generales ");
        Titulo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Titulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TituloMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TituloMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TituloMouseExited(evt);
            }
        });

        Reportes.setBackground(new java.awt.Color(242, 101, 34));
        Reportes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(187, 187, 187)));
        Reportes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Reportes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ReportesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ReportesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ReportesMouseExited(evt);
            }
        });

        Guardar.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        Guardar.setForeground(new java.awt.Color(255, 255, 255));
        Guardar.setText("Reportes");

        ImagenSAVE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/save_22dp_FFFFFF_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N

        javax.swing.GroupLayout ReportesLayout = new javax.swing.GroupLayout(Reportes);
        Reportes.setLayout(ReportesLayout);
        ReportesLayout.setHorizontalGroup(
            ReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ReportesLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(ImagenSAVE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Guardar)
                .addContainerGap(38, Short.MAX_VALUE))
        );
        ReportesLayout.setVerticalGroup(
            ReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ReportesLayout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addGroup(ReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Guardar)
                    .addComponent(ImagenSAVE))
                .addGap(10, 10, 10))
        );

        Guardar1.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        Guardar1.setForeground(new java.awt.Color(255, 255, 255));
        Guardar1.setText("Desde");

        Desde.setDateFormatString("dd/MM/yyyy");

        Guardar2.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        Guardar2.setForeground(new java.awt.Color(255, 255, 255));
        Guardar2.setText("Hasta");

        Hasta.setDateFormatString("dd/MM/yyyy");

        btnAplicar.setText("Aplicar");
        btnAplicar.addActionListener(this::btnAplicarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(Titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Reportes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAplicar)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Guardar1)
                        .addGap(83, 83, 83)
                        .addComponent(Guardar2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Desde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Hasta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(72, 72, 72))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Titulo)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Guardar1)
                                    .addComponent(Guardar2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Desde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Hasta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(Reportes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAplicar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void TituloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TituloMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_TituloMouseClicked

    private void TituloMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TituloMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_TituloMouseEntered

    private void TituloMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TituloMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_TituloMouseExited

    private void ReportesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReportesMouseClicked
        // TODO add your handling code here:
        if (fechaDesde == null || fechaHasta == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Primero aplica un rango de fechas.");
            return;
        }
        try {
            OrdenServicioDAO ordenDAO = new OrdenServicioDAO();
            ServicioDAO servicioDAO = new ServicioDAO();
            ProduceDAO produceDAO = new ProduceDAO();
            RepuestoDAO repuestoDAO = new RepuestoDAO();

            int totalOrdenes = ordenDAO.contarOrdenes(fechaDesde, fechaHasta);
            double totalIngresos = ordenDAO.sumarIngresos(fechaDesde, fechaHasta);
            int totalVehiculos = ordenDAO.contarVehiculosAtendidos(fechaDesde, fechaHasta);
            int totalServicios = servicioDAO.contarServiciosRealizados(fechaDesde, fechaHasta);
            int totalRepuestos = repuestoDAO.contarServiciosRealizados(fechaDesde, fechaHasta);
            java.util.List<ItemReporteDTO> items = new java.util.ArrayList<>();
            servicioDAO.topServiciosMasRealizados(fechaDesde, fechaHasta, 5)
                    .forEach((nombre, cant) -> items.add(new ItemReporteDTO("Servicio", nombre, cant)));
            repuestoDAO.topRepuestosMasUtilizados(fechaDesde, fechaHasta, 5)
                    .forEach((nombre, cant) -> items.add(new ItemReporteDTO("Repuesto", nombre, cant)));
            ordenDAO.topEmpleadosPorOrdenesCompletadas(fechaDesde, fechaHasta, 5)
                    .forEach((nombre, cant) -> items.add(new ItemReporteDTO("Empleado", nombre, cant)));
            produceDAO.sumarResiduosPorTipo(fechaDesde, fechaHasta)
                    .forEach((nombre, cant) -> items.add(new ItemReporteDTO("Residuo", nombre, cant)));
            java.util.Map<String, Object> parametros = new java.util.HashMap<>();
            parametros.put("pDesde", fechaDesde.toString());
            parametros.put("pHasta", fechaHasta.toString());
            parametros.put("pTotalOrdenes", totalOrdenes);
            parametros.put("pTotalIngresos", totalIngresos);
            parametros.put("pTotalVehiculos", totalVehiculos);
            parametros.put("pTotalServicios", totalServicios);
            parametros.put("pTotalRepuestos", totalRepuestos);

            org.jfree.data.category.DefaultCategoryDataset dataset = new org.jfree.data.category.DefaultCategoryDataset();
            for (ItemReporteDTO item : items) {
                dataset.addValue(item.getCantidad(), item.getCategoria(), item.getNombre());
            }
            org.jfree.chart.JFreeChart chart = org.jfree.chart.ChartFactory.createBarChart(
                    "Resumen del Período",
                    "Elemento",
                    "Cantidad",
                    dataset
            );
            java.awt.Image imagenGrafico = chart.createBufferedImage(450, 250);
            parametros.put("pGraficoImagen", imagenGrafico);

            net.sf.jasperreports.engine.data.JRBeanCollectionDataSource dataSource
                    = new net.sf.jasperreports.engine.data.JRBeanCollectionDataSource(items);
            String rutaJrxml = "src/main/resources/reportes/reporte_estadisticas.jrxml";
            net.sf.jasperreports.engine.JasperReport jasperReport
                    = net.sf.jasperreports.engine.JasperCompileManager.compileReport(rutaJrxml);
            net.sf.jasperreports.engine.JasperPrint jasperPrint
                    = net.sf.jasperreports.engine.JasperFillManager.fillReport(jasperReport, parametros, dataSource);
            net.sf.jasperreports.view.JasperViewer.viewReport(jasperPrint, false);
        } catch (Exception e) {
            e.printStackTrace();
            javax.swing.JOptionPane.showMessageDialog(this, "Error al generar el reporte: " + e.getMessage());
        }
    
    }//GEN-LAST:event_ReportesMouseClicked

    private void ReportesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReportesMouseEntered
        // TODO add your handling code here:
        Reportes.setBackground(new Color(227, 95, 32));
        Guardar.setForeground(new Color(217, 217, 192));
    }//GEN-LAST:event_ReportesMouseEntered

    private void ReportesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReportesMouseExited
        // TODO add your handling code here:
        Reportes.setBackground(new Color(242,101,34));
        Guardar.setForeground(Color.white);
    }//GEN-LAST:event_ReportesMouseExited

    private void btnAplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAplicarActionPerformed
        // TODO add your handling code here:
        if(Desde.getDate() == null || Hasta.getDate() == null){
            javax.swing.JOptionPane.showConfirmDialog(this, "Seleccione ambas fechas");
            return;
        }
        fechaDesde = Desde.getDate().toInstant().atZone(java.time.ZoneId.systemDefault()).toLocalDate();
        fechaHasta = Hasta.getDate().toInstant().atZone(java.time.ZoneId.systemDefault()).toLocalDate();

        if(fechaDesde.isAfter(fechaHasta)){
            javax.swing.JOptionPane.showConfirmDialog(this, "La fecha Desde no puede ser mayor a la fecha Hasta");
            return;
        }
        actualizarDashboard(fechaDesde, fechaHasta);
    }//GEN-LAST:event_btnAplicarActionPerformed
    
    private void actualizarDashboard(LocalDate Desde, LocalDate Hasta) {
        OrdenServicioDAO ordenDAO = new OrdenServicioDAO();
        ServicioDAO servicioDAO = new ServicioDAO();
        RepuestoDAO repuestoDAO = new RepuestoDAO();

        int totalOrdenes = ordenDAO.contarOrdenes(Desde, Hasta);
        double totalIngresos = ordenDAO.sumarIngresos(Desde, Hasta);
        int totalVehiculo = ordenDAO.contarVehiculosAtendidos(Desde, Hasta);
        int totalServicios = servicioDAO.contarServiciosRealizados(Desde, Hasta);
        int totalRepuestos = repuestoDAO.contarServiciosRealizados(Desde, Hasta);

        txtValorOrdenes.setText(String.valueOf(totalOrdenes));
        txtValorIngresos.setText(String.format("$%,.2f", totalIngresos));
        txtValorVehiculos.setText(String.valueOf(totalVehiculo));
        txtValorServicios.setText(String.valueOf(totalServicios));
        txtValorRepuestos.setText(String.valueOf(totalRepuestos));
        
        actualizarGraficoDona(Desde, Hasta);
        actualizarGraficosOrdenesPorDia(Desde, Hasta);
        actualizarGraficosIngresosPorDia(Desde, Hasta);
        actualizarGraficoServiciosMasRealizados(Desde, Hasta);
        actualizarGraficoRepuestosMasUtilizados(Desde, Hasta);
        
        long dias = ChronoUnit.DAYS.between(Desde, Hasta) + 1;
        double promedioordenes = dias == 0 ? 0 : (double) totalOrdenes / dias;
        double promedioingresos = dias == 0 ? 0 : totalIngresos / dias;
        
        txtDias.setText(String.valueOf(dias));
        txtPromedioOrdenes.setText(String.format("%.1f", promedioordenes));
        txtPromedioIngresos.setText(String.format("$%,.2f", promedioingresos));
    }
    private LocalDate fechaDesde;
    private LocalDate fechaHasta;
    
    private void actualizarGraficoDona(LocalDate Desde, LocalDate Hasta){
        OrdenServicioDAO ordenDAO = new OrdenServicioDAO();
        Map<String, Integer> datos = ordenDAO.contarOrdenesPorEstado(Desde, Hasta);
        int total = datos.values().stream().mapToInt(Integer::intValue).sum();
        
        DefaultPieDataset<String> dataset = new DefaultPieDataset<>();
        datos.forEach(dataset::setValue);
        
        JFreeChart chart = ChartFactory.createRingChart(null, dataset, false, false, false);
        RingPlot plot = (RingPlot) chart.getPlot();
        chart.setBackgroundPaint(null);
        plot.setBackgroundPaint(null);
        plot.setOutlineVisible(false);
        for(String estado : datos.keySet()){
            plot.setSectionPaint(estado, colorPorEstado(estado));
        }
        
        ChartPanel chartPanel = new ChartPanel(chart);
        chartPanel.setOpaque(false);
        
        JLabel titulo = (JLabel) tarjetaOrdenesServicioPorEstado.getComponent(0);
        tarjetaOrdenesServicioPorEstado.removeAll();
        tarjetaOrdenesServicioPorEstado.setLayout(new BorderLayout());
        tarjetaOrdenesServicioPorEstado.add(titulo, BorderLayout.NORTH);
        tarjetaOrdenesServicioPorEstado.add(chartPanel, BorderLayout.CENTER);
        
        JPanel leyenda = new JPanel();
        leyenda.setOpaque(false);
        leyenda.setLayout(new BoxLayout(leyenda, BoxLayout.Y_AXIS));
        datos.forEach((estado, cantidad) -> {
            double pct = total == 0 ? 0 : cantidad * 100.0 / total;
            JLabel lbl = new JLabel(String.format("●  %s — %d (%.1f%%)", estado, cantidad, pct));
            lbl.setForeground(colorPorEstado(estado));
            leyenda.add(lbl);
        });
        tarjetaOrdenesServicioPorEstado.add(leyenda, BorderLayout.SOUTH);
        
        tarjetaOrdenesServicioPorEstado.revalidate();
        tarjetaOrdenesServicioPorEstado.repaint();
    }
    
    private Color colorPorEstado(String estado){
        switch (estado) {
            case "En Proceso": return new Color(255,140,0);
            case "Completada": return new Color(30,100,220);
            case "Pendiente": return Color.GRAY;
            case "Cancelada": return new Color(200,30,30);
            default: return Color.LIGHT_GRAY;
        }
    }
    
    private void actualizarGraficosOrdenesPorDia(LocalDate Desde, LocalDate Hasta){
        OrdenServicioDAO ordenDAO = new OrdenServicioDAO();
        Map<LocalDate, Integer> datosCr = ordenDAO.contarOrdenesPorDia(Desde, Hasta);
        
        TimeSeries series = new TimeSeries("Ordenes");
        for (LocalDate fecha = Desde; !fecha.isAfter(Hasta); fecha = fecha.plusDays(1)){
            int cantidad = datosCr.getOrDefault(fecha, 0);
            series.add(new Day(fecha.getDayOfMonth(), fecha.getMonthValue(), fecha.getYear()), cantidad);
        }
        
        TimeSeriesCollection dataset = new TimeSeriesCollection();
        dataset.addSeries(series);
        
        JFreeChart chart = ChartFactory.createTimeSeriesChart(null, null, null, dataset, false, false, false);
        
        XYPlot plot = chart.getXYPlot();
        chart.setBackgroundPaint(null);
        plot.setBackgroundPaint(null);
        plot.setDomainGridlinesVisible(false);
        plot.setRangeGridlinesVisible(false);
        plot.setOutlineVisible(false);
        
        XYAreaRenderer render = new XYAreaRenderer(XYAreaRenderer.AREA);
        render.setSeriesPaint(0, new Color(255,140,0,120));
        plot.setRenderer(render);
        
        DateAxis ejex = (DateAxis) plot.getDomainAxis();
        ejex.setDateFormatOverride(new SimpleDateFormat("dd/MM"));
        
        ChartPanel chartpanel = new ChartPanel(chart);
        chartpanel.setOpaque(false);
        
        JLabel titulo = (JLabel) tarjetaOrdenesServicioPorDia.getComponent(0);
        tarjetaOrdenesServicioPorDia.removeAll();
        tarjetaOrdenesServicioPorDia.setLayout(new BorderLayout());
        tarjetaOrdenesServicioPorDia.add(titulo, BorderLayout.NORTH);
        tarjetaOrdenesServicioPorDia.add(chartpanel, BorderLayout.CENTER);
        
        tarjetaOrdenesServicioPorDia.revalidate();
        tarjetaOrdenesServicioPorDia.repaint();
    }
    
    private void actualizarGraficosIngresosPorDia(LocalDate Desde, LocalDate Hasta){
        OrdenServicioDAO ordenDAO = new OrdenServicioDAO();
        Map<LocalDate, Double> datosCr = ordenDAO.sumarIngresosPorDia(Desde, Hasta);
        
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        DateTimeFormatter formato = DateTimeFormatter.ofPattern("dd/MM");
        
        for (LocalDate fecha = Desde; !fecha.isAfter(Hasta); fecha = fecha.plusDays(1)){
            double total = datosCr.getOrDefault(fecha, 0.0);
            dataset.addValue(total, "Ingresos", fecha.format(formato));
        }
        
        JFreeChart chart = ChartFactory.createBarChart(null, null, null, dataset);
        
        CategoryPlot plot = chart.getCategoryPlot();
        chart.setBackgroundImage(null);
        plot.setBackgroundPaint(null);
        plot.setDomainGridlinesVisible(false);
        plot.setRangeGridlinesVisible(false);
        plot.setOutlineVisible(false);
        
        BarRenderer render = (BarRenderer) plot.getRenderer();
        render.setSeriesPaint(0, new Color(255, 140, 0));
        render.setShadowVisible(false);
        plot.setRenderer(render);
        
        plot.getRangeAxis().setVisible(true);
        chart.getLegend().setVisible(false);
        
        ChartPanel chartPanel = new ChartPanel(chart);
        chartPanel.setOpaque(false);
        
        JLabel titulo = (JLabel) TarjetaIngresosDia.getComponent(0);
        TarjetaIngresosDia.removeAll();
        TarjetaIngresosDia.setLayout(new BorderLayout());
        TarjetaIngresosDia.add(titulo, BorderLayout.NORTH);
        TarjetaIngresosDia.add(chartPanel, BorderLayout.CENTER);
        TarjetaIngresosDia.revalidate();
        TarjetaIngresosDia.repaint();
    }
    
    private void actualizarGraficoServiciosMasRealizados(LocalDate Desde, LocalDate Hasta) {
        ServicioDAO ordenDAO = new ServicioDAO();
        Map<String, Integer> datos = ordenDAO.topServiciosMasRealizados(Desde, Hasta, 5);
        
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        for(Map.Entry<String, Integer> entry : datos.entrySet()){
            dataset.addValue(entry.getValue(), "Cantidad", entry.getKey());
        }
        
        JFreeChart chart = ChartFactory.createBarChart(null, null, null, dataset, org.jfree.chart.plot.PlotOrientation.HORIZONTAL, false, false, false);

        CategoryPlot plot = chart.getCategoryPlot();
        chart.setBackgroundPaint(null);
        plot.setBackgroundPaint(null);
        plot.setDomainGridlinesVisible(false);
        plot.setRangeGridlinesVisible(false);
        plot.setOutlineVisible(false);
        
        BarRenderer render = (BarRenderer) plot.getRenderer();
        render.setSeriesPaint(0, new Color(255, 140, 0));
        render.setShadowVisible(false);
        
        ChartPanel chartPanel = new ChartPanel(chart);
        chartPanel.setOpaque(false);
        
        JLabel titulo = (JLabel) TarjetaServiciosRealizados.getComponent(0);
        TarjetaServiciosRealizados.removeAll();
        TarjetaServiciosRealizados.setLayout(new BorderLayout());
        TarjetaServiciosRealizados.add(titulo, BorderLayout.NORTH);
        TarjetaServiciosRealizados.add(chartPanel, BorderLayout.CENTER);
    }
    
    private void actualizarGraficoRepuestosMasUtilizados(LocalDate Desde, LocalDate Hasta) {
        RepuestoDAO ordenDAO = new RepuestoDAO();
        Map<String, Integer> datos = ordenDAO.topRepuestosMasUtilizados(Desde, Hasta, 5);

        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        for (Map.Entry<String, Integer> entry : datos.entrySet()) {
            dataset.addValue(entry.getValue(), "Cantidad", entry.getKey());
        }

        JFreeChart chart = ChartFactory.createBarChart(null, null, null, dataset, org.jfree.chart.plot.PlotOrientation.HORIZONTAL, false, false, false);

        CategoryPlot plot = chart.getCategoryPlot();
        chart.setBackgroundPaint(null);
        plot.setBackgroundPaint(null);
        plot.setDomainGridlinesVisible(false);
        plot.setRangeGridlinesVisible(false);
        plot.setOutlineVisible(false);

        BarRenderer render = (BarRenderer) plot.getRenderer();
        render.setSeriesPaint(0, new Color(30,100,220));
        render.setShadowVisible(false);

        ChartPanel chartPanel = new ChartPanel(chart);
        chartPanel.setOpaque(false);

        JLabel titulo = (JLabel) TarjetaRepuestosMasUtilizados.getComponent(0);
        TarjetaRepuestosMasUtilizados.removeAll();
        TarjetaRepuestosMasUtilizados.setLayout(new BorderLayout());
        TarjetaRepuestosMasUtilizados.add(titulo, BorderLayout.NORTH);
        TarjetaRepuestosMasUtilizados.add(chartPanel, BorderLayout.CENTER);
    }
    
    
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser Desde;
    private javax.swing.JLabel Guardar;
    private javax.swing.JLabel Guardar1;
    private javax.swing.JLabel Guardar2;
    private com.toedter.calendar.JDateChooser Hasta;
    private javax.swing.JLabel ImagenSAVE;
    private javax.swing.JPanel Reportes;
    private javax.swing.JPanel TarjetaIngresosDia;
    private javax.swing.JPanel TarjetaRepuestosMasUtilizados;
    private javax.swing.JPanel TarjetaServiciosRealizados;
    private javax.swing.JPanel TarjetaUsuario;
    private javax.swing.JLabel Titulo;
    private javax.swing.JButton btnAplicar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JLabel labelIngresos;
    private javax.swing.JLabel labelOrdenes;
    private javax.swing.JLabel labelOrdenesServicioDia;
    private javax.swing.JLabel labelOrdenesServicioEstado;
    private javax.swing.JLabel labelRepuestos;
    private javax.swing.JLabel labelServicios;
    private javax.swing.JLabel labelVehiculos;
    private javax.swing.JLabel labelVehiculos2;
    private javax.swing.JLabel labelVehiculos3;
    private javax.swing.JLabel labelVehiculos4;
    private javax.swing.JLabel labelVehiculos5;
    private javax.swing.JLabel lblIngresosDia;
    private javax.swing.JLabel lblRepuestosUtilizados;
    private javax.swing.JLabel lblSeriviciosRealzados;
    private javax.swing.JLabel lblUsuarios;
    private javax.swing.JPanel tarjetaIngresos;
    private javax.swing.JPanel tarjetaOrdenes;
    private javax.swing.JPanel tarjetaOrdenesServicioPorDia;
    private javax.swing.JPanel tarjetaOrdenesServicioPorEstado;
    private javax.swing.JPanel tarjetaRepuestos;
    private javax.swing.JPanel tarjetaServicios;
    private javax.swing.JPanel tarjetaVehiculos;
    private javax.swing.JLabel txtDias;
    private javax.swing.JLabel txtPromedioIngresos;
    private javax.swing.JLabel txtPromedioOrdenes;
    private javax.swing.JLabel txtValorIngresos;
    private javax.swing.JLabel txtValorOrdenes;
    private javax.swing.JLabel txtValorRepuestos;
    private javax.swing.JLabel txtValorServicios;
    private javax.swing.JLabel txtValorVehiculos;
    // End of variables declaration//GEN-END:variables
}
