/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.proyecto_m2b.Vista;

import com.mycompany.proyecto_m2b.Controlador.CompraDAO;
import com.mycompany.proyecto_m2b.Controlador.ConexionBD;
import com.mycompany.proyecto_m2b.Controlador.ProveedorDAO;
import com.mycompany.proyecto_m2b.Controlador.RepuestoDAO;
import com.mycompany.proyecto_m2b.modelo.Proveedor;
import com.mycompany.proyecto_m2b.modelo.Repuesto;
import com.mycompany.proyecto_m2b.modelo.TipoProveedor;
import java.sql.Connection;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP
 */
public class PanelProveedores extends javax.swing.JPanel {
    private Connection miConexion;
    private DefaultTableModel modeloTabla;
    private CompraDAO compraDAO = new CompraDAO();
    private ProveedorDAO proveedorDAO = new ProveedorDAO();
    private RepuestoDAO repuestoDAO = new RepuestoDAO();
    /**
     * Creates new form PanelProveedores
     */
    public PanelProveedores() {
    this.miConexion = ConexionBD.obtenerConexion();
    initComponents();
    txtIdCompra.setEditable(false);
    txtFechaCompra.setEnabled(false);
    txtTotalCompra.setEditable(false);
    txtFechaCompra.setDate(new Date());

    inicializarTabla();
    cargarCombos();
    generarSiguienteIdCompra();
    }
    
    private void inicializarTabla() {
    modeloTabla = new DefaultTableModel(
        new Object[]{"ID Repuesto", "Nombre Repuesto", "Cantidad", "Precio Unit.", "Subtotal"}, 0
    ) {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };
    tblDetalleCompra.setModel(modeloTabla);
}

private void cargarCombos() {
    cbxProveedor.removeAllItems();
    List<Proveedor> proveedores = proveedorDAO.obtenerProveedores(miConexion);
    for (Proveedor p : proveedores) {
        cbxProveedor.addItem(p);
    }

    cbxRepuesto.removeAllItems();
    List<Repuesto> repuestos = repuestoDAO.obtenerRepuestos(miConexion);
    for (Repuesto r : repuestos) {
        cbxRepuesto.addItem(r);
    }
}

private void generarSiguienteIdCompra() {
    txtIdCompra.setText(compraDAO.obtenerSiguienteIdCompra(miConexion));
}
    private void limpiarFormulario() {
    modeloTabla.setRowCount(0);
    txtTotalCompra.setText("");
    txtCantidadCompra.setText("");
    txtPrecioUnitarioCompra.setText("");
    generarSiguienteIdCompra();
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Fondo = new javax.swing.JPanel();
        BarraArriba = new javax.swing.JPanel();
        NombreVentanaProveedores = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JLabel();
        BarraAbajo = new javax.swing.JPanel();
        TituloFuncion1 = new javax.swing.JLabel();
        Proveedor = new javax.swing.JLabel();
        Factura = new javax.swing.JLabel();
        Fecha = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cbxProveedor = new javax.swing.JComboBox<>();
        TituloFuncion2 = new javax.swing.JLabel();
        Repuesto = new javax.swing.JLabel();
        Cantidad = new javax.swing.JLabel();
        Precio = new javax.swing.JLabel();
        txtCantidadCompra = new javax.swing.JTextField();
        cbxRepuesto = new javax.swing.JComboBox<>();
        txtIdCompra = new javax.swing.JTextField();
        txtFechaCompra = new com.toedter.calendar.JDateChooser();
        txtPrecioUnitarioCompra = new javax.swing.JTextField();
        btnAgregarItem = new javax.swing.JPanel();
        Nuevo = new javax.swing.JLabel();
        ImagenADD = new javax.swing.JLabel();
        btnGuardarCompra = new javax.swing.JPanel();
        Guardar = new javax.swing.JLabel();
        ImagenSAVE = new javax.swing.JLabel();
        PanelEditar = new javax.swing.JPanel();
        Editar = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        PanelBuscar = new javax.swing.JPanel();
        Buscar = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnAgregarProveedor = new javax.swing.JPanel();
        Nuevo1 = new javax.swing.JLabel();
        ImagenADD1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDetalleCompra = new javax.swing.JTable();
        txtTotalCompra = new javax.swing.JTextField();

        Fondo.setBackground(new java.awt.Color(255, 255, 255));
        Fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BarraArriba.setBackground(new java.awt.Color(0, 0, 0));

        NombreVentanaProveedores.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        NombreVentanaProveedores.setForeground(new java.awt.Color(255, 255, 255));
        NombreVentanaProveedores.setText("GESTIÓN DE PROVEEDORES Y COMPRA DE REPUESTOS");

        btnRegresar.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        btnRegresar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegresar.setText("Regresar");
        btnRegresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegresarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout BarraArribaLayout = new javax.swing.GroupLayout(BarraArriba);
        BarraArriba.setLayout(BarraArribaLayout);
        BarraArribaLayout.setHorizontalGroup(
            BarraArribaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BarraArribaLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(NombreVentanaProveedores, javax.swing.GroupLayout.PREFERRED_SIZE, 616, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 529, Short.MAX_VALUE)
                .addComponent(btnRegresar)
                .addGap(43, 43, 43))
        );
        BarraArribaLayout.setVerticalGroup(
            BarraArribaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BarraArribaLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(BarraArribaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegresar)
                    .addComponent(NombreVentanaProveedores))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Fondo.add(BarraArriba, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1320, 60));

        BarraAbajo.setBackground(new java.awt.Color(227, 153, 106));

        javax.swing.GroupLayout BarraAbajoLayout = new javax.swing.GroupLayout(BarraAbajo);
        BarraAbajo.setLayout(BarraAbajoLayout);
        BarraAbajoLayout.setHorizontalGroup(
            BarraAbajoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        BarraAbajoLayout.setVerticalGroup(
            BarraAbajoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        Fondo.add(BarraAbajo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 630, 1210, 70));

        TituloFuncion1.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        TituloFuncion1.setForeground(new java.awt.Color(153, 153, 153));
        TituloFuncion1.setText("ENCABEZADO DEL ENVÍO / COMPRA");
        Fondo.add(TituloFuncion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        Proveedor.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 13)); // NOI18N
        Proveedor.setForeground(new java.awt.Color(153, 153, 153));
        Proveedor.setText("Proveedor (RUC / Nombre)::");
        Fondo.add(Proveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        Factura.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 13)); // NOI18N
        Factura.setForeground(new java.awt.Color(153, 153, 153));
        Factura.setText("N° Factura / Referencia:");
        Fondo.add(Factura, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 120, -1, -1));

        Fecha.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 13)); // NOI18N
        Fecha.setForeground(new java.awt.Color(153, 153, 153));
        Fecha.setText("Fecha de Envío:");
        Fondo.add(Fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 170, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/images (2).jpg"))); // NOI18N
        Fondo.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 60, -1, -1));

        cbxProveedor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 2", "Item 3", "Item 4" }));
        Fondo.add(cbxProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 240, -1));

        TituloFuncion2.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        TituloFuncion2.setForeground(new java.awt.Color(153, 153, 153));
        TituloFuncion2.setText("DETALLE DE REPUESTOS SOLICITADOS");
        Fondo.add(TituloFuncion2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, -1));

        Repuesto.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 13)); // NOI18N
        Repuesto.setForeground(new java.awt.Color(153, 153, 153));
        Repuesto.setText("Repuesto:");
        Fondo.add(Repuesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, -1));

        Cantidad.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 13)); // NOI18N
        Cantidad.setForeground(new java.awt.Color(153, 153, 153));
        Cantidad.setText("Cantidad:");
        Fondo.add(Cantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 290, -1, -1));

        Precio.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 13)); // NOI18N
        Precio.setForeground(new java.awt.Color(153, 153, 153));
        Precio.setText("Precio Unitario:");
        Fondo.add(Precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 290, -1, -1));

        txtCantidadCompra.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCantidadCompraFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCantidadCompraFocusLost(evt);
            }
        });
        Fondo.add(txtCantidadCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 310, 270, -1));

        cbxRepuesto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 2", "Item 3", "Item 4" }));
        cbxRepuesto.addActionListener(this::cbxRepuestoActionPerformed);
        Fondo.add(cbxRepuesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 240, -1));

        txtIdCompra.addActionListener(this::txtIdCompraActionPerformed);
        Fondo.add(txtIdCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 140, 200, -1));
        Fondo.add(txtFechaCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 190, 200, -1));

        txtPrecioUnitarioCompra.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPrecioUnitarioCompraFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPrecioUnitarioCompraFocusLost(evt);
            }
        });
        Fondo.add(txtPrecioUnitarioCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 310, 270, -1));

        btnAgregarItem.setBackground(new java.awt.Color(255, 255, 255));
        btnAgregarItem.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(187, 187, 187)));
        btnAgregarItem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregarItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAgregarItemMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAgregarItemMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAgregarItemMouseExited(evt);
            }
        });

        Nuevo.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        Nuevo.setText("Agregar");

        ImagenADD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/add_22dp_000000_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N

        javax.swing.GroupLayout btnAgregarItemLayout = new javax.swing.GroupLayout(btnAgregarItem);
        btnAgregarItem.setLayout(btnAgregarItemLayout);
        btnAgregarItemLayout.setHorizontalGroup(
            btnAgregarItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnAgregarItemLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(ImagenADD)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Nuevo)
                .addContainerGap(33, Short.MAX_VALUE))
        );
        btnAgregarItemLayout.setVerticalGroup(
            btnAgregarItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnAgregarItemLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(btnAgregarItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ImagenADD)
                    .addComponent(Nuevo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Fondo.add(btnAgregarItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 310, -1, -1));

        btnGuardarCompra.setBackground(new java.awt.Color(242, 101, 34));
        btnGuardarCompra.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(187, 187, 187)));
        btnGuardarCompra.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardarCompra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGuardarCompraMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnGuardarCompraMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnGuardarCompraMouseExited(evt);
            }
        });

        Guardar.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        Guardar.setForeground(new java.awt.Color(255, 255, 255));
        Guardar.setText("Guardar");

        ImagenSAVE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/save_22dp_FFFFFF_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N

        javax.swing.GroupLayout btnGuardarCompraLayout = new javax.swing.GroupLayout(btnGuardarCompra);
        btnGuardarCompra.setLayout(btnGuardarCompraLayout);
        btnGuardarCompraLayout.setHorizontalGroup(
            btnGuardarCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnGuardarCompraLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(ImagenSAVE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Guardar)
                .addContainerGap(36, Short.MAX_VALUE))
        );
        btnGuardarCompraLayout.setVerticalGroup(
            btnGuardarCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnGuardarCompraLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(btnGuardarCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Guardar)
                    .addComponent(ImagenSAVE))
                .addContainerGap())
        );

        Fondo.add(btnGuardarCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 410, -1, -1));

        PanelEditar.setBackground(new java.awt.Color(255, 255, 255));
        PanelEditar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(187, 187, 187)));
        PanelEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PanelEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PanelEditarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PanelEditarMouseExited(evt);
            }
        });

        Editar.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        Editar.setText("Editar");

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/edit_22dp_000000_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N

        javax.swing.GroupLayout PanelEditarLayout = new javax.swing.GroupLayout(PanelEditar);
        PanelEditar.setLayout(PanelEditarLayout);
        PanelEditarLayout.setHorizontalGroup(
            PanelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelEditarLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Editar)
                .addContainerGap(33, Short.MAX_VALUE))
        );
        PanelEditarLayout.setVerticalGroup(
            PanelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelEditarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Editar)
                    .addComponent(jLabel2))
                .addContainerGap())
        );

        Fondo.add(PanelEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 410, -1, -1));

        PanelBuscar.setBackground(new java.awt.Color(255, 255, 255));
        PanelBuscar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(187, 187, 187)));
        PanelBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PanelBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PanelBuscarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PanelBuscarMouseExited(evt);
            }
        });

        Buscar.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        Buscar.setText("Buscar");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/person_search_22dp_000000_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N

        javax.swing.GroupLayout PanelBuscarLayout = new javax.swing.GroupLayout(PanelBuscar);
        PanelBuscar.setLayout(PanelBuscarLayout);
        PanelBuscarLayout.setHorizontalGroup(
            PanelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelBuscarLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Buscar)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        PanelBuscarLayout.setVerticalGroup(
            PanelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBuscarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Buscar)
                    .addComponent(jLabel3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Fondo.add(PanelBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 410, -1, -1));

        btnAgregarProveedor.setBackground(new java.awt.Color(255, 255, 255));
        btnAgregarProveedor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(187, 187, 187)));
        btnAgregarProveedor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregarProveedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAgregarProveedorMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAgregarProveedorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAgregarProveedorMouseExited(evt);
            }
        });

        Nuevo1.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        Nuevo1.setText("Nuevo");

        ImagenADD1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/add_22dp_000000_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N

        javax.swing.GroupLayout btnAgregarProveedorLayout = new javax.swing.GroupLayout(btnAgregarProveedor);
        btnAgregarProveedor.setLayout(btnAgregarProveedorLayout);
        btnAgregarProveedorLayout.setHorizontalGroup(
            btnAgregarProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnAgregarProveedorLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(ImagenADD1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Nuevo1)
                .addContainerGap(33, Short.MAX_VALUE))
        );
        btnAgregarProveedorLayout.setVerticalGroup(
            btnAgregarProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnAgregarProveedorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(btnAgregarProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ImagenADD1)
                    .addComponent(Nuevo1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Fondo.add(btnAgregarProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, -1));

        tblDetalleCompra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID Repuesto", "Nombre Repuesto", "Cantidad", "Precio Unit.", "Subtotal"
            }
        ));
        jScrollPane1.setViewportView(tblDetalleCompra);

        Fondo.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 480, 380, 100));
        Fondo.add(txtTotalCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 400, 110, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegresarMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnRegresarMouseClicked

    private void txtCantidadCompraFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCantidadCompraFocusGained
        if (txtCantidadCompra.getText().equals("Ingrese la cantidad a solicitar")) {
            txtCantidadCompra.setText("");
            txtCantidadCompra.setForeground(java.awt.Color.BLACK);
        }
    }//GEN-LAST:event_txtCantidadCompraFocusGained

    private void txtCantidadCompraFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCantidadCompraFocusLost
        if (txtCantidadCompra.getText().trim().isEmpty()) {
            txtCantidadCompra.setText("Ingrese la cantidad a solicitar");
            txtCantidadCompra.setForeground(java.awt.Color.GRAY);
        }
    }//GEN-LAST:event_txtCantidadCompraFocusLost

    private void txtIdCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdCompraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdCompraActionPerformed

    private void txtPrecioUnitarioCompraFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPrecioUnitarioCompraFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioUnitarioCompraFocusGained

    private void txtPrecioUnitarioCompraFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPrecioUnitarioCompraFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioUnitarioCompraFocusLost

    private void btnAgregarItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarItemMouseClicked
        // TODO add your handling code here:
        try {
        Repuesto repuestoSel = (Repuesto) cbxRepuesto.getSelectedItem();
        int cantidad = Integer.parseInt(txtCantidadCompra.getText().trim());
        double precio = Double.parseDouble(txtPrecioUnitarioCompra.getText().trim().replace(',', '.'));

        if (repuestoSel == null || cantidad <= 0 || precio <= 0) {
            JOptionPane.showMessageDialog(this, "Seleccione un repuesto e ingrese valores válidos.", "Validación", JOptionPane.WARNING_MESSAGE);
            return;
        }

        double subtotal = cantidad * precio;

        modeloTabla.addRow(new Object[]{
            repuestoSel.getIdRepuestos(),
            repuestoSel.getNomRepuesto(),
            cantidad,
            precio,
            subtotal
        });

        calcularTotal();

        txtCantidadCompra.setText("");
        txtPrecioUnitarioCompra.setText("");

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Ingrese una cantidad y precio válidos.", "Error", JOptionPane.ERROR_MESSAGE);
    }
}

private void calcularTotal() {
    double total = 0.0;
    for (int i = 0; i < modeloTabla.getRowCount(); i++) {
        total += (double) modeloTabla.getValueAt(i, 4);
    }
    txtTotalCompra.setText(String.format("%.2f", total).replace(',', '.'));
    }//GEN-LAST:event_btnAgregarItemMouseClicked

    private void btnAgregarItemMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarItemMouseEntered
        // TODO add your handling code here:
        btnAgregarItem.setBackground(new java.awt.Color(219,219,219));
        Nuevo.setForeground(new java.awt.Color(66, 66, 66));
    }//GEN-LAST:event_btnAgregarItemMouseEntered

    private void btnAgregarItemMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarItemMouseExited
        // TODO add your handling code here:
        btnAgregarItem.setBackground(java.awt.Color.white);
        Nuevo.setForeground(java.awt.Color.black);
    }//GEN-LAST:event_btnAgregarItemMouseExited

    private void btnGuardarCompraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarCompraMouseClicked
        // TODO add your handling code here:
    if (modeloTabla.getRowCount() == 0) {
        JOptionPane.showMessageDialog(this, "Debe agregar al menos un repuesto a la compra.", "Advertencia", JOptionPane.WARNING_MESSAGE);
        return;
    }

    Proveedor provSel = (Proveedor) cbxProveedor.getSelectedItem();
    if (provSel == null) {
        JOptionPane.showMessageDialog(this, "Seleccione un proveedor.", "Advertencia", JOptionPane.WARNING_MESSAGE);
        return;
    }

    String idCompra = txtIdCompra.getText().trim();
    Date fechaSeleccionada = txtFechaCompra.getDate();
String fecha = "";
if (fechaSeleccionada != null) {
    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd"); 
    fecha = sdf.format(fechaSeleccionada);
}
    double total = Double.parseDouble(txtTotalCompra.getText().trim().replace(',', '.'));

    if (compraDAO.guardarEncabezadoCompra(idCompra, fecha, total, provSel.getIdProveedor(), miConexion)) {

        for (int i = 0; i < modeloTabla.getRowCount(); i++) {
            String idDetalle = "DET-" + System.currentTimeMillis() + "-" + i;
            String idRepuesto = (String) modeloTabla.getValueAt(i, 0);
            int cantidad = (int) modeloTabla.getValueAt(i, 2);
            double subtotal = (double) modeloTabla.getValueAt(i, 4);

            compraDAO.guardarDetalleCompra(idDetalle, cantidad, subtotal, idRepuesto, idCompra, miConexion);
            compraDAO.actualizarStockRepuesto(idRepuesto, cantidad, miConexion);
        }

        JOptionPane.showMessageDialog(this, "¡Compra registrada y stock actualizado exitosamente!");
        limpiarFormulario();
    } else {
        JOptionPane.showMessageDialog(this, "Error al guardar la compra.", "Error SQL", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnGuardarCompraMouseClicked

    private void btnGuardarCompraMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarCompraMouseEntered
        // TODO add your handling code here:
        btnGuardarCompra.setBackground(new java.awt.Color(227, 95, 32));
        Guardar.setForeground(new java.awt.Color(217, 217, 192));
    }//GEN-LAST:event_btnGuardarCompraMouseEntered

    private void btnGuardarCompraMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarCompraMouseExited
        // TODO add your handling code here:
        btnGuardarCompra.setBackground(new java.awt.Color(242,101,34));
        Guardar.setForeground(java.awt.Color.white);
    }//GEN-LAST:event_btnGuardarCompraMouseExited

    private void PanelEditarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelEditarMouseEntered
        // TODO add your handling code here:
        PanelEditar.setBackground(new java.awt.Color(219,219,219));
        Editar.setForeground(new java.awt.Color(66, 66, 66));
    }//GEN-LAST:event_PanelEditarMouseEntered

    private void PanelEditarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelEditarMouseExited
        // TODO add your handling code here:
        PanelEditar.setBackground(java.awt.Color.white);
        Editar.setForeground(java.awt.Color.black);
    }//GEN-LAST:event_PanelEditarMouseExited

    private void PanelBuscarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelBuscarMouseEntered
        // TODO add your handling code here:
        PanelBuscar.setBackground(new java.awt.Color(219,219,219));
        Buscar.setForeground(new java.awt.Color(66, 66, 66));
    }//GEN-LAST:event_PanelBuscarMouseEntered

    private void PanelBuscarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelBuscarMouseExited
        // TODO add your handling code here:
        PanelBuscar.setBackground(java.awt.Color.white);
        Buscar.setForeground(java.awt.Color.black);
    }//GEN-LAST:event_PanelBuscarMouseExited

    private void btnAgregarProveedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarProveedorMouseClicked
        // TODO add your handling code here:
    JTextField txtRuc = new JTextField();
    JTextField txtNombre = new JTextField();
    JTextField txtTelefono = new JTextField();
    JComboBox<TipoProveedor> cbxTipoProvPop = new JComboBox<>();

    for (TipoProveedor tp : proveedorDAO.obtenerTiposProveedor(miConexion)) {
        cbxTipoProvPop.addItem(tp);
    }

    Object[] formulario = {
        "RUC / Identificación:", txtRuc,
        "Nombre Empresa:", txtNombre,
        "Teléfono:", txtTelefono,
        "Tipo de Proveedor:", cbxTipoProvPop
    };

    int opcion = JOptionPane.showConfirmDialog(this, formulario, "Registrar Nuevo Proveedor", JOptionPane.OK_CANCEL_OPTION);

    if (opcion == JOptionPane.OK_OPTION) {
        String ruc = txtRuc.getText().trim();
        String nombre = txtNombre.getText().trim();
        String telefono = txtTelefono.getText().trim();
        TipoProveedor tipoSel = (TipoProveedor) cbxTipoProvPop.getSelectedItem();

        if (!ruc.isEmpty() && !nombre.isEmpty() && tipoSel != null) {
            String idProv = proveedorDAO.obtenerSiguienteIdProveedor(miConexion);
            Proveedor nuevoProv = new Proveedor(idProv, ruc, nombre, telefono, tipoSel.getIdTipoProveedor());

            if (proveedorDAO.guardarProveedor(nuevoProv, miConexion)) {
                cbxProveedor.addItem(nuevoProv);
                cbxProveedor.setSelectedItem(nuevoProv);
                JOptionPane.showMessageDialog(this, "Proveedor guardado exitosamente.");
            }
        } else {
            JOptionPane.showMessageDialog(this, "RUC y Nombre son obligatorios.", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }
    }
    }//GEN-LAST:event_btnAgregarProveedorMouseClicked

    private void btnAgregarProveedorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarProveedorMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarProveedorMouseEntered

    private void btnAgregarProveedorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarProveedorMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarProveedorMouseExited

    private void cbxRepuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxRepuestoActionPerformed
        // TODO add your handling code here:
    Repuesto repuestoSel = (Repuesto) cbxRepuesto.getSelectedItem();
    if (repuestoSel != null) {
        txtPrecioUnitarioCompra.setText(String.valueOf(repuestoSel.getPrecioRepuestoUnit()));
    } else {
        txtPrecioUnitarioCompra.setText("");
    }

    }//GEN-LAST:event_cbxRepuestoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BarraAbajo;
    private javax.swing.JPanel BarraArriba;
    private javax.swing.JLabel Buscar;
    private javax.swing.JLabel Cantidad;
    private javax.swing.JLabel Editar;
    private javax.swing.JLabel Factura;
    private javax.swing.JLabel Fecha;
    private javax.swing.JPanel Fondo;
    private javax.swing.JLabel Guardar;
    private javax.swing.JLabel ImagenADD;
    private javax.swing.JLabel ImagenADD1;
    private javax.swing.JLabel ImagenSAVE;
    private javax.swing.JLabel NombreVentanaProveedores;
    private javax.swing.JLabel Nuevo;
    private javax.swing.JLabel Nuevo1;
    private javax.swing.JPanel PanelBuscar;
    private javax.swing.JPanel PanelEditar;
    private javax.swing.JLabel Precio;
    private javax.swing.JLabel Proveedor;
    private javax.swing.JLabel Repuesto;
    private javax.swing.JLabel TituloFuncion1;
    private javax.swing.JLabel TituloFuncion2;
    private javax.swing.JPanel btnAgregarItem;
    private javax.swing.JPanel btnAgregarProveedor;
    private javax.swing.JPanel btnGuardarCompra;
    private javax.swing.JLabel btnRegresar;
    private javax.swing.JComboBox<Object> cbxProveedor;
    private javax.swing.JComboBox<Object> cbxRepuesto;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDetalleCompra;
    private javax.swing.JTextField txtCantidadCompra;
    private com.toedter.calendar.JDateChooser txtFechaCompra;
    private javax.swing.JTextField txtIdCompra;
    private javax.swing.JTextField txtPrecioUnitarioCompra;
    private javax.swing.JTextField txtTotalCompra;
    // End of variables declaration//GEN-END:variables
}
