/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.proyecto_m2b.Vista;

import com.mycompany.proyecto_m2b.Controlador.Validaciones;
import com.mycompany.proyecto_m2b.Controlador.VehiculosDAO;
import com.mycompany.proyecto_m2b.modelo.Marca;
import com.mycompany.proyecto_m2b.modelo.Modelo;
import com.mycompany.proyecto_m2b.modelo.Propietario;
import com.mycompany.proyecto_m2b.modelo.Vehiculos;
import java.awt.Color;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class PanelVehiculos extends javax.swing.JPanel {

    /**
     * Creates new form PanelVehiculos
     */
    public PanelVehiculos() {
        initComponents();
        cargarComboMarcas();
        cargarComboPropietarios();
        cargarComboTransmision();
    txtPlaca.setText("Ingrese la placa del vehiculo");
    txtPlaca.setForeground(java.awt.Color.GRAY);

    txtColor.setText("Ingrese el color del vehiculo");
    txtColor.setForeground(java.awt.Color.GRAY);
    
    txtKilometraje.setText("Ingrese el kilometraje del vehiculo");
    txtKilometraje.setForeground(java.awt.Color.GRAY);

    txtChasis.setText("Ingrese el N° de chasis del vehiculo");
    txtChasis.setForeground(java.awt.Color.GRAY);
    
    txtMotor.setText("Ingrese el N° de motor del vehiculo");
    txtMotor.setForeground(java.awt.Color.GRAY);

    txtCilindraje.setText("Ingrese el cilindraje del vehiculo");
    txtCilindraje.setForeground(java.awt.Color.GRAY);

    txtPuertas.setText("Ingrese el N° de puertas del vehiculo");
    txtPuertas.setForeground(java.awt.Color.GRAY);    
 
    }
    
    public void cargarComboMarcas() {
        comboMarcas.removeAllItems();
    comboMarcas.addItem("Seleccione una marca"); 
    
    VehiculosDAO dao = new VehiculosDAO();
    List<Marca> lista = dao.listarMarcas();

    for (Marca m : lista) {
        comboMarcas.addItem(m.getNom_mar());
    }
    comboMarcas.revalidate();
    comboMarcas.repaint();
    }
    public void cargarComboModelos(String idMarca) {
    comboModelos.removeAllItems();
    comboModelos.addItem("Seleccione un modelo");

    if (idMarca != null) {
        VehiculosDAO dao = new VehiculosDAO();
        List<Modelo> lista = dao.listarModelosPorMarca(idMarca);

        for (Modelo mod : lista) {
            comboModelos.addItem(mod.getNom_mode()); 
        }
    }
    
    comboModelos.revalidate();
    comboModelos.repaint();
    }
    public void cargarComboPropietarios() {
    comboPropietarios.removeAllItems();
    comboPropietarios.addItem("Seleccione un propietario");

        VehiculosDAO dao = new VehiculosDAO();
        List<Propietario> lista = dao.listarPropietarios();

        for (Propietario p : lista) {
            comboPropietarios.addItem(p.getNombreCompleto()); 
        }
    comboPropietarios.revalidate();
    comboPropietarios.repaint();
    }
    public void cargarComboTransmision() {
    comboTransmision.removeAllItems();
    comboTransmision.addItem("Seleccione un tipo");
    comboTransmision.addItem("Manual");
    comboTransmision.addItem("Automática");
    comboTransmision.addItem("CVT");
    comboTransmision.addItem("Secuencial");
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Fondo = new javax.swing.JPanel();
        BarraArriba = new javax.swing.JPanel();
        NombreVentanaVehiculos = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        BarraAbajo = new javax.swing.JPanel();
        TituloFuncion1 = new javax.swing.JLabel();
        Placa = new javax.swing.JLabel();
        Marca = new javax.swing.JLabel();
        Color = new javax.swing.JLabel();
        Kilometraje = new javax.swing.JLabel();
        Modelo = new javax.swing.JLabel();
        Propietario = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        comboMarcas = new javax.swing.JComboBox<>();
        comboModelos = new javax.swing.JComboBox<>();
        comboPropietarios = new javax.swing.JComboBox<>();
        txtPlaca = new javax.swing.JTextField();
        txtColor = new javax.swing.JTextField();
        txtKilometraje = new javax.swing.JTextField();
        TituloFuncion2 = new javax.swing.JLabel();
        Ano = new javax.swing.JLabel();
        Chasis = new javax.swing.JLabel();
        Transmicion = new javax.swing.JLabel();
        Motor = new javax.swing.JLabel();
        Cilindraje = new javax.swing.JLabel();
        Puertas = new javax.swing.JLabel();
        comboTransmision = new javax.swing.JComboBox<>();
        txtChasis = new javax.swing.JTextField();
        txtMotor = new javax.swing.JTextField();
        txtCilindraje = new javax.swing.JTextField();
        txtPuertas = new javax.swing.JTextField();
        PanelGuardar = new javax.swing.JPanel();
        Guardar = new javax.swing.JLabel();
        ImagenSAVE = new javax.swing.JLabel();
        PanelEditar = new javax.swing.JPanel();
        Editar = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        PanelBuscar = new javax.swing.JPanel();
        Buscar = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        PanelNuevo = new javax.swing.JPanel();
        Nuevo = new javax.swing.JLabel();
        ImagenADD = new javax.swing.JLabel();
        jYearChooser1 = new com.toedter.calendar.JYearChooser();
        PanelAgregar = new javax.swing.JPanel();
        Buscar1 = new javax.swing.JLabel();
        ImagenADD3 = new javax.swing.JLabel();

        Fondo.setBackground(new java.awt.Color(255, 255, 255));
        Fondo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BarraArriba.setBackground(new java.awt.Color(0, 0, 0));

        NombreVentanaVehiculos.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        NombreVentanaVehiculos.setForeground(new java.awt.Color(255, 255, 255));
        NombreVentanaVehiculos.setText("REGISTRO DE VEHÍCULOS ");

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Regresar");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout BarraArribaLayout = new javax.swing.GroupLayout(BarraArriba);
        BarraArriba.setLayout(BarraArribaLayout);
        BarraArribaLayout.setHorizontalGroup(
            BarraArribaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BarraArribaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(NombreVentanaVehiculos, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 858, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(19, 19, 19))
        );
        BarraArribaLayout.setVerticalGroup(
            BarraArribaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BarraArribaLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(BarraArribaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(NombreVentanaVehiculos))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        Fondo.add(BarraArriba, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1320, 60));

        BarraAbajo.setBackground(new java.awt.Color(227, 153, 106));

        javax.swing.GroupLayout BarraAbajoLayout = new javax.swing.GroupLayout(BarraAbajo);
        BarraAbajo.setLayout(BarraAbajoLayout);
        BarraAbajoLayout.setHorizontalGroup(
            BarraAbajoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1320, Short.MAX_VALUE)
        );
        BarraAbajoLayout.setVerticalGroup(
            BarraAbajoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        Fondo.add(BarraAbajo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 630, 1320, 70));

        TituloFuncion1.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        TituloFuncion1.setForeground(new java.awt.Color(153, 153, 153));
        TituloFuncion1.setText("DATOS PRINCIPALES Y PROPIETARIO");
        Fondo.add(TituloFuncion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        Placa.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 13)); // NOI18N
        Placa.setForeground(new java.awt.Color(153, 153, 153));
        Placa.setText("Placa:");
        Fondo.add(Placa, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        Marca.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 13)); // NOI18N
        Marca.setForeground(new java.awt.Color(153, 153, 153));
        Marca.setText("Marca:");
        Fondo.add(Marca, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        Color.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 13)); // NOI18N
        Color.setForeground(new java.awt.Color(153, 153, 153));
        Color.setText("Color:");
        Fondo.add(Color, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, -1));

        Kilometraje.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 13)); // NOI18N
        Kilometraje.setForeground(new java.awt.Color(153, 153, 153));
        Kilometraje.setText("Kilometraje:");
        Fondo.add(Kilometraje, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, -1, -1));

        Modelo.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 13)); // NOI18N
        Modelo.setForeground(new java.awt.Color(153, 153, 153));
        Modelo.setText("Modelo:");
        Fondo.add(Modelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, -1, -1));

        Propietario.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 13)); // NOI18N
        Propietario.setForeground(new java.awt.Color(153, 153, 153));
        Propietario.setText("Propietario:");
        Fondo.add(Propietario, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 120, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/images (2).jpg"))); // NOI18N
        Fondo.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 70, -1, -1));

        comboMarcas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una marca", "Item 2", "Item 3", "Item 4" }));
        comboMarcas.addActionListener(this::comboMarcasActionPerformed);
        Fondo.add(comboMarcas, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 210, -1));

        comboModelos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione un modelo", "Item 2", "Item 3", "Item 4" }));
        comboModelos.addActionListener(this::comboModelosActionPerformed);
        Fondo.add(comboModelos, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 200, 240, -1));

        comboPropietarios.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione al propietario", "Item 2", "Item 3", "Item 4" }));
        comboPropietarios.addActionListener(this::comboPropietariosActionPerformed);
        Fondo.add(comboPropietarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 140, 240, -1));

        txtPlaca.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPlacaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPlacaFocusLost(evt);
            }
        });
        txtPlaca.addActionListener(this::txtPlacaActionPerformed);
        Fondo.add(txtPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 210, -1));

        txtColor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtColorFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtColorFocusLost(evt);
            }
        });
        Fondo.add(txtColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 210, -1));

        txtKilometraje.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtKilometrajeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtKilometrajeFocusLost(evt);
            }
        });
        Fondo.add(txtKilometraje, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 260, 240, -1));

        TituloFuncion2.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        TituloFuncion2.setForeground(new java.awt.Color(153, 153, 153));
        TituloFuncion2.setText("ESPECIFICACIONES TÉCNICAS");
        Fondo.add(TituloFuncion2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, -1, -1));

        Ano.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 13)); // NOI18N
        Ano.setForeground(new java.awt.Color(153, 153, 153));
        Ano.setText("Año:");
        Fondo.add(Ano, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, -1, -1));

        Chasis.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 13)); // NOI18N
        Chasis.setForeground(new java.awt.Color(153, 153, 153));
        Chasis.setText("N° Chasis:");
        Fondo.add(Chasis, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 460, -1, -1));

        Transmicion.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 13)); // NOI18N
        Transmicion.setForeground(new java.awt.Color(153, 153, 153));
        Transmicion.setText("Transmisión:");
        Fondo.add(Transmicion, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 400, -1, -1));

        Motor.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 13)); // NOI18N
        Motor.setForeground(new java.awt.Color(153, 153, 153));
        Motor.setText("N° Motor:");
        Fondo.add(Motor, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 460, -1, -1));

        Cilindraje.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 13)); // NOI18N
        Cilindraje.setForeground(new java.awt.Color(153, 153, 153));
        Cilindraje.setText("Cilindraje:");
        Fondo.add(Cilindraje, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 400, -1, -1));

        Puertas.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 13)); // NOI18N
        Puertas.setForeground(new java.awt.Color(153, 153, 153));
        Puertas.setText("N° Puertas:");
        Fondo.add(Puertas, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 460, -1, -1));

        comboTransmision.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione un tipo de transmision", "Item 2", "Item 3", "Item 4" }));
        Fondo.add(comboTransmision, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 420, 290, -1));

        txtChasis.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtChasisFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtChasisFocusLost(evt);
            }
        });
        Fondo.add(txtChasis, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 480, 270, -1));

        txtMotor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtMotorFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtMotorFocusLost(evt);
            }
        });
        Fondo.add(txtMotor, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 480, 290, -1));

        txtCilindraje.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCilindrajeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCilindrajeFocusLost(evt);
            }
        });
        Fondo.add(txtCilindraje, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 420, 270, -1));

        txtPuertas.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPuertasFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPuertasFocusLost(evt);
            }
        });
        Fondo.add(txtPuertas, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 480, 270, -1));

        PanelGuardar.setBackground(new java.awt.Color(242, 101, 34));
        PanelGuardar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(187, 187, 187)));
        PanelGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PanelGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PanelGuardarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PanelGuardarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PanelGuardarMouseExited(evt);
            }
        });

        Guardar.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        Guardar.setForeground(new java.awt.Color(255, 255, 255));
        Guardar.setText("Guardar");

        ImagenSAVE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/save_22dp_FFFFFF_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N

        javax.swing.GroupLayout PanelGuardarLayout = new javax.swing.GroupLayout(PanelGuardar);
        PanelGuardar.setLayout(PanelGuardarLayout);
        PanelGuardarLayout.setHorizontalGroup(
            PanelGuardarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelGuardarLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(ImagenSAVE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Guardar)
                .addContainerGap(36, Short.MAX_VALUE))
        );
        PanelGuardarLayout.setVerticalGroup(
            PanelGuardarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelGuardarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanelGuardarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Guardar)
                    .addComponent(ImagenSAVE))
                .addContainerGap())
        );

        Fondo.add(PanelGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 550, -1, -1));

        PanelEditar.setBackground(new java.awt.Color(255, 255, 255));
        PanelEditar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(187, 187, 187)));
        PanelEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PanelEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PanelEditarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PanelEditarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PanelEditarMouseExited(evt);
            }
        });

        Editar.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        Editar.setText("Editar");

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/edit_22dp_000000_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N

        javax.swing.GroupLayout PanelEditarLayout = new javax.swing.GroupLayout(PanelEditar);
        PanelEditar.setLayout(PanelEditarLayout);
        PanelEditarLayout.setHorizontalGroup(
            PanelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelEditarLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Editar)
                .addContainerGap(33, Short.MAX_VALUE))
        );
        PanelEditarLayout.setVerticalGroup(
            PanelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelEditarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Editar)
                    .addComponent(jLabel2))
                .addContainerGap())
        );

        Fondo.add(PanelEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 550, -1, -1));

        PanelBuscar.setBackground(new java.awt.Color(255, 255, 255));
        PanelBuscar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(187, 187, 187)));
        PanelBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PanelBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PanelBuscarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PanelBuscarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PanelBuscarMouseExited(evt);
            }
        });

        Buscar.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        Buscar.setText("Buscar");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/person_search_22dp_000000_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N

        javax.swing.GroupLayout PanelBuscarLayout = new javax.swing.GroupLayout(PanelBuscar);
        PanelBuscar.setLayout(PanelBuscarLayout);
        PanelBuscarLayout.setHorizontalGroup(
            PanelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelBuscarLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Buscar)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        PanelBuscarLayout.setVerticalGroup(
            PanelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBuscarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Buscar)
                    .addComponent(jLabel3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Fondo.add(PanelBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 550, -1, -1));

        PanelNuevo.setBackground(new java.awt.Color(255, 255, 255));
        PanelNuevo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(187, 187, 187)));
        PanelNuevo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PanelNuevo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PanelNuevoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PanelNuevoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PanelNuevoMouseExited(evt);
            }
        });

        Nuevo.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        Nuevo.setText("Añadir marca/modelo/tipo");
        Nuevo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NuevoMouseClicked(evt);
            }
        });

        ImagenADD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/add_22dp_000000_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N

        javax.swing.GroupLayout PanelNuevoLayout = new javax.swing.GroupLayout(PanelNuevo);
        PanelNuevo.setLayout(PanelNuevoLayout);
        PanelNuevoLayout.setHorizontalGroup(
            PanelNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelNuevoLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(ImagenADD)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Nuevo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelNuevoLayout.setVerticalGroup(
            PanelNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelNuevoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ImagenADD)
                    .addComponent(Nuevo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Fondo.add(PanelNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, -1, -1));

        jYearChooser1.setMaximum(2027);
        jYearChooser1.setMinimum(1900);
        Fondo.add(jYearChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, 110, -1));

        PanelAgregar.setBackground(new java.awt.Color(255, 255, 255));
        PanelAgregar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(187, 187, 187)));
        PanelAgregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PanelAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PanelAgregarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PanelAgregarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PanelAgregarMouseExited(evt);
            }
        });

        Buscar1.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        Buscar1.setText("Nuevo");

        ImagenADD3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/add_22dp_000000_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N

        javax.swing.GroupLayout PanelAgregarLayout = new javax.swing.GroupLayout(PanelAgregar);
        PanelAgregar.setLayout(PanelAgregarLayout);
        PanelAgregarLayout.setHorizontalGroup(
            PanelAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelAgregarLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(ImagenADD3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Buscar1)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        PanelAgregarLayout.setVerticalGroup(
            PanelAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAgregarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ImagenADD3)
                    .addComponent(Buscar1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Fondo.add(PanelAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 550, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
  
    }//GEN-LAST:event_jLabel1MouseClicked

    private void comboMarcasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboMarcasActionPerformed
        // TODO add your handling code here:
        if (comboMarcas.getSelectedIndex() > 0) {
        String nombreMarcaSeleccionada = comboMarcas.getSelectedItem().toString();
        
        VehiculosDAO dao = new VehiculosDAO();
        String idMarca = dao.obtenerIdMarcaPorNombre(nombreMarcaSeleccionada);
        if (idMarca != null) {
            cargarComboModelos(idMarca);
        } else {
            comboModelos.removeAllItems();
            comboModelos.addItem("Seleccione un modelo");
        }
    } else {
        comboModelos.removeAllItems();
        comboModelos.addItem("Seleccione un modelo");
    }
    }//GEN-LAST:event_comboMarcasActionPerformed

    private void txtPlacaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPlacaFocusGained
        if (txtPlaca.getText().equals("Ingrese la placa del vehiculo")) {
            txtPlaca.setText("");
            txtPlaca.setForeground(java.awt.Color.BLACK);
        }
    }//GEN-LAST:event_txtPlacaFocusGained

    private void txtPlacaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPlacaFocusLost
        if (txtPlaca.getText().trim().isEmpty()) {
            txtPlaca.setText("Ingrese la placa del vehiculo");
            txtPlaca.setForeground(java.awt.Color.GRAY);
        }
    }//GEN-LAST:event_txtPlacaFocusLost

    private void txtPlacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPlacaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPlacaActionPerformed

    private void txtColorFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtColorFocusGained
        if (txtColor.getText().equals("Ingrese el color del vehiculo")) {
            txtColor.setText("");
            txtColor.setForeground(java.awt.Color.BLACK);
        }
    }//GEN-LAST:event_txtColorFocusGained

    private void txtColorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtColorFocusLost
        if (txtColor.getText().trim().isEmpty()) {
            txtColor.setText("Ingrese el color del vehiculo");
            txtColor.setForeground(java.awt.Color.GRAY);
        }
    }//GEN-LAST:event_txtColorFocusLost

    private void txtKilometrajeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtKilometrajeFocusGained
        if (txtKilometraje.getText().equals("Ingrese el kilometraje del vehiculo")) {
            txtKilometraje.setText("");
            txtKilometraje.setForeground(java.awt.Color.BLACK);
        }
    }//GEN-LAST:event_txtKilometrajeFocusGained

    private void txtKilometrajeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtKilometrajeFocusLost
        if (txtKilometraje.getText().trim().isEmpty()) {
            txtKilometraje.setText("Ingrese el kilometraje del vehiculo");
            txtKilometraje.setForeground(java.awt.Color.GRAY);
        }
    }//GEN-LAST:event_txtKilometrajeFocusLost

    private void txtChasisFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtChasisFocusGained
        if (txtChasis.getText().equals("Ingrese el N° de chasis del vehiculo")) {
            txtChasis.setText("");
            txtChasis.setForeground(java.awt.Color.BLACK);
        }
    }//GEN-LAST:event_txtChasisFocusGained

    private void txtChasisFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtChasisFocusLost
        if (txtChasis.getText().trim().isEmpty()) {
            txtChasis.setText("Ingrese el N° de chasis del vehiculo");
            txtChasis.setForeground(java.awt.Color.GRAY);
        }
    }//GEN-LAST:event_txtChasisFocusLost

    private void txtMotorFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMotorFocusGained
        if (txtMotor.getText().equals("Ingrese el N° de motor del vehiculo")) {
            txtMotor.setText("");
            txtMotor.setForeground(java.awt.Color.BLACK);
        }
    }//GEN-LAST:event_txtMotorFocusGained

    private void txtMotorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMotorFocusLost
        if (txtMotor.getText().trim().isEmpty()) {
            txtMotor.setText("Ingrese el N° de motor del vehiculo");
            txtMotor.setForeground(java.awt.Color.GRAY);
        }
    }//GEN-LAST:event_txtMotorFocusLost

    private void txtCilindrajeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCilindrajeFocusGained
        if (txtCilindraje.getText().equals("Ingrese el cilindraje del vehiculo")) {
            txtCilindraje.setText("");
            txtCilindraje.setForeground(java.awt.Color.BLACK);
        }
    }//GEN-LAST:event_txtCilindrajeFocusGained

    private void txtCilindrajeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCilindrajeFocusLost
        if (txtCilindraje.getText().trim().isEmpty()) {
            txtCilindraje.setText("Ingrese el cilindraje del vehiculo");
            txtCilindraje.setForeground(java.awt.Color.GRAY);
        }
    }//GEN-LAST:event_txtCilindrajeFocusLost

    private void txtPuertasFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPuertasFocusGained
        if (txtPuertas.getText().equals("Ingrese el N° de puertas del vehiculo")) {
            txtPuertas.setText("");
            txtPuertas.setForeground(java.awt.Color.BLACK);
        }
    }//GEN-LAST:event_txtPuertasFocusGained

    private void txtPuertasFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPuertasFocusLost
        if (txtPuertas.getText().trim().isEmpty()) {
            txtPuertas.setText("Ingrese el N° de puertas del vehiculo");
            txtPuertas.setForeground(java.awt.Color.GRAY);
        }
    }//GEN-LAST:event_txtPuertasFocusLost

    private void PanelGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelGuardarMouseClicked
        // TODO add your handling code here:
        GuardarVehiculos();
    }//GEN-LAST:event_PanelGuardarMouseClicked

    private void PanelGuardarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelGuardarMouseEntered
        // TODO add your handling code here:
        PanelGuardar.setBackground(new java.awt.Color(227, 95, 32));
        Guardar.setForeground(new java.awt.Color(217, 217, 192));
    }//GEN-LAST:event_PanelGuardarMouseEntered

    private void PanelGuardarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelGuardarMouseExited
        // TODO add your handling code here:
        PanelGuardar.setBackground(new java.awt.Color(242,101,34));
        Guardar.setForeground(java.awt.Color.white);
    }//GEN-LAST:event_PanelGuardarMouseExited

    private void PanelEditarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelEditarMouseEntered
        // TODO add your handling code here:
        PanelEditar.setBackground(new java.awt.Color(219,219,219));
        Editar.setForeground(new java.awt.Color(66, 66, 66));
    }//GEN-LAST:event_PanelEditarMouseEntered

    private void PanelEditarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelEditarMouseExited
        // TODO add your handling code here:
        PanelEditar.setBackground(java.awt.Color.white);
        Editar.setForeground(java.awt.Color.black);
    }//GEN-LAST:event_PanelEditarMouseExited

    private void PanelBuscarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelBuscarMouseEntered
        // TODO add your handling code here:
        PanelBuscar.setBackground(new java.awt.Color(219,219,219));
        Buscar.setForeground(new java.awt.Color(66, 66, 66));
    }//GEN-LAST:event_PanelBuscarMouseEntered

    private void PanelBuscarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelBuscarMouseExited
        // TODO add your handling code here:
        PanelBuscar.setBackground(java.awt.Color.white);
        Buscar.setForeground(java.awt.Color.black);
    }//GEN-LAST:event_PanelBuscarMouseExited

    private void PanelNuevoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelNuevoMouseClicked
        // TODO add your handling code here:
        CrearNuevaMarcaModelo ventanaCrear = new CrearNuevaMarcaModelo();
        ventanaCrear.addWindowListener(new java.awt.event.WindowAdapter() {
        @Override
        public void windowClosed(java.awt.event.WindowEvent e) {
            cargarComboMarcas();
        }
    });
    ventanaCrear.setVisible(true);
    }//GEN-LAST:event_PanelNuevoMouseClicked

    private void PanelNuevoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelNuevoMouseEntered
        // TODO add your handling code here:
        PanelNuevo.setBackground(new Color(219,219,219));
        Nuevo.setForeground(new Color(66, 66, 66));
    }//GEN-LAST:event_PanelNuevoMouseEntered

    private void PanelNuevoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelNuevoMouseExited
        // TODO add your handling code here:
        PanelNuevo.setBackground(java.awt.Color.white);
        Nuevo.setForeground(java.awt.Color.black);
    }//GEN-LAST:event_PanelNuevoMouseExited

    private void NuevoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NuevoMouseClicked
        // TODO add your handling code here:
        CrearNuevaMarcaModelo marcanueva=new CrearNuevaMarcaModelo();
        marcanueva.setVisible(true);
    }//GEN-LAST:event_NuevoMouseClicked

    private void comboModelosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboModelosActionPerformed
        // TODO add your handling code here:
        if (comboModelos.getSelectedIndex() > 0) {
        String modeloSeleccionado = comboModelos.getSelectedItem().toString();
        }
    }//GEN-LAST:event_comboModelosActionPerformed

    private void comboPropietariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboPropietariosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboPropietariosActionPerformed

    private void PanelEditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelEditarMouseClicked
        // TODO add your handling code here:
        if (txtPlaca.isEditable()) {
        JOptionPane.showMessageDialog(this, 
            "Primero debe buscar un vehículo existente usando su placa antes de poder editarlo.", 
            "Atención", 
            JOptionPane.WARNING_MESSAGE);
        return;
    }

    try {
        Vehiculos v = new Vehiculos();
        
        v.setPlaca_carro(txtPlaca.getText().trim().toUpperCase());
        v.setColor_vehi(txtColor.getText().trim().toUpperCase());
        v.setCilindraje_vehi(txtCilindraje.getText().trim().toUpperCase());
        v.setNum_chasis_vehi(txtChasis.getText().trim().toUpperCase());
        v.setNum_motor_vehi(txtMotor.getText().trim().toUpperCase());
        
        v.setNum_puertas_vehi(Integer.parseInt(txtPuertas.getText().trim()));
        v.setKilometraje_vehi(Integer.parseInt(txtKilometraje.getText().trim()));
        
        int anio = jYearChooser1.getYear();
        java.util.Calendar cal = java.util.Calendar.getInstance();
        cal.set(anio, java.util.Calendar.JANUARY, 1);
        v.setAnio_sal_vehi(new java.sql.Date(cal.getTimeInMillis()));
        
        if (comboTransmision.getSelectedItem() != null) {
            v.setTransmision_vehi(comboTransmision.getSelectedItem().toString());
        }

        v.setID_mode_vehi(obtenerIdModeloSeleccionado());
        v.setID_propietario_vehi(obtenerIdPropietarioSeleccionado());

        VehiculosDAO dao = new VehiculosDAO();
        boolean actualizado = dao.actualizarVehiculo(v);

        if (actualizado) {
            JOptionPane.showMessageDialog(this, 
                "Los datos del vehículo han sido actualizados con éxito.", 
                "Éxito", 
                JOptionPane.INFORMATION_MESSAGE);
                LimpiarDatos(); 
        } else {
            JOptionPane.showMessageDialog(this, 
                "No se pudo actualizar el vehículo. Intente nuevamente.", 
                "Error", 
                JOptionPane.ERROR_MESSAGE);
        }

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, 
            "Por favor revise los campos numéricos (Puertas y Kilometraje). Deben ser números válidos.", 
            "Error de Formato", 
            JOptionPane.ERROR_MESSAGE);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, 
            "Ocurrió un error al intentar actualizar: " + e.getMessage(), 
            "Error del Sistema", 
            JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_PanelEditarMouseClicked
private void seleccionarPropietarioPorId(String idPropietario) {
    if (idPropietario == null) return;
    
    VehiculosDAO dao = new VehiculosDAO();
    String nombreBD = dao.obtenerNombrePropietario(idPropietario.trim());

    if (nombreBD != null) {
        for (int i = 0; i < comboPropietarios.getItemCount(); i++) {
            Object item = comboPropietarios.getItemAt(i);
            if (item != null && item.toString().trim().equalsIgnoreCase(nombreBD.trim())) {
                comboPropietarios.setSelectedIndex(i);
                break;
            }
        }
    }
}

private void seleccionarModeloPorId(String idModelo) {
    if (idModelo == null || idModelo.trim().isEmpty()) return;
    
    VehiculosDAO dao = new VehiculosDAO();
    String nombreMarcaBD = dao.obtenerNombreMarcaPorModelo(idModelo.trim());
    String nombreModeloBD = dao.obtenerNombreModelo(idModelo.trim());
    if (nombreMarcaBD != null) {
        for (int i = 0; i < comboMarcas.getItemCount(); i++) {
            Object item = comboMarcas.getItemAt(i);
            if (item != null && item.toString().trim().equalsIgnoreCase(nombreMarcaBD.trim())) {
                comboMarcas.setSelectedIndex(i); 
                break;
            }
        }
    }
    if (nombreModeloBD != null) {
        for (int i = 0; i < comboModelos.getItemCount(); i++) {
            Object item = comboModelos.getItemAt(i);
            if (item != null && item.toString().trim().equalsIgnoreCase(nombreModeloBD.trim())) {
                comboModelos.setSelectedIndex(i);
                break;
            }
        }
    }
}
private String obtenerIdModeloSeleccionado() {
    if (comboModelos.getSelectedItem() == null) return null;
    VehiculosDAO dao = new VehiculosDAO();
    return dao.obtenerIdModeloPorNombre(comboModelos.getSelectedItem().toString().trim());
}

private String obtenerIdPropietarioSeleccionado() {
    if (comboPropietarios.getSelectedItem() == null) return null;
    VehiculosDAO dao = new VehiculosDAO();
    return dao.obtenerIdPropietarioPorNombre(comboPropietarios.getSelectedItem().toString().trim());
}
    private void PanelBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelBuscarMouseClicked
        // TODO add your handling code here:
        String placaBuscar = txtPlaca.getText().trim();
    if (placaBuscar.isEmpty()) {
        JOptionPane.showMessageDialog(this, 
            "Por favor, ingrese el número de placa para realizar la búsqueda.", 
            "Atención", 
            JOptionPane.WARNING_MESSAGE);
        txtPlaca.requestFocus();
        return;
    }

    try {
        VehiculosDAO controlador = new VehiculosDAO(); 
        Vehiculos v = controlador.buscarPorPlaca(placaBuscar);
        if (v != null) {
            txtColor.setText(v.getColor_vehi());
            txtCilindraje.setText(v.getCilindraje_vehi());
            txtChasis.setText(v.getNum_chasis_vehi());
            txtMotor.setText(v.getNum_motor_vehi());
            txtPuertas.setText(String.valueOf(v.getNum_puertas_vehi()));
            txtKilometraje.setText(String.valueOf(v.getKilometraje_vehi()));
            if (v.getAnio_sal_vehi() != null) {
                java.util.Calendar cal = java.util.Calendar.getInstance();
                cal.setTime(v.getAnio_sal_vehi());
                jYearChooser1.setYear(cal.get(java.util.Calendar.YEAR));
            }
            if (v.getTransmision_vehi() != null) {
                comboTransmision.setSelectedItem(v.getTransmision_vehi());
            }

            seleccionarModeloPorId(v.getID_mode_vehi());
            seleccionarPropietarioPorId(v.getID_propietario_vehi());
            txtPlaca.setEditable(false);

            JOptionPane.showMessageDialog(this, 
                "Vehículo encontrado exitosamente.", 
                "Éxito", 
                JOptionPane.INFORMATION_MESSAGE);

        } else {
            JOptionPane.showMessageDialog(this, 
                "No se encontró ningún vehículo registrado con la placa: " + placaBuscar, 
                "Sin Resultados", 
                JOptionPane.ERROR_MESSAGE);
            txtPlaca.requestFocus();
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, 
            "Ocurrió un error al consultar la base de datos: " + e.getMessage(), 
            "Error del Sistema", 
            JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_PanelBuscarMouseClicked

    private void PanelAgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelAgregarMouseClicked
    LimpiarDatos();
    txtPlaca.setEditable(true);
    if (comboMarcas.getItemCount() > 0) comboMarcas.setSelectedIndex(0);
    if (comboModelos.getItemCount() > 0) comboModelos.setSelectedIndex(0);
    if (comboPropietarios.getItemCount() > 0) comboPropietarios.setSelectedIndex(0);
    if (comboTransmision.getItemCount() > 0) comboTransmision.setSelectedIndex(0);

    java.util.Calendar cal = java.util.Calendar.getInstance();
    jYearChooser1.setYear(cal.get(java.util.Calendar.YEAR));

    txtPlaca.requestFocus();
    }//GEN-LAST:event_PanelAgregarMouseClicked

    private void PanelAgregarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelAgregarMouseEntered
        // TODO add your handling code here:
        PanelAgregar.setBackground(new java.awt.Color(219,219,219));
        Buscar.setForeground(new java.awt.Color(66, 66, 66));
    }//GEN-LAST:event_PanelAgregarMouseEntered

    private void PanelAgregarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelAgregarMouseExited
        // TODO add your handling code here:
        PanelAgregar.setBackground(java.awt.Color.white);
        Buscar.setForeground(java.awt.Color.black);
    }//GEN-LAST:event_PanelAgregarMouseExited
    
    public void LimpiarDatos (){
        txtPlaca.setText("");
        txtPlaca.setForeground(new Color(94, 94, 94));
        txtColor.setText("");
        txtColor.setForeground(new Color(94, 94, 94));
        txtKilometraje.setText("");
        txtKilometraje.setForeground(new Color(94, 94, 94));
        txtChasis.setText("");
        txtChasis.setForeground(new Color(94, 94, 94));
        txtMotor.setText("");
        txtMotor.setForeground(new Color(94, 94, 94));
        txtCilindraje.setText("");
        txtCilindraje.setForeground(new Color(94, 94, 94));
        txtPuertas.setText("");
        txtPuertas.setForeground(new Color(94, 94, 94));
        comboMarcas.setSelectedIndex(0);
        comboPropietarios.setSelectedIndex(0);
        comboModelos.setSelectedIndex(0);
        comboTransmision.setSelectedIndex(0);

    }
    private void GuardarVehiculos() {
    try {
        if (comboPropietarios.getSelectedIndex() <= 0 || comboPropietarios.getSelectedItem().toString().toLowerCase().contains("seleccione")) {
            JOptionPane.showMessageDialog(this, "Por favor, seleccione un propietario válido.", "Campo Requerido", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (comboMarcas.getSelectedIndex() <= 0 || comboMarcas.getSelectedItem().toString().toLowerCase().contains("seleccione")) {
            JOptionPane.showMessageDialog(this, "Por favor, seleccione una marca válida.", "Campo Requerido", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (comboModelos.getSelectedIndex() <= 0 || comboModelos.getSelectedItem().toString().toLowerCase().contains("seleccione")) {
            JOptionPane.showMessageDialog(this, "Por favor, seleccione un modelo válido.", "Campo Requerido", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (comboTransmision.getSelectedIndex() <= 0 || comboTransmision.getSelectedItem().toString().toLowerCase().contains("seleccione")) {
            JOptionPane.showMessageDialog(this, "Por favor, seleccione una transmisión válida.", "Campo Requerido", JOptionPane.WARNING_MESSAGE);
            return;
        }
        String placa = txtPlaca.getText().trim().toUpperCase();
        String color = txtColor.getText().trim();
        String cilindraje = txtCilindraje.getText().trim().toUpperCase();
        String chasis = txtChasis.getText().trim().toUpperCase();
        String motor = txtMotor.getText().trim().toUpperCase();
        String puertasStr = txtPuertas.getText().trim();
        String kmStr = txtKilometraje.getText().trim();
        
        if (Validaciones.esVacio(placa) || Validaciones.esVacio(color) || 
            Validaciones.esVacio(chasis) || Validaciones.esVacio(motor)) {
            JOptionPane.showMessageDialog(this, "Todos los campos de texto son obligatorios.", "Atención", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (!Validaciones.esPlacaValida(placa)) {
            JOptionPane.showMessageDialog(this, "La placa ingresada no es válida (Ejemplo: ABC-1234 o ABC-123).", "Error de Formato", JOptionPane.WARNING_MESSAGE);
            txtPlaca.requestFocus();
            return;
        }

        if (!Validaciones.esTextoSoloLetras(color)) {
            JOptionPane.showMessageDialog(this, "El color solo debe contener letras.", "Error de Formato", JOptionPane.WARNING_MESSAGE);
            txtColor.requestFocus();
            return;
        }

        if (!Validaciones.esAlfanumerico(chasis) || !Validaciones.esAlfanumerico(motor)) {
            JOptionPane.showMessageDialog(this, "El número de chasis y motor deben ser alfanuméricos sin caracteres especiales.", "Error de Formato", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (!Validaciones.esNumeroEnteroPositivo(puertasStr) || 
            !Validaciones.esNumeroEnteroPositivo(kmStr) || 
            !Validaciones.esNumeroEnteroPositivo(cilindraje)) {
            JOptionPane.showMessageDialog(this, "Cilindraje, puertas y kilometraje deben ser números enteros positivos.", "Error de Formato", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (!Validaciones.esNumeroPuertasValido(puertasStr)) {
            JOptionPane.showMessageDialog(this, "El número de puertas debe estar entre 2 y 5 (incluyendo la compuerta trasera).", "Error de Validación", 
            JOptionPane.WARNING_MESSAGE);
            txtPuertas.requestFocus();
            return;
        }
        Vehiculos vehiculo = new Vehiculos();
        VehiculosDAO dao = new VehiculosDAO();

        String idGenerado = dao.generarSiguienteIdVehiculo(); 
        vehiculo.setID_vehi(idGenerado);

        int anio = jYearChooser1.getYear(); 
        int anioActual = java.time.Year.now().getValue();
        if (anio < 1900 || anio > (anioActual + 1)) {
          JOptionPane.showMessageDialog(this, 
          "Por favor, seleccione un año válido (entre 1900 y " + (anioActual + 1) + ").", 
          "Año Inválido", 
          JOptionPane.WARNING_MESSAGE);
          return; 
        }
        java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("yyyy-MM-dd");
        java.util.Date fechaAnio = sdf.parse(anio + "-01-01");
        vehiculo.setAnio_sal_vehi(fechaAnio);
        vehiculo.setNum_chasis_vehi(chasis);
        vehiculo.setColor_vehi(color);
        vehiculo.setCilindraje_vehi(cilindraje);
        vehiculo.setTransmision_vehi(comboTransmision.getSelectedItem().toString().trim());
        vehiculo.setNum_motor_vehi(motor);
        vehiculo.setPlaca_carro(placa);
        vehiculo.setNum_puertas_vehi(Integer.parseInt(puertasStr));
        vehiculo.setKilometraje_vehi(Integer.parseInt(kmStr));
        String nombrePropietario = comboPropietarios.getSelectedItem().toString().trim();
        String nombreModelo = comboModelos.getSelectedItem().toString().trim();
        String idPropietario = dao.obtenerIdPropietarioPorNombre(nombrePropietario);
        String idModelo = dao.obtenerIdModeloPorNombre(nombreModelo);

        if (idPropietario == null || idModelo == null) {
            JOptionPane.showMessageDialog(this, "No se encontró la referencia en la base de datos para el propietario o modelo.", "Error de Asociación", JOptionPane.ERROR_MESSAGE);
            return;
        }

        vehiculo.setID_propietario_vehi(idPropietario);
        vehiculo.setID_mode_vehi(idModelo);
        dao.insertarVehiculos(vehiculo);
        JOptionPane.showMessageDialog(this, "¡Vehículo guardado exitosamente!", "Éxito", JOptionPane.INFORMATION_MESSAGE);
        LimpiarDatos();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error al guardar el vehículo: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Ano;
    private javax.swing.JPanel BarraAbajo;
    private javax.swing.JPanel BarraArriba;
    private javax.swing.JLabel Buscar;
    private javax.swing.JLabel Buscar1;
    private javax.swing.JLabel Chasis;
    private javax.swing.JLabel Cilindraje;
    private javax.swing.JLabel Color;
    private javax.swing.JLabel Editar;
    private javax.swing.JPanel Fondo;
    private javax.swing.JLabel Guardar;
    private javax.swing.JLabel ImagenADD;
    private javax.swing.JLabel ImagenADD3;
    private javax.swing.JLabel ImagenSAVE;
    private javax.swing.JLabel Kilometraje;
    private javax.swing.JLabel Marca;
    private javax.swing.JLabel Modelo;
    private javax.swing.JLabel Motor;
    private javax.swing.JLabel NombreVentanaVehiculos;
    private javax.swing.JLabel Nuevo;
    private javax.swing.JPanel PanelAgregar;
    private javax.swing.JPanel PanelBuscar;
    private javax.swing.JPanel PanelEditar;
    private javax.swing.JPanel PanelGuardar;
    private javax.swing.JPanel PanelNuevo;
    private javax.swing.JLabel Placa;
    private javax.swing.JLabel Propietario;
    private javax.swing.JLabel Puertas;
    private javax.swing.JLabel TituloFuncion1;
    private javax.swing.JLabel TituloFuncion2;
    private javax.swing.JLabel Transmicion;
    private javax.swing.JComboBox<String> comboMarcas;
    private javax.swing.JComboBox<String> comboModelos;
    private javax.swing.JComboBox<String> comboPropietarios;
    private javax.swing.JComboBox<String> comboTransmision;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private com.toedter.calendar.JYearChooser jYearChooser1;
    private javax.swing.JTextField txtChasis;
    private javax.swing.JTextField txtCilindraje;
    private javax.swing.JTextField txtColor;
    private javax.swing.JTextField txtKilometraje;
    private javax.swing.JTextField txtMotor;
    private javax.swing.JTextField txtPlaca;
    private javax.swing.JTextField txtPuertas;
    // End of variables declaration//GEN-END:variables
}