/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.proyecto_m2b.Vista;

import com.mycompany.proyecto_m2b.Controlador.OrdenServicioDAO;
import com.mycompany.proyecto_m2b.Controlador.Servidor_de_correos;
import com.mycompany.proyecto_m2b.Controlador.Validaciones;
import com.mycompany.proyecto_m2b.Controlador.VehiculosDAO;
import com.mycompany.proyecto_m2b.modelo.orden_de_servicio;
import com.toedter.calendar.JTextFieldDateEditor;
import java.awt.Color;
import java.time.LocalDate;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class PanelOrdenesServicio extends javax.swing.JPanel {

    /**
     * Creates new form PanelOrdenesServicio
     */
    private String idOrdenCargada = null;
    public PanelOrdenesServicio() {
        initComponents();
        cargarCombosIniciales();
        CalendarioFechaIngreso.setDate(new java.util.Date());
        CalendarioFechaIngreso.setEnabled(false);
        ((JTextFieldDateEditor) CalendarioFechaIngreso.getDateEditor()).setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        TXTcostoTotal = new javax.swing.JTextField();
        Descripcion = new javax.swing.JTextField();
        PanelNuevo = new javax.swing.JPanel();
        Nuevo = new javax.swing.JLabel();
        ImagenADD = new javax.swing.JLabel();
        PanelGuardar = new javax.swing.JPanel();
        Guardar = new javax.swing.JLabel();
        ImagenSAVE = new javax.swing.JLabel();
        PanelEditar = new javax.swing.JPanel();
        Editar = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        PanelBuscar = new javax.swing.JPanel();
        Buscar = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Estados = new javax.swing.JComboBox<>();
        CalendarioFechaIngreso = new com.toedter.calendar.JDateChooser();
        CalendarioFechaEntrega = new com.toedter.calendar.JDateChooser();
        comboPlacas = new javax.swing.JComboBox<>();
        comboCliente = new javax.swing.JComboBox<>();
        comboEmpleado = new javax.swing.JComboBox<>();

        jPanel1.setBackground(new java.awt.Color(238, 238, 238));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(153, 153, 153));
        jLabel21.setText("<- REGRESAR");
        jLabel21.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel21MouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("ORDENES DE SERVICIO");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 906, Short.MAX_VALUE)
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1320, 60));

        jLabel5.setText("Placa del vehiculo:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        jLabel6.setText("Cedula del cliente:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jLabel7.setText("Empleado asignado:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        jLabel8.setText("Estado de Orden:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        jLabel10.setText("Fecha de ingreso:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 70, -1, -1));

        jLabel11.setText("Costo Total:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 130, -1, 20));

        jLabel12.setText("Detalle/Trabajo a realizar:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

        TXTcostoTotal.setForeground(new java.awt.Color(153, 153, 153));
        TXTcostoTotal.setText("0.00");
        TXTcostoTotal.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TXTcostoTotalFocusGained(evt);
            }
        });
        TXTcostoTotal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TXTcostoTotalMousePressed(evt);
            }
        });
        TXTcostoTotal.addActionListener(this::TXTcostoTotalActionPerformed);
        TXTcostoTotal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TXTcostoTotalKeyPressed(evt);
            }
        });
        jPanel1.add(TXTcostoTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 130, 250, -1));

        Descripcion.setForeground(new java.awt.Color(153, 153, 153));
        Descripcion.setText("Describa el trabajo a realizar");
        Descripcion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                DescripcionFocusGained(evt);
            }
        });
        Descripcion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                DescripcionMousePressed(evt);
            }
        });
        Descripcion.addActionListener(this::DescripcionActionPerformed);
        Descripcion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                DescripcionKeyPressed(evt);
            }
        });
        jPanel1.add(Descripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 630, 70));

        PanelNuevo.setBackground(new java.awt.Color(255, 255, 255));
        PanelNuevo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(187, 187, 187)));
        PanelNuevo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PanelNuevo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PanelNuevoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PanelNuevoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PanelNuevoMouseExited(evt);
            }
        });

        Nuevo.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        Nuevo.setText("Nuevo");

        ImagenADD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/add_22dp_000000_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N

        javax.swing.GroupLayout PanelNuevoLayout = new javax.swing.GroupLayout(PanelNuevo);
        PanelNuevo.setLayout(PanelNuevoLayout);
        PanelNuevoLayout.setHorizontalGroup(
            PanelNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelNuevoLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(ImagenADD)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Nuevo)
                .addContainerGap(33, Short.MAX_VALUE))
        );
        PanelNuevoLayout.setVerticalGroup(
            PanelNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelNuevoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ImagenADD)
                    .addComponent(Nuevo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(PanelNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, -1, -1));

        PanelGuardar.setBackground(new java.awt.Color(242, 101, 34));
        PanelGuardar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(187, 187, 187)));
        PanelGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PanelGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PanelGuardarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PanelGuardarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PanelGuardarMouseExited(evt);
            }
        });

        Guardar.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        Guardar.setForeground(new java.awt.Color(255, 255, 255));
        Guardar.setText("Guardar");

        ImagenSAVE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/save_22dp_FFFFFF_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N

        javax.swing.GroupLayout PanelGuardarLayout = new javax.swing.GroupLayout(PanelGuardar);
        PanelGuardar.setLayout(PanelGuardarLayout);
        PanelGuardarLayout.setHorizontalGroup(
            PanelGuardarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelGuardarLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(ImagenSAVE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Guardar)
                .addContainerGap(36, Short.MAX_VALUE))
        );
        PanelGuardarLayout.setVerticalGroup(
            PanelGuardarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelGuardarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanelGuardarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Guardar)
                    .addComponent(ImagenSAVE))
                .addContainerGap())
        );

        jPanel1.add(PanelGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, -1, -1));

        PanelEditar.setBackground(new java.awt.Color(255, 255, 255));
        PanelEditar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(187, 187, 187)));
        PanelEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PanelEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PanelEditarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PanelEditarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PanelEditarMouseExited(evt);
            }
        });

        Editar.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        Editar.setText("Editar");

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/edit_22dp_000000_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N

        javax.swing.GroupLayout PanelEditarLayout = new javax.swing.GroupLayout(PanelEditar);
        PanelEditar.setLayout(PanelEditarLayout);
        PanelEditarLayout.setHorizontalGroup(
            PanelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelEditarLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Editar)
                .addContainerGap(33, Short.MAX_VALUE))
        );
        PanelEditarLayout.setVerticalGroup(
            PanelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelEditarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Editar)
                    .addComponent(jLabel2))
                .addContainerGap())
        );

        jPanel1.add(PanelEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 310, -1, -1));

        PanelBuscar.setBackground(new java.awt.Color(255, 255, 255));
        PanelBuscar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(187, 187, 187)));
        PanelBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PanelBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PanelBuscarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PanelBuscarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PanelBuscarMouseExited(evt);
            }
        });

        Buscar.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        Buscar.setText("Buscar");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/person_search_22dp_000000_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N

        javax.swing.GroupLayout PanelBuscarLayout = new javax.swing.GroupLayout(PanelBuscar);
        PanelBuscar.setLayout(PanelBuscarLayout);
        PanelBuscarLayout.setHorizontalGroup(
            PanelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelBuscarLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Buscar)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        PanelBuscarLayout.setVerticalGroup(
            PanelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBuscarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Buscar)
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(PanelBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 310, -1, -1));

        jLabel3.setText("Fecha de entrega:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 100, -1, -1));

        Estados.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione uno", "Ingresado", "En Proceso", "Terminado", "Entregado" }));
        jPanel1.add(Estados, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, -1, -1));
        jPanel1.add(CalendarioFechaIngreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 70, 250, -1));
        jPanel1.add(CalendarioFechaEntrega, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 100, 250, -1));

        comboPlacas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboPlacas.addActionListener(this::comboPlacasActionPerformed);
        jPanel1.add(comboPlacas, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 210, -1));

        comboCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(comboCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 210, -1));

        comboEmpleado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(comboEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 210, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 669, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jLabel21MouseClicked

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged

    }//GEN-LAST:event_jPanel2MouseDragged

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        // TODO add your handling code here:
   
    }//GEN-LAST:event_jPanel2MousePressed

    private void TXTcostoTotalFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TXTcostoTotalFocusGained
        // TODO add your handling code here:
        if (TXTcostoTotal.getText().equals("0.00")){
            TXTcostoTotal.setText("");
            TXTcostoTotal.setForeground(Color.BLACK);
        }
        if (Descripcion.getText().isEmpty()){
            Descripcion.setText("Describa el trabajo a realizar");
            Descripcion.setForeground(new Color(94, 94, 94));
        }
    }//GEN-LAST:event_TXTcostoTotalFocusGained

    private void TXTcostoTotalMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TXTcostoTotalMousePressed
        // TODO add your handling code here:
        if (TXTcostoTotal.getText().equals("0.00")){
            TXTcostoTotal.setText("");
            TXTcostoTotal.setForeground(Color.BLACK);
        }
        if (Descripcion.getText().isEmpty()){
            Descripcion.setText("Describa el trabajo a realizar");
            Descripcion.setForeground(new Color(94, 94, 94));
        }
    }//GEN-LAST:event_TXTcostoTotalMousePressed

    private void TXTcostoTotalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXTcostoTotalKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_TXTcostoTotalKeyPressed

    private void DescripcionFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_DescripcionFocusGained
        // TODO add your handling code here:
        if (Descripcion.getText().equals("Describa el trabajo a realizar")){
            Descripcion.setText("");
            Descripcion.setForeground(Color.BLACK);
        }
        if (TXTcostoTotal.getText().isEmpty()){
            TXTcostoTotal.setText("Costo Total");
            TXTcostoTotal.setForeground(new Color(94, 94, 94));
        }
    }//GEN-LAST:event_DescripcionFocusGained

    private void DescripcionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DescripcionMousePressed
        // TODO add your handling code here:
        if (Descripcion.getText().equals("Describa el trabajo a realizar")){
            Descripcion.setText("");
            Descripcion.setForeground(Color.BLACK);
        }
        if (TXTcostoTotal.getText().isEmpty()){
            TXTcostoTotal.setText("Costo Total");
            TXTcostoTotal.setForeground(new Color(94, 94, 94));
        }
    }//GEN-LAST:event_DescripcionMousePressed

    private void DescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DescripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DescripcionActionPerformed

    private void DescripcionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DescripcionKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_DescripcionKeyPressed

    private void PanelNuevoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelNuevoMouseClicked
        // TODO add your handling code here:
        LimpiarDatos();
        JOptionPane.showMessageDialog(this, "Datos limpiados correctamente"+"\n"
            +"Ingrese los datos");
    }//GEN-LAST:event_PanelNuevoMouseClicked

    private void PanelNuevoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelNuevoMouseEntered
        // TODO add your handling code here:
        PanelNuevo.setBackground(new Color(219,219,219));
        Nuevo.setForeground(new Color(66, 66, 66));
    }//GEN-LAST:event_PanelNuevoMouseEntered

    private void PanelNuevoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelNuevoMouseExited
        // TODO add your handling code here:
        PanelNuevo.setBackground(Color.white);
        Nuevo.setForeground(Color.black);
    }//GEN-LAST:event_PanelNuevoMouseExited

    private void PanelGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelGuardarMouseClicked
        // TODO add your handling code here:
        GuardarOrdenDeServicio();
    }//GEN-LAST:event_PanelGuardarMouseClicked

    private void PanelGuardarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelGuardarMouseEntered
        // TODO add your handling code here:
        PanelGuardar.setBackground(new Color(227, 95, 32));
        Guardar.setForeground(new Color(217, 217, 192));
    }//GEN-LAST:event_PanelGuardarMouseEntered

    private void PanelGuardarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelGuardarMouseExited
        // TODO add your handling code here:
        PanelGuardar.setBackground(new Color(242,101,34));
        Guardar.setForeground(Color.white);
    }//GEN-LAST:event_PanelGuardarMouseExited

    private void PanelEditarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelEditarMouseEntered
        // TODO add your handling code here:
        PanelEditar.setBackground(new Color(219,219,219));
        Editar.setForeground(new Color(66, 66, 66));
    }//GEN-LAST:event_PanelEditarMouseEntered

    private void PanelEditarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelEditarMouseExited
        // TODO add your handling code here:
        PanelEditar.setBackground(Color.white);
        Editar.setForeground(Color.black);
    }//GEN-LAST:event_PanelEditarMouseExited

    private void PanelBuscarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelBuscarMouseEntered
        // TODO add your handling code here:
        PanelBuscar.setBackground(new Color(219,219,219));
        Buscar.setForeground(new Color(66, 66, 66));
    }//GEN-LAST:event_PanelBuscarMouseEntered

    private void PanelBuscarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelBuscarMouseExited
        // TODO add your handling code here:
        PanelBuscar.setBackground(Color.white);
        Buscar.setForeground(Color.black);
    }//GEN-LAST:event_PanelBuscarMouseExited

    private void comboPlacasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboPlacasActionPerformed
        // TODO add your handling code here:
        if (comboPlacas.getSelectedIndex() > 0) { // Ignora el índice 0 ("Seleccione...")
        String placaSeleccionada = comboPlacas.getSelectedItem().toString();
        
        OrdenServicioDAO dao = new OrdenServicioDAO();
        String datosCliente = dao.obtenerCedulaPorPlaca(placaSeleccionada);

        if (datosCliente != null) {
            comboCliente.removeAllItems();
            comboCliente.addItem(datosCliente);
            comboCliente.setSelectedIndex(0);
        }
    } else {
        comboCliente.removeAllItems();
    }
    }//GEN-LAST:event_comboPlacasActionPerformed
public void cargarCombosIniciales() {
    OrdenServicioDAO dao = new OrdenServicioDAO();

    comboPlacas.removeAllItems();
    comboPlacas.addItem("Seleccione una placa");
    for (String placa : dao.obtenerPlacas()) {
        comboPlacas.addItem(placa);
    }
    comboEmpleado.removeAllItems();
    comboEmpleado.addItem("Seleccione un empleado");
    for (String emp : dao.obtenerEmpleadosConEspecialidad()) {
        comboEmpleado.addItem(emp);
    }
}
    private void TXTcostoTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTcostoTotalActionPerformed
        // TODO add your handling code here:
        OrdenServicioDAO dao=new OrdenServicioDAO();
        dao.sumarIngresosPorDia(LocalDate.MIN, LocalDate.MAX);
    }//GEN-LAST:event_TXTcostoTotalActionPerformed
private void EditarOrdenDeServicio() {
    try {
        
        if (idOrdenCargada == null || idOrdenCargada.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, 
                "Por favor seleccione o busque primero la orden que desea editar.", 
                "Atención", 
                JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (Estados == null || Estados.getSelectedIndex() <= 0) {
            JOptionPane.showMessageDialog(this, 
                "Por favor seleccione un estado de orden válido.", 
                "Atención", 
                JOptionPane.WARNING_MESSAGE);
            return;
        }

        String estadoSeleccionado = Estados.getSelectedItem().toString().trim();

        OrdenServicioDAO dao = new OrdenServicioDAO();
        orden_de_servicio orden = new orden_de_servicio();
        
        orden.setId_orden_serv(idOrdenCargada);
        orden.setEstadoorden_servi(estadoSeleccionado);

        orden.setFecha_ingreso(CalendarioFechaIngreso.getDate());
        if (CalendarioFechaEntrega != null && CalendarioFechaEntrega.getDate() != null) {
            orden.setFecha_entrega(CalendarioFechaEntrega.getDate());
        } else {
            orden.setFecha_entrega(null);
        }

        double costoTotal = 0.0;
        if (TXTcostoTotal != null && !TXTcostoTotal.getText().trim().isEmpty()) {
            try {
                costoTotal = Double.parseDouble(TXTcostoTotal.getText().trim());
            } catch (NumberFormatException nfe) {
                costoTotal = 0.0;
            }
        }
        orden.setCosto_total(costoTotal);

        if (comboPlacas != null && comboPlacas.getSelectedIndex() > 0) {
            String placa = comboPlacas.getSelectedItem().toString().trim();
            orden.setId_vehi(dao.obtenerIdVehiculoPorPlaca(placa));
        }

        if (comboEmpleado != null && comboEmpleado.getSelectedIndex() > 0) {
            String empleadoNombre = comboEmpleado.getSelectedItem().toString().trim();
            orden.setId_empleado(dao.obtenerIdEmpleadoPorNombre(empleadoNombre));
        }

        boolean actualizado = dao.actualizarOrdenServicio(orden);

        if (actualizado) {
            JOptionPane.showMessageDialog(this, 
                "La Orden de Servicio (" + idOrdenCargada + ") ha sido actualizada con éxito.", 
                "Actualización Exitosa", 
                JOptionPane.INFORMATION_MESSAGE);
            if (estadoSeleccionado.equalsIgnoreCase("Terminado") || estadoSeleccionado.equalsIgnoreCase("Finalizado")) {
                new Thread(() -> {
                    String[] datosPropietario = dao.obtenerDatosPropietarioPorVehiculo(orden.getId_vehi());
                    String nombrePropietario = datosPropietario[0];
                    String correoPropietario = datosPropietario[1];
                    Servidor_de_correos correo=new Servidor_de_correos();
                    if (correoPropietario != null && !correoPropietario.trim().isEmpty()) {
                        correo.enviarCorreoEstadoVehiculo(nombrePropietario, estadoSeleccionado, correoPropietario);
                    } else {
                        System.out.println("No se envió correo: El propietario no registra un correo válido.");
                    }
                }).start();
            }
            LimpiarDatos();

        } else {
            JOptionPane.showMessageDialog(this, 
                "No se pudo actualizar la orden de servicio en la base de datos.", 
                "Error de Actualización", 
                JOptionPane.ERROR_MESSAGE);
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, 
            "Error inesperado al editar: " + e.getMessage(), 
            "Error General", 
            JOptionPane.ERROR_MESSAGE);
        e.printStackTrace();
    }
}
    private void PanelEditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelEditarMouseClicked
        // TODO add your handling code here:
        EditarOrdenDeServicio();
    }//GEN-LAST:event_PanelEditarMouseClicked

    private void PanelBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelBuscarMouseClicked
        // TODO add your handling code here:
        if (comboPlacas.getSelectedIndex() <= 0) {
        JOptionPane.showMessageDialog(this, 
            "Por favor seleccione una placa de la lista para buscar su orden.", 
            "Atención", 
            JOptionPane.WARNING_MESSAGE);
        return;
    }

    String placaSeleccionada = comboPlacas.getSelectedItem().toString().trim();
    OrdenServicioDAO dao = new OrdenServicioDAO();
    orden_de_servicio orden = dao.buscarOrdenPorPlaca(placaSeleccionada);

    if (orden != null) {
        this.idOrdenCargada = orden.getId_orden_serv();

        Estados.setSelectedItem(orden.getEstadoorden_servi());
        CalendarioFechaIngreso.setDate(orden.getFecha_ingreso());
        CalendarioFechaEntrega.setDate(orden.getFecha_entrega());
        TXTcostoTotal.setText(String.format(java.util.Locale.US, "%.2f", orden.getCosto_total()));

        JOptionPane.showMessageDialog(this, "Datos de la orden cargados correctamente.");
    } else {
        JOptionPane.showMessageDialog(this, "El vehículo no tiene una orden de servicio registrada.");
    }
    }//GEN-LAST:event_PanelBuscarMouseClicked


    public void LimpiarDatos() {
    if (TXTcostoTotal != null) {
        TXTcostoTotal.setText("0.00");
        TXTcostoTotal.setForeground(new Color(94, 94, 94));
    }
        if (Descripcion != null) {
        Descripcion.setText("");
        Descripcion.setForeground(new Color(94, 94, 94));
    }
    if (Estados != null && Estados.getItemCount() > 0) Estados.setSelectedIndex(0);
    if (comboPlacas != null && comboPlacas.getItemCount() > 0) comboPlacas.setSelectedIndex(0);
    if (comboCliente != null && comboCliente.getItemCount() > 0) comboCliente.setSelectedIndex(0);
    if (comboEmpleado != null && comboEmpleado.getItemCount() > 0) comboEmpleado.setSelectedIndex(0);
    if (CalendarioFechaEntrega != null) CalendarioFechaEntrega.setDate(null);
    this.idOrdenCargada = null; 
}
    private void GuardarOrdenDeServicio() {
    try {
        if (comboPlacas.getSelectedIndex() <= 0) {
            JOptionPane.showMessageDialog(this, 
                "Por favor seleccione una placa de vehículo.", 
                "Atención", 
                JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (CalendarioFechaIngreso.getDate() == null) {
            JOptionPane.showMessageDialog(this, 
                "Por favor seleccione la fecha de ingreso.", 
                "Atención", 
                JOptionPane.WARNING_MESSAGE);
            return;
        }

        OrdenServicioDAO dao = new OrdenServicioDAO();
        orden_de_servicio orden = new orden_de_servicio();
        String nuevoId = dao.generarSiguienteIdOrden();
        orden.setId_orden_serv(nuevoId);
        
        if (Estados != null && Estados.getSelectedItem() != null) {
            orden.setEstadoorden_servi(Estados.getSelectedItem().toString());
        } else {
            orden.setEstadoorden_servi("Ingresado"); 
        }
        orden.setFecha_ingreso(CalendarioFechaIngreso.getDate());
        
        if (CalendarioFechaEntrega != null && CalendarioFechaEntrega.getDate() != null) {
            orden.setFecha_entrega(CalendarioFechaEntrega.getDate());
        } else {
            orden.setFecha_entrega(null);
        }
        double costoTotal = 0.0;
        String textoCosto = TXTcostoTotal.getText().trim();
        if (!textoCosto.isEmpty()) {
            costoTotal = Double.parseDouble(textoCosto);
        }
        orden.setCosto_total(costoTotal);

        String placaSeleccionada = comboPlacas.getSelectedItem().toString().trim().toUpperCase();
        String idVehiculo = dao.obtenerIdVehiculoPorPlaca(placaSeleccionada);

        if (idVehiculo == null) {
            JOptionPane.showMessageDialog(this, 
                "No se encontró el registro del vehículo seleccionado en la base de datos.", 
                "Error de Referencia", 
                JOptionPane.ERROR_MESSAGE);
            return;
        }
        orden.setId_vehi(idVehiculo);
        
        if (comboEmpleado != null && comboEmpleado.getSelectedIndex() > 0) {
    String empleadoTexto = comboEmpleado.getSelectedItem().toString().toUpperCase();
    String idEmpleado = dao.obtenerIdEmpleadoPorNombre(empleadoTexto);
    
    if (idEmpleado == null) {
        JOptionPane.showMessageDialog(this, 
            "No se encontró el ID del empleado seleccionado en la base de datos.", 
            "Error de Empleado", 
            JOptionPane.WARNING_MESSAGE);
        return; 
    }
    
    orden.setId_empleado(idEmpleado);
} else {
    JOptionPane.showMessageDialog(this, 
        "Por favor seleccione un empleado asignado.", 
        "Atención", 
        JOptionPane.WARNING_MESSAGE);
    return;
}
    if (comboPlacas == null || comboPlacas.getSelectedIndex() <= 0) {
    JOptionPane.showMessageDialog(this, "Por favor seleccione una placa de vehículo.", "Atención", JOptionPane.WARNING_MESSAGE);
    return;
}
    if (comboEmpleado == null || comboEmpleado.getSelectedIndex() <= 0) {
    JOptionPane.showMessageDialog(this, "Por favor seleccione un empleado asignado.", "Atención", JOptionPane.WARNING_MESSAGE);
    return;
}
    if (Estados == null || Estados.getSelectedIndex() <= 0) {
    JOptionPane.showMessageDialog(this, "Por favor seleccione un estado para la orden.", "Atención", JOptionPane.WARNING_MESSAGE);
    return;
}
    if (CalendarioFechaIngreso == null || CalendarioFechaIngreso.getDate() == null) {
    JOptionPane.showMessageDialog(this, "Por favor seleccione la fecha de ingreso.", "Atención", JOptionPane.WARNING_MESSAGE);
    return;
}
    if (Descripcion == null || Descripcion.getText().trim().isEmpty()) {
    JOptionPane.showMessageDialog(this, "Por favor ingrese la descripción del trabajo a realizar.", "Atención", JOptionPane.WARNING_MESSAGE);
    return;
}
        boolean guardadoExitoso = dao.guardarOrdenServicio(orden);

        if (guardadoExitoso) {
            JOptionPane.showMessageDialog(this, 
                "Orden de Servicio registrada con éxito.\nCódigo: " + nuevoId, 
                "Registro Exitoso", 
                JOptionPane.INFORMATION_MESSAGE);
            LimpiarDatos();
        } else {
            JOptionPane.showMessageDialog(this, 
                "No se pudo guardar la orden de servicio. Verifique la conexión o los datos.", 
                "Error de Guardado", 
                JOptionPane.ERROR_MESSAGE);
        }

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, 
            "El costo total debe ser un número válido (ejemplo: 45.50).", 
            "Error de Formato", 
            JOptionPane.ERROR_MESSAGE);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, 
            "Ocurrió un error inesperado: " + e.getMessage(), 
            "Error General", 
            JOptionPane.ERROR_MESSAGE);
        e.printStackTrace();
    }
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Buscar;
    private com.toedter.calendar.JDateChooser CalendarioFechaEntrega;
    private com.toedter.calendar.JDateChooser CalendarioFechaIngreso;
    private javax.swing.JTextField Descripcion;
    private javax.swing.JLabel Editar;
    private javax.swing.JComboBox<String> Estados;
    private javax.swing.JLabel Guardar;
    private javax.swing.JLabel ImagenADD;
    private javax.swing.JLabel ImagenSAVE;
    private javax.swing.JLabel Nuevo;
    private javax.swing.JPanel PanelBuscar;
    private javax.swing.JPanel PanelEditar;
    private javax.swing.JPanel PanelGuardar;
    private javax.swing.JPanel PanelNuevo;
    private javax.swing.JTextField TXTcostoTotal;
    private javax.swing.JComboBox<String> comboCliente;
    private javax.swing.JComboBox<String> comboEmpleado;
    private javax.swing.JComboBox<String> comboPlacas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
