/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.proyecto_m2b.Vista;

import com.mycompany.proyecto_m2b.Controlador.ConexionBD;
import com.mycompany.proyecto_m2b.Controlador.RepuestoDAO;
import com.mycompany.proyecto_m2b.modelo.MarcaRepuesto;
import com.mycompany.proyecto_m2b.modelo.Repuesto;
import com.mycompany.proyecto_m2b.modelo.TipoRepuesto;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class PanelRepuestos extends javax.swing.JPanel {
private java.sql.Connection miConexion = ConexionBD.obtenerConexion();

    /**
     * Creates new form PanelRepuestos
     */
    public PanelRepuestos() {
    initComponents();
    cargarCombos();
    txtIdRepuesto.setEditable(false);
    generarIdAutomatico();
}
    private void cargarCombos() {
        cbxTipoRepuesto.removeAllItems();
        cbxMarcaRepuesto.removeAllItems();

        RepuestoDAO dao = new RepuestoDAO();
        for (TipoRepuesto t : dao.obtenerTipos(miConexion)) {
            cbxTipoRepuesto.addItem(t);
        }
        for (MarcaRepuesto m : dao.obtenerMarcas(miConexion)) {
            cbxMarcaRepuesto.addItem(m);
        }
    }
    
    private void limpiarCampos() {
    txtIdRepuesto.setText("");
    txtNomRepuesto.setText("");
    txtStockActual.setText("");
    txtCantidadMinima.setText("");
    txtCantidadMaxima.setText("");
    txtPrecioBase.setText("");
    txtDescripRepuesto.setText("");
    generarIdAutomatico();

    if (cbxTipoRepuesto.getItemCount() > 0) {
        cbxTipoRepuesto.setSelectedIndex(0);
    }
    if (cbxMarcaRepuesto.getItemCount() > 0) {
        cbxMarcaRepuesto.setSelectedIndex(0);
    }

    txtIdRepuesto.requestFocus();
}
    
    private void generarIdAutomatico() {
    RepuestoDAO dao = new RepuestoDAO();
    String nuevoId = dao.obtenerSiguienteIdRepuesto(miConexion);
    txtIdRepuesto.setText(nuevoId);
}
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtDescripRepuesto = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JPanel();
        Guardar = new javax.swing.JLabel();
        ImagenSAVE = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtIdRepuesto = new javax.swing.JTextField();
        txtNomRepuesto = new javax.swing.JTextField();
        cbxTipoRepuesto = new javax.swing.JComboBox<>();
        cbxMarcaRepuesto = new javax.swing.JComboBox<>();
        txtStockActual = new javax.swing.JTextField();
        txtCantidadMinima = new javax.swing.JTextField();
        txtCantidadMaxima = new javax.swing.JTextField();
        txtPrecioBase = new javax.swing.JTextField();
        btnAgregarMarca = new javax.swing.JPanel();
        Nuevo2 = new javax.swing.JLabel();
        ImagenADD2 = new javax.swing.JLabel();
        btnAgregarTipo = new javax.swing.JPanel();
        Nuevo3 = new javax.swing.JLabel();
        ImagenADD3 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(238, 238, 238));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel21.setText("<- REGRESAR");
        jLabel21.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel21MouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("GESTIÓN DE REPUESTOS");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 899, Short.MAX_VALUE)
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1320, 50));

        jLabel5.setText("ID Repuesto");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jLabel6.setText("Nombre Repueseto");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jLabel7.setText("Tipo:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        jLabel8.setText("Marca:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        jLabel10.setText("Stock Actual:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 70, -1, -1));

        jLabel11.setText("Cantidad Mínima:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 100, -1, 20));

        jLabel12.setText("Descripción del repuesto:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        jLabel13.setText("Cantidad Máxima:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 130, -1, -1));

        txtDescripRepuesto.setForeground(new java.awt.Color(153, 153, 153));
        txtDescripRepuesto.setText("Describa el repuesto");
        txtDescripRepuesto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtDescripRepuestoFocusGained(evt);
            }
        });
        txtDescripRepuesto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtDescripRepuestoMousePressed(evt);
            }
        });
        jPanel1.add(txtDescripRepuesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 690, 70));

        btnGuardar.setBackground(new java.awt.Color(242, 101, 34));
        btnGuardar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(187, 187, 187)));
        btnGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGuardarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnGuardarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnGuardarMouseExited(evt);
            }
        });

        Guardar.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        Guardar.setForeground(new java.awt.Color(255, 255, 255));
        Guardar.setText("Guardar");

        ImagenSAVE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/save_22dp_FFFFFF_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N

        javax.swing.GroupLayout btnGuardarLayout = new javax.swing.GroupLayout(btnGuardar);
        btnGuardar.setLayout(btnGuardarLayout);
        btnGuardarLayout.setHorizontalGroup(
            btnGuardarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnGuardarLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(ImagenSAVE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Guardar)
                .addContainerGap(36, Short.MAX_VALUE))
        );
        btnGuardarLayout.setVerticalGroup(
            btnGuardarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnGuardarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(btnGuardarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Guardar)
                    .addComponent(ImagenSAVE))
                .addContainerGap())
        );

        jPanel1.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 350, -1, -1));

        jLabel3.setText("Precio Base:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 160, -1, -1));
        jPanel1.add(txtIdRepuesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 160, -1));
        jPanel1.add(txtNomRepuesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 160, -1));

        cbxTipoRepuesto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(cbxTipoRepuesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 170, -1));

        cbxMarcaRepuesto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(cbxMarcaRepuesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 170, -1));
        jPanel1.add(txtStockActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 70, 170, -1));
        jPanel1.add(txtCantidadMinima, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 100, 170, -1));
        jPanel1.add(txtCantidadMaxima, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 130, 170, -1));
        jPanel1.add(txtPrecioBase, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 160, 170, -1));

        btnAgregarMarca.setBackground(new java.awt.Color(255, 255, 255));
        btnAgregarMarca.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(187, 187, 187)));
        btnAgregarMarca.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregarMarca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAgregarMarcaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAgregarMarcaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAgregarMarcaMouseExited(evt);
            }
        });

        Nuevo2.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        Nuevo2.setText("Nuevo");

        ImagenADD2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/add_22dp_000000_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N

        javax.swing.GroupLayout btnAgregarMarcaLayout = new javax.swing.GroupLayout(btnAgregarMarca);
        btnAgregarMarca.setLayout(btnAgregarMarcaLayout);
        btnAgregarMarcaLayout.setHorizontalGroup(
            btnAgregarMarcaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnAgregarMarcaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ImagenADD2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Nuevo2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnAgregarMarcaLayout.setVerticalGroup(
            btnAgregarMarcaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnAgregarMarcaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(btnAgregarMarcaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ImagenADD2)
                    .addComponent(Nuevo2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(btnAgregarMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, -1, -1));

        btnAgregarTipo.setBackground(new java.awt.Color(255, 255, 255));
        btnAgregarTipo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(187, 187, 187)));
        btnAgregarTipo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregarTipo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAgregarTipoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAgregarTipoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAgregarTipoMouseExited(evt);
            }
        });

        Nuevo3.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        Nuevo3.setText("Nuevo");

        ImagenADD3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/add_22dp_000000_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N

        javax.swing.GroupLayout btnAgregarTipoLayout = new javax.swing.GroupLayout(btnAgregarTipo);
        btnAgregarTipo.setLayout(btnAgregarTipoLayout);
        btnAgregarTipoLayout.setHorizontalGroup(
            btnAgregarTipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnAgregarTipoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ImagenADD3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Nuevo3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnAgregarTipoLayout.setVerticalGroup(
            btnAgregarTipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnAgregarTipoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(btnAgregarTipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ImagenADD3)
                    .addComponent(Nuevo3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(btnAgregarTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jLabel21MouseClicked

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged

    }//GEN-LAST:event_jPanel2MouseDragged

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed

    }//GEN-LAST:event_jPanel2MousePressed

    private void txtDescripRepuestoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDescripRepuestoFocusGained
        // TODO add your handling code here:

    }//GEN-LAST:event_txtDescripRepuestoFocusGained

    private void txtDescripRepuestoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDescripRepuestoMousePressed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtDescripRepuestoMousePressed

    private void btnGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseClicked
    try {
        String id = txtIdRepuesto.getText().trim();
        String nombre = txtNomRepuesto.getText().trim();
        int stockActual = Integer.parseInt(txtStockActual.getText().trim());
        int stockMin = Integer.parseInt(txtCantidadMinima.getText().trim());
        int stockMax = Integer.parseInt(txtCantidadMaxima.getText().trim());
        double precio = Double.parseDouble(txtPrecioBase.getText().trim());
        String descripcion = txtDescripRepuesto.getText().trim();

        TipoRepuesto tipoSel = (TipoRepuesto) cbxTipoRepuesto.getSelectedItem();
        MarcaRepuesto marcaSel = (MarcaRepuesto) cbxMarcaRepuesto.getSelectedItem();

        if (id.isEmpty() || nombre.isEmpty() || tipoSel == null || marcaSel == null) {
            JOptionPane.showMessageDialog(this, "Por favor complete los campos obligatorios.", "Campos vacíos", JOptionPane.WARNING_MESSAGE);
            return;
        }

        Repuesto repuesto = new Repuesto(
            id, nombre, stockMax, stockMin, stockActual, 
            precio, descripcion, tipoSel.getIdTipRepuesto(), marcaSel.getIdMarcaRepuesto()
        );

        RepuestoDAO dao = new RepuestoDAO();
        if (dao.guardarRepuesto(repuesto, miConexion)) {
            JOptionPane.showMessageDialog(this, "¡Repuesto guardado en la base de datos!", "Éxito", JOptionPane.INFORMATION_MESSAGE);
            limpiarCampos();
        }

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Asegúrese de ingresar números válidos en los Stocks y Precio.", "Error de entrada", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnGuardarMouseClicked

    private void btnGuardarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseEntered
        // TODO add your handling code here:
        btnGuardar.setBackground(new Color(227, 95, 32));
        Guardar.setForeground(new Color(217, 217, 192));
    }//GEN-LAST:event_btnGuardarMouseEntered

    private void btnGuardarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseExited
        // TODO add your handling code here:
        btnGuardar.setBackground(new Color(242,101,34));
        Guardar.setForeground(Color.white);
    }//GEN-LAST:event_btnGuardarMouseExited

    private void btnAgregarMarcaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarMarcaMouseClicked
        // TODO add your handling code here:
        String nombreMarca = JOptionPane.showInputDialog(this, "Ingrese el nombre de la nueva marca:", "Nueva Marca", JOptionPane.QUESTION_MESSAGE);
    if (nombreMarca != null && !nombreMarca.trim().isEmpty()) {
        String idMarca = "MAR-" + (System.currentTimeMillis() % 10000);
        MarcaRepuesto nuevaMarca = new MarcaRepuesto(idMarca, nombreMarca.trim());

        RepuestoDAO dao = new RepuestoDAO();
        if (dao.guardarMarca(nuevaMarca, miConexion)) {
            cbxMarcaRepuesto.addItem(nuevaMarca);
            cbxMarcaRepuesto.setSelectedItem(nuevaMarca);
            JOptionPane.showMessageDialog(this, "Marca registrada con éxito.");
        }
    }

    }//GEN-LAST:event_btnAgregarMarcaMouseClicked

    private void btnAgregarMarcaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarMarcaMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarMarcaMouseEntered

    private void btnAgregarMarcaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarMarcaMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarMarcaMouseExited

    private void btnAgregarTipoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarTipoMouseClicked
        // TODO add your handling code here:
    javax.swing.JTextField txtNombre = new javax.swing.JTextField();
    javax.swing.JTextField txtDescripcion = new javax.swing.JTextField();

    Object[] formulario = {
        "Nombre del Tipo:", txtNombre,
        "Descripción:", txtDescripcion
    };

    int opcion = javax.swing.JOptionPane.showConfirmDialog(
        this, 
        formulario, 
        "Registrar Nuevo Tipo de Repuesto", 
        javax.swing.JOptionPane.OK_CANCEL_OPTION
    );

    if (opcion == javax.swing.JOptionPane.OK_OPTION) {
        String nombre = txtNombre.getText().trim();
        String descripcion = txtDescripcion.getText().trim();

        if (!nombre.isEmpty()) {
            String idTipo = "TIP-" + (System.currentTimeMillis() % 10000);
            
            if (descripcion.isEmpty()) {
                descripcion = "Sin descripción";
            }

            TipoRepuesto nuevoTipo = new TipoRepuesto(idTipo, nombre, descripcion);

            RepuestoDAO dao = new RepuestoDAO();
            if (dao.guardarTipo(nuevoTipo, miConexion)) {
                cbxTipoRepuesto.addItem(nuevoTipo);
                cbxTipoRepuesto.setSelectedItem(nuevoTipo);
                javax.swing.JOptionPane.showMessageDialog(this, "Tipo guardado exitosamente.");
            }
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "El nombre del tipo no puede estar vacío.", "Advertencia", javax.swing.JOptionPane.WARNING_MESSAGE);
        }
    
    }

    }//GEN-LAST:event_btnAgregarTipoMouseClicked

    private void btnAgregarTipoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarTipoMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarTipoMouseEntered

    private void btnAgregarTipoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarTipoMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarTipoMouseExited
    
    public void LimpiarDatos (){

    }
    public void GuardarRepuestos (){

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Guardar;
    private javax.swing.JLabel ImagenADD2;
    private javax.swing.JLabel ImagenADD3;
    private javax.swing.JLabel ImagenSAVE;
    private javax.swing.JLabel Nuevo2;
    private javax.swing.JLabel Nuevo3;
    private javax.swing.JPanel btnAgregarMarca;
    private javax.swing.JPanel btnAgregarTipo;
    private javax.swing.JPanel btnGuardar;
    private javax.swing.JComboBox<Object> cbxMarcaRepuesto;
    private javax.swing.JComboBox<Object> cbxTipoRepuesto;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtCantidadMaxima;
    private javax.swing.JTextField txtCantidadMinima;
    private javax.swing.JTextField txtDescripRepuesto;
    private javax.swing.JTextField txtIdRepuesto;
    private javax.swing.JTextField txtNomRepuesto;
    private javax.swing.JTextField txtPrecioBase;
    private javax.swing.JTextField txtStockActual;
    // End of variables declaration//GEN-END:variables
}
