/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyecto_m2b.Vista;

import com.mycompany.proyecto_m2b.Controlador.OrdenServicioDAO;
import com.mycompany.proyecto_m2b.Controlador.ProduceDAO;
import com.mycompany.proyecto_m2b.Controlador.ResiduoDAO;
import com.mycompany.proyecto_m2b.modelo.Produce;
import com.mycompany.proyecto_m2b.modelo.Residuos;
import com.mycompany.proyecto_m2b.modelo.orden_de_servicio;
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author usuario
 */
public class PanelProduce extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PanelProduce.class.getName());

    /**
     * Creates new form PanelProduce
     */
    public PanelProduce() {
        initComponents();
        ResiduoDAO rd=new ResiduoDAO();
        rd.cargarResiduos(ComboResiduos);
        OrdenServicioDAO od=new OrdenServicioDAO();
        od.cargarOrdenServicio(ComboOrdenesServicio);
        this.setLocationRelativeTo(null);
    }

    int Mousex;
    int Mousey;
    private Residuos residuo;
    private orden_de_servicio ordenServicio;
    private List<Produce> listaTemporal = new ArrayList<>();
    private List<Produce> historialProduce = new ArrayList<>();
    private Produce produceTabla;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Detalles_de_produccion1 = new javax.swing.JLabel();
        ComboOrdenesServicio = new javax.swing.JComboBox<>();
        ComboResiduos = new javax.swing.JComboBox<>();
        TXTCantidad = new javax.swing.JTextField();
        PanelAgregarResiduo = new javax.swing.JPanel();
        Nuevo2 = new javax.swing.JLabel();
        ImagenADD2 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        TablaProduce = new javax.swing.JTable();
        Detalles_de_produccion2 = new javax.swing.JLabel();
        PanelNuevo = new javax.swing.JPanel();
        Nuevo = new javax.swing.JLabel();
        ImagenADD = new javax.swing.JLabel();
        Detalles_de_produccion3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaHistorial = new javax.swing.JTable();
        PanelGuardar = new javax.swing.JPanel();
        Guardar = new javax.swing.JLabel();
        ImagenSAVE = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Regresar = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        PanelEditar = new javax.swing.JPanel();
        Editar = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        PanelEliminarServicio = new javax.swing.JPanel();
        DarDeBaja = new javax.swing.JLabel();
        ImagenDarBaja = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        Detalles_de_produccion1.setBackground(new java.awt.Color(0, 0, 0));
        Detalles_de_produccion1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Detalles_de_produccion1.setText("DETALLE DE LOS RESIDUOS:");

        ComboOrdenesServicio.addItemListener(this::ComboOrdenesServicioItemStateChanged);

        PanelAgregarResiduo.setBackground(new java.awt.Color(255, 255, 255));
        PanelAgregarResiduo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(187, 187, 187)));
        PanelAgregarResiduo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PanelAgregarResiduo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PanelAgregarResiduoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PanelAgregarResiduoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PanelAgregarResiduoMouseExited(evt);
            }
        });

        Nuevo2.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        Nuevo2.setText("Agregar Residuo");

        ImagenADD2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/add_22dp_000000_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N

        javax.swing.GroupLayout PanelAgregarResiduoLayout = new javax.swing.GroupLayout(PanelAgregarResiduo);
        PanelAgregarResiduo.setLayout(PanelAgregarResiduoLayout);
        PanelAgregarResiduoLayout.setHorizontalGroup(
            PanelAgregarResiduoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAgregarResiduoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ImagenADD2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Nuevo2)
                .addGap(16, 16, 16))
        );
        PanelAgregarResiduoLayout.setVerticalGroup(
            PanelAgregarResiduoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAgregarResiduoLayout.createSequentialGroup()
                .addGroup(PanelAgregarResiduoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Nuevo2)
                    .addComponent(ImagenADD2))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        TablaProduce.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(TablaProduce);

        Detalles_de_produccion2.setBackground(new java.awt.Color(0, 0, 0));
        Detalles_de_produccion2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Detalles_de_produccion2.setText("CANTIDAD:");

        PanelNuevo.setBackground(new java.awt.Color(255, 255, 255));
        PanelNuevo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(187, 187, 187)));
        PanelNuevo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PanelNuevo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PanelNuevoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PanelNuevoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PanelNuevoMouseExited(evt);
            }
        });

        Nuevo.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        Nuevo.setText("Nuevo detalle");

        ImagenADD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/add_22dp_000000_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N

        javax.swing.GroupLayout PanelNuevoLayout = new javax.swing.GroupLayout(PanelNuevo);
        PanelNuevo.setLayout(PanelNuevoLayout);
        PanelNuevoLayout.setHorizontalGroup(
            PanelNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelNuevoLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(ImagenADD)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Nuevo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelNuevoLayout.setVerticalGroup(
            PanelNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelNuevoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ImagenADD)
                    .addComponent(Nuevo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Detalles_de_produccion3.setBackground(new java.awt.Color(0, 0, 0));
        Detalles_de_produccion3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Detalles_de_produccion3.setText("HISTORIAL DE RESIDUOS:");

        TablaHistorial.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TablaHistorial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaHistorialMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablaHistorial);

        PanelGuardar.setBackground(new java.awt.Color(242, 101, 34));
        PanelGuardar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(187, 187, 187)));
        PanelGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PanelGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PanelGuardarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PanelGuardarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PanelGuardarMouseExited(evt);
            }
        });

        Guardar.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        Guardar.setForeground(new java.awt.Color(255, 255, 255));
        Guardar.setText("Guardar");

        ImagenSAVE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/save_22dp_FFFFFF_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N

        javax.swing.GroupLayout PanelGuardarLayout = new javax.swing.GroupLayout(PanelGuardar);
        PanelGuardar.setLayout(PanelGuardarLayout);
        PanelGuardarLayout.setHorizontalGroup(
            PanelGuardarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelGuardarLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(ImagenSAVE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Guardar)
                .addContainerGap(36, Short.MAX_VALUE))
        );
        PanelGuardarLayout.setVerticalGroup(
            PanelGuardarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelGuardarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanelGuardarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Guardar)
                    .addComponent(ImagenSAVE))
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });

        Regresar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Regresar.setForeground(new java.awt.Color(153, 153, 153));
        Regresar.setText("<- REGRESAR");
        Regresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Regresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RegresarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                RegresarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                RegresarMouseExited(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("DETALLE DE RESIDUOS");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 700, Short.MAX_VALUE)
                .addComponent(Regresar, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Regresar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
        );

        PanelEditar.setBackground(new java.awt.Color(255, 255, 255));
        PanelEditar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(187, 187, 187)));
        PanelEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PanelEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PanelEditarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PanelEditarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PanelEditarMouseExited(evt);
            }
        });

        Editar.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        Editar.setText("Editar");

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/edit_22dp_000000_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N

        javax.swing.GroupLayout PanelEditarLayout = new javax.swing.GroupLayout(PanelEditar);
        PanelEditar.setLayout(PanelEditarLayout);
        PanelEditarLayout.setHorizontalGroup(
            PanelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelEditarLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Editar)
                .addContainerGap(33, Short.MAX_VALUE))
        );
        PanelEditarLayout.setVerticalGroup(
            PanelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelEditarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Editar)
                    .addComponent(jLabel2))
                .addContainerGap())
        );

        PanelEliminarServicio.setBackground(new java.awt.Color(255, 255, 255));
        PanelEliminarServicio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(215, 106, 106)));
        PanelEliminarServicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PanelEliminarServicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PanelEliminarServicioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PanelEliminarServicioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PanelEliminarServicioMouseExited(evt);
            }
        });

        DarDeBaja.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        DarDeBaja.setForeground(new java.awt.Color(215, 106, 106));
        DarDeBaja.setText("Eliminar");

        ImagenDarBaja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/person_cancel_22dp_EA3323_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N

        javax.swing.GroupLayout PanelEliminarServicioLayout = new javax.swing.GroupLayout(PanelEliminarServicio);
        PanelEliminarServicio.setLayout(PanelEliminarServicioLayout);
        PanelEliminarServicioLayout.setHorizontalGroup(
            PanelEliminarServicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelEliminarServicioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ImagenDarBaja)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(DarDeBaja)
                .addGap(30, 30, 30))
        );
        PanelEliminarServicioLayout.setVerticalGroup(
            PanelEliminarServicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelEliminarServicioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelEliminarServicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DarDeBaja)
                    .addComponent(ImagenDarBaja))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Detalles_de_produccion1)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(ComboOrdenesServicio, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ComboResiduos, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TXTCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Detalles_de_produccion2)
                                .addGap(54, 54, 54))))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PanelNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PanelAgregarResiduo, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PanelGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Detalles_de_produccion3)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PanelEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PanelEliminarServicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Detalles_de_produccion1)
                            .addComponent(Detalles_de_produccion2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ComboOrdenesServicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ComboResiduos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TXTCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Detalles_de_produccion3)
                        .addGap(50, 50, 50)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(PanelNuevo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(PanelAgregarResiduo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(PanelGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PanelEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PanelEliminarServicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void limpiarDatos (){
        ComboOrdenesServicio.setSelectedIndex(0);
        ComboResiduos.setSelectedIndex(0);
        TXTCantidad.setText("");
    }
    public void limpiarDatosCompleto(){
        residuo=null;
        ordenServicio=null;
        TXTCantidad.setText("");
        DefaultTableModel modelo=(DefaultTableModel) TablaProduce.getModel();
        modelo.setRowCount(0);
        if (listaTemporal!=null){
            listaTemporal.clear();
        }
    }
    public void cargarHistorialProduce(String idOrden) {
        ProduceDAO produceDAO = new ProduceDAO();
        historialProduce = produceDAO.listarProducePorOrden(idOrden);
        String[] columnas = {"Residuo", "Cantidad generada", "Fecha de registro"};
        DefaultTableModel modelo = new DefaultTableModel(null, columnas);
        for (Produce produce : historialProduce) {
            Object[] fila = {
                produce.getNom_residuo(),
                produce.getCant_gene(),
                produce.getFecha_registro()
            };
            modelo.addRow(fila);
        }
        TablaHistorial.setModel(modelo);
    }
    
    public void cargarTablaTemporal() {
        String[] columnas = {"Residuo", "Cantidad generada"};
        DefaultTableModel modelo=new DefaultTableModel(null, columnas);
        for (Produce produce : listaTemporal) {
            Object[] fila = {
                produce.getNom_residuo(),
                produce.getCant_gene()
            };
            modelo.addRow(fila);
        }
        TablaProduce.setModel(modelo);
    }
    
    public void eliminarProduceRegistrado() {
        if (produceTabla == null) {JOptionPane.showMessageDialog(this, "Seleccione un residuo de la tabla de historial.");
            return;
        }
        
        ProduceDAO produceDAO = new ProduceDAO();
        
        boolean exito = produceDAO.eliminarProduce(produceTabla.getId_produccion(), produceTabla.getId_residuos(), produceTabla.getCant_gene());
        if (!exito) {
            JOptionPane.showMessageDialog(this, "No se pudo eliminar el residuo.");
            return;
        }
        String idOrden = produceTabla.getId_orden_serv();
        JOptionPane.showMessageDialog(this,"Residuo eliminado y cantidad revertida correctamente.");
        produceTabla = null;
        TXTCantidad.setText("");
        ComboOrdenesServicio.setEnabled(true);
        ComboResiduos.setEnabled(true);
        cargarHistorialProduce(idOrden);
    }
    public void agregarResiduo() {
        residuo = (Residuos) ComboResiduos.getSelectedItem();        
        if (residuo == null) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un residuo para poder agregar");
            return;
        }
        String textoCantidad = TXTCantidad.getText().trim();
        if (textoCantidad.isEmpty()) {JOptionPane.showMessageDialog(this, "Debe ingresar la cantidad que quiere agregar");
            return;
        }
        int cantidad;
        try {
            cantidad = Integer.parseInt(textoCantidad);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this,"La cantidad debe ser un número entero, sin decimales");
            return;
        }
        if (cantidad <= 0) {
            JOptionPane.showMessageDialog(this, "Debe ser un número mayor a cero");
            return;
        }
        if (cantidad>residuo.getCantidad_max()){
            JOptionPane.showMessageDialog(this, "Supera la cantidad máxima del producto");
            return;
        }
        boolean encontrado = false;
        for (Produce pendiente : listaTemporal) {
            if (pendiente.getId_residuos().equals(residuo.getID_resiudos())) {
                pendiente.setCant_gene(pendiente.getCant_gene() + cantidad);
                JOptionPane.showMessageDialog(this, "Se ha agredado el siguiente residuo: "+residuo.getNom_residuo());
                encontrado = true;
                break;
            }
        }
        if (!encontrado) {
            Produce nuevo = new Produce();
            nuevo.setId_residuos(residuo.getID_resiudos());
            nuevo.setNom_residuo(residuo.getNom_residuo());
            nuevo.setCant_gene(cantidad);
            JOptionPane.showMessageDialog(this, "Se ha agredado el siguiente residuo: "+residuo.getNom_residuo());
            TXTCantidad.setText("");
            ComboResiduos.setSelectedIndex(0);
            listaTemporal.add(nuevo);
        }
        cargarTablaTemporal();
    }
    
    public void guardarProduce() {        
        ordenServicio = (orden_de_servicio) ComboOrdenesServicio.getSelectedItem();
        if (ordenServicio == null) {
            JOptionPane.showMessageDialog(this, "Debe de seleccionar primero una orden de servicio");
            return;
        }
        if (listaTemporal.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar al menos un residuo");
            return;
        }
        
        String idOrden = ordenServicio.getId_orden_serv();
        for (Produce produce : listaTemporal) {
            produce.setId_orden_serv(idOrden);
        }
        ProduceDAO produceDAO = new ProduceDAO();
        boolean exito = produceDAO.guardarListaTemporal(listaTemporal);
        if (exito) {
            JOptionPane.showMessageDialog(this, "Se han registrado correctamente los residuos");
            limpiarDatosCompleto();
            cargarTablaTemporal();
            cargarHistorialProduce(idOrden);
        } else {
            JOptionPane.showMessageDialog(this,"No se pudo registrar \n"
                    + "Verifique la cantidad máxima de los residuos"
            );
        }
    }
    private void PanelAgregarResiduoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelAgregarResiduoMouseClicked
        // TODO add your handling code here:
        ComboOrdenesServicio.setEnabled(false);
        int opcion=JOptionPane.showConfirmDialog(this, "Está seguro de quere guardar este residuo", "Confrimar",JOptionPane.YES_NO_OPTION);
        if (opcion==JOptionPane.YES_OPTION){
            agregarResiduo();            
        }
        else{
            JOptionPane.showMessageDialog(this, "Se ha cancelado la acción");
        }
    }//GEN-LAST:event_PanelAgregarResiduoMouseClicked

    private void PanelAgregarResiduoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelAgregarResiduoMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_PanelAgregarResiduoMouseEntered

    private void PanelAgregarResiduoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelAgregarResiduoMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_PanelAgregarResiduoMouseExited

    private void PanelNuevoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelNuevoMouseClicked
        // TODO add your handling code here:
        limpiarDatosCompleto();
        ComboOrdenesServicio.setEnabled(true);
        JOptionPane.showMessageDialog(this, "Datos limpiados correctamente"+"\n"
            +"Ingrese los datos");
    }//GEN-LAST:event_PanelNuevoMouseClicked

    private void PanelNuevoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelNuevoMouseEntered
        // TODO add your handling code here:
        PanelNuevo.setBackground(new Color(219,219,219));
        Nuevo.setForeground(new Color(66, 66, 66));
    }//GEN-LAST:event_PanelNuevoMouseEntered

    private void PanelNuevoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelNuevoMouseExited
        // TODO add your handling code here:
        PanelNuevo.setBackground(Color.white);
        Nuevo.setForeground(Color.black);
    }//GEN-LAST:event_PanelNuevoMouseExited

    private void ComboOrdenesServicioItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ComboOrdenesServicioItemStateChanged
        // TODO add your handling code here:
        if (evt.getStateChange() != java.awt.event.ItemEvent.SELECTED) {
            return;
        }
        ordenServicio = (orden_de_servicio) ComboOrdenesServicio.getSelectedItem();
        if (ordenServicio != null) {
            listaTemporal.clear();
            cargarTablaTemporal();
            String idOrden=ordenServicio.getId_orden_serv();
            System.out.println("es: "+idOrden);
            cargarHistorialProduce(ordenServicio.getId_orden_serv());
        }
    }//GEN-LAST:event_ComboOrdenesServicioItemStateChanged

    private void PanelGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelGuardarMouseClicked
        // TODO add your handling code here:
        int opcion = JOptionPane.showConfirmDialog(this, "Esta seguro de quere guardar este detalle de residuos","Confirmar", JOptionPane.YES_NO_OPTION);
        if (opcion==JOptionPane.YES_OPTION){
            guardarProduce();
            limpiarDatosCompleto();
        }
        else{
            JOptionPane.showMessageDialog(this, "Acción cancelada");
        }
    }//GEN-LAST:event_PanelGuardarMouseClicked

    private void PanelGuardarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelGuardarMouseEntered
        // TODO add your handling code here:
        PanelGuardar.setBackground(new Color(227, 95, 32));
        Guardar.setForeground(new Color(217, 217, 192));
    }//GEN-LAST:event_PanelGuardarMouseEntered

    private void PanelGuardarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelGuardarMouseExited
        // TODO add your handling code here:
        PanelGuardar.setBackground(new Color(242,101,34));
        Guardar.setForeground(Color.white);
    }//GEN-LAST:event_PanelGuardarMouseExited

    private void RegresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegresarMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_RegresarMouseClicked

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        int x=evt.getXOnScreen();
        int y=evt.getYOnScreen();
        this.setLocation(x-Mousex, y-Mousey);
    }//GEN-LAST:event_jPanel2MouseDragged

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        // TODO add your handling code here:
        Mousex=evt.getX();
        Mousey=evt.getY();
    }//GEN-LAST:event_jPanel2MousePressed

    private void RegresarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegresarMouseEntered
        // TODO add your handling code here:
        Regresar.setForeground(Color.white);
    }//GEN-LAST:event_RegresarMouseEntered

    private void RegresarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegresarMouseExited
        // TODO add your handling code here:
        Regresar.setForeground(new Color(153,153,153));
    }//GEN-LAST:event_RegresarMouseExited

    private void seleccionarOrden(JComboBox<?> combo, String idOrden) {
        if (idOrden==null){
            combo.setSelectedIndex(0);
        }
        else{
            for (int i=0; i < combo.getItemCount(); i++){
                Object orden = combo.getItemAt(i);
                if (orden !=null && orden.toString().equalsIgnoreCase(idOrden.trim())){
                    combo.setSelectedIndex(i);
                    return;
                }
            }
            System.out.println("No se encontro el comboBox de ordenes de servicio");
        }
    }
    private void seleccionarResiduo(JComboBox<?> combo, String NomResiduo) {
        if (NomResiduo==null){
            combo.setSelectedIndex(0);
        }
        else{
            for (int i=0; i < combo.getItemCount(); i++){
                Object orden = combo.getItemAt(i);
                if (orden !=null && orden.toString().equalsIgnoreCase(NomResiduo.trim())){
                    combo.setSelectedIndex(i);
                    return;
                }
            }
            System.out.println("No se encontro el comboBox de residuos");
        }
    }
    public void editarProduce() {
        if (produceTabla == null) {
            JOptionPane.showMessageDialog(this, "Tiene que seleccionar un residuo de la tabla historial para continuar");
            return;
        }
        String textoCantidad = TXTCantidad.getText().trim();
        if (textoCantidad.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe ingresar la nueva cantidad");
            return;
        }
        int cantidadNueva;
        try {
            cantidadNueva = Integer.parseInt(textoCantidad);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this,"La cantidad no respeta el formato establecido");
            return;
        }
        if (cantidadNueva <= 0) {
            JOptionPane.showMessageDialog(this, "Debe ser mayor a cero");
            return;
        }
        ProduceDAO produceDAO = new ProduceDAO();
        boolean exito = produceDAO.editarProduceAnterior(produceTabla.getId_produccion(), produceTabla.getId_residuos(), produceTabla.getCant_gene(), cantidadNueva);
        if (!exito) {
            JOptionPane.showMessageDialog(this, "No se pudo modificar la cantidad, revise el máximo permitido del residuo");
            return;
        }
        JOptionPane.showMessageDialog(this, "Cantidad modificada correctamente.");
        String idOrden = produceTabla.getId_orden_serv();
        produceTabla = null;
        TXTCantidad.setText("");
        ComboOrdenesServicio.setEnabled(true);
        ComboResiduos.setEnabled(true);
        cargarHistorialProduce(idOrden);
    }
    
    
    private void TablaHistorialMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaHistorialMouseClicked
        // TODO add your handling code here:
        int fila = TablaHistorial.getSelectedRow();
        if (fila == -1 || fila >= historialProduce.size()) {
            return;
        }
        produceTabla = historialProduce.get(fila);
        seleccionarOrden(ComboOrdenesServicio, produceTabla.getId_orden_serv());
        seleccionarResiduo(ComboResiduos, produceTabla.getNom_residuo());
        TXTCantidad.setText(String.valueOf(produceTabla.getCant_gene()));
        ComboOrdenesServicio.setEnabled(false);
        ComboResiduos.setEnabled(false);
    }//GEN-LAST:event_TablaHistorialMouseClicked

    private void PanelEditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelEditarMouseClicked
        // TODO add your handling code here:
        int opcion = JOptionPane.showConfirmDialog(this, "¿Esta seguro de querer modificar el siguiente registro?", "Confirmar", JOptionPane.YES_NO_OPTION);
        if (opcion==JOptionPane.YES_OPTION){
            editarProduce();
        }
        else{
            JOptionPane.showMessageDialog(this, "Acción cancelada");
        }
    }//GEN-LAST:event_PanelEditarMouseClicked

    private void PanelEditarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelEditarMouseEntered
        // TODO add your handling code here:
        PanelEditar.setBackground(new Color(219,219,219));
        Editar.setForeground(new Color(66, 66, 66));
    }//GEN-LAST:event_PanelEditarMouseEntered

    private void PanelEditarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelEditarMouseExited
        // TODO add your handling code here:
        PanelEditar.setBackground(Color.white);
        Editar.setForeground(Color.black);
    }//GEN-LAST:event_PanelEditarMouseExited

    private void PanelEliminarServicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelEliminarServicioMouseClicked
        // TODO add your handling code here:
        int opcion = JOptionPane.showConfirmDialog(this, "Está seguro de querer eliminar este registro de la tabla", "Confirmar", JOptionPane.YES_NO_OPTION);
        if (opcion == JOptionPane.YES_OPTION){
            eliminarProduceRegistrado();
        }
        else{
            JOptionPane.showMessageDialog(this, "Acción cancelada");
        }
    }//GEN-LAST:event_PanelEliminarServicioMouseClicked

    private void PanelEliminarServicioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelEliminarServicioMouseEntered
        // TODO add your handling code here:
        PanelEliminarServicio.setBackground(new Color (252, 168, 168));
        DarDeBaja.setForeground(Color.white);
    }//GEN-LAST:event_PanelEliminarServicioMouseEntered

    private void PanelEliminarServicioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelEliminarServicioMouseExited
        // TODO add your handling code here:
        PanelEliminarServicio.setBackground(Color.white);
        DarDeBaja.setForeground(new Color(215, 106, 106));
    }//GEN-LAST:event_PanelEliminarServicioMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new PanelProduce().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboOrdenesServicio;
    private javax.swing.JComboBox<String> ComboResiduos;
    private javax.swing.JLabel DarDeBaja;
    private javax.swing.JLabel Detalles_de_produccion1;
    private javax.swing.JLabel Detalles_de_produccion2;
    private javax.swing.JLabel Detalles_de_produccion3;
    private javax.swing.JLabel Editar;
    private javax.swing.JLabel Guardar;
    private javax.swing.JLabel ImagenADD;
    private javax.swing.JLabel ImagenADD2;
    private javax.swing.JLabel ImagenDarBaja;
    private javax.swing.JLabel ImagenSAVE;
    private javax.swing.JLabel Nuevo;
    private javax.swing.JLabel Nuevo2;
    private javax.swing.JPanel PanelAgregarResiduo;
    private javax.swing.JPanel PanelEditar;
    private javax.swing.JPanel PanelEliminarServicio;
    private javax.swing.JPanel PanelGuardar;
    private javax.swing.JPanel PanelNuevo;
    private javax.swing.JLabel Regresar;
    private javax.swing.JTextField TXTCantidad;
    private javax.swing.JTable TablaHistorial;
    private javax.swing.JTable TablaProduce;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    // End of variables declaration//GEN-END:variables
}
