/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.proyecto_m2b.Vista;

import com.mycompany.proyecto_m2b.Controlador.RegistrarEmpresaRecicladoraDAO;
import com.mycompany.proyecto_m2b.Controlador.ResiduoDAO;
import com.mycompany.proyecto_m2b.Controlador.VentaDAO;
import com.mycompany.proyecto_m2b.modelo.DetalleVenta;
import com.mycompany.proyecto_m2b.modelo.Empresa_recicladora;
import com.mycompany.proyecto_m2b.modelo.EncabezadoVenta;
import com.mycompany.proyecto_m2b.modelo.Residuos;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class PanelResiduos extends javax.swing.JPanel {

    /**
     * Creates new form PanelResiduos
     */
    public PanelResiduos() {
    initComponents();

    java.time.LocalDate fechaActual = java.time.LocalDate.now();
    dateReciclaje.setDate(java.sql.Date.valueOf(fechaActual));
    dateReciclaje.setEnabled(false); 

    txtNReciclaje.setText(generarNumeroFactura());
    txtNReciclaje.setEditable(false); 
    txtNReciclaje.setEnabled(false);
    txtDireccion.setEnabled(false);
    txtTipoEmpresa.setEnabled(false);

    cargarComboResiduos();
    cargarEmpresasEnCombo();
    }
    
    private void cargarEmpresasEnCombo() {
    comboEmpresas.removeAllItems();

    comboEmpresas.addItem((Object) "Seleccione una empresa recicladora");

    RegistrarEmpresaRecicladoraDAO dao = new RegistrarEmpresaRecicladoraDAO();
    List<Empresa_recicladora> empresas = dao.obtenerEmpresasParaCombo();

    for (Empresa_recicladora emp : empresas) {
        comboEmpresas.addItem((Object) emp);
    }
    }
    private String generarNumeroFactura() {
    VentaDAO dao = new VentaDAO();
    return dao.obtenerSiguienteNumeroFactura();
}

    public void cargarComboResiduos() {
    comboVentaResiduo.removeAllItems();
    comboVentaResiduo.addItem("Seleccione un residuo...");

    ResiduoDAO dao = new ResiduoDAO();
    List<Residuos> lista = dao.listarResiduos();

    for (Residuos r : lista) {
        comboVentaResiduo.addItem(r.getID_resiudos() + " - " + r.getNom_residuo());
    }
}
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Fondo = new javax.swing.JPanel();
        BarraArriba = new javax.swing.JPanel();
        NombreVentanaResiduos = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JLabel();
        BarraAbajo = new javax.swing.JPanel();
        TituloFuncion1 = new javax.swing.JLabel();
        FacturaResiduos = new javax.swing.JLabel();
        DireccionResiduos = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        TituloFuncion2 = new javax.swing.JLabel();
        Residuo = new javax.swing.JLabel();
        PrecioUnitario = new javax.swing.JLabel();
        comboEmpresas = new javax.swing.JComboBox<>();
        Empresa = new javax.swing.JLabel();
        FechaResiduos = new javax.swing.JLabel();
        dateReciclaje = new com.toedter.calendar.JDateChooser();
        txtDireccion = new javax.swing.JTextField();
        txtNReciclaje = new javax.swing.JTextField();
        PanelNuevoResiduo = new javax.swing.JPanel();
        Nuevo1 = new javax.swing.JLabel();
        ImagenADD1 = new javax.swing.JLabel();
        PanelNuevaEmpresa = new javax.swing.JPanel();
        Nuevo2 = new javax.swing.JLabel();
        ImagenADD2 = new javax.swing.JLabel();
        PanelGuardar = new javax.swing.JPanel();
        Guardar = new javax.swing.JLabel();
        ImagenSAVE = new javax.swing.JLabel();
        PanelAgregar = new javax.swing.JPanel();
        Buscar = new javax.swing.JLabel();
        ImagenADD3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtTipoEmpresa = new javax.swing.JTextField();
        comboVentaResiduo = new javax.swing.JComboBox<>();
        txtCantidadVenta = new javax.swing.JTextField();
        txtPrecioUnitario = new javax.swing.JTextField();
        txtTotal = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        TotalPrecio = new javax.swing.JLabel();
        Kilos2 = new javax.swing.JLabel();

        Fondo.setBackground(new java.awt.Color(255, 255, 255));
        Fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BarraArriba.setBackground(new java.awt.Color(0, 0, 0));

        NombreVentanaResiduos.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        NombreVentanaResiduos.setForeground(new java.awt.Color(255, 255, 255));
        NombreVentanaResiduos.setText("GESTIÓN DE RESIDUOS Y RECICLAJE");

        btnRegresar.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        btnRegresar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegresar.setText("Regresar");
        btnRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegresarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout BarraArribaLayout = new javax.swing.GroupLayout(BarraArriba);
        BarraArriba.setLayout(BarraArribaLayout);
        BarraArribaLayout.setHorizontalGroup(
            BarraArribaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BarraArribaLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(NombreVentanaResiduos, javax.swing.GroupLayout.PREFERRED_SIZE, 616, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 529, Short.MAX_VALUE)
                .addComponent(btnRegresar)
                .addGap(43, 43, 43))
        );
        BarraArribaLayout.setVerticalGroup(
            BarraArribaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BarraArribaLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(BarraArribaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegresar)
                    .addComponent(NombreVentanaResiduos))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        Fondo.add(BarraArriba, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1320, 60));

        BarraAbajo.setBackground(new java.awt.Color(227, 153, 106));

        javax.swing.GroupLayout BarraAbajoLayout = new javax.swing.GroupLayout(BarraAbajo);
        BarraAbajo.setLayout(BarraAbajoLayout);
        BarraAbajoLayout.setHorizontalGroup(
            BarraAbajoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1320, Short.MAX_VALUE)
        );
        BarraAbajoLayout.setVerticalGroup(
            BarraAbajoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        Fondo.add(BarraAbajo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 630, 1320, 70));

        TituloFuncion1.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        TituloFuncion1.setForeground(new java.awt.Color(153, 153, 153));
        TituloFuncion1.setText("DATOS DE LA EMPRESA RECICLADORA Y VENTA");
        Fondo.add(TituloFuncion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        FacturaResiduos.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 13)); // NOI18N
        FacturaResiduos.setForeground(new java.awt.Color(153, 153, 153));
        FacturaResiduos.setText("N° Factura / Comprobante:");
        Fondo.add(FacturaResiduos, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        DireccionResiduos.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 13)); // NOI18N
        DireccionResiduos.setForeground(new java.awt.Color(153, 153, 153));
        DireccionResiduos.setText("Dirección Planta:");
        Fondo.add(DireccionResiduos, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/images (2).jpg"))); // NOI18N
        Fondo.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 70, -1, -1));

        TituloFuncion2.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        TituloFuncion2.setForeground(new java.awt.Color(153, 153, 153));
        TituloFuncion2.setText("REGISTRO DE RESIDUOS A ENTREGAR");
        Fondo.add(TituloFuncion2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));

        Residuo.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 13)); // NOI18N
        Residuo.setForeground(new java.awt.Color(153, 153, 153));
        Residuo.setText("Residuo / Tipo:");
        Fondo.add(Residuo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, -1, -1));

        PrecioUnitario.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 13)); // NOI18N
        PrecioUnitario.setForeground(new java.awt.Color(153, 153, 153));
        PrecioUnitario.setText("Precio Unitario:");
        Fondo.add(PrecioUnitario, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 280, -1, -1));

        comboEmpresas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                comboEmpresasMouseClicked(evt);
            }
        });
        comboEmpresas.addActionListener(this::comboEmpresasActionPerformed);
        Fondo.add(comboEmpresas, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 260, -1));

        Empresa.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 13)); // NOI18N
        Empresa.setForeground(new java.awt.Color(153, 153, 153));
        Empresa.setText("Empresa Recicladora:");
        Fondo.add(Empresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        FechaResiduos.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 13)); // NOI18N
        FechaResiduos.setForeground(new java.awt.Color(153, 153, 153));
        FechaResiduos.setText("Fecha de Transacción:");
        Fondo.add(FechaResiduos, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 120, -1, -1));
        Fondo.add(dateReciclaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 140, 200, -1));
        Fondo.add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 200, 200, -1));
        Fondo.add(txtNReciclaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 260, -1));

        PanelNuevoResiduo.setBackground(new java.awt.Color(255, 255, 255));
        PanelNuevoResiduo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(187, 187, 187)));
        PanelNuevoResiduo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PanelNuevoResiduo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PanelNuevoResiduoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PanelNuevoResiduoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PanelNuevoResiduoMouseExited(evt);
            }
        });

        Nuevo1.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        Nuevo1.setText("Nuevo Residuo");

        ImagenADD1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/add_22dp_000000_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N

        javax.swing.GroupLayout PanelNuevoResiduoLayout = new javax.swing.GroupLayout(PanelNuevoResiduo);
        PanelNuevoResiduo.setLayout(PanelNuevoResiduoLayout);
        PanelNuevoResiduoLayout.setHorizontalGroup(
            PanelNuevoResiduoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelNuevoResiduoLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(ImagenADD1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Nuevo1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelNuevoResiduoLayout.setVerticalGroup(
            PanelNuevoResiduoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelNuevoResiduoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelNuevoResiduoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ImagenADD1)
                    .addComponent(Nuevo1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Fondo.add(PanelNuevoResiduo, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 270, -1, -1));

        PanelNuevaEmpresa.setBackground(new java.awt.Color(255, 255, 255));
        PanelNuevaEmpresa.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(187, 187, 187)));
        PanelNuevaEmpresa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PanelNuevaEmpresa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PanelNuevaEmpresaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PanelNuevaEmpresaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PanelNuevaEmpresaMouseExited(evt);
            }
        });

        Nuevo2.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        Nuevo2.setText("Nueva Empresa");

        ImagenADD2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/add_22dp_000000_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N

        javax.swing.GroupLayout PanelNuevaEmpresaLayout = new javax.swing.GroupLayout(PanelNuevaEmpresa);
        PanelNuevaEmpresa.setLayout(PanelNuevaEmpresaLayout);
        PanelNuevaEmpresaLayout.setHorizontalGroup(
            PanelNuevaEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelNuevaEmpresaLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(ImagenADD2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Nuevo2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelNuevaEmpresaLayout.setVerticalGroup(
            PanelNuevaEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelNuevaEmpresaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelNuevaEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ImagenADD2)
                    .addComponent(Nuevo2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Fondo.add(PanelNuevaEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 190, -1, -1));

        PanelGuardar.setBackground(new java.awt.Color(242, 101, 34));
        PanelGuardar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(187, 187, 187)));
        PanelGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PanelGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PanelGuardarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PanelGuardarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PanelGuardarMouseExited(evt);
            }
        });

        Guardar.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        Guardar.setForeground(new java.awt.Color(255, 255, 255));
        Guardar.setText("Guardar");

        ImagenSAVE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/save_22dp_FFFFFF_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N

        javax.swing.GroupLayout PanelGuardarLayout = new javax.swing.GroupLayout(PanelGuardar);
        PanelGuardar.setLayout(PanelGuardarLayout);
        PanelGuardarLayout.setHorizontalGroup(
            PanelGuardarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelGuardarLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(ImagenSAVE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Guardar)
                .addContainerGap(36, Short.MAX_VALUE))
        );
        PanelGuardarLayout.setVerticalGroup(
            PanelGuardarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelGuardarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanelGuardarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Guardar)
                    .addComponent(ImagenSAVE))
                .addContainerGap())
        );

        Fondo.add(PanelGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 380, -1, -1));

        PanelAgregar.setBackground(new java.awt.Color(255, 255, 255));
        PanelAgregar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(187, 187, 187)));
        PanelAgregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PanelAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PanelAgregarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PanelAgregarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PanelAgregarMouseExited(evt);
            }
        });

        Buscar.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        Buscar.setText("Agregar");

        ImagenADD3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/add_22dp_000000_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N

        javax.swing.GroupLayout PanelAgregarLayout = new javax.swing.GroupLayout(PanelAgregar);
        PanelAgregar.setLayout(PanelAgregarLayout);
        PanelAgregarLayout.setHorizontalGroup(
            PanelAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelAgregarLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(ImagenADD3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Buscar)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        PanelAgregarLayout.setVerticalGroup(
            PanelAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAgregarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ImagenADD3)
                    .addComponent(Buscar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Fondo.add(PanelAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 290, -1, -1));

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setText("Tipo de Empresa");
        Fondo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 120, -1, -1));
        Fondo.add(txtTipoEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 140, 200, -1));

        comboVentaResiduo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboVentaResiduo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                comboVentaResiduoMouseClicked(evt);
            }
        });
        Fondo.add(comboVentaResiduo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 120, -1));
        Fondo.add(txtCantidadVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, 120, -1));
        Fondo.add(txtPrecioUnitario, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 300, 120, -1));
        Fondo.add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 340, 140, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID Residuo", "Nombre Residuo", "Cantidad", "Precio U.", "Subtotal"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        Fondo.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 430, 470, 190));

        TotalPrecio.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 13)); // NOI18N
        TotalPrecio.setForeground(new java.awt.Color(153, 153, 153));
        TotalPrecio.setText("Total:");
        Fondo.add(TotalPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 320, -1, -1));

        Kilos2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 13)); // NOI18N
        Kilos2.setForeground(new java.awt.Color(153, 153, 153));
        Kilos2.setText("Cantidad:");
        Fondo.add(Kilos2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegresarMouseClicked

    }//GEN-LAST:event_btnRegresarMouseClicked

    
    private void comboEmpresasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboEmpresasActionPerformed
        Object seleccionado = comboEmpresas.getSelectedItem();

        if (seleccionado instanceof Empresa_recicladora) {
            Empresa_recicladora emp = (Empresa_recicladora) seleccionado;

            txtTipoEmpresa.setText(emp.getDescTipoEmp());
            txtDireccion.setText(emp.getDireccionCompleta());
        } else {
            txtTipoEmpresa.setText("");
            txtDireccion.setText("");
        }
    }//GEN-LAST:event_comboEmpresasActionPerformed

    private void PanelNuevoResiduoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelNuevoResiduoMouseClicked
        NuevoResiduo panel = new NuevoResiduo();

        java.awt.Window parentWindow = javax.swing.SwingUtilities.getWindowAncestor(this);
        javax.swing.JDialog dialog;

        if (parentWindow instanceof java.awt.Frame) {
            dialog = new javax.swing.JDialog((java.awt.Frame) parentWindow);
        } else if (parentWindow instanceof java.awt.Dialog) {
            dialog = new javax.swing.JDialog((java.awt.Dialog) parentWindow);
        } else {
            dialog = new javax.swing.JDialog();
        }

        dialog.setUndecorated(true);
        dialog.add(panel);
        dialog.pack();

        java.awt.Point location = new java.awt.Point(0, PanelNuevoResiduo.getHeight());
        javax.swing.SwingUtilities.convertPointToScreen(location, PanelNuevoResiduo);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        int dialogWidth = dialog.getWidth();
        int dialogHeight = dialog.getHeight();

        if (location.x + dialogWidth > screenSize.width) {
            location.x = location.x + PanelNuevoResiduo.getWidth() - dialogWidth;
        }

        if (location.y + dialogHeight > screenSize.height) {
            java.awt.Point locationAbove = new java.awt.Point(0, -dialogHeight);
            javax.swing.SwingUtilities.convertPointToScreen(locationAbove, PanelNuevoResiduo);
            location.y = locationAbove.y;
        }

    dialog.addWindowFocusListener(new java.awt.event.WindowFocusListener() {
    @Override
    public void windowGainedFocus(java.awt.event.WindowEvent e) {}

    @Override
    public void windowLostFocus(java.awt.event.WindowEvent e) {
        java.awt.Window opposite = e.getOppositeWindow();
        
        if (opposite != null && opposite.getOwner() == dialog) {
            return; 
        }
        
        dialog.dispose();
    }
});

        dialog.setVisible(true);
    }//GEN-LAST:event_PanelNuevoResiduoMouseClicked

    private void PanelNuevoResiduoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelNuevoResiduoMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_PanelNuevoResiduoMouseEntered

    private void PanelNuevoResiduoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelNuevoResiduoMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_PanelNuevoResiduoMouseExited

    private void PanelNuevaEmpresaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelNuevaEmpresaMouseClicked
        // TODO add your handling code here:

    javax.swing.JTextField txtIDNuevaEmpresa = new javax.swing.JTextField(15);
    javax.swing.JTextField txtNombreNuevaEmpresa = new javax.swing.JTextField(15);
    javax.swing.JTextField txtTelefonoNuevaEmpresa = new javax.swing.JTextField(15);
    javax.swing.JTextField txtIDTipoNuevaEmpresa = new javax.swing.JTextField(15);
    javax.swing.JTextField txtDescripcionNuevaEmpresa = new javax.swing.JTextField(15);
    javax.swing.JTextField txtIDDireccionNuevaEmpresa = new javax.swing.JTextField(15);
    javax.swing.JTextField txtCiudadNuevaEmpresa = new javax.swing.JTextField(15);
    javax.swing.JTextField txtCallesNuevaEmpresa = new javax.swing.JTextField(15);

    txtIDNuevaEmpresa.setEnabled(false);
    txtIDTipoNuevaEmpresa.setEnabled(false);
    txtIDDireccionNuevaEmpresa.setEnabled(false);

    com.mycompany.proyecto_m2b.Controlador.RegistrarEmpresaRecicladoraDAO dao = new com.mycompany.proyecto_m2b.Controlador.RegistrarEmpresaRecicladoraDAO();
    txtIDNuevaEmpresa.setText(dao.generarSiguienteID("empresa_recicladora", "id_empresa_rec", "ER-"));
    txtIDTipoNuevaEmpresa.setText(dao.generarSiguienteID("tipo_empresa", "id_tipo_emp", "TER-"));
    txtIDDireccionNuevaEmpresa.setText(dao.generarSiguienteID("direccion_empresa_recicladora", "id_direccion_empresa_recicladora", "DER-"));

    txtTelefonoNuevaEmpresa.setText("Ingrese el telefono de la empresa");
    txtTelefonoNuevaEmpresa.setForeground(java.awt.Color.GRAY);
    txtNombreNuevaEmpresa.setText("Ingrese el nombre de la empresa");
    txtNombreNuevaEmpresa.setForeground(java.awt.Color.GRAY);
    txtDescripcionNuevaEmpresa.setText("Ingrese una descripcion");
    txtDescripcionNuevaEmpresa.setForeground(java.awt.Color.GRAY);
    txtCiudadNuevaEmpresa.setText("Ingrese la ciudad");
    txtCiudadNuevaEmpresa.setForeground(java.awt.Color.GRAY);
    txtCallesNuevaEmpresa.setText("Ingrese calles");
    txtCallesNuevaEmpresa.setForeground(java.awt.Color.GRAY);

    txtTelefonoNuevaEmpresa.addFocusListener(new java.awt.event.FocusAdapter() {
        public void focusGained(java.awt.event.FocusEvent evt) {
            if (txtTelefonoNuevaEmpresa.getText().equals("Ingrese el telefono de la empresa")) {
                txtTelefonoNuevaEmpresa.setText("");
                txtTelefonoNuevaEmpresa.setForeground(java.awt.Color.BLACK);
            }
        }
        public void focusLost(java.awt.event.FocusEvent evt) {
            if (txtTelefonoNuevaEmpresa.getText().trim().isEmpty()) {
                txtTelefonoNuevaEmpresa.setText("Ingrese el telefono de la empresa");
                txtTelefonoNuevaEmpresa.setForeground(java.awt.Color.GRAY);
            }
        }
    });

    txtNombreNuevaEmpresa.addFocusListener(new java.awt.event.FocusAdapter() {
        public void focusGained(java.awt.event.FocusEvent evt) {
            if (txtNombreNuevaEmpresa.getText().equals("Ingrese el nombre de la empresa")) {
                txtNombreNuevaEmpresa.setText("");
                txtNombreNuevaEmpresa.setForeground(java.awt.Color.BLACK);
            }
        }
        public void focusLost(java.awt.event.FocusEvent evt) {
            if (txtNombreNuevaEmpresa.getText().trim().isEmpty()) {
                txtNombreNuevaEmpresa.setText("Ingrese el nombre de la empresa");
                txtNombreNuevaEmpresa.setForeground(java.awt.Color.GRAY);
            }
        }
    });

    txtDescripcionNuevaEmpresa.addFocusListener(new java.awt.event.FocusAdapter() {
        public void focusGained(java.awt.event.FocusEvent evt) {
            if (txtDescripcionNuevaEmpresa.getText().equals("Ingrese una descripcion")) {
                txtDescripcionNuevaEmpresa.setText("");
                txtDescripcionNuevaEmpresa.setForeground(java.awt.Color.BLACK);
            }
        }
        public void focusLost(java.awt.event.FocusEvent evt) {
            if (txtDescripcionNuevaEmpresa.getText().trim().isEmpty()) {
                txtDescripcionNuevaEmpresa.setText("Ingrese una descripcion");
                txtDescripcionNuevaEmpresa.setForeground(java.awt.Color.GRAY);
            }
        }
    });

    txtCiudadNuevaEmpresa.addFocusListener(new java.awt.event.FocusAdapter() {
        public void focusGained(java.awt.event.FocusEvent evt) {
            if (txtCiudadNuevaEmpresa.getText().equals("Ingrese la ciudad")) {
                txtCiudadNuevaEmpresa.setText("");
                txtCiudadNuevaEmpresa.setForeground(java.awt.Color.BLACK);
            }
        }
        public void focusLost(java.awt.event.FocusEvent evt) {
            if (txtCiudadNuevaEmpresa.getText().trim().isEmpty()) {
                txtCiudadNuevaEmpresa.setText("Ingrese la ciudad");
                txtCiudadNuevaEmpresa.setForeground(java.awt.Color.GRAY);
            }
        }
    });

    txtCallesNuevaEmpresa.addFocusListener(new java.awt.event.FocusAdapter() {
        public void focusGained(java.awt.event.FocusEvent evt) {
            if (txtCallesNuevaEmpresa.getText().equals("Ingrese calles")) {
                txtCallesNuevaEmpresa.setText("");
                txtCallesNuevaEmpresa.setForeground(java.awt.Color.BLACK);
            }
        }
        public void focusLost(java.awt.event.FocusEvent evt) {
            if (txtCallesNuevaEmpresa.getText().trim().isEmpty()) {
                txtCallesNuevaEmpresa.setText("Ingrese calles");
                txtCallesNuevaEmpresa.setForeground(java.awt.Color.GRAY);
            }
        }
    });

    javax.swing.JPanel panel = new javax.swing.JPanel(new java.awt.GridBagLayout());
    panel.setBackground(java.awt.Color.WHITE);
    panel.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 15, 20));

    java.awt.GridBagConstraints gbc = new java.awt.GridBagConstraints();
    gbc.insets = new java.awt.Insets(6, 6, 6, 6);
    gbc.fill = java.awt.GridBagConstraints.HORIZONTAL;

    gbc.gridx = 0; gbc.gridy = 0; gbc.gridwidth = 2;
    javax.swing.JLabel lblTituloDatos = new javax.swing.JLabel("Datos de la Empresa");
    lblTituloDatos.setFont(new java.awt.Font("Arial Black", 0, 14));
    lblTituloDatos.setForeground(new java.awt.Color(153, 153, 153));
    panel.add(lblTituloDatos, gbc);

    gbc.gridwidth = 1;
    gbc.gridx = 0; gbc.gridy = 1; gbc.anchor = java.awt.GridBagConstraints.WEST;
    javax.swing.JLabel lbl1 = new javax.swing.JLabel("ID_Nueva Empresa Recicladora:");
    lbl1.setForeground(new java.awt.Color(153, 153, 153));
    panel.add(lbl1, gbc);

    gbc.gridx = 1; gbc.weightx = 1.0;
    javax.swing.JLabel lbl4 = new javax.swing.JLabel("Nombre Empresa:");
    lbl4.setForeground(new java.awt.Color(153, 153, 153));
    panel.add(lbl4, gbc);

    gbc.gridx = 0; gbc.gridy = 2; gbc.weightx = 0.0;
    panel.add(txtIDNuevaEmpresa, gbc);

    gbc.gridx = 1; gbc.weightx = 1.0;
    panel.add(txtNombreNuevaEmpresa, gbc);

    gbc.gridx = 0; gbc.gridy = 3; gbc.weightx = 0.0;
    javax.swing.JLabel lbl5 = new javax.swing.JLabel("Telefono de Contacto:");
    lbl5.setForeground(new java.awt.Color(153, 153, 153));
    panel.add(lbl5, gbc);

    gbc.gridx = 1; gbc.weightx = 1.0;
    javax.swing.JLabel lbl6 = new javax.swing.JLabel("ID tipo de Empresa:");
    lbl6.setForeground(new java.awt.Color(153, 153, 153));
    panel.add(lbl6, gbc);

    gbc.gridx = 0; gbc.gridy = 4; gbc.weightx = 0.0;
    panel.add(txtTelefonoNuevaEmpresa, gbc);

    gbc.gridx = 1; gbc.weightx = 1.0;
    panel.add(txtIDTipoNuevaEmpresa, gbc);

    gbc.gridx = 0; gbc.gridy = 5; gbc.weightx = 0.0;
    javax.swing.JLabel lbl12 = new javax.swing.JLabel("Descripcion:");
    lbl12.setForeground(new java.awt.Color(153, 153, 153));
    panel.add(lbl12, gbc);

    gbc.gridx = 1; gbc.weightx = 1.0;
    panel.add(txtDescripcionNuevaEmpresa, gbc);

    gbc.gridx = 0; gbc.gridy = 6; gbc.gridwidth = 2;
    javax.swing.JLabel lblTituloDir = new javax.swing.JLabel("Direccion");
    lblTituloDir.setFont(new java.awt.Font("Arial Black", 0, 14));
    lblTituloDir.setForeground(new java.awt.Color(153, 153, 153));
    panel.add(lblTituloDir, gbc);

    gbc.gridwidth = 1;
    gbc.gridx = 0; gbc.gridy = 7; 
    javax.swing.JLabel lbl8 = new javax.swing.JLabel("ID_Direccion:");
    lbl8.setForeground(new java.awt.Color(153, 153, 153));
    panel.add(lbl8, gbc);

    gbc.gridx = 1; gbc.weightx = 1.0;
    javax.swing.JLabel lbl9 = new javax.swing.JLabel("Ciudad:");
    lbl9.setForeground(new java.awt.Color(153, 153, 153));
    panel.add(lbl9, gbc);

    gbc.gridx = 0; gbc.gridy = 8; gbc.weightx = 0.0;
    panel.add(txtIDDireccionNuevaEmpresa, gbc);

    gbc.gridx = 1; gbc.weightx = 1.0;
    panel.add(txtCiudadNuevaEmpresa, gbc);

    gbc.gridx = 0; gbc.gridy = 9; gbc.weightx = 0.0;
    javax.swing.JLabel lbl10 = new javax.swing.JLabel("Calles:");
    lbl10.setForeground(new java.awt.Color(153, 153, 153));
    panel.add(lbl10, gbc);

    gbc.gridx = 1; gbc.weightx = 1.0;
    panel.add(txtCallesNuevaEmpresa, gbc);

    javax.swing.JButton btnGuardar = new javax.swing.JButton("Guardar");
    javax.swing.JButton btnCancelar = new javax.swing.JButton("Cancelar");

    btnGuardar.setBackground(new java.awt.Color(242, 101, 34));
    btnGuardar.setForeground(java.awt.Color.WHITE);
    btnGuardar.setFocusPainted(false);

    final int[] opcion = {javax.swing.JOptionPane.CANCEL_OPTION};

    javax.swing.JDialog dialogo;
    java.awt.Window ventanaPrincipal = javax.swing.SwingUtilities.getWindowAncestor(this);

    if (ventanaPrincipal instanceof java.awt.Frame) {
        dialogo = new javax.swing.JDialog((java.awt.Frame) ventanaPrincipal, "Registrar Nueva Empresa Recicladora", true);
    } else {
        dialogo = new javax.swing.JDialog((java.awt.Dialog) ventanaPrincipal, "Registrar Nueva Empresa Recicladora", true);
    }

    dialogo.setUndecorated(true);
    dialogo.getRootPane().setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(180, 180, 180), 1));

    btnGuardar.addActionListener(e -> {
        opcion[0] = javax.swing.JOptionPane.OK_OPTION;
        dialogo.dispose();
    });

    btnCancelar.addActionListener(e -> {
        opcion[0] = javax.swing.JOptionPane.CANCEL_OPTION;
        dialogo.dispose();
    });

    javax.swing.JPanel panelBotones = new javax.swing.JPanel();
    panelBotones.setBackground(java.awt.Color.WHITE);
    panelBotones.add(btnCancelar);
    panelBotones.add(btnGuardar);

    dialogo.setLayout(new java.awt.BorderLayout());
    dialogo.add(panel, java.awt.BorderLayout.CENTER);
    dialogo.add(panelBotones, java.awt.BorderLayout.SOUTH);
    dialogo.pack();
    dialogo.setLocationRelativeTo(this);

    dialogo.addWindowListener(new java.awt.event.WindowAdapter() {
        @Override
        public void windowOpened(java.awt.event.WindowEvent e) {
            txtNombreNuevaEmpresa.requestFocusInWindow();
        }
    });

    dialogo.setVisible(true);

    if (opcion[0] == javax.swing.JOptionPane.OK_OPTION) {
        String idEmp = txtIDNuevaEmpresa.getText().trim();
        String nomEmp = txtNombreNuevaEmpresa.getText().trim();
        String telf = txtTelefonoNuevaEmpresa.getText().trim();
        String idTipo = txtIDTipoNuevaEmpresa.getText().trim();                       
        String descTipo = txtDescripcionNuevaEmpresa.getText().trim();            
        String idDir = txtIDDireccionNuevaEmpresa.getText().trim();                           
        String ciudad = txtCiudadNuevaEmpresa.getText().trim();
        String calles = txtCallesNuevaEmpresa.getText().trim();

        if (idEmp.isEmpty() || nomEmp.isEmpty() || nomEmp.equals("Ingrese el nombre de la empresa") || 
            idDir.isEmpty() || idTipo.isEmpty() || descTipo.isEmpty() || descTipo.equals("Ingrese una descripcion")) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                    "Por favor complete todos los campos obligatorios.", 
                    "Campos incompletos", 
                    javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        boolean guardado = dao.guardarEmpresaCompleta(idDir, ciudad, calles, idTipo, descTipo, idEmp, nomEmp, telf);

        if (guardado) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                    "Empresa recicladora registrada exitosamente en la base de datos", 
                    "Exito", 
                    javax.swing.JOptionPane.INFORMATION_MESSAGE);
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, 
                    "Error al guardar la empresa en la base de datos", 
                    "Error", 
                    javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }
    }//GEN-LAST:event_PanelNuevaEmpresaMouseClicked

    private void PanelNuevaEmpresaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelNuevaEmpresaMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_PanelNuevaEmpresaMouseEntered

    private void PanelNuevaEmpresaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelNuevaEmpresaMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_PanelNuevaEmpresaMouseExited

    private void PanelGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelGuardarMouseClicked
        // TODO add your handling code here:
    Object empSel = comboEmpresas.getSelectedItem();
    if (!(empSel instanceof Empresa_recicladora)) {
        JOptionPane.showMessageDialog(this, "Debe seleccionar una empresa recicladora válida.", "Advertencia", JOptionPane.WARNING_MESSAGE);
        return;
    }
    Empresa_recicladora empresa = (Empresa_recicladora) empSel;
    String idEmpresa = empresa.getID_empresa_rec();
    javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) jTable1.getModel();

    java.util.List<DetalleVenta> detalles = new java.util.ArrayList<>();
    String idEncab = txtNReciclaje.getText().trim();

    for (int i = 0; i < model.getRowCount(); i++) {
        Object objIdRes = model.getValueAt(i, 0);
        
        if (objIdRes != null && !objIdRes.toString().trim().isEmpty()) {
            String timeStr = String.valueOf(System.currentTimeMillis());
            String idDet = "DET-" + timeStr.substring(timeStr.length() - 7) + "-" + i;
            
            String idRes = objIdRes.toString().trim();
            
            int cant = (int) Double.parseDouble(model.getValueAt(i, 2).toString().replace(",", "."));
            double subtotal = Double.parseDouble(model.getValueAt(i, 4).toString().replace(",", "."));

            detalles.add(new DetalleVenta(idDet, idEncab, idRes, cant, subtotal));
        }
    }

    if (detalles.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Debe agregar al menos un residuo a la tabla antes de guardar.", "Tabla Vacía", JOptionPane.WARNING_MESSAGE);
        return;
    }

    java.sql.Date fecha = new java.sql.Date(System.currentTimeMillis());
    double total = Double.parseDouble(txtTotal.getText().trim().replace(",", "."));
    EncabezadoVenta encab = new EncabezadoVenta(idEncab, idEmpresa, fecha, total);

    VentaDAO dao = new VentaDAO();
    if (dao.registrarVenta(encab, detalles)) {
        JOptionPane.showMessageDialog(this, "¡Venta y detalles registrados con éxito!", "Éxito", JOptionPane.INFORMATION_MESSAGE);
        
        model.setRowCount(0);
        txtTotal.setText("0.00");
        txtNReciclaje.setText(generarNumeroFactura());
        comboEmpresas.setSelectedIndex(0);
    } else {
        JOptionPane.showMessageDialog(this, "Error al guardar la transacción en la base de datos.", "Error SQL", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_PanelGuardarMouseClicked

    private void PanelGuardarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelGuardarMouseEntered
        // TODO add your handling code here:
        PanelGuardar.setBackground(new java.awt.Color(227, 95, 32));
        Guardar.setForeground(new java.awt.Color(217, 217, 192));
    }//GEN-LAST:event_PanelGuardarMouseEntered

    private void PanelGuardarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelGuardarMouseExited
        // TODO add your handling code here:
        PanelGuardar.setBackground(new java.awt.Color(242,101,34));
        Guardar.setForeground(java.awt.Color.white);
    }//GEN-LAST:event_PanelGuardarMouseExited

    private void PanelAgregarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelAgregarMouseEntered
        // TODO add your handling code here:
        PanelAgregar.setBackground(new java.awt.Color(219,219,219));
        Buscar.setForeground(new java.awt.Color(66, 66, 66));
    }//GEN-LAST:event_PanelAgregarMouseEntered

    private void PanelAgregarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelAgregarMouseExited
        // TODO add your handling code here:
        PanelAgregar.setBackground(java.awt.Color.white);
        Buscar.setForeground(java.awt.Color.black);
    }//GEN-LAST:event_PanelAgregarMouseExited

    private void PanelAgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelAgregarMouseClicked
       if (comboVentaResiduo.getSelectedIndex() <= 0) {
        JOptionPane.showMessageDialog(this, "Seleccione un residuo válido.", "Advertencia", JOptionPane.WARNING_MESSAGE);
        return;
    }

    if (txtCantidadVenta.getText().trim().isEmpty() || txtPrecioUnitario.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Por favor ingrese la cantidad y el precio unitario.", "Campos vacíos", JOptionPane.WARNING_MESSAGE);
        return;
    }

    try {
        String itemSel = comboVentaResiduo.getSelectedItem().toString(); 
        String[] partes = itemSel.split(" - ");
        String idResiduo = partes[0].trim();
        String nombreResiduo = partes[1].trim();

        double cantidadNueva = Double.parseDouble(txtCantidadVenta.getText().trim().replace(",", "."));
        double precioUnitario = Double.parseDouble(txtPrecioUnitario.getText().trim().replace(",", "."));

        if (cantidadNueva <= 0) {
            JOptionPane.showMessageDialog(this, "La cantidad debe ser mayor a 0.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }

        ResiduoDAO dao = new ResiduoDAO();
        double stockDisponible = dao.obtenerStockActual(idResiduo); 

        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) jTable1.getModel();
        boolean encontrado = false;

        for (int i = 0; i < model.getRowCount(); i++) {
            Object objId = model.getValueAt(i, 0);

            if (objId != null && objId.toString().trim().equals(idResiduo)) {
                Object objCant = model.getValueAt(i, 2);
                double cantidadExistente = Double.parseDouble(objCant.toString().trim().replace(",", "."));
                double cantidadTotal = cantidadExistente + cantidadNueva;

                if (cantidadTotal > stockDisponible) {
                    JOptionPane.showMessageDialog(this, 
                        "Stock insuficiente. Stock actual: " + stockDisponible + 
                        " | Ya tiene " + cantidadExistente + " en la tabla.", 
                        "Stock Excedido", JOptionPane.WARNING_MESSAGE);
                    return;
                }

                double nuevoSubtotal = cantidadTotal * precioUnitario;

                model.setValueAt(cantidadTotal, i, 2);
                model.setValueAt(precioUnitario, i, 3);
                model.setValueAt(nuevoSubtotal, i, 4);

                encontrado = true;
                break;
            }
        }

        if (!encontrado) {
            if (cantidadNueva > stockDisponible) {
                JOptionPane.showMessageDialog(this, 
                    "Stock insuficiente. Solo quedan " + stockDisponible + " unidades disponibles.", 
                    "Stock Excedido", JOptionPane.WARNING_MESSAGE);
                return;
            }

            double subtotal = cantidadNueva * precioUnitario;
            model.addRow(new Object[]{idResiduo, nombreResiduo, cantidadNueva, precioUnitario, subtotal});
        }

        calcularTotalVenta();

        txtCantidadVenta.setText("");
        txtPrecioUnitario.setText("");
        comboVentaResiduo.setSelectedIndex(0);

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Ingrese valores numéricos válidos en Cantidad y Precio.", "Error de formato", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_PanelAgregarMouseClicked

    private void comboEmpresasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comboEmpresasMouseClicked
        // TODO add your handling code here:
        cargarEmpresasEnCombo();
    }//GEN-LAST:event_comboEmpresasMouseClicked

    private void comboVentaResiduoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comboVentaResiduoMouseClicked
        // TODO add your handling code here:
        cargarComboResiduos();
    }//GEN-LAST:event_comboVentaResiduoMouseClicked
    
    public void calcularTotalVenta() {
    javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) jTable1.getModel();
    double totalAcumulado = 0.0;

    for (int i = 0; i < model.getRowCount(); i++) {
        Object valorSubtotal = model.getValueAt(i, 4); 
        
        if (valorSubtotal != null && !valorSubtotal.toString().trim().isEmpty()) {
            try {
                totalAcumulado += Double.parseDouble(valorSubtotal.toString().trim().replace(",", "."));
            } catch (NumberFormatException e) {
                System.err.println("Error al parsear subtotal en la fila " + i + ": " + e.getMessage());
            }
        }
    }

    txtTotal.setText(String.format(java.util.Locale.US, "%.2f", totalAcumulado));
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BarraAbajo;
    private javax.swing.JPanel BarraArriba;
    private javax.swing.JLabel Buscar;
    private javax.swing.JLabel DireccionResiduos;
    private javax.swing.JLabel Empresa;
    private javax.swing.JLabel FacturaResiduos;
    private javax.swing.JLabel FechaResiduos;
    private javax.swing.JPanel Fondo;
    private javax.swing.JLabel Guardar;
    private javax.swing.JLabel ImagenADD1;
    private javax.swing.JLabel ImagenADD2;
    private javax.swing.JLabel ImagenADD3;
    private javax.swing.JLabel ImagenSAVE;
    private javax.swing.JLabel Kilos2;
    private javax.swing.JLabel NombreVentanaResiduos;
    private javax.swing.JLabel Nuevo1;
    private javax.swing.JLabel Nuevo2;
    private javax.swing.JPanel PanelAgregar;
    private javax.swing.JPanel PanelGuardar;
    private javax.swing.JPanel PanelNuevaEmpresa;
    private javax.swing.JPanel PanelNuevoResiduo;
    private javax.swing.JLabel PrecioUnitario;
    private javax.swing.JLabel Residuo;
    private javax.swing.JLabel TituloFuncion1;
    private javax.swing.JLabel TituloFuncion2;
    private javax.swing.JLabel TotalPrecio;
    private javax.swing.JLabel btnRegresar;
    private javax.swing.JComboBox<Object> comboEmpresas;
    private javax.swing.JComboBox<String> comboVentaResiduo;
    private com.toedter.calendar.JDateChooser dateReciclaje;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtCantidadVenta;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtNReciclaje;
    private javax.swing.JTextField txtPrecioUnitario;
    private javax.swing.JTextField txtTipoEmpresa;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
