/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyecto_m2b.Vista;

/**
 *
 * @author jose
 */
public class Proveedores extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Proveedores.class.getName());

    /**
     * Creates new form Proveedores
     */
    public Proveedores() {
        initComponents();
        
    txtCantidad.setText("Ingrese la cantidad a solicitar");
    txtCantidad.setForeground(java.awt.Color.GRAY);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Fondo = new javax.swing.JPanel();
        BarraArriba = new javax.swing.JPanel();
        NombreVentanaProveedores = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JLabel();
        BarraAbajo = new javax.swing.JPanel();
        TituloFuncion1 = new javax.swing.JLabel();
        Proveedor = new javax.swing.JLabel();
        Tipo = new javax.swing.JLabel();
        Factura = new javax.swing.JLabel();
        Fecha = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        comboProveedores = new javax.swing.JComboBox<>();
        TituloFuncion2 = new javax.swing.JLabel();
        Repuesto = new javax.swing.JLabel();
        Cantidad = new javax.swing.JLabel();
        Precio = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        btnNuevoProvee = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnVP = new javax.swing.JButton();
        comboRepuestos = new javax.swing.JComboBox<>();
        txtFactura = new javax.swing.JTextField();
        dateProveedores = new com.toedter.calendar.JDateChooser();
        txtPrecio = new javax.swing.JTextField();
        comboTipoProvee = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        Fondo.setBackground(new java.awt.Color(255, 255, 255));
        Fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BarraArriba.setBackground(new java.awt.Color(0, 0, 0));

        NombreVentanaProveedores.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        NombreVentanaProveedores.setForeground(new java.awt.Color(255, 255, 255));
        NombreVentanaProveedores.setText("GESTIÓN DE PROVEEDORES Y COMPRA DE REPUESTOS");

        btnRegresar.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        btnRegresar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegresar.setText("Regresar");
        btnRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegresarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout BarraArribaLayout = new javax.swing.GroupLayout(BarraArriba);
        BarraArriba.setLayout(BarraArribaLayout);
        BarraArribaLayout.setHorizontalGroup(
            BarraArribaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BarraArribaLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(NombreVentanaProveedores, javax.swing.GroupLayout.PREFERRED_SIZE, 616, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 417, Short.MAX_VALUE)
                .addComponent(btnRegresar)
                .addGap(43, 43, 43))
        );
        BarraArribaLayout.setVerticalGroup(
            BarraArribaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BarraArribaLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(BarraArribaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegresar)
                    .addComponent(NombreVentanaProveedores))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        Fondo.add(BarraArriba, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1210, 60));

        BarraAbajo.setBackground(new java.awt.Color(227, 153, 106));

        javax.swing.GroupLayout BarraAbajoLayout = new javax.swing.GroupLayout(BarraAbajo);
        BarraAbajo.setLayout(BarraAbajoLayout);
        BarraAbajoLayout.setHorizontalGroup(
            BarraAbajoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1210, Short.MAX_VALUE)
        );
        BarraAbajoLayout.setVerticalGroup(
            BarraAbajoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        Fondo.add(BarraAbajo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 630, 1210, 70));

        TituloFuncion1.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        TituloFuncion1.setForeground(new java.awt.Color(153, 153, 153));
        TituloFuncion1.setText("ENCABEZADO DEL ENVÍO / COMPRA");
        Fondo.add(TituloFuncion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        Proveedor.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 13)); // NOI18N
        Proveedor.setForeground(new java.awt.Color(153, 153, 153));
        Proveedor.setText("Proveedor (RUC / Nombre)::");
        Fondo.add(Proveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        Tipo.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 13)); // NOI18N
        Tipo.setForeground(new java.awt.Color(153, 153, 153));
        Tipo.setText("Tipo de Proveedor:");
        Fondo.add(Tipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        Factura.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 13)); // NOI18N
        Factura.setForeground(new java.awt.Color(153, 153, 153));
        Factura.setText("N° Factura / Referencia:");
        Fondo.add(Factura, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, -1, -1));

        Fecha.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 13)); // NOI18N
        Fecha.setForeground(new java.awt.Color(153, 153, 153));
        Fecha.setText("Fecha de Envío:");
        Fondo.add(Fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 120, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/images (2).jpg"))); // NOI18N
        Fondo.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 70, -1, -1));

        comboProveedores.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione un proveedor", "Item 2", "Item 3", "Item 4" }));
        Fondo.add(comboProveedores, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 240, -1));

        TituloFuncion2.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        TituloFuncion2.setForeground(new java.awt.Color(153, 153, 153));
        TituloFuncion2.setText("DETALLE DE REPUESTOS SOLICITADOS");
        Fondo.add(TituloFuncion2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, -1));

        Repuesto.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 13)); // NOI18N
        Repuesto.setForeground(new java.awt.Color(153, 153, 153));
        Repuesto.setText("Repuesto:");
        Fondo.add(Repuesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, -1));

        Cantidad.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 13)); // NOI18N
        Cantidad.setForeground(new java.awt.Color(153, 153, 153));
        Cantidad.setText("Cantidad:");
        Fondo.add(Cantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 290, -1, -1));

        Precio.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 13)); // NOI18N
        Precio.setForeground(new java.awt.Color(153, 153, 153));
        Precio.setText("Precio Unitario:");
        Fondo.add(Precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 290, -1, -1));

        txtCantidad.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCantidadFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCantidadFocusLost(evt);
            }
        });
        Fondo.add(txtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 310, 270, -1));

        btnNuevoProvee.setText("Agregar Nuevo Proveedor");
        btnNuevoProvee.addActionListener(this::btnNuevoProveeActionPerformed);
        Fondo.add(btnNuevoProvee, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 120, 190, 70));

        btnGuardar.setText("Guardar");
        Fondo.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 380, 140, 70));

        btnModificar.setText("Modificar");
        Fondo.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 380, 140, 70));

        btnVP.setText("Ver Proveedores Registrados");
        btnVP.addActionListener(this::btnVPActionPerformed);
        Fondo.add(btnVP, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 380, 220, 70));

        comboRepuestos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione un tipo de proveedor", "Item 2", "Item 3", "Item 4" }));
        Fondo.add(comboRepuestos, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 240, -1));
        Fondo.add(txtFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 200, 200, -1));
        Fondo.add(dateProveedores, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 140, 200, -1));

        txtPrecio.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPrecioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPrecioFocusLost(evt);
            }
        });
        Fondo.add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 310, 270, -1));

        comboTipoProvee.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione un tipo de proveedor", "Item 2", "Item 3", "Item 4" }));
        Fondo.add(comboTipoProvee, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 240, -1));

        jButton1.setText("+  Agregar Item");
        Fondo.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 280, 190, 70));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegresarMouseClicked
        // TODO add your handling code here:
        Menu m = new Menu();
        m.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresarMouseClicked

    private void txtCantidadFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCantidadFocusGained
        if (txtCantidad.getText().equals("Ingrese la cantidad a solicitar")) {
            txtCantidad.setText("");
            txtCantidad.setForeground(java.awt.Color.BLACK);
        }
    }//GEN-LAST:event_txtCantidadFocusGained

    private void txtCantidadFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCantidadFocusLost
        if (txtCantidad.getText().trim().isEmpty()) {
            txtCantidad.setText("Ingrese la cantidad a solicitar");
            txtCantidad.setForeground(java.awt.Color.GRAY);
        }
    }//GEN-LAST:event_txtCantidadFocusLost

    private void btnNuevoProveeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoProveeActionPerformed
        NuevoProveedor mp = new NuevoProveedor();
        javax.swing.JDialog ventana = new javax.swing.JDialog(this, "", true);
        ventana.add(mp);
        ventana.pack();
        ventana.setLocationRelativeTo(this);
        ventana.setVisible(true);
    }//GEN-LAST:event_btnNuevoProveeActionPerformed

    private void btnVPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVPActionPerformed
        // TODO add your handling code here:
        ProveedoresRegistrados mp = new ProveedoresRegistrados();
        javax.swing.JDialog ventana = new javax.swing.JDialog(this, "", true);
        ventana.add(mp);
        ventana.pack();
        ventana.setLocationRelativeTo(this);
        ventana.setVisible(true);
    }//GEN-LAST:event_btnVPActionPerformed

    private void txtPrecioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPrecioFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioFocusGained

    private void txtPrecioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPrecioFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Proveedores().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BarraAbajo;
    private javax.swing.JPanel BarraArriba;
    private javax.swing.JLabel Cantidad;
    private javax.swing.JLabel Factura;
    private javax.swing.JLabel Fecha;
    private javax.swing.JPanel Fondo;
    private javax.swing.JLabel NombreVentanaProveedores;
    private javax.swing.JLabel Precio;
    private javax.swing.JLabel Proveedor;
    private javax.swing.JLabel Repuesto;
    private javax.swing.JLabel Tipo;
    private javax.swing.JLabel TituloFuncion1;
    private javax.swing.JLabel TituloFuncion2;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnNuevoProvee;
    private javax.swing.JLabel btnRegresar;
    private javax.swing.JButton btnVP;
    private javax.swing.JComboBox<String> comboProveedores;
    private javax.swing.JComboBox<String> comboRepuestos;
    private javax.swing.JComboBox<String> comboTipoProvee;
    private com.toedter.calendar.JDateChooser dateProveedores;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtFactura;
    private javax.swing.JTextField txtPrecio;
    // End of variables declaration//GEN-END:variables
}
