/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyecto_m2b.Vista;

/**
 *
 * @author jose
 */
public class Residuos extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Residuos.class.getName());

    /**
     * Creates new form Residuos
     */
    public Residuos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Fondo = new javax.swing.JPanel();
        BarraArriba = new javax.swing.JPanel();
        NombreVentanaResiduos = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JLabel();
        BarraAbajo = new javax.swing.JPanel();
        TituloFuncion1 = new javax.swing.JLabel();
        FacturaResiduos = new javax.swing.JLabel();
        DireccionResiduos = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        TituloFuncion2 = new javax.swing.JLabel();
        Residuo = new javax.swing.JLabel();
        Kilos = new javax.swing.JLabel();
        PrecioResiduos = new javax.swing.JLabel();
        btnNER = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        comboEmpresas = new javax.swing.JComboBox<>();
        Empresa = new javax.swing.JLabel();
        FechaResiduos = new javax.swing.JLabel();
        dateReciclaje = new com.toedter.calendar.JDateChooser();
        btnAgregar = new javax.swing.JButton();
        btnNR = new javax.swing.JButton();
        txtDireccion = new javax.swing.JTextField();
        txtNReciclaje = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        comboResiduos = new javax.swing.JComboBox<>();
        txtKilos = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        Fondo.setBackground(new java.awt.Color(255, 255, 255));
        Fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BarraArriba.setBackground(new java.awt.Color(0, 0, 0));

        NombreVentanaResiduos.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        NombreVentanaResiduos.setForeground(new java.awt.Color(255, 255, 255));
        NombreVentanaResiduos.setText("GESTIÓN DE RESIDUOS Y RECICLAJE");

        btnRegresar.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        btnRegresar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegresar.setText("Regresar");
        btnRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegresarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout BarraArribaLayout = new javax.swing.GroupLayout(BarraArriba);
        BarraArriba.setLayout(BarraArribaLayout);
        BarraArribaLayout.setHorizontalGroup(
            BarraArribaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BarraArribaLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(NombreVentanaResiduos, javax.swing.GroupLayout.PREFERRED_SIZE, 616, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 417, Short.MAX_VALUE)
                .addComponent(btnRegresar)
                .addGap(43, 43, 43))
        );
        BarraArribaLayout.setVerticalGroup(
            BarraArribaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BarraArribaLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(BarraArribaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegresar)
                    .addComponent(NombreVentanaResiduos))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        Fondo.add(BarraArriba, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1210, 60));

        BarraAbajo.setBackground(new java.awt.Color(227, 153, 106));

        javax.swing.GroupLayout BarraAbajoLayout = new javax.swing.GroupLayout(BarraAbajo);
        BarraAbajo.setLayout(BarraAbajoLayout);
        BarraAbajoLayout.setHorizontalGroup(
            BarraAbajoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1210, Short.MAX_VALUE)
        );
        BarraAbajoLayout.setVerticalGroup(
            BarraAbajoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        Fondo.add(BarraAbajo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 630, 1210, 70));

        TituloFuncion1.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        TituloFuncion1.setForeground(new java.awt.Color(153, 153, 153));
        TituloFuncion1.setText("DATOS DE LA EMPRESA RECICLADORA Y VENTA");
        Fondo.add(TituloFuncion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        FacturaResiduos.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 13)); // NOI18N
        FacturaResiduos.setForeground(new java.awt.Color(153, 153, 153));
        FacturaResiduos.setText("N° Factura / Comprobante:");
        Fondo.add(FacturaResiduos, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        DireccionResiduos.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 13)); // NOI18N
        DireccionResiduos.setForeground(new java.awt.Color(153, 153, 153));
        DireccionResiduos.setText("Dirección Planta:");
        Fondo.add(DireccionResiduos, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/images (2).jpg"))); // NOI18N
        Fondo.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 70, -1, -1));

        TituloFuncion2.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        TituloFuncion2.setForeground(new java.awt.Color(153, 153, 153));
        TituloFuncion2.setText("REGISTRO DE RESIDUOS A ENTREGAR");
        Fondo.add(TituloFuncion2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));

        Residuo.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 13)); // NOI18N
        Residuo.setForeground(new java.awt.Color(153, 153, 153));
        Residuo.setText("Residuo / Tipo:");
        Fondo.add(Residuo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, -1, -1));

        Kilos.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 13)); // NOI18N
        Kilos.setForeground(new java.awt.Color(153, 153, 153));
        Kilos.setText("Cantidad (Kg/L):");
        Fondo.add(Kilos, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 280, -1, -1));

        PrecioResiduos.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 13)); // NOI18N
        PrecioResiduos.setForeground(new java.awt.Color(153, 153, 153));
        PrecioResiduos.setText("Precio Unitario:");
        Fondo.add(PrecioResiduos, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 280, -1, -1));

        btnNER.setText("Agregar Empresa Reciladora");
        btnNER.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNERMouseClicked(evt);
            }
        });
        btnNER.addActionListener(this::btnNERActionPerformed);
        Fondo.add(btnNER, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 130, 200, 70));

        btnGuardar.setText("Guardar");
        Fondo.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 370, 140, 70));

        btnModificar.setText("Modificar");
        Fondo.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 370, 140, 70));

        comboEmpresas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una empresa recicladora", "Item 2", "Item 3", "Item 4" }));
        Fondo.add(comboEmpresas, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 260, -1));

        Empresa.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 13)); // NOI18N
        Empresa.setForeground(new java.awt.Color(153, 153, 153));
        Empresa.setText("Empresa Recicladora:");
        Fondo.add(Empresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        FechaResiduos.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 13)); // NOI18N
        FechaResiduos.setForeground(new java.awt.Color(153, 153, 153));
        FechaResiduos.setText("Fecha de Transacción:");
        Fondo.add(FechaResiduos, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 120, -1, -1));
        Fondo.add(dateReciclaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 140, 200, -1));

        btnAgregar.setText("+  Agregar Item");
        Fondo.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 340, 190, 70));

        btnNR.setText("Agregar Nuevo Residuo");
        btnNR.addActionListener(this::btnNRActionPerformed);
        Fondo.add(btnNR, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 260, 190, 70));
        Fondo.add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 200, 200, -1));
        Fondo.add(txtNReciclaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 260, -1));
        Fondo.add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 300, 240, -1));

        comboResiduos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccion un tipo de residuo", "Item 2", "Item 3", "Item 4" }));
        Fondo.add(comboResiduos, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 240, -1));
        Fondo.add(txtKilos, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 300, 240, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegresarMouseClicked
        // TODO add your handling code here:
        Menu m = new Menu();
        m.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresarMouseClicked

    private void btnNERMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNERMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNERMouseClicked

    private void btnNERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNERActionPerformed
        NuevaEmpresaReciclaje mp = new NuevaEmpresaReciclaje();
        javax.swing.JDialog ventana = new javax.swing.JDialog(this, "", true);
        ventana.add(mp);
        ventana.pack();
        ventana.setLocationRelativeTo(this);
        ventana.setVisible(true);
    }//GEN-LAST:event_btnNERActionPerformed

    private void btnNRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNRActionPerformed
        // TODO add your handling code here:
        NuevoResiduo mp = new NuevoResiduo();
        javax.swing.JDialog ventana = new javax.swing.JDialog(this, "", true);
        ventana.add(mp);
        ventana.pack();
        ventana.setLocationRelativeTo(this);
        ventana.setVisible(true);
        
    }//GEN-LAST:event_btnNRActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Residuos().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BarraAbajo;
    private javax.swing.JPanel BarraArriba;
    private javax.swing.JLabel DireccionResiduos;
    private javax.swing.JLabel Empresa;
    private javax.swing.JLabel FacturaResiduos;
    private javax.swing.JLabel FechaResiduos;
    private javax.swing.JPanel Fondo;
    private javax.swing.JLabel Kilos;
    private javax.swing.JLabel NombreVentanaResiduos;
    private javax.swing.JLabel PrecioResiduos;
    private javax.swing.JLabel Residuo;
    private javax.swing.JLabel TituloFuncion1;
    private javax.swing.JLabel TituloFuncion2;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnNER;
    private javax.swing.JButton btnNR;
    private javax.swing.JLabel btnRegresar;
    private javax.swing.JComboBox<String> comboEmpresas;
    private javax.swing.JComboBox<String> comboResiduos;
    private com.toedter.calendar.JDateChooser dateReciclaje;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtKilos;
    private javax.swing.JTextField txtNReciclaje;
    private javax.swing.JTextField txtPrecio;
    // End of variables declaration//GEN-END:variables
}
