/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyecto_m2b.Vista;

import com.mycompany.proyecto_m2b.Controlador.Validaciones;
import com.mycompany.proyecto_m2b.Controlador.CreacionCredenciales;
import com.mycompany.proyecto_m2b.Controlador.Servidor_de_correos;
import com.mycompany.proyecto_m2b.Controlador.TipoUsuarioDAO;
import com.mycompany.proyecto_m2b.Controlador.UsuarioDAO;
import com.mycompany.proyecto_m2b.modelo.Usuario;
import java.awt.Color;
import java.time.ZoneId;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author usuario
 */
public class Usuarios extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Usuarios.class.getName());

    /**
     * Creates new form CrearUsuario
     */
    public Usuarios() {
        initComponents();
        this.setLocationRelativeTo(null);
        Estados.setEnabled(false);
        UsuarioDAO ud=new UsuarioDAO();
        ud.cargarIDusuarios(this.Usuarios);
        TipoUsuarioDAO Tip=new TipoUsuarioDAO();
        Tip.cargarTiposUsuario(TiposDeUsuario);
        PanelBuscarTabla.setVisible(false);
        cargarTablaUsuario();
        TablaUsuario.setEnabled(false);
    }
    int xMouse, yMouse;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        BGempleados = new javax.swing.JPanel();
        Desplazar = new javax.swing.JPanel();
        NomVentana = new javax.swing.JLabel();
        Volver = new javax.swing.JLabel();
        NombreDeUsuario = new javax.swing.JLabel();
        TXTnombreDeUsuario = new javax.swing.JTextField();
        Contrasena = new javax.swing.JLabel();
        Estado = new javax.swing.JLabel();
        Estados = new javax.swing.JComboBox<>();
        TiposUsuario = new javax.swing.JLabel();
        TiposDeUsuario = new javax.swing.JComboBox<>();
        Permisos = new javax.swing.JLabel();
        Permiso = new javax.swing.JComboBox<>();
        PanelGuardar = new javax.swing.JPanel();
        Guardar = new javax.swing.JLabel();
        ImagenSAVE = new javax.swing.JLabel();
        PanelEditar = new javax.swing.JPanel();
        Editar = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        PanelDarBaja = new javax.swing.JPanel();
        DarDeBaja = new javax.swing.JLabel();
        ImagenDarBaja = new javax.swing.JLabel();
        PanelBuscar = new javax.swing.JPanel();
        Buscar = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Usuariostext = new javax.swing.JLabel();
        Usuarios = new javax.swing.JComboBox<>();
        TXTcontraseña = new javax.swing.JPasswordField();
        PanelDarDeAlta = new javax.swing.JPanel();
        DarDeAlta = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        PanelBuscarTabla = new javax.swing.JPanel();
        Empleado = new javax.swing.JLabel();
        TXTEmpleado = new javax.swing.JTextField();
        Cedula = new javax.swing.JLabel();
        TXTCedula = new javax.swing.JTextField();
        estado = new javax.swing.JLabel();
        TXTEstado = new javax.swing.JTextField();
        OtroNombreUsuario = new javax.swing.JLabel();
        TXTNombreUsuario = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablaUsuario = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BGempleados.setBackground(new java.awt.Color(255, 255, 255));
        BGempleados.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Desplazar.setBackground(new java.awt.Color(28, 28, 28));
        Desplazar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                DesplazarMouseDragged(evt);
            }
        });
        Desplazar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                DesplazarMousePressed(evt);
            }
        });

        NomVentana.setFont(new java.awt.Font("Roboto Condensed ExtraBold", 1, 18)); // NOI18N
        NomVentana.setForeground(new java.awt.Color(255, 255, 255));
        NomVentana.setText("GESTION DE USUARIOS");

        Volver.setBackground(new java.awt.Color(182, 182, 182));
        Volver.setFont(new java.awt.Font("Roboto Condensed", 1, 18)); // NOI18N
        Volver.setForeground(new java.awt.Color(182, 182, 182));
        Volver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/keyboard_backspace_22dp_FFFFFF_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N
        Volver.setText("Regresar");
        Volver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Volver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VolverMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                VolverMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                VolverMouseExited(evt);
            }
        });

        javax.swing.GroupLayout DesplazarLayout = new javax.swing.GroupLayout(Desplazar);
        Desplazar.setLayout(DesplazarLayout);
        DesplazarLayout.setHorizontalGroup(
            DesplazarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DesplazarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(NomVentana)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Volver)
                .addGap(27, 27, 27))
        );
        DesplazarLayout.setVerticalGroup(
            DesplazarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DesplazarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DesplazarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NomVentana)
                    .addComponent(Volver))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        NombreDeUsuario.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        NombreDeUsuario.setText("Nombre de usuario:");

        TXTnombreDeUsuario.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        TXTnombreDeUsuario.setForeground(new java.awt.Color(94, 94, 94));
        TXTnombreDeUsuario.setText("Nombre de usuario");
        TXTnombreDeUsuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TXTnombreDeUsuarioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TXTnombreDeUsuarioFocusLost(evt);
            }
        });
        TXTnombreDeUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TXTnombreDeUsuarioMousePressed(evt);
            }
        });

        Contrasena.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        Contrasena.setText("Contraseña de usuario:");

        Estado.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        Estado.setText("Estado:");

        Estados.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una opción", "Activo", "En pausa" }));
        Estados.addActionListener(this::EstadosActionPerformed);

        TiposUsuario.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        TiposUsuario.setText("Tipo de usuario");

        TiposDeUsuario.setBackground(new java.awt.Color(247, 247, 247));
        TiposDeUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una opción", "Empleado", "Jefe latonero", "Jefe mecánico", "Jefe del taller" }));
        TiposDeUsuario.addActionListener(this::TiposDeUsuarioActionPerformed);

        Permisos.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        Permisos.setText("Permisos:");

        Permiso.setBackground(new java.awt.Color(247, 247, 247));
        Permiso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una opción", "Pintura", "Motor", "Enderezado", "Cambio de aceites", "Cambio de pastillas" }));
        Permiso.addActionListener(this::PermisoActionPerformed);

        PanelGuardar.setBackground(new java.awt.Color(242, 101, 34));
        PanelGuardar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(187, 187, 187)));
        PanelGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PanelGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PanelGuardarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PanelGuardarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PanelGuardarMouseExited(evt);
            }
        });

        Guardar.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        Guardar.setForeground(new java.awt.Color(255, 255, 255));
        Guardar.setText("Guardar");

        ImagenSAVE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/save_22dp_FFFFFF_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N

        javax.swing.GroupLayout PanelGuardarLayout = new javax.swing.GroupLayout(PanelGuardar);
        PanelGuardar.setLayout(PanelGuardarLayout);
        PanelGuardarLayout.setHorizontalGroup(
            PanelGuardarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelGuardarLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(ImagenSAVE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Guardar)
                .addContainerGap(36, Short.MAX_VALUE))
        );
        PanelGuardarLayout.setVerticalGroup(
            PanelGuardarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelGuardarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanelGuardarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Guardar)
                    .addComponent(ImagenSAVE))
                .addContainerGap())
        );

        PanelEditar.setBackground(new java.awt.Color(255, 255, 255));
        PanelEditar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(187, 187, 187)));
        PanelEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PanelEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PanelEditarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PanelEditarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PanelEditarMouseExited(evt);
            }
        });

        Editar.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        Editar.setText("Editar");

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/edit_22dp_000000_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N

        javax.swing.GroupLayout PanelEditarLayout = new javax.swing.GroupLayout(PanelEditar);
        PanelEditar.setLayout(PanelEditarLayout);
        PanelEditarLayout.setHorizontalGroup(
            PanelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelEditarLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Editar)
                .addContainerGap(33, Short.MAX_VALUE))
        );
        PanelEditarLayout.setVerticalGroup(
            PanelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelEditarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Editar)
                    .addComponent(jLabel2))
                .addContainerGap())
        );

        PanelDarBaja.setBackground(new java.awt.Color(255, 255, 255));
        PanelDarBaja.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(215, 106, 106)));
        PanelDarBaja.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PanelDarBaja.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PanelDarBajaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PanelDarBajaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PanelDarBajaMouseExited(evt);
            }
        });

        DarDeBaja.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        DarDeBaja.setForeground(new java.awt.Color(215, 106, 106));
        DarDeBaja.setText("Dar de baja");

        ImagenDarBaja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/person_cancel_22dp_EA3323_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N

        javax.swing.GroupLayout PanelDarBajaLayout = new javax.swing.GroupLayout(PanelDarBaja);
        PanelDarBaja.setLayout(PanelDarBajaLayout);
        PanelDarBajaLayout.setHorizontalGroup(
            PanelDarBajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelDarBajaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ImagenDarBaja)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(DarDeBaja)
                .addGap(30, 30, 30))
        );
        PanelDarBajaLayout.setVerticalGroup(
            PanelDarBajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDarBajaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelDarBajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DarDeBaja)
                    .addComponent(ImagenDarBaja))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PanelBuscar.setBackground(new java.awt.Color(255, 255, 255));
        PanelBuscar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(187, 187, 187)));
        PanelBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PanelBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PanelBuscarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PanelBuscarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PanelBuscarMouseExited(evt);
            }
        });

        Buscar.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        Buscar.setText("Buscar");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/person_search_22dp_000000_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N

        javax.swing.GroupLayout PanelBuscarLayout = new javax.swing.GroupLayout(PanelBuscar);
        PanelBuscar.setLayout(PanelBuscarLayout);
        PanelBuscarLayout.setHorizontalGroup(
            PanelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelBuscarLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Buscar)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        PanelBuscarLayout.setVerticalGroup(
            PanelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBuscarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Buscar)
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Usuariostext.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        Usuariostext.setText("Usuarios:");

        Usuarios.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Usuarios.addItemListener(this::UsuariosItemStateChanged);

        TXTcontraseña.setText("********");
        TXTcontraseña.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TXTcontraseñaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TXTcontraseñaFocusLost(evt);
            }
        });
        TXTcontraseña.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TXTcontraseñaMouseClicked(evt);
            }
        });

        PanelDarDeAlta.setBackground(new java.awt.Color(255, 255, 255));
        PanelDarDeAlta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(187, 187, 187)));
        PanelDarDeAlta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PanelDarDeAlta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PanelDarDeAltaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PanelDarDeAltaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PanelDarDeAltaMouseExited(evt);
            }
        });

        DarDeAlta.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        DarDeAlta.setText("Dar de alta");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/add_22dp_000000_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N

        javax.swing.GroupLayout PanelDarDeAltaLayout = new javax.swing.GroupLayout(PanelDarDeAlta);
        PanelDarDeAlta.setLayout(PanelDarDeAltaLayout);
        PanelDarDeAltaLayout.setHorizontalGroup(
            PanelDarDeAltaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelDarDeAltaLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DarDeAlta)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelDarDeAltaLayout.setVerticalGroup(
            PanelDarDeAltaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDarDeAltaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelDarDeAltaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DarDeAlta)
                    .addComponent(jLabel3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PanelBuscarTabla.setBackground(new java.awt.Color(255, 213, 158));
        PanelBuscarTabla.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        Empleado.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        Empleado.setText("Empleado:");

        TXTEmpleado.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        TXTEmpleado.setForeground(new java.awt.Color(94, 94, 94));
        TXTEmpleado.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TXTEmpleadoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TXTEmpleadoFocusLost(evt);
            }
        });
        TXTEmpleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TXTEmpleadoMousePressed(evt);
            }
        });
        TXTEmpleado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TXTEmpleadoKeyReleased(evt);
            }
        });

        Cedula.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        Cedula.setText("Cedula:");

        TXTCedula.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        TXTCedula.setForeground(new java.awt.Color(94, 94, 94));
        TXTCedula.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TXTCedulaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TXTCedulaFocusLost(evt);
            }
        });
        TXTCedula.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TXTCedulaMousePressed(evt);
            }
        });
        TXTCedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TXTCedulaKeyReleased(evt);
            }
        });

        estado.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        estado.setText("Estado:");

        TXTEstado.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        TXTEstado.setForeground(new java.awt.Color(94, 94, 94));
        TXTEstado.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TXTEstadoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TXTEstadoFocusLost(evt);
            }
        });
        TXTEstado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TXTEstadoMousePressed(evt);
            }
        });
        TXTEstado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TXTEstadoKeyReleased(evt);
            }
        });

        OtroNombreUsuario.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        OtroNombreUsuario.setText("Nombre de usuario:");

        TXTNombreUsuario.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        TXTNombreUsuario.setForeground(new java.awt.Color(94, 94, 94));
        TXTNombreUsuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TXTNombreUsuarioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TXTNombreUsuarioFocusLost(evt);
            }
        });
        TXTNombreUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TXTNombreUsuarioMousePressed(evt);
            }
        });
        TXTNombreUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TXTNombreUsuarioKeyReleased(evt);
            }
        });

        TablaUsuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(TablaUsuario);

        javax.swing.GroupLayout PanelBuscarTablaLayout = new javax.swing.GroupLayout(PanelBuscarTabla);
        PanelBuscarTabla.setLayout(PanelBuscarTablaLayout);
        PanelBuscarTablaLayout.setHorizontalGroup(
            PanelBuscarTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBuscarTablaLayout.createSequentialGroup()
                .addGroup(PanelBuscarTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelBuscarTablaLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(PanelBuscarTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TXTCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Cedula))
                        .addGap(18, 18, 18)
                        .addGroup(PanelBuscarTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Empleado)
                            .addComponent(TXTEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(PanelBuscarTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TXTNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(OtroNombreUsuario))
                        .addGap(18, 18, 18)
                        .addGroup(PanelBuscarTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(estado)
                            .addComponent(TXTEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(PanelBuscarTablaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 748, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        PanelBuscarTablaLayout.setVerticalGroup(
            PanelBuscarTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBuscarTablaLayout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(PanelBuscarTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelBuscarTablaLayout.createSequentialGroup()
                        .addGroup(PanelBuscarTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Empleado)
                            .addComponent(Cedula))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelBuscarTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TXTEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TXTCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelBuscarTablaLayout.createSequentialGroup()
                        .addGroup(PanelBuscarTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(OtroNombreUsuario)
                            .addComponent(estado))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelBuscarTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TXTNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TXTEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout BGempleadosLayout = new javax.swing.GroupLayout(BGempleados);
        BGempleados.setLayout(BGempleadosLayout);
        BGempleadosLayout.setHorizontalGroup(
            BGempleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Desplazar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(BGempleadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BGempleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BGempleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(BGempleadosLayout.createSequentialGroup()
                            .addGroup(BGempleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(BGempleadosLayout.createSequentialGroup()
                                    .addComponent(Contrasena)
                                    .addGap(232, 232, 232))
                                .addGroup(BGempleadosLayout.createSequentialGroup()
                                    .addComponent(TXTcontraseña)
                                    .addGap(166, 166, 166)))
                            .addGroup(BGempleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Estado)
                                .addComponent(Estados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(BGempleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(TiposUsuario)
                                .addComponent(TiposDeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(BGempleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Permisos)
                                .addComponent(Permiso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(BGempleadosLayout.createSequentialGroup()
                            .addGroup(BGempleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Usuariostext)
                                .addComponent(Usuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(BGempleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(NombreDeUsuario)
                                .addComponent(TXTnombreDeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, BGempleadosLayout.createSequentialGroup()
                            .addComponent(PanelGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(PanelEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(PanelDarBaja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(PanelDarDeAlta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(PanelBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(PanelBuscarTabla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(111, Short.MAX_VALUE))
        );
        BGempleadosLayout.setVerticalGroup(
            BGempleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BGempleadosLayout.createSequentialGroup()
                .addComponent(Desplazar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(BGempleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NombreDeUsuario)
                    .addComponent(Usuariostext))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BGempleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TXTnombreDeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Usuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(BGempleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(BGempleadosLayout.createSequentialGroup()
                        .addComponent(Contrasena)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TXTcontraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6))
                    .addGroup(BGempleadosLayout.createSequentialGroup()
                        .addComponent(Estado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Estados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(BGempleadosLayout.createSequentialGroup()
                        .addComponent(TiposUsuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TiposDeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(BGempleadosLayout.createSequentialGroup()
                        .addComponent(Permisos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Permiso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(BGempleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(BGempleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(PanelGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(PanelEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(PanelDarBaja, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(PanelBuscar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(PanelDarDeAlta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(PanelBuscarTabla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        getContentPane().add(BGempleados, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VolverMouseClicked
        // TODO add your handling code here:;
        this.dispose();
    }//GEN-LAST:event_VolverMouseClicked

    private void VolverMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VolverMouseEntered
        // TODO add your handling code here:
        Volver.setForeground(Color.white);
    }//GEN-LAST:event_VolverMouseEntered

    private void VolverMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VolverMouseExited
        // TODO add your handling code here:
        Volver.setForeground(new Color(182, 182, 182));
    }//GEN-LAST:event_VolverMouseExited

    private void DesplazarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DesplazarMousePressed
        // TODO add your handling code here:
        xMouse=evt.getX();
        yMouse=evt.getY();
    }//GEN-LAST:event_DesplazarMousePressed

    private void DesplazarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DesplazarMouseDragged
        // TODO add your handling code here:
        int x=evt.getXOnScreen();
        int y=evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_DesplazarMouseDragged

    private void EstadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EstadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EstadosActionPerformed

    private void TiposDeUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TiposDeUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TiposDeUsuarioActionPerformed

    private void PermisoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PermisoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PermisoActionPerformed

    private void PanelEditarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelEditarMouseEntered
        // TODO add your handling code here:
        PanelEditar.setBackground(new Color(219,219,219));
        Editar.setForeground(new Color(66, 66, 66));
    }//GEN-LAST:event_PanelEditarMouseEntered

    
    private void PanelBuscarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelBuscarMouseEntered
        // TODO add your handling code here:
        PanelBuscar.setBackground(new Color(219,219,219));
        Buscar.setForeground(new Color(66, 66, 66));
    }//GEN-LAST:event_PanelBuscarMouseEntered

    private void PanelEditarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelEditarMouseExited
        // TODO add your handling code here:
        PanelEditar.setBackground(Color.white);
        Editar.setForeground(Color.black);
    }//GEN-LAST:event_PanelEditarMouseExited

    private void PanelBuscarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelBuscarMouseExited
        // TODO add your handling code here:
        PanelBuscar.setBackground(Color.white);
        Buscar.setForeground(Color.black);
    }//GEN-LAST:event_PanelBuscarMouseExited

    private void PanelDarBajaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelDarBajaMouseEntered
        // TODO add your handling code here:
        PanelDarBaja.setBackground(new Color (252, 168, 168));
        DarDeBaja.setForeground(Color.white);
    }//GEN-LAST:event_PanelDarBajaMouseEntered

    private void PanelDarBajaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelDarBajaMouseExited
        // TODO add your handling code here:
        PanelDarBaja.setBackground(Color.white);
        DarDeBaja.setForeground(new Color(215, 106, 106));
    }//GEN-LAST:event_PanelDarBajaMouseExited

    public void LimpiarDatos (){
        TXTnombreDeUsuario.setText("Nombre de usuario");
        TXTnombreDeUsuario.setForeground(new Color(94, 94, 94));        
        TXTcontraseña.setText("********");
        TXTcontraseña.setForeground(new Color(94, 94, 94));        
        Estados.setSelectedIndex(0);
        TiposDeUsuario.setSelectedIndex(0);
        Permiso.setSelectedIndex(0);
        
    }
    private void TXTnombreDeUsuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TXTnombreDeUsuarioMousePressed
        // TODO add your handling code here:
        if (TXTnombreDeUsuario.getText().equals("Nombre de usuario")){
            TXTnombreDeUsuario.setText("");
            TXTnombreDeUsuario.setForeground(Color.BLACK);
        }        
        if (String.valueOf(TXTcontraseña.getPassword()).isEmpty()){
            TXTcontraseña.setText("********");
            TXTcontraseña.setForeground(new Color(94, 94, 94));
        }        
    }//GEN-LAST:event_TXTnombreDeUsuarioMousePressed

    private void TXTnombreDeUsuarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TXTnombreDeUsuarioFocusGained
        // TODO add your handling code here:
        if (TXTnombreDeUsuario.getText().equals("Nombre de usuario")){
            TXTnombreDeUsuario.setText("");
            TXTnombreDeUsuario.setForeground(Color.BLACK);
        }        
        if (String.valueOf(TXTcontraseña.getPassword()).isEmpty()){
            TXTcontraseña.setText("********");
            TXTcontraseña.setForeground(new Color(94, 94, 94));
        }        
    }//GEN-LAST:event_TXTnombreDeUsuarioFocusGained

    public void Dinamico (){
        String cedula=TXTCedula.getText().trim();
        String empleado=TXTEmpleado.getText().trim();
        String usuario=TXTNombreUsuario.getText().trim();
        String estado=TXTEstado.getText().trim();
        cargarTablaUsuario(cedula, empleado, usuario, estado);
    }
    public void cargarTablaUsuario(){
        cargarTablaUsuario("", "", "", "");
    }
    public void cargarTablaUsuario (String cedula, String empleado, String usuario, String estado){        
        UsuarioDAO ud=new UsuarioDAO();
        List<Usuario> lista= ud.listarUsuario();
        String columnas []={"Cédula","ID","Nombre usuario","Empleado", "Tipo usuario", "Estado"};
        DefaultTableModel modelo = new DefaultTableModel (null, columnas);
        modelo.setRowCount(0);
        System.out.println(lista.size());
        for (Usuario u : lista){
            Object [] fila={
                u.getCed_perso(),
                u.getID_usuario(),
                u.getNombre_usuario(),
                u.getNombre_completo(),
                u.getTip_usuario(),
                u.isEstado_acti_usuario()?"Activo":"En pausa"
            };
            modelo.addRow(fila);
        }
        // table nombre asignado a la tabla
        TablaUsuario.setModel(modelo);
    }
    
    private void PanelDarBajaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelDarBajaMouseClicked
        // TODO add your handling code here:
        Usuario selecc=(Usuario) Usuarios.getSelectedItem();
        if (selecc!=null){
            int opcion=JOptionPane.showConfirmDialog(this, "¿Esta seguro de dar de baja a este empleado?","Confirmar",JOptionPane.YES_NO_OPTION);
            if (opcion==JOptionPane.YES_OPTION){
                    String id_selecc=selecc.getID_usuario();
                    UsuarioDAO u=new UsuarioDAO();
                    boolean exito=u.DarDeBaja(id_selecc);
                    if (exito){
                        Estados.setSelectedItem("En pausa");                        
                        JOptionPane.showMessageDialog(this, "Modificado de manera correcta");
                        u.cargarIDusuarios(this.Usuarios);
                        //Hilo para el envio de correos
        
                String correo_perso=u.DevolverCorreoPerson(selecc.getId_empleado());                

                new Thread(() -> {
                    Servidor_de_correos sv=new Servidor_de_correos();
                    sv.InformarBaja(correo_perso);
                }).start();
                        LimpiarDatos();
                        cargarTablaUsuario();
                    }
                    else{
                        JOptionPane.showMessageDialog(this, "Error al modificar al usuario: "+selecc.getNombre_usuario());
                    }
            }
            else{
                JOptionPane.showMessageDialog(this, "Gracias por confirmar");
            }
        }
        else{
            JOptionPane.showMessageDialog(this, "Por favor escoga a un usuario");
        }
    }//GEN-LAST:event_PanelDarBajaMouseClicked

    private void UsuariosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_UsuariosItemStateChanged
        // TODO add your handling code here:
        Usuario selecc=(Usuario) Usuarios.getSelectedItem();
        if (selecc !=null){
            TXTnombreDeUsuario.setText(selecc.getNombre_usuario());
            TXTnombreDeUsuario.setText(selecc.getNombre_usuario());
            TXTcontraseña.setText(selecc.getContra_usuario());
            if(selecc.isEstado_acti_usuario()){
                Estados.setSelectedItem("Activo");
            }
            else{
                Estados.setSelectedItem("En pausa");
            }
        }
    }//GEN-LAST:event_UsuariosItemStateChanged

    private void TXTcontraseñaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TXTcontraseñaFocusGained
        // TODO add your handling code here:
        Usuario selecc= (Usuario) Usuarios.getSelectedItem();
        if (selecc==null){
            JOptionPane.showMessageDialog(this, "Error al obtener la contraseña, por favor intente de nuevo");
            return;
        }
        if (String.valueOf(TXTcontraseña.getPassword()).equals("********") || String.valueOf(TXTcontraseña.getPassword()).equals(selecc.getContra_usuario())){
            TXTcontraseña.setText("");
            TXTcontraseña.setForeground(new Color(176, 166, 157));
        }
        if (TXTnombreDeUsuario.getText().isEmpty()){
            TXTnombreDeUsuario.setText("Nombre de usuario");
            TXTnombreDeUsuario.setForeground(new Color(94, 94, 94));
        }
    }//GEN-LAST:event_TXTcontraseñaFocusGained

    private void TXTcontraseñaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TXTcontraseñaMouseClicked
        // TODO add your handling code here:
        if (String.valueOf(TXTcontraseña.getPassword()).equals("********")){
            TXTcontraseña.setText("");
            TXTcontraseña.setForeground(new Color(176, 166, 157));
        }
        if (TXTnombreDeUsuario.getText().isEmpty()){
            TXTnombreDeUsuario.setText("Nombre de usuario");
            TXTnombreDeUsuario.setForeground(new Color(94, 94, 94));
        }
    }//GEN-LAST:event_TXTcontraseñaMouseClicked

    private void TXTcontraseñaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TXTcontraseñaFocusLost
        // TODO add your handling code here:
        Usuario selecc= (Usuario) Usuarios.getSelectedItem();
        if (selecc==null){
            JOptionPane.showMessageDialog(this, "Error al obtener la contraseña, por favor intente de nuevo");
            return;
        }
        if (String.valueOf(TXTcontraseña.getPassword()).equals("********") || String.valueOf(TXTcontraseña.getPassword()).equals(selecc.getContra_usuario())){
            TXTcontraseña.setText("");
            TXTcontraseña.setForeground(new Color(176, 166, 157));
        }
        if (TXTnombreDeUsuario.getText().isEmpty()){
            TXTnombreDeUsuario.setText("Nombre de usuario");
            TXTnombreDeUsuario.setForeground(new Color(94, 94, 94));
        }
    }//GEN-LAST:event_TXTcontraseñaFocusLost

    private void TXTnombreDeUsuarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TXTnombreDeUsuarioFocusLost
        // TODO add your handling code here:
        if (TXTnombreDeUsuario.getText().equals("Nombre de usuario")){
            TXTnombreDeUsuario.setText("");
            TXTnombreDeUsuario.setForeground(Color.BLACK);
        }        
        if (String.valueOf(TXTcontraseña.getPassword()).isEmpty()){
            TXTcontraseña.setText("********");
            TXTcontraseña.setForeground(new Color(94, 94, 94));
        }   
    }//GEN-LAST:event_TXTnombreDeUsuarioFocusLost

    private void PanelDarDeAltaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelDarDeAltaMouseEntered
        // TODO add your handling code here:
        PanelDarDeAlta.setBackground(new Color(219,219,219));
        PanelDarDeAlta.setForeground(new Color(66, 66, 66));
    }//GEN-LAST:event_PanelDarDeAltaMouseEntered

    private void PanelDarDeAltaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelDarDeAltaMouseExited
        // TODO add your handling code here:
        PanelDarDeAlta.setBackground(Color.white);
        PanelDarDeAlta.setForeground(Color.black);
    }//GEN-LAST:event_PanelDarDeAltaMouseExited

    private void PanelDarDeAltaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelDarDeAltaMouseClicked
        // TODO add your handling code here:
        Usuario selecc=(Usuario) Usuarios.getSelectedItem();
        if (selecc!=null){
            int opcion=JOptionPane.showConfirmDialog(this, "¿Esta seguro de dar de alta a este empleado?"+JOptionPane.YES_NO_OPTION);
            if (opcion==JOptionPane.YES_OPTION){
                    String id_selecc=selecc.getID_usuario();
                    UsuarioDAO u=new UsuarioDAO();
                    boolean exito=u.DarDeAlta(id_selecc);
                    if (exito){
                        Estados.setSelectedItem("Activo");                        
                        JOptionPane.showMessageDialog(this, "Modificado de manera correcta");
                        u.cargarIDusuarios(this.Usuarios);
                        //Hilo para el envio de correos
        
                String correo_perso=u.DevolverCorreoPerson(selecc.getId_empleado());                

                new Thread(() -> {
                    Servidor_de_correos sv=new Servidor_de_correos();
                    sv.InformarAlta(correo_perso);
                }).start();
                        
                        LimpiarDatos();
                        cargarTablaUsuario();
                    }
                    else{
                        JOptionPane.showMessageDialog(this, "Error al modificar al usuario: "+selecc.getNombre_usuario());
                    }
            }
            else{
                JOptionPane.showMessageDialog(this, "Gracias por confirmar");
            }
        }
        else{
            JOptionPane.showMessageDialog(this, "Por favor escoga a un usuario");
        }
    }//GEN-LAST:event_PanelDarDeAltaMouseClicked

    private void PanelGuardarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelGuardarMouseExited
        // TODO add your handling code here:
        PanelGuardar.setBackground(new Color(242,101,34));
        Guardar.setForeground(Color.white);
    }//GEN-LAST:event_PanelGuardarMouseExited

    private void PanelGuardarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelGuardarMouseEntered
        // TODO add your handling code here:
        PanelGuardar.setBackground(new Color(227, 95, 32));
        Guardar.setForeground(new Color(217, 217, 192));
    }//GEN-LAST:event_PanelGuardarMouseEntered

    private void PanelGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelGuardarMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_PanelGuardarMouseClicked

    private void PanelEditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelEditarMouseClicked
        // TODO add your handling code here:
        Usuario selecc= (Usuario) Usuarios.getSelectedItem();
        if (selecc!=null){
            int opcion = JOptionPane.showConfirmDialog(this, "¿Esta seguro de modificar al usuario con nombre: "+selecc.getNombre_usuario()+"?"+"\n"
                    + "Confirmar su respuesta", "Condirmar", JOptionPane.YES_NO_OPTION);
            if (opcion==JOptionPane.YES_OPTION){
            Validaciones V=new Validaciones();
            String NomNuevo = TXTnombreDeUsuario.getText();
            String ContraNuevo=String.valueOf(TXTcontraseña.getPassword());
            if (!V.validarNombreUsuario(NomNuevo)){
                JOptionPane.showMessageDialog(this, "Este nombre no es valido");
                return;
            }
            if (!V.validarContrasena(ContraNuevo)){
                JOptionPane.showMessageDialog(this, "Esta contraseña no es valida");
                return;
            }
            Usuario u=new Usuario();
            u.setNombre_usuario(NomNuevo);
            u.setContra_usuario(ContraNuevo);
            u.setTip_usuario(selecc.getTip_usuario());
            u.setID_usuario(selecc.getID_usuario().toString());
            UsuarioDAO ud=new UsuarioDAO();
            boolean exist = ud.modificarUsuario(u);
            if (exist){                
                JOptionPane.showMessageDialog(this, "Se ha modificado de manera correcta");
                ud.cargarIDusuarios(this.Usuarios);
                //Hilo para el envio de correos
        
                String correo_perso=ud.DevolverCorreoPerson(selecc.getId_empleado());
                String nom_usuario=NomNuevo;
                String contra_usuario=ContraNuevo;

                new Thread(() -> {
                    Servidor_de_correos sv=new Servidor_de_correos();
                    sv.enviarCorreoActualizacionUsuario(nom_usuario, contra_usuario, correo_perso);
                }).start();
                
                
                LimpiarDatos();
                cargarTablaUsuario();
            }
            else{
                JOptionPane.showMessageDialog(this, "Error al modificar al usaurio");
            }
            }
            else{
                JOptionPane.showMessageDialog(this, "Gracias por su confirmación");
            }            
        }
        else{
            JOptionPane.showMessageDialog(this, "Error al escoger el usuario");
        }        
    }//GEN-LAST:event_PanelEditarMouseClicked

    private void PanelBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelBuscarMouseClicked
        // TODO add your handling code here:
        if (PanelBuscarTabla.isVisible()==false){
            PanelBuscarTabla.setVisible(true);
        }
        else{
            PanelBuscarTabla.setVisible(false);
        }
    }//GEN-LAST:event_PanelBuscarMouseClicked

    private void TXTEmpleadoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TXTEmpleadoFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTEmpleadoFocusGained

    private void TXTEmpleadoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TXTEmpleadoFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTEmpleadoFocusLost

    private void TXTEmpleadoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TXTEmpleadoMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTEmpleadoMousePressed

    private void TXTCedulaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TXTCedulaFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTCedulaFocusGained

    private void TXTCedulaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TXTCedulaFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTCedulaFocusLost

    private void TXTCedulaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TXTCedulaMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTCedulaMousePressed

    private void TXTEstadoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TXTEstadoFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTEstadoFocusGained

    private void TXTEstadoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TXTEstadoFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTEstadoFocusLost

    private void TXTEstadoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TXTEstadoMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTEstadoMousePressed

    private void TXTNombreUsuarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TXTNombreUsuarioFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTNombreUsuarioFocusGained

    private void TXTNombreUsuarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TXTNombreUsuarioFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTNombreUsuarioFocusLost

    private void TXTNombreUsuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TXTNombreUsuarioMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTNombreUsuarioMousePressed

    private void TXTCedulaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXTCedulaKeyReleased
        // TODO add your handling code here:
        //Dinamico();
    }//GEN-LAST:event_TXTCedulaKeyReleased

    private void TXTEmpleadoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXTEmpleadoKeyReleased
        // TODO add your handling code here:
        //Dinamico();
    }//GEN-LAST:event_TXTEmpleadoKeyReleased

    private void TXTNombreUsuarioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXTNombreUsuarioKeyReleased
        // TODO add your handling code here:
        //Dinamico();
    }//GEN-LAST:event_TXTNombreUsuarioKeyReleased

    private void TXTEstadoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXTEstadoKeyReleased
        // TODO add your handling code here:
        //Dinamico();
    }//GEN-LAST:event_TXTEstadoKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Usuarios().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BGempleados;
    private javax.swing.JLabel Buscar;
    private javax.swing.JLabel Cedula;
    private javax.swing.JLabel Contrasena;
    private javax.swing.JLabel DarDeAlta;
    private javax.swing.JLabel DarDeBaja;
    private javax.swing.JPanel Desplazar;
    private javax.swing.JLabel Editar;
    private javax.swing.JLabel Empleado;
    private javax.swing.JLabel Estado;
    private javax.swing.JComboBox<String> Estados;
    private javax.swing.JLabel Guardar;
    private javax.swing.JLabel ImagenDarBaja;
    private javax.swing.JLabel ImagenSAVE;
    private javax.swing.JLabel NomVentana;
    private javax.swing.JLabel NombreDeUsuario;
    private javax.swing.JLabel OtroNombreUsuario;
    private javax.swing.JPanel PanelBuscar;
    private javax.swing.JPanel PanelBuscarTabla;
    private javax.swing.JPanel PanelDarBaja;
    private javax.swing.JPanel PanelDarDeAlta;
    private javax.swing.JPanel PanelEditar;
    private javax.swing.JPanel PanelGuardar;
    private javax.swing.JComboBox<String> Permiso;
    private javax.swing.JLabel Permisos;
    private javax.swing.JTextField TXTCedula;
    private javax.swing.JTextField TXTEmpleado;
    private javax.swing.JTextField TXTEstado;
    private javax.swing.JTextField TXTNombreUsuario;
    private javax.swing.JPasswordField TXTcontraseña;
    private javax.swing.JTextField TXTnombreDeUsuario;
    private javax.swing.JTable TablaUsuario;
    private javax.swing.JComboBox<String> TiposDeUsuario;
    private javax.swing.JLabel TiposUsuario;
    private javax.swing.JComboBox<String> Usuarios;
    private javax.swing.JLabel Usuariostext;
    private javax.swing.JLabel Volver;
    private javax.swing.JLabel estado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
