/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyecto_m2b.Vista;

import com.mycompany.proyecto_m2b.Controlador.Validaciones;
import com.mycompany.proyecto_m2b.Controlador.VehiculosDAO;
import com.mycompany.proyecto_m2b.modelo.Marca;
import com.mycompany.proyecto_m2b.modelo.Modelo;
import java.awt.Color;
import java.util.List;
import javax.swing.JOptionPane;


/**
 *
 * @author jose
 */
public class Vehiculos extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Vehiculos.class.getName());

    /**
     * Creates new form Vehiculos
     */
    public Vehiculos() {
        initComponents();
        cargarComboMarcas();
        PanelNuevo3.addMouseListener(new java.awt.event.MouseAdapter() {
        @Override
        public void mousePressed(java.awt.event.MouseEvent evt) {
            CrearNuevaMarcaModelo ventana = new CrearNuevaMarcaModelo();
            ventana.setLocationRelativeTo(Vehiculos.this);
            ventana.setVisible(true);
        }
    });
    txtPlaca.setText("Ingrese la placa del vehiculo");
    txtPlaca.setForeground(java.awt.Color.GRAY);

    txtColor.setText("Ingrese el color del vehiculo");
    txtColor.setForeground(java.awt.Color.GRAY);
    
    txtKilometraje.setText("Ingrese el kilometraje del vehiculo");
    txtKilometraje.setForeground(java.awt.Color.GRAY);
    
    txtAnio.setText("Ingrese el año de fabricacion del vehiculo");
    txtAnio.setForeground(java.awt.Color.GRAY);

    txtChasis.setText("Ingrese el N° de chasis del vehiculo");
    txtChasis.setForeground(java.awt.Color.GRAY);
    
    txtMotor.setText("Ingrese el N° de motor del vehiculo");
    txtMotor.setForeground(java.awt.Color.GRAY);

    txtCilindraje.setText("Ingrese el cilindraje del vehiculo");
    txtCilindraje.setForeground(java.awt.Color.GRAY);

    txtPuertas.setText("Ingrese el N° de puertas del vehiculo");
    txtPuertas.setForeground(java.awt.Color.GRAY);    
    this.setLocationRelativeTo(null);     
        
    }
    public void cargarComboMarcas() {
        comboMarcas.removeAllItems();
        VehiculosDAO dao = new VehiculosDAO();
        List<Marca> lista = dao.listarMarcas(); // Método en DAO que lee SELECT * FROM marca
    
        for (Marca m : lista) {
        comboMarcas.addItem(m.getNom_mar()); // Agrega el objeto Marca completo
        }
    }
    public void cargarComboModelos(String idMarca) {
    comboModelos.removeAllItems();
    VehiculosDAO dao = new VehiculosDAO();
    List<Modelo> lista = dao.listarModelosPorMarca(idMarca);

    for (Modelo mod : lista) {
        comboModelos.addItem(mod.getNom_mode()); // Agregas solo el texto del modelo
    }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Fondo = new javax.swing.JPanel();
        BarraArriba = new javax.swing.JPanel();
        NombreVentanaVehiculos = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        BarraAbajo = new javax.swing.JPanel();
        TituloFuncion1 = new javax.swing.JLabel();
        Placa = new javax.swing.JLabel();
        Marca = new javax.swing.JLabel();
        Color = new javax.swing.JLabel();
        Kilometraje = new javax.swing.JLabel();
        Modelo = new javax.swing.JLabel();
        Propietario = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        comboMarcas = new javax.swing.JComboBox<>();
        comboModelos = new javax.swing.JComboBox<>();
        comboPropietarios = new javax.swing.JComboBox<>();
        txtPlaca = new javax.swing.JTextField();
        txtColor = new javax.swing.JTextField();
        txtKilometraje = new javax.swing.JTextField();
        TituloFuncion2 = new javax.swing.JLabel();
        Ano = new javax.swing.JLabel();
        Chasis = new javax.swing.JLabel();
        Transmicion = new javax.swing.JLabel();
        Motor = new javax.swing.JLabel();
        Cilindraje = new javax.swing.JLabel();
        Puertas = new javax.swing.JLabel();
        comboTransmision = new javax.swing.JComboBox<>();
        txtAnio = new javax.swing.JTextField();
        txtChasis = new javax.swing.JTextField();
        txtMotor = new javax.swing.JTextField();
        txtCilindraje = new javax.swing.JTextField();
        txtPuertas = new javax.swing.JTextField();
        PanelGuardar = new javax.swing.JPanel();
        Guardar = new javax.swing.JLabel();
        ImagenSAVE = new javax.swing.JLabel();
        PanelEditar = new javax.swing.JPanel();
        Editar = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        PanelBuscar = new javax.swing.JPanel();
        Buscar = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        PanelNuevo3 = new javax.swing.JPanel();
        Nuevo3 = new javax.swing.JLabel();
        ImagenADD3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        Fondo.setBackground(new java.awt.Color(255, 255, 255));
        Fondo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BarraArriba.setBackground(new java.awt.Color(0, 0, 0));

        NombreVentanaVehiculos.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        NombreVentanaVehiculos.setForeground(new java.awt.Color(255, 255, 255));
        NombreVentanaVehiculos.setText("REGISTRO DE VEHÍCULOS ");

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Regresar");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout BarraArribaLayout = new javax.swing.GroupLayout(BarraArriba);
        BarraArriba.setLayout(BarraArribaLayout);
        BarraArribaLayout.setHorizontalGroup(
            BarraArribaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BarraArribaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(NombreVentanaVehiculos, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 776, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(19, 19, 19))
        );
        BarraArribaLayout.setVerticalGroup(
            BarraArribaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BarraArribaLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(BarraArribaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(NombreVentanaVehiculos))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        Fondo.add(BarraArriba, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1240, 60));

        BarraAbajo.setBackground(new java.awt.Color(227, 153, 106));

        javax.swing.GroupLayout BarraAbajoLayout = new javax.swing.GroupLayout(BarraAbajo);
        BarraAbajo.setLayout(BarraAbajoLayout);
        BarraAbajoLayout.setHorizontalGroup(
            BarraAbajoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1240, Short.MAX_VALUE)
        );
        BarraAbajoLayout.setVerticalGroup(
            BarraAbajoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        Fondo.add(BarraAbajo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 630, 1240, 70));

        TituloFuncion1.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        TituloFuncion1.setForeground(new java.awt.Color(153, 153, 153));
        TituloFuncion1.setText("DATOS PRINCIPALES Y PROPIETARIO");
        Fondo.add(TituloFuncion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        Placa.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 13)); // NOI18N
        Placa.setForeground(new java.awt.Color(153, 153, 153));
        Placa.setText("Placa:");
        Fondo.add(Placa, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        Marca.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 13)); // NOI18N
        Marca.setForeground(new java.awt.Color(153, 153, 153));
        Marca.setText("Marca:");
        Fondo.add(Marca, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        Color.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 13)); // NOI18N
        Color.setForeground(new java.awt.Color(153, 153, 153));
        Color.setText("Color:");
        Fondo.add(Color, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, -1));

        Kilometraje.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 13)); // NOI18N
        Kilometraje.setForeground(new java.awt.Color(153, 153, 153));
        Kilometraje.setText("Kilometraje:");
        Fondo.add(Kilometraje, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, -1, -1));

        Modelo.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 13)); // NOI18N
        Modelo.setForeground(new java.awt.Color(153, 153, 153));
        Modelo.setText("Modelo:");
        Fondo.add(Modelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, -1, -1));

        Propietario.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 13)); // NOI18N
        Propietario.setForeground(new java.awt.Color(153, 153, 153));
        Propietario.setText("Propietario:");
        Fondo.add(Propietario, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 120, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/images (2).jpg"))); // NOI18N
        Fondo.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 70, -1, -1));

        comboMarcas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una marca", " " }));
        comboMarcas.addActionListener(this::comboMarcasActionPerformed);
        Fondo.add(comboMarcas, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 210, -1));

        comboModelos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccion un modelo", "Item 2", "Item 3", "Item 4" }));
        Fondo.add(comboModelos, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 200, 240, -1));

        comboPropietarios.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione al propietario", "Item 2", "Item 3", "Item 4" }));
        Fondo.add(comboPropietarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 140, 240, -1));

        txtPlaca.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPlacaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPlacaFocusLost(evt);
            }
        });
        txtPlaca.addActionListener(this::txtPlacaActionPerformed);
        Fondo.add(txtPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 210, -1));

        txtColor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtColorFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtColorFocusLost(evt);
            }
        });
        Fondo.add(txtColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 210, -1));

        txtKilometraje.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtKilometrajeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtKilometrajeFocusLost(evt);
            }
        });
        Fondo.add(txtKilometraje, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 260, 240, -1));

        TituloFuncion2.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        TituloFuncion2.setForeground(new java.awt.Color(153, 153, 153));
        TituloFuncion2.setText("ESPECIFICACIONES TÉCNICAS");
        Fondo.add(TituloFuncion2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, -1, -1));

        Ano.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 13)); // NOI18N
        Ano.setForeground(new java.awt.Color(153, 153, 153));
        Ano.setText("Añ0:");
        Fondo.add(Ano, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, -1, -1));

        Chasis.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 13)); // NOI18N
        Chasis.setForeground(new java.awt.Color(153, 153, 153));
        Chasis.setText("N° Chasis:");
        Fondo.add(Chasis, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, -1, -1));

        Transmicion.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 13)); // NOI18N
        Transmicion.setForeground(new java.awt.Color(153, 153, 153));
        Transmicion.setText("Transmisión:");
        Fondo.add(Transmicion, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 370, -1, -1));

        Motor.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 13)); // NOI18N
        Motor.setForeground(new java.awt.Color(153, 153, 153));
        Motor.setText("N° Motor:");
        Fondo.add(Motor, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 430, -1, -1));

        Cilindraje.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 13)); // NOI18N
        Cilindraje.setForeground(new java.awt.Color(153, 153, 153));
        Cilindraje.setText("Cilindraje:");
        Fondo.add(Cilindraje, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 370, -1, -1));

        Puertas.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 13)); // NOI18N
        Puertas.setForeground(new java.awt.Color(153, 153, 153));
        Puertas.setText("N° Puertas:");
        Fondo.add(Puertas, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 430, -1, -1));

        comboTransmision.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione un tipo de transmicion", "Item 2", "Item 3", "Item 4" }));
        Fondo.add(comboTransmision, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 390, 290, -1));

        txtAnio.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtAnioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtAnioFocusLost(evt);
            }
        });
        Fondo.add(txtAnio, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, 270, -1));

        txtChasis.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtChasisFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtChasisFocusLost(evt);
            }
        });
        Fondo.add(txtChasis, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, 270, -1));

        txtMotor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtMotorFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtMotorFocusLost(evt);
            }
        });
        Fondo.add(txtMotor, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 450, 290, -1));

        txtCilindraje.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCilindrajeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCilindrajeFocusLost(evt);
            }
        });
        Fondo.add(txtCilindraje, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 390, 270, -1));

        txtPuertas.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPuertasFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPuertasFocusLost(evt);
            }
        });
        Fondo.add(txtPuertas, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 450, 270, -1));

        PanelGuardar.setBackground(new java.awt.Color(242, 101, 34));
        PanelGuardar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(187, 187, 187)));
        PanelGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PanelGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PanelGuardarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PanelGuardarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PanelGuardarMouseExited(evt);
            }
        });

        Guardar.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        Guardar.setForeground(new java.awt.Color(255, 255, 255));
        Guardar.setText("Guardar");

        ImagenSAVE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/save_22dp_FFFFFF_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N

        javax.swing.GroupLayout PanelGuardarLayout = new javax.swing.GroupLayout(PanelGuardar);
        PanelGuardar.setLayout(PanelGuardarLayout);
        PanelGuardarLayout.setHorizontalGroup(
            PanelGuardarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelGuardarLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(ImagenSAVE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Guardar)
                .addContainerGap(36, Short.MAX_VALUE))
        );
        PanelGuardarLayout.setVerticalGroup(
            PanelGuardarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelGuardarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanelGuardarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Guardar)
                    .addComponent(ImagenSAVE))
                .addContainerGap())
        );

        Fondo.add(PanelGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 520, -1, -1));

        PanelEditar.setBackground(new java.awt.Color(255, 255, 255));
        PanelEditar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(187, 187, 187)));
        PanelEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PanelEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PanelEditarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PanelEditarMouseExited(evt);
            }
        });

        Editar.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        Editar.setText("Editar");

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/edit_22dp_000000_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N

        javax.swing.GroupLayout PanelEditarLayout = new javax.swing.GroupLayout(PanelEditar);
        PanelEditar.setLayout(PanelEditarLayout);
        PanelEditarLayout.setHorizontalGroup(
            PanelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelEditarLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Editar)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        PanelEditarLayout.setVerticalGroup(
            PanelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelEditarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Editar)
                    .addComponent(jLabel2))
                .addContainerGap())
        );

        Fondo.add(PanelEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 520, 130, -1));

        PanelBuscar.setBackground(new java.awt.Color(255, 255, 255));
        PanelBuscar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(187, 187, 187)));
        PanelBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PanelBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PanelBuscarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PanelBuscarMouseExited(evt);
            }
        });

        Buscar.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        Buscar.setText("Buscar");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/person_search_22dp_000000_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N

        javax.swing.GroupLayout PanelBuscarLayout = new javax.swing.GroupLayout(PanelBuscar);
        PanelBuscar.setLayout(PanelBuscarLayout);
        PanelBuscarLayout.setHorizontalGroup(
            PanelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelBuscarLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Buscar)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        PanelBuscarLayout.setVerticalGroup(
            PanelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBuscarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Buscar)
                    .addComponent(jLabel3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Fondo.add(PanelBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 520, -1, -1));

        PanelNuevo3.setBackground(new java.awt.Color(255, 255, 255));
        PanelNuevo3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(187, 187, 187)));
        PanelNuevo3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PanelNuevo3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PanelNuevoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PanelNuevoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PanelNuevoMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PanelNuevoMousePressed(evt);
            }
        });

        Nuevo3.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        Nuevo3.setText("Añadir marca/modelo");

        ImagenADD3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/add_22dp_000000_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N

        javax.swing.GroupLayout PanelNuevo3Layout = new javax.swing.GroupLayout(PanelNuevo3);
        PanelNuevo3.setLayout(PanelNuevo3Layout);
        PanelNuevo3Layout.setHorizontalGroup(
            PanelNuevo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelNuevo3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(ImagenADD3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Nuevo3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelNuevo3Layout.setVerticalGroup(
            PanelNuevo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelNuevo3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelNuevo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ImagenADD3)
                    .addComponent(Nuevo3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Fondo.add(PanelNuevo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo, javax.swing.GroupLayout.DEFAULT_SIZE, 702, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPlacaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPlacaFocusGained
        if (txtPlaca.getText().equals("Ingrese la placa del vehiculo")) {
            txtPlaca.setText("");
            txtPlaca.setForeground(java.awt.Color.BLACK);
        }
    }//GEN-LAST:event_txtPlacaFocusGained

    private void txtPlacaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPlacaFocusLost
        if (txtPlaca.getText().trim().isEmpty()) {
            txtPlaca.setText("Ingrese la placa del vehiculo");
            txtPlaca.setForeground(java.awt.Color.GRAY);
        }
    }//GEN-LAST:event_txtPlacaFocusLost

    private void txtColorFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtColorFocusGained
        if (txtColor.getText().equals("Ingrese el color del vehiculo")) {
            txtColor.setText("");
            txtColor.setForeground(java.awt.Color.BLACK);
        }
    }//GEN-LAST:event_txtColorFocusGained

    private void txtColorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtColorFocusLost
        if (txtColor.getText().trim().isEmpty()) {
            txtColor.setText("Ingrese el color del vehiculo");
            txtColor.setForeground(java.awt.Color.GRAY);
        }
    }//GEN-LAST:event_txtColorFocusLost

    private void txtKilometrajeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtKilometrajeFocusGained
        if (txtKilometraje.getText().equals("Ingrese el kilometraje del vehiculo")) {
            txtKilometraje.setText("");
            txtKilometraje.setForeground(java.awt.Color.BLACK);
        }
    }//GEN-LAST:event_txtKilometrajeFocusGained

    private void txtKilometrajeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtKilometrajeFocusLost
        if (txtKilometraje.getText().trim().isEmpty()) {
            txtKilometraje.setText("Ingrese el kilometraje del vehiculo");
            txtKilometraje.setForeground(java.awt.Color.GRAY);
        }
    }//GEN-LAST:event_txtKilometrajeFocusLost

    private void txtAnioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAnioFocusGained
        if (txtAnio.getText().equals("Ingrese el año de fabricacion del vehiculo")) {
            txtAnio.setText("");
            txtAnio.setForeground(java.awt.Color.BLACK);
        }        
    }//GEN-LAST:event_txtAnioFocusGained

    private void txtAnioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAnioFocusLost
        if (txtAnio.getText().trim().isEmpty()) {
            txtAnio.setText("Ingrese el año de fabricacion del vehiculo");
            txtAnio.setForeground(java.awt.Color.GRAY);
        }        
    }//GEN-LAST:event_txtAnioFocusLost

    private void txtChasisFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtChasisFocusGained
        if (txtChasis.getText().equals("Ingrese el N° de chasis del vehiculo")) {
            txtChasis.setText("");
            txtChasis.setForeground(java.awt.Color.BLACK);
        }        
    }//GEN-LAST:event_txtChasisFocusGained

    private void txtChasisFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtChasisFocusLost
        if (txtChasis.getText().trim().isEmpty()) {
            txtChasis.setText("Ingrese el N° de chasis del vehiculo");
            txtChasis.setForeground(java.awt.Color.GRAY);
        }        
    }//GEN-LAST:event_txtChasisFocusLost

    private void txtMotorFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMotorFocusGained
        if (txtMotor.getText().equals("Ingrese el N° de motor del vehiculo")) {
            txtMotor.setText("");
            txtMotor.setForeground(java.awt.Color.BLACK);
        }       
    }//GEN-LAST:event_txtMotorFocusGained

    private void txtMotorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMotorFocusLost
        if (txtMotor.getText().trim().isEmpty()) {
            txtMotor.setText("Ingrese el N° de motor del vehiculo");
            txtMotor.setForeground(java.awt.Color.GRAY);
        }        
    }//GEN-LAST:event_txtMotorFocusLost

    private void txtCilindrajeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCilindrajeFocusGained
        if (txtCilindraje.getText().equals("Ingrese el cilindraje del vehiculo")) {
            txtCilindraje.setText("");
            txtCilindraje.setForeground(java.awt.Color.BLACK);
        }        
    }//GEN-LAST:event_txtCilindrajeFocusGained

    private void txtCilindrajeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCilindrajeFocusLost
        if (txtCilindraje.getText().trim().isEmpty()) {
            txtCilindraje.setText("Ingrese el cilindraje del vehiculo");
            txtCilindraje.setForeground(java.awt.Color.GRAY);
        }        
    }//GEN-LAST:event_txtCilindrajeFocusLost

    private void txtPuertasFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPuertasFocusGained
        if (txtPuertas.getText().equals("Ingrese el N° de puertas del vehiculo")) {
            txtPuertas.setText("");
            txtPuertas.setForeground(java.awt.Color.BLACK);
        }       
    }//GEN-LAST:event_txtPuertasFocusGained

    private void txtPuertasFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPuertasFocusLost
        if (txtPuertas.getText().trim().isEmpty()) {
            txtPuertas.setText("Ingrese el N° de puertas del vehiculo");
            txtPuertas.setForeground(java.awt.Color.GRAY);
        }       
    }//GEN-LAST:event_txtPuertasFocusLost

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void PanelGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelGuardarMouseClicked
        // TODO add your handling code here:
        String placa = txtPlaca.getText().trim();
    
    if (placa.isEmpty() || placa.equals("Ingrese la placa del vehiculo")) {
        JOptionPane.showMessageDialog(this, "Por favor ingrese una placa válida.", "Campo Requerido", JOptionPane.WARNING_MESSAGE);
        return;
    }
        GuardarVehiculos();
    }//GEN-LAST:event_PanelGuardarMouseClicked

    private void PanelGuardarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelGuardarMouseEntered
        // TODO add your handling code here:
        PanelGuardar.setBackground(new java.awt.Color(227, 95, 32));
        Guardar.setForeground(new java.awt.Color(217, 217, 192));
    }//GEN-LAST:event_PanelGuardarMouseEntered

    private void PanelGuardarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelGuardarMouseExited
        // TODO add your handling code here:
        PanelGuardar.setBackground(new java.awt.Color(242,101,34));
        Guardar.setForeground(java.awt.Color.white);
    }//GEN-LAST:event_PanelGuardarMouseExited

    private void PanelEditarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelEditarMouseEntered
        // TODO add your handling code here:
        PanelEditar.setBackground(new java.awt.Color(219,219,219));
        Editar.setForeground(new java.awt.Color(66, 66, 66));
    }//GEN-LAST:event_PanelEditarMouseEntered

    private void PanelEditarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelEditarMouseExited
        // TODO add your handling code here:
        PanelEditar.setBackground(java.awt.Color.white);
        Editar.setForeground(java.awt.Color.black);
    }//GEN-LAST:event_PanelEditarMouseExited

    private void PanelBuscarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelBuscarMouseEntered
        // TODO add your handling code here:
        PanelBuscar.setBackground(new java.awt.Color(219,219,219));
        Buscar.setForeground(new java.awt.Color(66, 66, 66));
    }//GEN-LAST:event_PanelBuscarMouseEntered

    private void PanelBuscarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelBuscarMouseExited
        // TODO add your handling code here:
        PanelBuscar.setBackground(java.awt.Color.white);
        Buscar.setForeground(java.awt.Color.black);
    }//GEN-LAST:event_PanelBuscarMouseExited

    private void txtPlacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPlacaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPlacaActionPerformed

    private void comboMarcasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboMarcasActionPerformed
        // TODO add your handling code here:
        if (comboMarcas.getSelectedIndex() > 0) {
        // Asumiendo que guardas el ID o el objeto Marca en el combo
        String marcaSeleccionada = (String) comboMarcas.getSelectedItem();
        // Carga los modelos pasando la marca o su ID correspondiente
        cargarComboModelos(marcaSeleccionada);
    }
        if (comboMarcas.getSelectedIndex() > 0) { // Asumiendo que el índice 0 es "Seleccione una marca"
        // Si tu combo guarda objetos Marca o cadenas con ID:
        String marcaSeleccionada = comboMarcas.getSelectedItem().toString();
        
        // Si necesitas el ID de la marca, puedes recuperarlo desde la BD o guardar objetos Marca directamente
        cargarComboModelos(marcaSeleccionada);
    } else {
        comboModelos.removeAllItems();
        comboModelos.addItem("Seleccione un modelo");
    }
    }//GEN-LAST:event_comboMarcasActionPerformed

    private void PanelNuevoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelNuevoMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_PanelNuevoMousePressed

    private void PanelNuevoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelNuevoMouseExited
        // TODO add your handling code here:
        PanelNuevo.setBackground(java.awt.Color.white);
        Nuevo.setForeground(java.awt.Color.black);
    }//GEN-LAST:event_PanelNuevoMouseExited

    private void PanelNuevoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelNuevoMouseEntered
        // TODO add your handling code here:
        PanelNuevo.setBackground(new Color(219,219,219));
        Nuevo.setForeground(new Color(66, 66, 66));
    }//GEN-LAST:event_PanelNuevoMouseEntered

    private void PanelNuevoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelNuevoMouseClicked
        // TODO add your handling code here:
        CrearNuevaMarcaModelo CMM=new CrearNuevaMarcaModelo();
        CMM.setVisible(true);
    }//GEN-LAST:event_PanelNuevoMouseClicked
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        /* Create and display the form */
        }
    public void LimpiarDatos (){
        txtPlaca.setText("");
        txtPlaca.setForeground(new Color(94, 94, 94));
        txtColor.setText("");
        txtColor.setForeground(new Color(94, 94, 94));
        txtKilometraje.setText("");
        txtKilometraje.setForeground(new Color(94, 94, 94));
        txtAnio.setText("");
        txtAnio.setForeground(new Color(94, 94, 94));
        txtChasis.setText("");
        txtChasis.setForeground(new Color(94, 94, 94));
        txtMotor.setText("");
        txtMotor.setForeground(new Color(94, 94, 94));
        txtCilindraje.setText("");
        txtCilindraje.setForeground(new Color(94, 94, 94));
        txtPuertas.setText("");
        txtPuertas.setForeground(new Color(94, 94, 94));
        comboMarcas.setSelectedIndex(0);
        comboPropietarios.setSelectedIndex(0);
        comboModelos.setSelectedIndex(0);
        comboTransmision.setSelectedIndex(0);

    }
    public void GuardarVehiculos (){        
        String Placa=txtPlaca.getText().trim();
        String Color=txtColor.getText().trim().toUpperCase();
        String Kilometraje=txtKilometraje.getText().trim().toUpperCase();
        String Anio=txtAnio.getText().trim().toUpperCase();
        String Chasis=txtChasis.getText().trim().toUpperCase();
        String Motor=txtMotor.getText().trim().toUpperCase();
        String Cilindraje=txtCilindraje.getText().trim().toUpperCase();
        String Puertas=txtPuertas.getText().trim().toUpperCase();
        String Marcas = comboMarcas.getSelectedItem().toString();
        String Propietarios= comboPropietarios.getSelectedItem().toString();
        String Modelos= comboModelos.getSelectedItem().toString();
        String Transmision= comboTransmision.getSelectedItem().toString();
        if (Placa.isEmpty()|| Color.isEmpty()||Kilometraje.isEmpty()||Anio.isEmpty()||Chasis.isEmpty()||Motor.isEmpty()||Cilindraje.isEmpty()||Puertas.isEmpty()){
            JOptionPane.showMessageDialog (this, "Por favor complete los datos que faltan");
            return;
        }
        if (Placa.isEmpty()|| Color.isEmpty()||Kilometraje.isEmpty()||Anio.isEmpty()||Chasis.isEmpty()||Motor.isEmpty()||Cilindraje.isEmpty()||Puertas.isEmpty()){
            JOptionPane.showMessageDialog (this, "Por favor complete los datos que faltan");
            return;
        }
        if (Marcas.equals("Seleccione una opción") ){
            JOptionPane.showMessageDialog (this, "Por favor escoga una opción");
            return;
        }
         if (Propietarios.equals("Seleccione una opción") ){
            JOptionPane.showMessageDialog (this, "Por favor escoga una opción");
            return;
        }
         if (Transmision.equals("Seleccione una opción") ){
            JOptionPane.showMessageDialog (this, "Por favor escoga una opción");
            return;
        }
         if (Modelos.equals("Seleccione una opción") ){
            JOptionPane.showMessageDialog (this, "Por favor escoga una opción");
            return;
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Ano;
    private javax.swing.JPanel BarraAbajo;
    private javax.swing.JPanel BarraArriba;
    private javax.swing.JLabel Buscar;
    private javax.swing.JLabel Chasis;
    private javax.swing.JLabel Cilindraje;
    private javax.swing.JLabel Color;
    private javax.swing.JLabel Editar;
    private javax.swing.JPanel Fondo;
    private javax.swing.JLabel Guardar;
    private javax.swing.JLabel ImagenADD;
    private javax.swing.JLabel ImagenADD2;
    private javax.swing.JLabel ImagenADD3;
    private javax.swing.JLabel ImagenSAVE;
    private javax.swing.JLabel Kilometraje;
    private javax.swing.JLabel Marca;
    private javax.swing.JLabel Modelo;
    private javax.swing.JLabel Motor;
    private javax.swing.JLabel NombreVentanaVehiculos;
    private javax.swing.JLabel Nuevo;
    private javax.swing.JLabel Nuevo2;
    private javax.swing.JLabel Nuevo3;
    private javax.swing.JPanel PanelBuscar;
    private javax.swing.JPanel PanelEditar;
    private javax.swing.JPanel PanelGuardar;
    private javax.swing.JPanel PanelNuevo;
    private javax.swing.JPanel PanelNuevo2;
    private javax.swing.JPanel PanelNuevo3;
    private javax.swing.JLabel Placa;
    private javax.swing.JLabel Propietario;
    private javax.swing.JLabel Puertas;
    private javax.swing.JLabel TituloFuncion1;
    private javax.swing.JLabel TituloFuncion2;
    private javax.swing.JLabel Transmicion;
    private javax.swing.JComboBox<String> comboMarcas;
    private javax.swing.JComboBox<String> comboModelos;
    private javax.swing.JComboBox<String> comboPropietarios;
    private javax.swing.JComboBox<String> comboTransmision;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtAnio;
    private javax.swing.JTextField txtChasis;
    private javax.swing.JTextField txtCilindraje;
    private javax.swing.JTextField txtColor;
    private javax.swing.JTextField txtKilometraje;
    private javax.swing.JTextField txtMotor;
    private javax.swing.JTextField txtPlaca;
    private javax.swing.JTextField txtPuertas;
    // End of variables declaration//GEN-END:variables
}